[FIX] l10n_br_sale
OCA/l10n-brazil pull request #1003
Opened 2020-10-23 19:41 UTC by marcelsavegnago

Correção da divisão da SO em mais de um documento fiscal.

2020-10-27 18:56 UTC, mbcosta commented
ola @marcelsavegnago  obrigado pelo PR

Eu havia feito na migração a correção para criar uma ou mais Faturas caso houvesse diferença no Tipo Fiscal do Documento a partir do Pedido de Venda mas faltou validar nos testes além da Fatura/account.invoice o Documento Fiscal/l10n_br_fiscal.document, bom conversando com o @renatonlima acreditamos que o melhor lugar para corrigir isso seria antes de chamar o "super" aqui https://github.com/Escodoo/l10n-brazil/blob/12.0-l10n_br_sale-fix_document_split/l10n_br_account/models/account_invoice_line.py#L146 verificando se está vindo no dicionario "vals" o campo "invoice_id", caso esteja o método deve atualizar o campo document_id de acordo com o fiscal_document_id que está preenchido nessa nova "invoice", aparentemente isso resolveria o problema tanto para a Vendas quanto para Compras.

Seria bom se puder acrescentar nos testes essa validação de que o Documento Fiscal relacionado também está correto.

2020-10-27 19:09 UTC, marcelsavegnago commented
> https://github.com/Escodoo/l10n-brazil/blob/12.0-l10n_br_sale-fix_document_split/l10n_br_account/models/account_invoice_line.py#L146

Grande @mbcosta. Obrigado pela orientação. Vou trabalhar nela atualizo a PR.

Vejo os testes tbm.

2020-10-28 02:37 UTC, marcelsavegnago commented
@mbcosta não implementei nenhum teste ainda mas dá uma olha fazendo favor.

2020-10-28 23:32 UTC, marcelsavegnago commented
@mbcosta tem alguma dica de como implementar o teste ?

2020-10-31 19:53 UTC, mileo requested changes

2020-10-31 19:53 UTC, mileo commented on l10n_br_account/models/account_invoice_line.py
> +        if values['invoice_id']:
Pode alterar estre trecho para vals.get('invoice_id') para evitar erros:

```
>>> vals = dict()
>>> vals
{}
>>> if vals['bla']:
...     print('ok')
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'bla'
```

2020-11-02 17:54 UTC, marcelsavegnago commented on l10n_br_account/models/account_invoice_line.py
> +        if values['invoice_id']:
@mileo Done

2020-11-03 17:59 UTC, marcelsavegnago commented
ping @mileo @mbcosta

2020-11-06 18:41 UTC, renatonlima approved these changes

2020-11-06 19:42 UTC, marcelsavegnago commented
@mileo consegue revisar?

2020-11-06 19:43 UTC, mileo approved these changes

2020-11-06 19:44 UTC, mileo commented
/ocabot merge nobump

2020-11-06 19:58 UTC, merged

2020-11-06 20:21 UTC, rvalyi commented
@mileo isso nao cria nehnum problema com aquele lance do GINFES de vcs que tem linhas de account.invoice.line com que pertencem a documentos fiscais diferentes? cc @gabrielcardoso21 . Eu tava olhando isso ainda nesses minutos que vc fez o commit.

2020-11-06 20:54 UTC, mileo commented
> @mileo isso nao cria nehnum problema com aquele lance do GINFES de vcs que tem linhas de account.invoice.line com que pertencem a documentos fiscais diferentes? cc @gabrielcardoso21 . Eu tava olhando isso ainda nesses minutos que vc fez o commit.

@gabrielcardoso21 e o @luismalta são mais indicados para responder isso, vou verificar com eles.