[12.0] [IMP] Document Cancel workflow
OCA/l10n-brazil pull request #1007
Opened 2020-10-26 15:03 UTC by luismalta

Melhora o fluxo de cancelamento de um documento usando a validação de alteração do estado do documento introduzida no PR #1006 .

Depende do PR #1006.

2020-10-26 15:15 UTC, renatonlima commented
@luismalta, @mileo Please look up my PR #983, I had already made corrections and improvements did in this PR and #1006

2020-10-26 17:53 UTC, renatonlima requested changes, later dismissed
Deve ser verficado o PR #983 pois foram feitas melhorias e correções deste PR e do #1006

2020-10-26 18:58 UTC, mileo approved these changes

2020-10-31 20:01 UTC, mileo commented
> Deve ser verficado o PR #983 pois foram feitas melhorias e correções deste PR e do #1006

@renatonlima não encontrei melhorias nesse sentido no seu PR. Como o seu PR é uma melhoria e neste momento ele esta com conflito, fico aguardando sua ação para revisar o #983

2020-10-31 20:56 UTC, marcelsavegnago approved these changes
LGTM

2020-10-31 21:53 UTC, mileo commented
/ocabot merge nobump

2020-10-31 22:20 UTC, merged