[12.0][IMP] l10n_br_stock_account: Adicionado suporte para utilizar a posição fiscal da operação
OCA/l10n-brazil pull request #1009
Opened 2020-10-30 19:58 UTC by marcelsavegnago

2020-10-30 19:58 UTC, marcelsavegnago commented
cc @mileo @jpcarassato

2020-10-31 17:21 UTC, marcelsavegnago commented
@mileo para mudar a conta contábil que vem do parceiro eu coloquei um trecho de código para buscar a conta do diário caso ela esteja definida.. dá uma olhada e me fala se faz sentido fazendo favor.

A conta definida no diário normalmente é aplicada em que situação ?

cc @renatonlima

2020-11-03 17:56 UTC, marcelsavegnago commented
@mileo consegue dar uma olhada nesta PR? 

@jpcarassato se puder fazer a revisão funcional eu agradeço.

2020-11-03 20:16 UTC, jpcarassato approved these changes
Teste funcional ok!

2020-11-05 20:40 UTC, renatonlima commented
Olá @marcel,

É importante você utilizar nesta implementação a classe como o exemplo da https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_account/models/account_document_line_mixin.py que é o mixin para adicionar as features comuns contábeis nas linhas dos documentos.

2020-11-05 20:41 UTC, renatonlima requested changes
É importante você utilizar nesta implementação a classe como o exemplo da https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_account/models/account_document_line_mixin.py que é o mixin para adicionar as features comuns contábeis nas linhas dos documentos.

2020-11-05 20:44 UTC, marcelsavegnago commented
> É importante você utilizar nesta implementação a classe como o exemplo da https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_account/models/account_document_line_mixin.py que é o mixin para adicionar as features comuns contábeis nas linhas dos documentos.

Obrigado @renatonlima Vou mexer nisso agora. Vlw

2020-11-12 14:23 UTC, mileo commented
@marcelsavegnago 

Será que não é melhor vc implementar essa lógica no 

odoo.addons.account.models.account_invoice.AccountInvoice._get_onchange_create

Ou 

odoo.addons.account.models.account_invoice.AccountInvoice._onchange_journal_id

Pois ai ela também funcionaria em uma fatura criada manualmente?

2020-12-10 15:28 UTC, marcelsavegnago commented
> @marcelsavegnago
> 
> Será que não é melhor vc implementar essa lógica no
> 
> odoo.addons.account.models.account_invoice.AccountInvoice._get_onchange_create
> 
> Ou
> 
> odoo.addons.account.models.account_invoice.AccountInvoice._onchange_journal_id
> 
> Pois ai ela também funcionaria em uma fatura criada manualmente?

@mileo qual trecho vc sugere implementar nestes locais ?

2021-03-16 21:35 UTC, mileo commented
@marcelsavegnago e esse PR ainda é necessário? Pode fazer um rebase?

2021-03-16 21:38 UTC, marcelsavegnago commented
@mileo deixei parado mas farei o rebase e se achara que vale a pena nós vamos nos falando

2021-06-06 21:46 UTC, marcelsavegnago commented
Pessoal, por ora estou fechando esta PR. Submeti outras duas PRs que acredito que já atendem.

#1429 e #1273

2021-06-06 21:46 UTC, closed without merging