[12.0][ADD] 10n_br_coa_complete: proposta de novo plano contas ou substituição do genérico
OCA/l10n-brazil pull request #1071
Opened 2021-01-09 15:55 UTC by marcelsavegnago

replace #974 

cc @rvalyi

2021-01-11 18:35 UTC, rvalyi commented
valeu @marcelsavegnago . O Runbot rodou mas deu algum warning. Nao tinha mais os logs dai deu um rebuild para ver se a gente consegue descobrir porque nao rodou.

2021-01-11 22:19 UTC, rvalyi requested changes
o log do Runbot tem esse warning
```
2021-01-11 19:21:21,260 177 WARNING openerp_test odoo.models: account.chart.template.create() with unknown fields: spoken_languages
```
ver aqui por examplo https://runbot2.odoo-community.org/runbot/static/build/3459462-1071-5785a3/logs/job_20_test_all.txt

2021-01-11 22:19 UTC, rvalyi commented on l10n_br_coa_complete/data/l10n_br_coa_complete_template.xml
> +            <field name="spoken_languages" eval="'pt_BR'"/>
parece que esse campo nao existe nas dependencias.
Isso é que da um warning no Runbot e que faz que ele nao fica verde. @marcelsavegnago vc pode ver?

2021-01-12 03:11 UTC, marcelsavegnago commented on l10n_br_coa_complete/data/l10n_br_coa_complete_template.xml
> +            <field name="spoken_languages" eval="'pt_BR'"/>
Feito.

2021-01-15 15:18 UTC, marcelsavegnago commented
@mileo pode revisar ?

2021-01-25 16:09 UTC, marcelsavegnago commented
ping @mileo @rvalyi @renatonlima

2021-01-25 16:26 UTC, rvalyi requested changes
Ola @marcelsavegnago vi mais um detalhe mas que tem usa importancia, parece que o README/DESCRIPTION nao esta correcto, pois parece que eh uma copia do DESCRIPTION do l10n_br_generic, ai fica confuso... Pode atualizar?

2021-01-25 16:53 UTC, marcelsavegnago commented
> Ola @marcelsavegnago vi mais um detalhe mas que tem usa importancia, parece que o README/DESCRIPTION nao esta correcto, pois parece que eh uma copia do DESCRIPTION do l10n_br_generic, ai fica confuso... Pode atualizar?

Putzz.. verdade :) vou corrigir.

2021-02-02 14:10 UTC, marcelsavegnago commented
> Ola @marcelsavegnago vi mais um detalhe mas que tem usa importancia, parece que o README/DESCRIPTION nao esta correcto, pois parece que eh uma copia do DESCRIPTION do l10n_br_generic, ai fica confuso... Pode atualizar?

@rvalyi feito. Se puder revisar eu agradeço.

2021-02-02 14:12 UTC, marcelsavegnago commented
ping @mileo

2021-02-02 14:12 UTC, marcelsavegnago commented
ping @mileo

2021-02-02 14:24 UTC, rvalyi approved these changes
OK para mim, parabens @marcelsavegnago mais um modulo que vai aumentar a popularidade do projeto!

2021-02-02 14:51 UTC, mileo commented on l10n_br_coa_complete/hooks.py
> +    #         user_admin.company_id = env.ref('base.main_company')
Remove esses comentários plz

2021-02-02 14:51 UTC, mileo approved these changes

2021-02-02 14:55 UTC, renatonlima requested changes

2021-02-02 14:55 UTC, renatonlima commented on l10n_br_coa_complete/tests/test_l10n_br_coa_complete.py
> +# Copyright (C) 2020  Luis Felipe Mileo - KMEE
@marcelsavegnago,

Eu imagino que você copiou o módulo l10n_br_coa_generic como base para a criação do l10n_br_coa_complete e tenha mantido o header do módulo l10n_br_coa_generic (o que vocês fez esta corretissimo), só que o @mileo havia copiado esse arquivo do [l10n_br_coa_simple](https://github.com/OCA/l10n-brazil/pull/778/commits/897e8bedaaf4d2fdaf6ac7b49e4d773338bf865f) quando criou o l10n_br_coa_generic e removeu o header o que esta errado, no l10n_br_coa_simple quando eu copiei o hook do l10n_br_generic como base no l10n_br_coa_simple eu também mantive o [header](https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_coa_simple/hooks.py). Por favor coloquei o mesmo header do l10n_br_coa_simple/tests/test_l10n_br_coa_complete.py

2021-02-02 15:17 UTC, marcelsavegnago commented on l10n_br_coa_complete/hooks.py
> +    #         user_admin.company_id = env.ref('base.main_company')
Feito

2021-02-02 15:17 UTC, marcelsavegnago commented on l10n_br_coa_complete/tests/test_l10n_br_coa_complete.py
> +# Copyright (C) 2020  Luis Felipe Mileo - KMEE
Feito

2021-02-02 18:17 UTC, renatonlima approved these changes

2021-02-02 18:17 UTC, renatonlima commented
/ocabot merge nobump

2021-02-02 18:56 UTC, merged