[12.0] l10n_br_sale partial deliveries
OCA/l10n-brazil pull request #1109
Opened 2021-01-29 18:52 UTC by renatonlima

No módulo de vendas quando um pedido de vendas é faturado baseado nas quantidades entregues e esta é diferente da quantidade pedida, os valores dos impostos são copiados das linhas dos pedidos de vendas que ficam incorretos. Esse PR chama o método _update_taxes das linhas dos documentos fiscais para corrigir esses valores, e também adiciona um campo calculado na linha de vendas para calcular a quantidade tributada entregue.

2021-01-29 21:02 UTC, marcelsavegnago approved these changes
lgtm

2021-02-01 14:32 UTC, gabrielcardoso21 approved these changes

2021-02-01 14:33 UTC, luismalta approved these changes

2021-02-01 18:24 UTC, mileo commented
/ocabot merge minor

2021-02-01 18:33 UTC, marcelsavegnago requested changes
@mileo ta com a tag de WIP. @renatonlima pode seguir com o merge ?

2021-02-01 20:52 UTC, renatonlima commented
@mileo e @marcelsavegnago O PR está com o label "Work in progress" tem um problema de arredondamento nos impostos....

2021-02-01 21:10 UTC, mileo commented
> @mileo e @marcelsavegnago O PR está com o label "Work in progress" tem um problema de arredondamento nos impostos....

Cancelado o merge

2021-02-01 21:11 UTC, mileo requested changes
Verificar a questão do arredondamento

2021-02-12 18:40 UTC, mileo requested changes
Seria legal tb colocar um grupo nesse campo para que ele só seja exibido na view caso o usuário queira, mas isso pode envolver os outros campos relacionados tb.

2021-02-12 18:40 UTC, mileo commented on l10n_br_sale/models/sale_order_line.py
> +        'analytic_line_ids.product_uom_id')
Estes campos não deveriam estar no depends

2021-02-12 18:40 UTC, mileo commented on l10n_br_sale/models/sale_order_line.py
> +        'analytic_line_ids.product_uom_id')
```
 @api.multi
    @api.depends('qty_delivered_method', 'qty_delivered_manual', 'analytic_line_ids.so_line', 'analytic_line_ids.unit_amount', 'analytic_line_ids.product_uom_id')
    def _compute_qty_delivered(self):
        """ This method compute the delivered quantity of the SO lines: it covers the case provide by sale module, aka
            expense/vendor bills (sum of unit_amount of AAL), and manual case.
            This method should be overriden to provide other way to automatically compute delivered qty. Overrides should
            take their concerned so lines, compute and set the `qty_delivered` field, and call super with the remaining
            records.
        """
        # compute for analytic lines
        lines_by_analytic = self.filtered(lambda sol: sol.qty_delivered_method == 'analytic')
        mapping = lines_by_analytic._get_delivered_quantity_by_analytic([('amount', '<=', 0.0)])
        for so_line in lines_by_analytic:
            so_line.qty_delivered = mapping.get(so_line.id, 0.0)
        # compute for manual lines
        for line in self:
            if line.qty_delivered_method == 'manual':
                line.qty_delivered = line.qty_delivered_manual or 0.0
``` 

Os depends não tem relação com o código copiado do core.

2021-03-06 21:50 UTC, renatonlima commented
Depends #1175

2021-03-30 16:03 UTC, marcelsavegnago approved these changes

2021-03-30 17:36 UTC, renatonlima commented
Pessoal, eu atualizei o PR, corrigi o problema e fiz rebase da branch.


cc @mbcosta, @rvalyi, @marcelsavegnago, @mileo

2021-03-30 17:38 UTC, marcelsavegnago commented
@renatonlima pode remover a tag "needs fixing" ?

2021-03-30 18:39 UTC, rvalyi commented on l10n_br_sale/models/sale_order_line.py
> +        'analytic_line_ids.product_uom_id')
talvez nao seja obrigatorio listar os campos que nao tem impacto no override. Porem tb nao da para dizer que faz mal, no sentido que deixa explicito o que vai de fato chamar o metodo e o override dele junto (por examplo se vc pensar em mudar alguma logica ou simplesmente para saber o gatilho mesmo).

Se vc olhar, na OCA a galera faz esse tipo de codigo mesmo, algums examplos que eu achei em 2 minutos:
https://github.com/OCA/account-financial-tools/blob/12.0/account_invoice_currency/models/account_invoice.py#L21
https://github.com/OCA/account-financial-tools/blob/12.0/account_payment_netting/models/account_payment.py#L92
https://github.com/OCA/timesheet/blob/12.0/hr_timesheet_sheet_period/models/hr_timesheet_sheet.py#L53

Entao eu nao diria nem que seria melhor tirar.

2021-03-31 13:02 UTC, rvalyi requested changes

2021-03-31 13:02 UTC, rvalyi commented on l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
> +                    price / product.uot_factor or 1.0)
isso cria uma divisao por zero quando uot_factor vale 0, alias ta acontecendo nos testes:
https://travis-ci.com/github/OCA/l10n-brazil/jobs/495030745#L2559

2021-03-31 17:33 UTC, mbcosta approved these changes

2021-03-31 18:48 UTC, rvalyi approved these changes

2021-03-31 19:29 UTC, renatonlima commented on l10n_br_sale/models/sale_order_line.py
> +        'analytic_line_ids.product_uom_id')
Eu particularmente deixo o depends destes métodos para deixar o código mais explicito e como o @rvalyi comentou acima, alguns contribuidores na OCA fazem o mesmo.

2021-03-31 19:46 UTC, renatonlima commented
> Seria legal tb colocar um grupo nesse campo para que ele só seja exibido na view caso o usuário queira, mas isso pode envolver os outros campos relacionados tb.

Qual campo o fiscal_qty_delivered? Esse campo não está visível e não precisa porque é apenas um campo técnico, o campo visivel é a quantidade (comercial) entregue

2021-03-31 23:59 UTC, mileo approved these changes

2021-04-01 00:43 UTC, rvalyi commented
/ocabot merge minor

2021-04-01 01:28 UTC, rvalyi commented
/ocabot merge minor

2021-04-01 02:24 UTC, mileo commented
/ocabot merge minor

2021-04-01 04:18 UTC, merged