[12.0][[REF] l10n_br_stock_account
OCA/l10n-brazil pull request #1114
Opened 2021-02-01 22:59 UTC by mbcosta

* Corrigido a criação do Documento Fiscal e incluído o campo partner_shipping_id ( depende https://github.com/OCA/l10n-brazil/pull/1099 )
* Removido o Invoice State da Operação Fiscal ( o stock rule e o res config de Politica de Criação de Fatura em Vendas e Compras não seriam suficientes ? )
* Recolocado o campo do set_to_be_invoiced no Stock Picking ( não encontrei um motivo para remove-lo )

cc @renatonlima @rvalyi @marcelsavegnago @mileo @gabrielcardoso21

2021-02-02 01:51 UTC, rvalyi commented
só se liga que com esse refator, tem problema no l10n_br_sale_stock (sei que vc ta trabalhando nele tb, porem teremos que ter a CI OK para fazer merge desse refator): https://travis-ci.com/github/OCA/l10n-brazil/jobs/479407493#L3863

2021-02-08 18:35 UTC, mbcosta commented
ola @rvalyi para deixar o CI verde não será possível alterando apenas o modulo l10n_br_stock_account aqui, o que pode ser feito é comentar esse codigo https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_sale_stock/models/sale_order_line.py#L17 que gera o erro com um "TODO remover no outro PR do l10n_br_sale_stock"

Depende do https://github.com/OCA/account-invoicing/pull/859 ( será melhor aprovar esse PR https://github.com/OCA/account-invoicing/pull/862 antes e fazer o rebase no primeiro devido ao problema com as informações de Vendas/compras no Agrupamento de Pickings )

cc @renatonlima

2021-02-10 16:05 UTC, marcelsavegnago commented
@mbcosta acredito que o rebase já possa feito

2021-02-17 17:24 UTC, renatonlima approved these changes

2021-02-17 22:37 UTC, marcelsavegnago approved these changes

2021-02-17 22:50 UTC, marcelsavegnago commented
@mileo @gabrielcardoso21 @luismalta um de vocês pode revisar por favor ?

2021-02-18 02:23 UTC, rvalyi requested changes
parabens pelo excelente trabalho @mbcosta porem eu acho que eu peguei algo no override do _split como eu comentei.

2021-02-18 02:23 UTC, rvalyi commented on l10n_br_stock_account/models/stock_move.py
> +        return new_move_id
Eu acho que tem que chamar esses 2 onchanges no new_move_id tb. Pois senao ele vai ser criado com uma quantitade inferior sem que nada chama esses onchanges (ainda mais que vc tirou os onchanges do overrides do action_confirm) e os valores fiscais vao ser copidados do move original antes do split (ver como esta no metodo _split no modulo stock).

2021-02-18 21:30 UTC, rvalyi commented
teve um erro inconsistente no l10n_br_website_sale_delivery/tests/test_website_sale_tour.py que é inconsistente com o Javascript, mas for isso parece OK.

2021-02-18 21:38 UTC, rvalyi approved these changes

2021-02-18 21:40 UTC, rvalyi commented
/ocabot merge major

2021-02-18 23:10 UTC, rvalyi commented
de novo uma inconsistência do teste Javascript no modulo l10n_br_website_sale_delivery
iniciando o merge de novo...

2021-02-18 23:10 UTC, rvalyi commented
/ocabot merge major

2021-02-19 12:47 UTC, rvalyi commented
estranho os testes do ocabot passaram mas o merge nao foi, Testando de novo...

2021-02-19 12:47 UTC, rvalyi commented
/ocabot merge major

2021-02-19 13:36 UTC, merged