[12.0][FIX] View error
OCA/l10n-brazil pull request #1119
Opened 2021-02-03 17:05 UTC by gabrielcardoso21

Estava tendo um erro na visão ao adicionar linhas nas ordens de reparo

2021-02-03 17:15 UTC, marcelsavegnago approved these changes

2021-02-03 17:27 UTC, gabrielcardoso21 commented
@marcelsavegnago aproveitei o PR pra consertar um outro detalhe nos formulários das linhas. Pode revisar de novo, por favor?

2021-02-03 17:41 UTC, marcelsavegnago commented
> @marcelsavegnago aproveitei o PR pra consertar um outro detalhe nos formulários das linhas. Pode revisar de novo, por favor?

Opa.. soh achei estranho este ! no começo do nome do grupo  **!l10n_br_repair.group_discount_per_value** ?

2021-02-03 18:48 UTC, renatonlima commented
@marcelsavegnago o groups="! é o operador logico not https://github.com/odoo/odoo/blob/12.0/addons/website/views/res_config_settings_views.xml#L28

2021-02-03 18:50 UTC, renatonlima requested changes

2021-02-03 18:50 UTC, renatonlima commented on l10n_br_repair/views/repair_fee.xml
> +                    <field name="uot_id" force_save="1" groups="uom.group_uom" class="oe_inline oe_no_button" attrs="{'invisible': 1}"/>
Não poderia ser mais simples, tipo: invisible="1"?

2021-02-03 19:42 UTC, marcelsavegnago commented
> @marcelsavegnago o groups="! é o operador logico not https://github.com/odoo/odoo/blob/12.0/addons/website/views/res_config_settings_views.xml#L28

ahhh.. blz :). Vlw

2021-02-04 13:04 UTC, marcelsavegnago commented on l10n_br_repair/views/repair_fee.xml
> +                    <field name="uot_id" force_save="1" groups="uom.group_uom" class="oe_inline oe_no_button" attrs="{'invisible': 1}"/>
ping @gabrielcardoso21

2021-02-04 13:05 UTC, marcelsavegnago commented
> @marcelsavegnago aproveitei o PR pra consertar um outro detalhe nos formulários das linhas. Pode revisar de novo, por favor?

@gabrielcardoso21 pra mim está ok.

2021-02-05 15:08 UTC, marcelsavegnago commented on l10n_br_repair/views/repair_fee.xml
> +                    <field name="uot_id" force_save="1" groups="uom.group_uom" class="oe_inline oe_no_button" attrs="{'invisible': 1}"/>
@gabrielcardoso21 https://github.com/kmee/l10n-brazil/pull/648

2021-02-05 22:22 UTC, marcelsavegnago commented
@renatonlima pode revisar novamente ?

2021-02-08 12:46 UTC, renatonlima approved these changes

2021-02-08 12:47 UTC, renatonlima commented
/oca merge nobump

2021-02-08 13:12 UTC, renatonlima commented
/ocabot merge nobump

2021-02-08 14:02 UTC, merged