Feature/820 - Pagamentos no Fiscal
OCA/l10n-brazil pull request #1125
Opened 2021-02-06 00:14 UTC by mileo

2021-02-06 13:16 UTC, mileo commented
@renatonlima pode revisar novamente e verificar oq vc quer que eu ajuste? Não encontrei seu comentário no PR #820 

@rvalyi A funcionalidade esta sendo testa via XML, e o coverage esta sendo mantido, não vejo motivo para colocar testes Python, mas se vocês acharem necessário podemos providenciar.

@marcelsavegnago poderia revisar novamente.

cc: @gabrielcardoso21 @luismalta @sadamo @hendrixcosta @rlimaeco @DiegoParadeda @mbcosta

2021-02-06 14:34 UTC, rvalyi requested changes
Depois eu tomo tempo para explicar em detalhes, mas so para evitar o que ja aconteceu ha 3 semanas, eu quero ja deixar claro eu que sou totalmente **contra o merge** desse PR na forma atual dele. Deixando claro que tb em diversas ocasioes, a gente atrasou bastante porque teve propostas assim das quais a gente discordava muito (sem voltar sobre as tentativas cagadas de fork/re-eescritura da v10 e v11), apenas na v12 a gente pode citar: 

- https://github.com/OCA/l10n-brazil/pull/806 + 12000+ linhas de codigo (num modulo que ja tem 23000!) e que deu para  implementar em menos de 200 linhas porque o Odoo ja sabia lidar com taxas dedutiveis e nao precisava partir para contornar o modulo account totalmente assim.

- https://github.com/OCA/l10n-brazil/pull/928 enfiado a força na calada da noite no nosso modulo l10n_br_fiscal sem nossa revisao. 830 linhas de novas funcionalidades nao solicitadas e copiadas de forma porca de uma fork da v10/v11 e que junto com o codigo anterior dos eventos, da para reduizir em quase mil linhas. Um trabalho de limpeza que nem terminamos de fazer hoje enquanto a gente teve que fazer o deploy de divida tecnologica para todos nossos clientes para funcionalidades que eles nem tinha interesse e para quais teremos que gastar tempo fazendo migraçao la na frente...

Aqui vemos a mesma coisa, 1300+ linhas enquanto em 80% dos casos de uso pelo menos a metade desse codigo vira inutil logo que o modulo account é instalado. E tb vemos a mesma atitude de tentar passar por cima da aprovaçao do autores do codigo atual (ja que tinha sido feito o merge sem nossa apovaçao 3 semanas atras). 

Isso é chato, esse tipo de atitude **ATRASA O PROJETO**, tem que ficar claro para todo mundo. Luis se vc ou o Gabriel praticasse mais os outros repos da OCA assim como o @marcelsavegnago  faz por examplo, ficaria obvio para vcs que vcs tem que pensar mais modular e parar de querer produzir modulos obesos que procura fazer tudo. E uma pena que vc nao enxerga isso. Em muitos aspectos, especialmente funcionais, vc tem sim competencia para participar do projeto, mas em outros aspectos como de arquitetura de software, infelizmente a sua falta de experiencia fica gritante e eu acho que vc deveria procurar saber um pouco mais sobre o efeito Dunning Kruger. Desculpa a sinceridade.

2021-02-06 17:46 UTC, marcelsavegnago commented
@mileo vou testar sim. Porém, por ser um assunto mais polemico eu seguraria um pouco e priorizaria revisão, testes e correções em algumas PRs para permitir o merge delas o quanto antes.

- https://github.com/OCA/l10n-brazil/pull/1043
- https://github.com/OCA/l10n-brazil/pull/1117
- https://github.com/OCA/l10n-brazil/pull/983
- https://github.com/OCA/l10n-brazil/pull/768
- https://github.com/OCA/l10n-brazil/pull/1099
- https://github.com/OCA/l10n-brazil/pull/1109
- https://github.com/erpbrasil/erpbrasil.edoc/pull/30

Estas foram algumas que considerei que precisam de atenção mas com certeza os demais podem ter outra visão.

2021-06-11 20:29 UTC, marcelsavegnago commented
@mileo se puder, faz um rebase desta tbm por favor.

2021-07-19 23:37 UTC, netosjb commented on l10n_br_fiscal/models/payment_mixin.py
> +        return self.amount_financial
```suggestion
        return self.amount_financial_total
```
o nome dessa variavel foi refatorado no merge dessa pr:

https://github.com/OCA/l10n-brazil/pull/1502

2021-07-20 03:46 UTC, rvalyi commented
Pessoal, ressalvando que a gente ja teve que tirar esse codigo a localizaçao  (com um git push --force)  depois que o @mileo fez o merge disso sem esperar a nossa validação. A gente entende que algumas coisas são utis e bem vindas. Porem a gente rejeita facilemente 80% desse codigo no l10n_br_fiscal então eu prefiro re-afirmar isso para não rolar surpresa e frustração deṕois.

@mileo vc tem que pensar numa versão minimalista disso no fiscal e jogar o restante em outros modulos. Vc é campião de engordar o modulo fiscal com funcionalidades que poderiam muito bem estar em outros modulos como as coisas do closing ou da dfe para pegar so alguns examplos, vc realmente tem que pensar mais modular e praticar outros repos da OCA para se dar conta disso... O tamanho medio de um modulo da OCA deve ser uns 400 linhas, e vc faz PR de mais de 1500 linhas no mesmo modulo amigo... Quando eu vejo isso e que vc tem temosia com essas coisas, eu juro que me pergunto se vc tem seu lugar no PSC, desculpa a sinceridade.

cc @renatonlima

2023-03-26 12:07 UTC, closed without merging