[FIX] Sale report improve
OCA/l10n-brazil pull request #1161
Opened 2021-03-01 14:59 UTC by mileo

After:

![image](https://user-images.githubusercontent.com/1975978/109515169-8d03af00-7a85-11eb-9f31-ddfc6f377c84.png)

Before:

![image](https://user-images.githubusercontent.com/1975978/109515047-6ba2c300-7a85-11eb-837b-4144f717dd07.png)

2021-03-01 15:13 UTC, renatonlima commented
@mileo

- Deveria deixar invisível o campo "Amount  Gross" caso não tiver desconto;
- Talvez deveria imprimir somente os fiscal_tax_id onde tiver percent_amout ou value_amount preenchidos.

2021-03-01 16:55 UTC, mileo commented
> @mileo
> 
> * Deveria deixar invisível o campo "Amount  Gross" caso não tiver desconto;
> * Talvez deveria imprimir somente os fiscal_tax_id onde tiver percent_amout ou value_amount preenchidos.

Vou dar uma melhorada, obrigado.

2021-03-02 11:30 UTC, renatonlima requested changes

2021-03-02 11:30 UTC, renatonlima commented on l10n_br_sale/report/sale_report_templates.xml
> +                 <t t-foreach="line.fiscal_tax_ids.filtered(lambda x: x.percent_amount)" t-as="tax">
Poderia ser lambda x: x.percent_amount or x.value_amount

2021-03-06 21:32 UTC, renatonlima approved these changes

2021-03-06 21:36 UTC, rvalyi approved these changes

2021-03-06 21:36 UTC, rvalyi commented
/ocabot merge minor

2021-03-06 21:58 UTC, merged