[12.0][ADD] Fiscal Operations
OCA/l10n-brazil pull request #1201
Opened 2021-03-11 14:16 UTC by luismalta

Hi guys. 
This PR adds the following Fiscal Operations:

- Remessa para industrialização por encomenda
- Retorno de mercadoria ou bem recebido para conserto ou reparo

2021-03-11 15:02 UTC, mileo commented
Bacana, pode criar e entrada do reparo tb?

2915 - Entrada de mercadoria ou bem recebido para conserto ou reparo

cc: @marcelsavegnago

2021-03-11 15:17 UTC, renatonlima requested changes

2021-03-11 15:17 UTC, renatonlima commented on l10n_br_fiscal/data/operation_data.xml
> +        <field name="fiscal_type">sale</field>
O tipo esta errado, deve ser: return_out

2021-03-11 15:17 UTC, renatonlima commented on l10n_br_fiscal/data/operation_data.xml
> +        <field name="default_price_unit">sale_price</field>
O preço deve ser o de custo e não o de venda.

2021-03-11 15:17 UTC, renatonlima commented on l10n_br_fiscal/data/operation_data.xml
> +        <field name="fiscal_type">sale</field>
O tipo esta errado, deve ser: return_out

2021-03-11 15:17 UTC, renatonlima commented on l10n_br_fiscal/data/operation_data.xml
> +        <field name="default_price_unit">sale_price</field>
O preço deve ser o de custo e não o de venda.

2021-03-11 15:19 UTC, renatonlima commented
Seria interessante criar as respectivas operações de entrada e relaciona-las para facilitar a utilização e geração das operações inversas de devolução.

2021-03-11 15:50 UTC, mileo commented
Não esqueça também de nos dados de demo parametrizar as linhas das operações, para que elas contemplem a tributação correta, assim como alguns exemplos de notas fiscais.

2021-03-19 16:00 UTC, luismalta commented
Olá pessoal. Eu e o @ygcarvalh, fizemos algumas correções e adições solicitadas. Se puderem da uma olhada novamente para vê se eram essas modificações esperadas mesmo, obrigado.

2021-03-19 16:49 UTC, marcelsavegnago commented on l10n_br_fiscal/data/l10n_br_fiscal_tax_icms_data.xml
> +<!--  &lt;!&ndash; PIS - Saída de Retorno para Reparo &ndash;&gt;-->
Favor remover se este trecho não for necessário.

2021-03-19 16:49 UTC, marcelsavegnago commented on l10n_br_fiscal/data/l10n_br_fiscal_tax_icms_data.xml
> +  <!--  &lt;!&ndash; PIS - Entrada de Retorno para Reparo &ndash;&gt;-->
idem

2021-03-20 00:10 UTC, ygcarvalh commented
Não conseguimos encontrar nenhuma tributação envolvendo o PIS/COFINS envolvendo as duas operações de entrada, por isso não temos certeza se esses dois dados vão ou não ser necessários.

2021-03-22 13:27 UTC, ygcarvalh commented
Olá, pessoal. Eu acho que conseguimos entender as operações de entrada e de saída envolvendo o CFOP e dessa maneira foi possível corrigir um erro envolvendo as relacionadas com operações de reparo. Além disso, as devidas tributações foram colocadas.

Se puderem olhar novamente se tudo está correto.

Obrigado.

2021-03-22 13:50 UTC, mileo commented
@ygcarvalh Pode verificar o travis?

2021-03-22 13:53 UTC, ygcarvalh commented
> @ygcarvalh Pode verificar o travis?

Posso sim

2021-04-08 00:16 UTC, marcelsavegnago commented
@mileo consegue revisar ?

2021-04-08 00:21 UTC, mileo commented
> @mileo consegue revisar ? alias.. está pronta para revisão ? :D

Pelo que eu olhei não esta 100% pronta, mas já da pra fazer o merge desta forma, esta faltando implementar uns testes/dados de demo.

Mas o @luismalta e @ygcarvalh estão focados em finalizar o https://github.com/OCA/l10n-brazil/pull/1240 e https://github.com/akretion/l10n-brazil/pull/164 antes que são garantia que a NF-e esta estabilizada.

2021-04-08 00:22 UTC, marcelsavegnago commented
> > @mileo consegue revisar ? alias.. está pronta para revisão ? :D
> 
> Pelo que eu olhei não esta 100% pronta, mas já da pra fazer o merge desta forma, esta faltando implementar uns testes/dados de demo.
> 
> Mas o @luismalta e @ygcarvalh estão focados em finalizar o #1240 e [akretion#164](https://github.com/akretion/l10n-brazil/pull/164) antes que são garantia que a NF-e esta estabilizada.

perfeito

2021-04-08 13:13 UTC, luismalta commented
Bom dia pessoal. Esse PR está pronto para a revisão.

2021-04-08 16:16 UTC, marcelsavegnago approved these changes
LGTM

2021-04-08 16:17 UTC, marcelsavegnago commented
> Bom dia pessoal. Esse PR está pronto para a revisão.

@mileo altera as tags da PR por favor. thanks

2021-04-08 17:19 UTC, renatonlima requested changes, later dismissed

2021-04-08 17:19 UTC, renatonlima commented on l10n_br_fiscal/data/l10n_br_fiscal_tax_icms_data.xml
> +  <!-- ICMS - Remessa de Industrialização -->
Por favor mova todos os tax.definition criados para os fiscal_operation_line_id para o arquivo data/operation_data.xml

2021-04-09 13:15 UTC, ygcarvalh commented on l10n_br_fiscal/data/l10n_br_fiscal_tax_icms_data.xml
> +  <!-- ICMS - Remessa de Industrialização -->
Modificações realizadas

2021-04-09 23:42 UTC, mileo approved these changes

2021-04-10 14:04 UTC, mileo commented
/ocabot merge patch

2021-04-10 14:28 UTC, merged