[FIX] remove copy=True in invoice_state field
OCA/l10n-brazil pull request #1214
Opened 2021-03-16 18:51 UTC by renatonlima

Corrige o problema relatado no issue #1200

2021-03-16 18:56 UTC, rvalyi approved these changes, later dismissed

2021-03-16 18:58 UTC, marcelsavegnago approved these changes

2021-03-16 19:32 UTC, mileo requested changes
Could you override the copy method and check if the record is a backorder, keeping the invoice_state field?

2021-03-16 19:52 UTC, renatonlima commented
> Could you override the copy method and check if the record is a backorder, keeping the invoice_state field?

It's not necessary, because in l10n_br_stock_account already done using the correct methods to copy invoice_state info https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_stock_account/models/stock_move.py#L117

2021-03-16 19:54 UTC, mileo approved these changes

2021-03-16 19:54 UTC, mileo commented
/ocabot merge minor

2021-03-19 02:39 UTC, renatonlima commented
Pessoal, verificando melhor, eu fiz a correção deste PR, mas vi que na verdade isso e uma parte do código que esta no l10n_br_stock_account/models/stock_move.py deveria estar no módulo stock_picking_invoicing na OCA, até para que o módulo da OCA funcione de forma melhor. eu criei esse PR https://github.com/OCA/account-invoicing/pull/894 quem puder revisar lá, porque com esse PR resolvemos o problema deste PR e também removemos algumas linhas do módulo l10n_br_stock_account.

2021-03-22 11:18 UTC, mileo commented
@renatonlima pode dar amend desses commits?

2021-03-22 23:40 UTC, renatonlima commented
@mileo,

Um commit foi feito no stock_picking para corrigir o bug do atributo copy=True no invoice_state e outro commit foi feito no stock_move para adaptar as mudanças realizadas no PR OCA/account-invoicing#894 eu não necessidade de fazer amend dos commits!

2021-03-23 10:12 UTC, mileo approved these changes

2021-03-23 10:12 UTC, mileo commented
/ocabot merge nobump

2021-03-23 10:13 UTC, mileo commented
> @mileo,
> 
> Um commit foi feito no stock_picking para corrigir o bug do atributo copy=True no invoice_state e outro commit foi feito no stock_move para adaptar as mudanças realizadas no PR [OCA/account-invoicing#894](https://github.com/OCA/account-invoicing/pull/894) eu não necessidade de fazer amend dos commits!

Eu não vejo necessidade de quebrar commits tão pequenos no mesmo módulo e com a mesma função. Só servem para aumentar a quantidade de commits.

2021-03-23 11:59 UTC, merged