[12.0][ADD] Calculation of MVA
OCA/l10n-brazil pull request #1223
Opened 2021-03-18 14:26 UTC by gabrielcardoso21

This Pull Request makes the calculation of the ICMSST take the MVA Percent of the tax into cosideration to reach its final value.

2021-03-18 16:56 UTC, marcelsavegnago commented
@gabrielcardoso21 check travis erros please.

2021-03-22 11:21 UTC, mileo approved these changes

2021-03-22 11:48 UTC, mileo commented
@luismalta Could you review this PR plz?

2021-03-22 12:21 UTC, luismalta approved these changes
LGTM

2021-03-22 13:29 UTC, mileo commented
Pessoal estou revisando novamente este PR, pois estou confirmando outro bug no fiscal.

2021-03-22 14:25 UTC, mileo commented
> Pessoal estou revisando novamente este PR, pois estou confirmando outro bug no fiscal.

2021-03-22 14:27 UTC, mileo commented
Ops, fechei sem querer.

2021-03-24 19:04 UTC, marcelsavegnago commented
@gabrielcardoso21 pode fazer o rebase ?

2021-03-25 20:39 UTC, renatonlima requested changes

2021-03-25 20:39 UTC, renatonlima commented on l10n_br_fiscal/models/tax.py
> +            if tax_dict.get("icmsst_mva_percent"):
Essa parte do código deve ser implementada no método _compute_icmsst

2021-03-25 20:39 UTC, renatonlima commented on l10n_br_fiscal/models/tax.py
> +        tax_dict["icmsst_mva_percent"] = tax.icmsst_mva_percent
Essa parte do código deve ser implementada no método _compute_icmsst

2021-03-26 16:19 UTC, marcelsavegnago commented
@gabrielcardoso21 pode verificar o travis ?

2021-03-28 22:30 UTC, mileo approved these changes

2021-03-28 22:30 UTC, mileo commented
LGTM, tested on runbot

2021-03-28 22:48 UTC, marcelsavegnago commented
> LGTM, tested on runbot

Neste caso é válido remover o block do @renatonlima e solicitar uma nova revisão já que em tese as solicitações dele foram atendidas.

2021-03-29 16:44 UTC, ygcarvalh approved these changes

2021-04-01 01:16 UTC, renatonlima approved these changes

2021-04-01 01:17 UTC, renatonlima commented
/ocabot merge nobump

2021-04-01 02:05 UTC, merged