[FIX] Demo company partner number
OCA/l10n-brazil pull request #1231
Opened 2021-03-19 14:34 UTC by mileo

Corrige o número da empresa que não esta sendo setado nos dados de demo das empresas Main company e Lucro Presumido.

2021-03-19 14:37 UTC, mileo commented
cc: @luismalta  e @ygcarvalh

2021-03-19 16:41 UTC, renatonlima requested changes
Não entendi a necessidade este PR pode explicar melhor o motivo desta alteração?

2021-03-19 17:08 UTC, mileo commented
> Não entendi a necessidade este PR pode explicar melhor o motivo desta alteração?

Eu tb não me aprofundei para explicar, entretanto só a empresa do simples esta com número da empresa setado. (Se for testar no runbot, cuidado que eu acessei lá e alterei da instância 12.0)

Creio que seja algo que esteja relacionado ao inverse. Entretanto somente a empresa do simples esta com o número definido, sem debugar e me aprofundar muito reparei que:

https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_base/demo/res_company_demo.xml#L60-L82

Só ela não redefine os dados de endereço que já esta definido no parceiro, e fiz a mesma coisa pras outras nesse PR.

2021-03-19 17:09 UTC, mileo commented
Isso é um dos pontos que ferram os testes automatizados da NF-e que estamos trabalhando fazem uns 10 dias.

Creio que o time consiga subir isso hj.

2021-03-19 18:59 UTC, renatonlima commented
@mileo,

Independente do problema relatado por você no base.main_company, você não deve usa-lo  para fazer os testes da NFe porque não vai funcionar corretamente no travis, lá a sequencia de instalação acaba instalado o l10n_generic_coa na empresa base.main_company, por isso eu criei a empresa l10n_br_base.empresa_simples_nacional para fazer os testes fiscais e contábeis da localização.

2021-03-19 20:03 UTC, mbcosta commented
@mileo tem alterações de ordem de campos e uma remoção de endereço e eu também não estou entendendo o que remover dados de endereço podem resolver em um teste, se vocês encontraram algum problema com campos inverse reportem melhor o problema.

2021-03-19 21:16 UTC, mileo commented
> @mileo,
> 
> Independente do problema relatado por você no base.main_company, você não deve usa-lo para fazer os testes da NFe porque não vai funcionar corretamente no travis, lá a sequencia de instalação acaba instalado o l10n_generic_coa na empresa base.main_company, por isso eu criei a empresa l10n_br_base.empresa_simples_nacional para fazer os testes fiscais e contábeis da localização.

Não estamos usando ele para os testes, mas a empresa esta s/ número.

@mbcosta 

Este problema só acontece através de dados XML, se vc criar uma empresa pela interface isso não ocorre, ou alterar o número da empresa via interface.

Esta só foi a forma mais simples de resolver o problema dos testes, sem precisar debugar e refatorar o código do cadastro da empresa, que tem aquele link com as taxas que será trabalhoso.

2021-03-19 21:16 UTC, mileo commented
E alem disso ele reduz a quantidade de código.

2021-03-19 21:18 UTC, mileo commented
Mas eu não consegui acessar o runbot para verificar se o problema foi efetivamente resolvido.

Então vou pedir para o @luismalta confirmar se com esse commit o problema esta finalizado. Pois o problema pode estar em algum outro ponto / módulo.

2021-03-20 19:16 UTC, renatonlima commented
Pessoal, eu entendi o problema, basicamente, quando se carrega os dados de demo de um parceiro o método https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_base/models/res_partner.py#L236 _set_street, como esta lendo o país do company e esse campo é calculado ele vai pegar os dados do company que esta implemento, então esta correto deixar o endereço do base.main_partner.

2021-03-20 19:18 UTC, renatonlima approved these changes

2021-03-20 20:00 UTC, marcelsavegnago approved these changes

2021-03-20 20:14 UTC, renatonlima commented
/ocabot merge nobump

2021-03-20 20:37 UTC, merged