[12.0][ADD] Invisible fields to persist sale line taxes
OCA/l10n-brazil pull request #1234
Opened 2021-03-19 17:06 UTC by gabrielcardoso21

The values of the taxes bases and values change with the discount onchange, but are not persisted to the lines. The result is that when we invoice the sale order (directly or through stock pickings), the values in the invoice are correct, but the taxes bases and values in the invoice lines are wrong. This Pull Request adds the missing fields invisible in the sale order line tree view so they can be persisted in the database.

2021-03-19 17:11 UTC, mileo commented
@gabrielcardoso21 vale fazer a mesma coisa para os outros módulos purchase / repair e etc

2021-03-19 17:11 UTC, mileo approved these changes

2021-03-19 17:12 UTC, mileo commented
Vale tb dar uma revisa aqui: 

https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml

Ver se vc não esqueceu nenhum campo.

2021-03-19 17:27 UTC, rvalyi commented
ta meio esquezito accrescentar esses campos um a um, nao deveria sera feito pelo fields_view_get do mixin?

2021-03-19 17:35 UTC, renatonlima requested changes
Eu não estou certo da necessidade de existir esses campos na visão tree...

2021-03-19 17:35 UTC, marcelsavegnago commented
> ta meio esquezito accrescentar esses campos um a um, nao deveria sera feito pelo fields_view_get do mixin?

Pensei a mesma coisa.

2021-03-19 17:38 UTC, gabrielcardoso21 commented
> Eu não estou certo da necessidade de existir esses campos na visão tree...

These fields exist in the form view and are not being persisted. If there's another way of persisting them without they're present in the tree view I'll be glad to change the approach.

2021-03-19 17:42 UTC, gabrielcardoso21 commented
> ta meio esquezito accrescentar esses campos um a um, nao deveria sera feito pelo fields_view_get do mixin?

The problem is that there is just a few fields that need to be included. In theory, the only ones that need to be included are the base and the value of the taxes. But it sure can be done, even with a search in line mixin fields terminated in `'_base'` or `'_value'`, I'll look into it. Thank you.

2021-03-26 17:17 UTC, gabrielcardoso21 commented
Solved by: https://github.com/OCA/l10n-brazil/pull/1175

2021-03-26 17:17 UTC, closed without merging