[FIX] Processador edoc OCA on nfse
OCA/l10n-brazil pull request #1241
Opened 2021-03-23 10:07 UTC by mileo

2021-03-23 12:35 UTC, gabrielcardoso21 approved these changes

2021-03-23 15:11 UTC, marcelsavegnago commented
@mileo pode verificar os erros do travis ?

2021-03-24 03:41 UTC, rvalyi requested changes

2021-03-24 03:41 UTC, rvalyi commented on l10n_br_nfse/models/document.py
> +    if (record.processador_edoc == PROCESSADOR_OCA and
nesse filtro, para a NFe eu tive que bolar mais uma condiçao. Pois agora, com a integraçao entre o invoice e  o documento fiscal, pode ter algum teste num outro modulo que procura validar uma invoice qualquer ate d eoutra empresa e pode passar no seu override de transmissao de NFSe. Nisso se nao tiver certificado para NFSe ou configuraçao para NFSe vai dar pau.

Veja esse tipo de bug que eu peguei no PR da NFe:

![2021-03-24_00-36](https://user-images.githubusercontent.com/16926/112250972-1d728100-8c39-11eb-9540-5d7bed1b84b3.png)


https://travis-ci.com/github/OCA/l10n-brazil/jobs/493271652

No module l10n_br_nfe tinha o mesmo tipo de problema depois do rebase e eu resolvi adicionando mais essa condiçao no filtro:

```
    if config['test_enable'] and not record.company_id.certificate_nfe_id:
        return False
```
nesse commit https://github.com/OCA/l10n-brazil/pull/1043/commits/4ef7c5aae3f374f248b8fb52cdf7050c5f3c9649

Ainda pegamos o bug com a nfse ate vc botar algo semelhante mas no caso da nfe ja resolveu.

2021-03-24 13:00 UTC, rvalyi commented on l10n_br_nfse/models/document.py
> +    if (record.processador_edoc == PROCESSADOR_OCA and
na vdd, ja concertando o filtro como vc fez é provavel que resolve os testes e a maioria dos casos. Mas eu acho melhor fazer o que eu fiz na NFe e eu propois ainda assim porque facilmente la no futuro a gente tem alguma nfse de alguma empresa sem processador configurado que acaba sendo validado num teste, ai fica melhor a gente aproveitar para ja matar esse problema. Logico como tem mais testes com NFe do que com NFSe hoje a gente apenas pegou o problema mais generico no caso da NFe mas com o aumento do coverage vale a pena anticipar.

2021-03-24 14:18 UTC, rvalyi commented
@mileo @gabrielcardoso21 se puderem dar um gas nesse PR por favor, ta pegando bastante essa interference no l10n_br_nfse com os outros tests...

2021-03-25 01:00 UTC, mileo commented
@rvalyi @marcelsavegnago @renatonlima @gabrielcardoso21 podem revisar por favor?

2021-03-25 01:09 UTC, marcelsavegnago approved these changes
LGTM

2021-03-25 02:32 UTC, rvalyi requested changes
No geral eu acho OK, mas eu prefiro que vc joga esse ´create_fake_certificate_file´ la no erpbrasil.assinatura. Tem mais a ver para ser encapsulado la e compratilhado entre as versoes do Odoo do que de engordar o modulo l10n_br_fiscal com coisa que nao tem a ver com Odoo e fica melhor fora dele. 
cc @renatonlima

2021-03-25 09:39 UTC, mileo commented on l10n_br_fiscal/tools/misc.py
> +        TODO: Move this method to erpbrasil
Sim @rvalyi até coloquei um comentário aqui.

Essa semana já esta na minha lista fechar uma nova versão das libs do erpbrasil, assim que der tempo de fazer isso, eu faço um PR removendo/alterando isso.

2021-03-25 14:56 UTC, gabrielcardoso21 approved these changes

2021-03-25 15:00 UTC, marcelsavegnago commented on l10n_br_fiscal/tools/misc.py
> +        TODO: Move this method to erpbrasil
@mileo Provisoriamente e com o objetivo de eliminar os entraves para os demais merges eu acho válido.

2021-03-25 15:19 UTC, rvalyi requested changes
Eu posso ate aceitar a presencia temporaria do gerador de certificado no l10n_br_fiscal, mas os botoes para gerir os cerificidados, IMHO isso tem que ir nos modulos respeitivos. Senao a gente ja abre a perna para ter 200 linhas de codigo a mais no l10n_br_fiscal qdo tiver mais documentos fiscais e isso certamente nao é uma arquitetura viável.

2021-03-25 15:19 UTC, rvalyi commented on l10n_br_fiscal/models/res_company.py
> +            )
na minha opinaio esses botaoes devem ser implementados nos respeitivos modulos apenas. Nao da para ir copiando no l10n_br_fiscal as pecularidades de cada documento fiscal. A gente tem que estar preocupado em tirar codigo do modulo fiscal ou dividir ele, nao fazer esse tipo de codigo eu acho. Porque de poucos em poucos é assim que se cria um montro e desculpa mas no passado @mileo vc ja mostrou que por vc ta tudo bem ter modulos enormes e sem testes alias. Mas nos modulos que a gente usa com nossos clientes eu acho que a gente tem direito de nao aceitar essa deriva.

2021-03-25 15:19 UTC, rvalyi commented on l10n_br_fiscal/views/res_company_view.xml
>                              </group>
mesmo comentario, mover esses botoes nos respeitivos modulos.

2021-03-25 15:20 UTC, rvalyi commented
sugiro esperar ver com o @renatonlima ja que toca no modulo l10n_br_fiscal que ele desenhou e mantem uns 90% valeu.

2021-03-25 15:31 UTC, rvalyi commented on l10n_br_fiscal/tools/misc.py
> +        TODO: Move this method to erpbrasil
blz eu posso ate aceitar isso de forma temporaria.
Porem vi outros problemas que eu comentei num novo review.

2021-03-25 19:10 UTC, renatonlima commented
Algumas observações sobre a alterações deste PR:

 Eu concordo em criar certificados fakes para as empresas que estão nos dados de demonstração, mas isso deve ser carregado no hook do l10n_br_fiscal.

1. Para mim esta tudo bem mover o método de criação do certificado falso ir para no erpbrsasil mas por enquanto ficar no misc do l10n_br_fiscal 👍 
2. Eu não vejo utilidade funcional em colocar um botão para criar um certificado digital fake porque isso não tem utilidade nenhuma funcional assim como a criação de um campo is_fake no objeto de certificado 👎

2021-03-25 19:10 UTC, renatonlima submitted a review, later dismissed
Algumas observações sobre a alterações deste PR:

Eu concordo em criar certificados fakes para as empresas que estão nos dados de demonstração, mas isso deve ser carregado no hook do l10n_br_fiscal.

Para mim esta tudo bem mover o método de criação do certificado falso ir para no erpbrsasil mas por enquanto ficar no misc do l10n_br_fiscal 👍
Eu não vejo utilidade funcional em colocar um botão para criar um certificado digital fake porque isso não tem utilidade nenhuma funcional assim como a criação de um campo is_fake no objeto de certificado 👎

2021-03-25 19:12 UTC, marcelsavegnago commented
> Eu não vejo utilidade funcional em colocar um botão para criar um certificado digital fake porque isso não tem utilidade nenhuma funcional assim como a criação de um campo is_fake no objeto de certificado 👎

Fato

2021-03-26 00:17 UTC, mileo commented
Pessoal corrigido as questões citadas, obrigado pela revisão.

A ideia do campo "is_fake" era criar possibilidades de funcionais com o certificado fake em um ambiente de testes/runbot, mas mais pra frente vejo isso.

@rvalyi @renatonlima @marcelsavegnago

2021-03-26 00:28 UTC, rvalyi submitted a review, later dismissed
OK

2021-03-26 00:39 UTC, rvalyi commented
@mileo tem so uma besterinha de PEP8 https://travis-ci.com/github/OCA/l10n-brazil/jobs/493885930#L437

2021-03-26 00:46 UTC, mileo commented
> @mileo tem so uma besterinha de PEP8 https://travis-ci.com/github/OCA/l10n-brazil/jobs/493885930#L437

Corrigido

2021-03-26 00:48 UTC, rvalyi approved these changes
OK

2021-03-26 00:51 UTC, rvalyi commented
/ocabot merge major

2021-03-26 02:20 UTC, merged