[12.0][FIX] ICMS Tax Definition NBM not existent
OCA/l10n-brazil pull request #1246
Opened 2021-03-24 16:50 UTC by gabrielcardoso21

2021-03-24 17:12 UTC, renatonlima commented
@gabrielcardoso21,

In ICMS Tax definitions there are some NCMs, CESTs and NBM, could you add these records in demo data files?

2021-03-24 17:17 UTC, gabrielcardoso21 commented
> @gabrielcardoso21,
> 
> In ICMS Tax definitions there are some NCMs, CESTs and NBM, could you add these records in demo data files?

@luismalta Can you explain here, please?

2021-03-24 18:11 UTC, luismalta commented
Olá pessoal, explicando a necessidade da correção introduzida pelo Gabriel.

 Durante os testes dos dados de demo do PR https://github.com/OCA/l10n-brazil/pull/1240 , observamos que existia um problema na definição de impostos padrões. Em bases de demonstração, algumas das definições de impostos do ICMS Regulation cai na condição de ser uma definição genérica (https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_fiscal/models/icms_regulation.py#L1087). Isso ocorre pois o CEST usado para preencher o dado dessa definição não existe nos dados de demonstração. Por tanto, ele sendo considerado uma definição genérica ele acaba sendo usado como uma definição de ICMS padrão. 

Exemplo: Usar um produto com uma NCM que não se encontra em nenhuma definição fiscal para realizar uma venda para dentro do estado de São Paulo. A definição de ICMS padrão deveria ser a de 18% (tax_icms_regulation_sp_sp_icms_18_default), porém é selecionado o imposto de ICMS de 7% (tax_icms_regulation_sp_sp_icms_7). Apesar da definição do icms de 7% possuir o NBM 4014.10.0000 setado (https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_fiscal/data/l10n_br_fiscal_icms_tax_definition_data.xml#L3317), esse NBM não está nos dados de demonstração e por isso ele não vai para os campos de nbm_ids e a definição 'tax_icms_regulation_sp_sp_icms_7' passar a ser considerada como padrão. Provavelmente por ela ser definida antes da de 18% ela acaba sendo usada na venda.

2021-03-24 18:21 UTC, luismalta commented
Se for testado essa situação no runbot desse PR e comparar com um runbot da 12.0 é possível validar que o problema foi corrigido

2021-03-24 18:24 UTC, mileo commented
> Se for testado essa situação no runbot desse PR e comparar com um runbot da 12.0 é possível validar que o problema foi corrigido

Era por isso que eu estava confuso se o PR #1223 estava pronto para o merge.

2021-03-24 18:26 UTC, mileo commented
> > Se for testado essa situação no runbot desse PR e comparar com um runbot da 12.0 é possível validar que o problema foi corrigido
> 
> Era por isso que eu estava confuso se o PR #1223 estava pronto para o merge.

Vou testar aqui e já comento.

2021-03-24 19:03 UTC, renatonlima commented
@luismalta,

Existe duas formas para resolver esse problema

1. Deixar o tax.definition com o xml_ref_id (tax_icms_regulation_sp_sp_icms_7) com o state draft
2. Da forma que o @gabrielcardoso21 resolveu em adicionar o NBM

Antes era carregado todos os dados de NCM, CST, NBS, NBM na criação do banco de dados, mas como isso ficava muito pesado, decidimos reduzir esses arquivos quando o banco de dados for carregado com dados de demo para a criação da base de dados ficar mais rápida, a maioria dos tax.definitions que não são padrões eu deixei com o state 'draft' mas por isso que comentei com o @gabrielcardoso21 que talvez é bom verificar se ficou mais algum tax def com dados de NCM, NBS, CEST ou NBM

2021-03-24 21:05 UTC, mileo approved these changes

2021-03-24 21:07 UTC, mileo commented
> @luismalta,
> 
> Existe duas formas para resolver esse problema
> 
> 1. Deixar o tax.definition com o xml_ref_id (tax_icms_regulation_sp_sp_icms_7) com o state draft
> 2. Da forma que o @gabrielcardoso21 resolveu em adicionar o NBM
> 
> Antes era carregado todos os dados de NCM, CST, NBS, NBM na criação do banco de dados, mas como isso ficava muito pesado, decidimos reduzir esses arquivos quando o banco de dados for carregado com dados de demo para a criação da base de dados ficar mais rápida, a maioria dos tax.definitions que não são padrões eu deixei com o state 'draft' mas por isso que comentei com o @gabrielcardoso21 que talvez é bom verificar se ficou mais algum tax def com dados de NCM, NBS, CEST ou NBM

Outra coisa a considerar seria a busca dos generics resultar em mais de um registro, seria correto avisar o usuário com um warning. Pois uma tributação incorreta pode ser carregada.

Estou aprovando este PR pois a solução já resolve o problema e mantem o caso de teste com o 
    <field name="nbms">4014.10.0000</field>
funcionando tb.

2021-03-25 02:11 UTC, renatonlima requested changes

2021-03-25 02:11 UTC, renatonlima commented on l10n_br_fiscal/demo/l10n_br_fiscal.nbm-demo.csv
> +nbm_4014100000,4014.10.0000,"PRESERVATIVO DE BORRACHA VULCANIZADA,N/ENDURECIDA",40141000
Seria bom você adicionar pelo menos o [NCM](https://github.com/OCA/l10n-brazil/blob/8eafc35e63b2f6f32cc105647159e1b9d488959d/l10n_br_fiscal/demo/l10n_br_fiscal.ncm-demo.csv) no arquivo de demo  4014.10.00 relacionado ao NBM

2021-03-25 02:22 UTC, mileo commented on l10n_br_fiscal/demo/l10n_br_fiscal.nbm-demo.csv
> +nbm_4014100000,4014.10.0000,"PRESERVATIVO DE BORRACHA VULCANIZADA,N/ENDURECIDA",40141000
Feito

2021-03-25 14:46 UTC, renatonlima approved these changes

2021-03-25 14:47 UTC, renatonlima commented
/ocabot merge nobump

2021-03-25 15:17 UTC, merged