[FIX] Evento de cancelamento
OCA/l10n-brazil pull request #1256
Opened 2021-03-26 03:59 UTC by mileo

2021-03-26 14:17 UTC, gabrielcardoso21 approved these changes

2021-03-26 15:27 UTC, mileo commented
@gabrielcardoso21 pode revisar novamente plz

cc: @renatonlima @rvalyi @marcelsavegnago

2021-03-26 16:11 UTC, marcelsavegnago commented on l10n_br_fiscal/wizards/wizard_document_cancel.py
>                  'cancel_document_event_id': cancel.id,
Acho que ficou errado.. nao deveria ser document_cancel_id ?

2021-03-26 16:30 UTC, gabrielcardoso21 commented on l10n_br_fiscal/models/document_eletronic.py
> +    cancel_event_id = fields.Many2one(
When is this field filled?

2021-03-26 17:50 UTC, gabrielcardoso21 commented on l10n_br_fiscal/models/document_eletronic.py
> +    cancel_event_id = fields.Many2one(
Found it https://github.com/akretion/l10n-brazil/pull/171

2021-03-26 18:57 UTC, mileo commented
Pessoal ainda estou resolvendo um problema nesse PR e testando ele junto com o da correção do fechamento fiscal 
#1221

2021-03-29 20:24 UTC, renatonlima requested changes
@mileo,


Eu havia feito um refactoring porque os eventos fiscais não estão bem implementados, eu havia feito um PR https://github.com/OCA/l10n-brazil/pull/983, mas esse acabou deixando para depois porque na época precisava estabilizar o módulo de l10n_br_nfe e havia outros PRs importantes como o https://github.com/OCA/l10n-brazil/pull/1175 (Totais no mixin), https://github.com/OCA/l10n-brazil/pull/1146 (Edição da Fatura e Documento Fiscal)

Eu fiz o rebase do PR https://github.com/OCA/l10n-brazil/pull/983 e seria interessante resolver os problemas da implementação primeiro.

2021-04-18 19:15 UTC, marcelsavegnago commented
@mileo houve algum problema no runbot ?

2021-04-18 19:16 UTC, marcelsavegnago commented
@mileo pode corrigir os erros do travis ?

2021-04-20 13:36 UTC, mileo commented
Pessoal estou encerrando este PR pois ele foi integrado no #1300 se possível revisem ele, minha previsão é finaliza-lo hoje até o fim da tarde.

2021-04-20 13:36 UTC, closed without merging