[12.0][IMP] Variables for ICMSSN
OCA/l10n-brazil pull request #1270
Opened 2021-04-08 18:03 UTC by ygcarvalh

Good afternoon people.

This PR adds some variables that were missing for the calculation of the taxation of Simples Nacional and was affecting the generation of the fields of the NF-e when the CSOSN was worth 500 or 900.

I also put these fields in the view and the conditions for them to appear only when they are needed.

2021-04-08 18:03 UTC, ygcarvalh commented
@mileo @luismalta

2021-04-12 14:57 UTC, gabrielcardoso21 approved these changes

2021-04-12 16:22 UTC, marcelsavegnago approved these changes
LGTM

2021-04-12 16:22 UTC, marcelsavegnago requested changes
@ygcarvalh  Pode verificar os erros do travis por favor ?

2021-04-13 18:01 UTC, marcelsavegnago commented
![image](https://user-images.githubusercontent.com/3595132/114599103-0daef100-9c69-11eb-9820-6fd575e58c00.png)

cc @mileo @ygcarvalh @luismalta @DiegoParadeda @gabrielcardoso21

2021-04-14 11:40 UTC, ygcarvalh commented
@marcelsavegnago @mileo se puderem revisar novamente.

Outro ponto é que essa ainda semana vou fazer um novo PR para calcular essas novas variáveis que foram criadas.

2021-04-14 13:22 UTC, marcelsavegnago approved these changes
lgtm

2021-04-19 11:07 UTC, mileo approved these changes

2021-04-19 11:09 UTC, mileo commented on l10n_br_fiscal/models/document_fiscal_line_mixin.py
> +    effective_base_value = fields.Monetary(string="Effective Base Value")
Esses campos não deveriam iniciar com icms_? @ygcarvalh

2021-04-19 11:36 UTC, mileo commented on l10n_br_fiscal/models/document_fiscal_line_mixin.py
> +
Ainda não esta legal, tenta seguir a nomemclatura atual, por exemplo:

https://github.com/OCA/l10n-brazil/blob/4112414667b72b023a6b92ed91aa929899d70353/l10n_br_fiscal/models/document_fiscal_line_mixin.py#L340-L350

```
    # vBC - Valor da base de cálculo do ICMS
    icms_base = fields.Monetary(string="ICMS Base")

    # pICMS - Alíquota do IMCS
    icms_percent = fields.Float(string="ICMS %")

    # pRedBC - Percentual de redução do ICMS
    icms_reduction = fields.Float(string="ICMS % Reduction")

    # vICMS - Valor do ICMS
    icms_value = fields.Monetary(string="ICMS Value")
```

2021-04-19 11:45 UTC, mileo commented on l10n_br_fiscal/models/document_fiscal_line_mixin.py
> +
icms_effective_base_value -> icms_effective_base
icms_effective_percent ok
icms_effective_base_percent -> icms_effective_reducion
icms_effective_value ok

2021-04-19 13:32 UTC, mileo approved these changes

2021-04-19 13:32 UTC, mileo commented
/ocabot merge patch

2021-04-19 13:40 UTC, renatonlima approved these changes

2021-04-19 15:57 UTC, mileo commented
/ocabot merge patch

Tentando novamente!

2021-04-19 15:59 UTC, mileo commented
O erro foi no webservice do correios que parece estar fora do ar:

2021-04-19 21:34 UTC, merged