[12.0][IMP] Test and demo products for NF-e
OCA/l10n-brazil pull request #1281
Opened 2021-04-15 13:50 UTC by ygcarvalh

Hey guys.

This PR aims to test the new testing framework with the new demo data.

2021-04-18 16:48 UTC, mileo commented
@ygcarvalh fiz um rebase e salvei uma cópia da branch antiga em: https://github.com/kmee/l10n-brazil/tree/backup/imp/nfe_demo_tests_oca/l10n_br_fiscal/l10n_br_fiscal

2021-04-18 16:50 UTC, mileo commented
Pelo que eu entendi os commits desse PR https://github.com/OCA/l10n-brazil/pull/1240 estão contidos aqui é isso?

Só para facilitar a obtenção do coverage e dos testes automatizados.

2021-04-18 17:07 UTC, ygcarvalh commented
> Pelo que eu entendi os commits desse PR #1240 estão contidos aqui é isso?
> 
> Só para facilitar a obtenção do coverage e dos testes automatizados.

Isso mesmo.

2021-04-18 17:32 UTC, mileo commented
@ygcarvalh tem um erro nos testes: https://travis-ci.com/github/OCA/l10n-brazil/jobs/499323551#L2553

2021-04-18 18:28 UTC, ygcarvalh commented
> @ygcarvalh tem um erro nos testes: https://travis-ci.com/github/OCA/l10n-brazil/jobs/499323551#L2553

Acho que consegui ver qual era o problema:

As alterações para o testes precisaram de modificações tanto no módulo da nfe quanto no módulo fiscal. Houve a alteração do NCM no módulo fiscal, porém o mesmo não foi feito no da nfe, por isso o erro de referência externa. Mas acredito que agora isso tenha sido solucionado.

Vou ficar de olho no runbot e no travis pra ver se vai ter mais algum erro.

cc: @mileo

2021-04-18 18:56 UTC, ygcarvalh commented
@mileo pode ver o erro que deu no travis? é algo relacionado com o serialize da nfe

2021-04-18 19:04 UTC, mileo commented
Creio que essa linhas não são necessárias, pois não estão sendo usadas para nada.

https://github.com/kmee/l10n-brazil/blob/imp/nfe_demo_tests_oca/l10n_br_nfe/tests/test_nfe_serialize_sn.py#L10-L11
https://github.com/kmee/l10n-brazil/blob/imp/nfe_demo_tests_oca/l10n_br_nfe/tests/test_nfe_serialize_lc.py#L10-L11

E elas não estão sendo consideradas da forma correta no 

https://github.com/kmee/l10n-brazil/blob/imp/nfe_demo_tests_oca/l10n_br_nfe/tests/test_nfe_serialize.py

2021-04-19 10:58 UTC, luismalta commented
> Creio que essa linhas não são necessárias, pois não estão sendo usadas para nada.
> 
> https://github.com/kmee/l10n-brazil/blob/imp/nfe_demo_tests_oca/l10n_br_nfe/tests/test_nfe_serialize_sn.py#L10-L11
> https://github.com/kmee/l10n-brazil/blob/imp/nfe_demo_tests_oca/l10n_br_nfe/tests/test_nfe_serialize_lc.py#L10-L11
> 
> E elas não estão sendo consideradas da forma correta no
> 
> https://github.com/kmee/l10n-brazil/blob/imp/nfe_demo_tests_oca/l10n_br_nfe/tests/test_nfe_serialize.py

As linhas não estão sendo usadas pois com os rebases as mudanças no framework dos testes foram perdidas. Ainda é necessário refazer esse framework considerando as mudanças aplicadas no PR de NF-e. Só então as linhas referenciadas farão sentido.

2021-05-14 15:59 UTC, mileo commented
Podem verificar o erro no runbot:

```
2021-05-14 15:33:03,327 177 WARNING openerp_test odoo.models: l10n_br_fiscal.document.create() with unknown fields: document_section
2021-05-14 15:33:06,185 177 WARNING openerp_test odoo.models: l10n_br_fiscal.document.create() with unknown fields: document_section
2021-05-14 15:33:09,046 177 WARNING openerp_test odoo.models: l10n_br_fiscal.document.create() with unknown fields: document_section
2021-05-14 15:33:11,859 177 WARNING openerp_test odoo.models: l10n_br_fiscal.document.create() with unknown fields: document_section
2021-05-14 15:33:14,742 177 WARNING openerp_test odoo.models: l10n_br_fiscal.document.create() with unknown fields: document_section
2021-05-14 15:33:17,612 177 WARNING openerp_test odoo.models: l10n_br_fiscal.document.create() with unknown fields: document_section
 ```

2021-06-10 14:31 UTC, ygcarvalh commented
Bom, atualizamos esse PR também, assim como fizemos com o https://github.com/OCA/l10n-brazil/pull/1240 e o https://github.com/OCA/l10n-brazil/pull/1275. No caso, esse PR utiliza dos campos adicionados no 1275 e dos dados adicionados em 1240 e realiza os testes.

2021-06-14 12:43 UTC, rvalyi requested changes
Pessoal, esse PR ta bem perto para mim. Aprovei o outro https://github.com/OCA/l10n-brazil/pull/1275. Para esse #1281 porem, eu acho que vou sugerir uma mudança. Tenho uma reunião agora, mas daqui o inicio da tarde eu comento de novo. Por mim podem proseguir com o merge do #1275.

2021-06-14 20:57 UTC, mileo commented
@ygcarvalh pode fazer um rebase?

2021-06-14 21:25 UTC, ygcarvalh commented
> @ygcarvalh pode fazer um rebase?

posso sim

2021-06-15 01:52 UTC, rvalyi approved these changes
Olhando bem, ta OK por mim. Valeu pelo trabalho! isso vai trazer mais segurança quando a gente mexer nos módulos.

2021-06-15 01:55 UTC, renatonlima approved these changes

2021-06-15 01:56 UTC, renatonlima commented
/ocabot merge nobump

2021-06-15 02:27 UTC, merged