[12.0][REF] Delivery Costs( Freight, Insurance and Other Value )
OCA/l10n-brazil pull request #1301
Opened 2021-04-19 21:36 UTC by mbcosta

Refectoring Delivery Costs( Freight, Insurance and Other Value )

Alterações:
* Questões de autoria referente ao modulo l10n_br_delivery https://github.com/OCA/l10n-brazil/issues/1252 ( PSCs por favor validem quem e quais empresas devem constar no modulo ) 
* Criado Parâmetro para definir se os valores de entrega Frete, Seguro e Outros Valores devem ser informados "Por Linhas" ( caso onde as linhas podem ter valores diferentes e não se quer ratear o valor ) ou "Por Total" ( caso onde é informado apenas o valor total e será rateado os valores por linhas ) dentro do modulo l10n_br_sale
* Movido métodos de inversão de campos no caso de rateio do l10n_br_delivery para o l10n_br_sale, pois esses campos já existem ao instalar apenas o l10n_br_sale
* Apagado o arquivo que implementava os campos inversos no Documento Fiscal porque o valor deve ser definido por linha e caso se queira lá informar apenas os Valores Totais e esses valores serem rateados por linha isso deve ser implementado pelo wizard  https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_fiscal/wizards/l10n_br_account_invoice_costs_ratio.py ( TODO )
* Retornado os objetos l10n_br_delivery.carrier.vehicle e l10n_br_delivery.shipment https://github.com/OCA/l10n-brazil/blob/10.0/l10n_br_delivery/models/l10n_br_delivery.py https://github.com/OCA/l10n-brazil/blob/10.0/l10n_br_delivery/views/l10n_br_delivery_view.xml ( verificar o Cabeçalho de Licença do arquivo pois mantive o que existia, já que não houve grande mudança, deveria ser alterado ? )
* Incluído Teste do caso de valores diferentes nas linhas, onde não deve ocorrer o rateio dos valores, e comentado teste onde já não é mais possível a edição dos Valores Totais no Documento Fiscal.

cc @renatonlima @rvalyi @mileo @gabrielcardoso21

2021-04-24 21:06 UTC, renatonlima approved these changes

2021-04-27 20:12 UTC, renatonlima requested changes
@mbcosta 

Eu testei e se a opção do lançamento dos valores por linha e esta dando um erro ao criar um novo pedido de venda em loop

2021-05-03 15:22 UTC, mbcosta commented
Corrigido o erro de recursividade e foram incluídas as seguintes alterações e melhorias:
* O name_get do objeto account.incoterms retornar o "Codigo - Descrição", muitas pessoas no Brasil conhecem mais os tipos de Frete pela sigla em inglês do que pela descrição tanto em inglês quanto português, antes:

![image](https://user-images.githubusercontent.com/6341149/116893736-b072e380-ac07-11eb-9f8f-8ea392292220.png)

depois:
![image](https://user-images.githubusercontent.com/6341149/116893789-bff22c80-ac07-11eb-847a-8b709008d243.png)

* Incluído dois campos tipo 'compute' com o Total de Peso e Volume no Pedido de Venda/sale.order em muitos casos a empresa usa essa informação para fazer a cotação do valor do frete, mesmo antes de gerar a nota fiscal

![image](https://user-images.githubusercontent.com/6341149/116895643-cb465780-ac09-11eb-808c-56b90ba09634.png)

2021-05-20 01:25 UTC, marcelsavegnago requested changes

2021-05-20 01:25 UTC, marcelsavegnago commented on l10n_br_delivery/__manifest__.py
> +    'version': "14.0.1.0.0",
Porque 14 ?

2021-05-20 01:35 UTC, rvalyi commented on l10n_br_delivery/__manifest__.py
> +    'version': "14.0.1.0.0",
ostentação!

2021-05-20 01:36 UTC, marcelsavegnago commented on l10n_br_delivery/__manifest__.py
> +    'version': "14.0.1.0.0",
hahahahahahhahahahahahahahahahahhahahaha

2021-05-20 13:56 UTC, rvalyi commented on l10n_br_delivery/__manifest__.py
> +    'version': "14.0.1.0.0",
foi um commit errado, eu tirei.

2021-06-10 15:54 UTC, renatonlima commented
@mbcosta,


Você pode fazer o rebase desta branch?

2021-07-14 18:43 UTC, renatonlima commented
@mbcosta,


Você pode dá uma olhada no erro do travis? https://app.travis-ci.com/github/OCA/l10n-brazil/jobs/524473845#L4366

2021-07-15 21:36 UTC, mbcosta commented
ola @renatonlima , pelo o que entendi do erro isso está acontecendo devido a alteração que ocorre no campo price_unit da stock.move ao Confirmar o stock.picking devido aos métodos de Valorização de Estoque do core eu procurei resolver esse problema aqui https://github.com/OCA/l10n-brazil/pull/1523

2021-08-17 18:31 UTC, renatonlima commented
@mileo,

You added  "blocked" label in this PR, but it is important that you comment and explain the reason that you added this and we debate about changes of this PR.

2021-08-17 18:31 UTC, renatonlima commented
@mbcosta please can you rebase?

2021-08-17 19:40 UTC, rvalyi commented on l10n_br_delivery/models/sale_order.py
>      )
Ola @mbcosta eu tambem pensei igual vc num projeto. Porem uma galera de peso mergulhou nessa questão agora (featuring @legalsylvain @dreispt ) e a conclusão é que o o campo weight do Odoo v12 é mesmo o peso BRUTO.

Por isso nesse module, o @legalsylvain adiciona o peso liquido de volta com net_weight https://github.com/OCA/product-attribute/pull/894

as justificativas de interpretar dessa maneira podem ser lida aqui:
https://github.com/OCA/product-attribute/pull/894#issuecomment-893683814
ou aqui:
https://github.com/OCA/product-attribute/pull/894#issuecomment-894089008

Eu nao recomando de depender do módulo para apenas um campo. Mas o que deve ser feito nesse modulo l10n_br_delivery é ter aderencia com os campos weight (peso bruto) e net_weight (peso liquido) do modulo do Sylvain https://github.com/OCA/product-attribute/pull/894/files

Vc ja avaliou se isso teria um impacto no que vc fez aqui?

Agora no stock.picking, vc tem o peso bruto incluindo as embalagens aqui pelo modulo delivery:
https://github.com/odoo/odoo/blob/12.0/addons/delivery/models/stock_picking.py#L28

cc @renatonlima @marcelsavegnago

2021-08-19 19:10 UTC, mbcosta commented on l10n_br_delivery/models/sale_order.py
>      )
ola @rvalyi 
Aqui apenas existia um campo compute para o Total do Peso, agora que está identificado como sendo o Peso Bruto eu deixei isso explicito na definição e descrição do campos.

Sobre depender desse modulo ele é bem simples( adiciona apenas um campo ), teria que confirmar se existe necessidade do Peso Liquido na NFe( Alguém sabe informar? ), se sim não vejo como não depender.

2021-08-20 13:29 UTC, mbcosta commented on l10n_br_delivery/models/sale_order.py
>      )
Até onde vi não há obrigação em informar o Peso Liquido na NFe.

2021-08-20 13:51 UTC, rvalyi commented on l10n_br_delivery/models/sale_order.py
>      )
legal ai depois poderia ter algum glue-module opcional, mas não depender por padrão.

2021-08-23 04:40 UTC, rvalyi commented
/ocabot rebase

2021-08-23 05:30 UTC, rvalyi commented
@mbcosta achei o problema e resolvi, comentei aqui https://github.com/OCA/l10n-brazil/pull/1587
Dei um rebase desse PR em cima desse fix na 12.0,.

2021-08-23 18:55 UTC, rvalyi requested changes
almost OK, Excellent work! Please also remove the models/stock_picking.py file entirely as it is not used anywhere at all anymore.

2021-08-23 18:55 UTC, rvalyi commented on l10n_br_delivery/__manifest__.py
> +        'l10n_br_account',
remove l10n_br_account, this is implied by l10n_br_sale_stock already

2021-08-23 23:48 UTC, rvalyi approved these changes

2021-08-24 01:01 UTC, rvalyi requested changes
Ola @mbcosta vc esqueceu de remover o arquivo models/stock_picking.py isso não esta usado em lugar nenhum.

2021-08-24 03:30 UTC, rvalyi approved these changes
Falei besteira, o override no stock_picking.py tá sendo chamado no módulo delivery. Portanto tá tudo OK.

2021-08-24 03:30 UTC, renatonlima approved these changes

2021-08-24 03:31 UTC, renatonlima commented
/ocabot merge nobump

2021-08-24 04:00 UTC, renatonlima commented
/ocabot merge nobump

2021-08-24 06:00 UTC, merged