[FIX] Invoice Refund
OCA/l10n-brazil pull request #1317
Opened 2021-04-29 16:00 UTC by mileo

Depends of #1296 

O domínio do campo force_fiscal_operation_id não esta pegando, creio que vale a pena resolver isso somente depois do merge do #1300.

2021-05-11 02:09 UTC, mileo commented
@gabrielcardoso21 pode revisar plz?

2021-05-11 02:49 UTC, mileo commented
@renatonlima se vc puder dar uma olhada tb!

2021-05-11 12:50 UTC, gabrielcardoso21 commented on l10n_br_account/models/account_invoice.py
> +        self.invalidate_cache()
Is this line still necessary?

2021-05-11 13:00 UTC, gabrielcardoso21 commented on l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
> +                self.env.context.get('TAX_CALC_MANUAL')):
Shoud the variable in the context be 'TAX_CALC_MANUAL' or TAX_CALC_MANUAL (without the single quotes)? I didn't find any use of it in the code to be able to deduce it.

2021-05-11 13:07 UTC, mileo commented on l10n_br_account/models/account_invoice.py
> +        self.invalidate_cache()
No thanks

2021-05-11 14:52 UTC, mileo commented
@gabrielcardoso21 pode revisar novamente fiz algumas alterações na questão do contexto, veja se ficou bom.

2021-05-11 18:15 UTC, gabrielcardoso21 approved these changes

2021-05-11 18:30 UTC, marcelsavegnago commented
@mileo pode verificar os erros do travis ?

2021-05-11 18:39 UTC, mileo commented
> @mileo pode verificar os erros do travis ?

Corrigido

2021-05-12 17:06 UTC, mileo commented
@rvalyi @renatonlima @marcelsavegnago conseguem revisar?

2021-05-12 17:15 UTC, marcelsavegnago approved these changes
LGTM

2021-05-12 17:17 UTC, mileo commented
Lembrando que essa lógica pode ser explorada nos casos das compras e importações de notas fiscais.

2021-05-13 13:20 UTC, renatonlima requested changes, later dismissed

2021-05-13 13:20 UTC, renatonlima commented on l10n_br_fiscal/models/operation_line.py
> +    tax_calc = fields.Selection(
Seria interessante esse campo não ser um related e não ser requerido para permitir alterar o método de calculo dos impostos a nível da linha da operação caso seja necessário especificar um método diferente a operação fiscal, deixaria mais especifico.

2021-05-13 13:20 UTC, renatonlima commented on l10n_br_account/wizards/account_invoice_refund.py
> +    use_origin_tax = fields.Boolean(
Como já existe o parâmetro nas operações fiscais eu acho esse opção no wizard inconsistente deixar isso a cargo do usuário que vai fazer a devolução, deveria ser usado a opção da operação fiscal.

2021-05-13 13:20 UTC, renatonlima commented on l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
> +        tax_calc = self.env.context.get('TAX_CALC_OVERRIDE',
Ao invés de usar uma chave no contexto seria melhor usar a opção da linha da operação fiscal ou da operação fiscal (nesta sequencia).

2021-05-14 12:29 UTC, gabrielcardoso21 approved these changes

2021-05-14 14:01 UTC, mileo commented
Pessoal finalizei o trabalho nesse PR, esse domino do force vou abrir um issue.

2021-05-16 02:44 UTC, marcelsavegnago approved these changes

2021-05-16 14:34 UTC, rvalyi commented
pessoal, so blocando esse PR por enquanto para nao rolar merge de bobeira ja que é relativamente impactante. A gente começou a olhar mas talvez tem algumas coisas importantes que a gente queria mudar. Logo vem mais do @renatonlima .

2021-05-17 13:51 UTC, mileo commented
@renatonlima @rvalyi Bom dia algum posicionamento sobre o PR?

2021-05-19 10:57 UTC, mileo commented
> @renatonlima @rvalyi Bom dia algum posicionamento sobre o PR?

Bom dia pessoal, 

Algum motivo para segurar esse PR?

2021-05-19 18:21 UTC, marcelsavegnago commented
@mileo pode fazer o rebase fazendo favor?

2021-05-19 18:32 UTC, mileo commented
@marcelsavegnago rebase feito

2021-05-21 19:34 UTC, mileo commented
> > @renatonlima @rvalyi Bom dia algum posicionamento sobre o PR?
> 
> Bom dia pessoal,
> 
> Algum motivo para segurar esse PR?

Algum motivo para segurar esse PR? @renatonlima @rvalyi

2021-05-21 19:49 UTC, rvalyi commented
> > > @renatonlima @rvalyi Bom dia algum posicionamento sobre o PR?
> > 
> > 
> > Bom dia pessoal,
> > Algum motivo para segurar esse PR?
> 
> Algum motivo para segurar esse PR? @renatonlima @rvalyi

eu acho que nao mais do que esse que ta um ano mais velho https://github.com/OCA/l10n-brazil/pull/768
mas vamos olhar sim. Se vc observar esses dias a gente ja dedicou bastante horas para revisar seus PR's de graça.
Ate onde eu vejo nos outros repos vc nao tem a coragem de ter fazer essa pressaozinha toda https://github.com/OCA/contract/pull/626
Eu so nao entendo porque vc faz isso nesse repo, mas eu acho problematico.

2021-05-23 00:59 UTC, mileo commented
> > > > @renatonlima @rvalyi Bom dia algum posicionamento sobre o PR?
> > > 
> > > 
> > > Bom dia pessoal,
> > > Algum motivo para segurar esse PR?
> > 
> > 
> > Algum motivo para segurar esse PR? @renatonlima @rvalyi
> 
> eu acho que nao mais do que esse que ta um ano mais velho #768
> mas vamos olhar sim. Se vc observar esses dias a gente ja dedicou bastante horas para revisar seus PR's de graça.
> Ate onde eu vejo nos outros repos vc nao tem a coragem de ter fazer essa pressaozinha toda [OCA/contract#626](https://github.com/OCA/contract/pull/626)
> Eu so nao entendo porque vc faz isso nesse repo, mas eu acho problematico.

Posso citar alguns também que andamos revisando de vocês esta semana inclusive:
 
https://github.com/OCA/sale-workflow/pull/955
https://github.com/OCA/sale-workflow/pull/1117

E não tem pressão, só tem um block que não tem explicação, se algo errado é só falar que ficaremos feliz em corrigir ou implementar algo diferente, como já implementado nas sugestões feitas acima pelo @renatonlima.

Quanto o #768 vou voltar a olhar ele semana q vem, pelo que me lembro comentei sobre isso em algum PR essa semana, mas comento aqui novamente: O @gabrielcardoso21 vai assumir o #1355 com o auxilio do @bmessiaz e eu vou retomar a parte bancária.

2021-05-25 13:53 UTC, mileo commented
> > > @renatonlima @rvalyi Bom dia algum posicionamento sobre o PR?
> > 
> > 
> > Bom dia pessoal,
> > Algum motivo para segurar esse PR?
> 
> Algum motivo para segurar esse PR? @renatonlima @rvalyi

Alguma novidade deste PR?

2021-05-26 06:31 UTC, rvalyi commented
Essa é uma das nossas prioridades. So que vai precisar o @renatonlima olhar bem é desde a semana é fogo a gente migrou nosso maior cliente do Brasil da v8 para a v12, deu um certo trabalho digamos... Mas agora ta aliviando, deveria ser possivel. Mas de uma forma geral, se vc olhar nos outros repos da OCA, o que ajuda é mandar os PRs da forma mais independente possiveis e nao juntar varios PRs em coisas grandes, em especial quando vc pretende que seja incluido em modulos de terceiros. Nao falo desse em especial, mas de outros na vdd.

2021-05-26 19:31 UTC, renatonlima requested changes
Eu fiz algumas anotações, é importante dividir esse PR em 2:

1. A alteração do modo de calculo das operações fiscais, isso é muito critico e hoje a implementação tem regressões e correções que precisam ser feitas e é importante adicionar pelo menos 3 testes para cada modo de calculo para certificar que a mudança não quebra o motor atual de calculo.

2. A correção das NF-e de de devolução.

2021-05-26 19:31 UTC, renatonlima commented on l10n_br_fiscal/models/document_fiscal_mixin.py
> +    fiscal_operation_tax_calc = fields.Selection(
Esse campo não tem utilidade....

2021-05-26 19:31 UTC, renatonlima commented on l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
> +        if (self.fiscal_operation_line_id.tax_calc == TAX_CALC_MANUAL or
Tem que testa se a linha da operação fiscal existe senão vai ter um erro https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py#L384, isso é importante quando for criado uma fatura não fiscal por exemplo...

2021-05-26 19:31 UTC, renatonlima commented on l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
> +        tax_calc = self.env.context.get('TAX_CALC_OVERRIDE',
Esse conceito de TAX_CALC_OVERRIDE não é bom, se uma operação ou linha de operação esta definida o tax_calc, isso tem que ser preservado, imagine que a contabilidade configura as operações fiscais e valida essas configurações, depois o faturista faz uma nota de devolução e altera o modo de calculo... Isso vai gerar inconsistência!

2021-05-26 19:31 UTC, renatonlima commented on l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
>              self.comment_ids = self.fiscal_operation_line_id.comment_ids
Se o método de calculo for manual não vai copiar as observações da linha da operação fiscal

2021-05-26 19:31 UTC, renatonlima commented on l10n_br_fiscal/models/operation_line.py
> +        if tax_calc == TAX_CALC_ONLY:
Se esse método for chamado com o TAX_CALC_MANUAL vai calcular automaticamente os impostos... o correto seria fazer if tax_calc != TAX_CALC_AUTO

2021-05-26 19:31 UTC, renatonlima commented on l10n_br_account/models/account_invoice.py
> +            'document_serie_id',
Seria bom fazer uma devolução de compras.... devia considerar os campos de um documento fiscal de entrada...

2021-05-27 00:23 UTC, rvalyi commented
Pessoal quando tiver separado os PRs em 2 como o @renatonlima pediu eu reviso mais a parte técnica... No aguardando.

2021-05-28 14:30 UTC, renatonlima commented
Como esse PR foi dividido nos dois PRs:

https://github.com/OCA/l10n-brazil/pull/1412;
https://github.com/OCA/l10n-brazil/pull/1413;

Esse PR vai ser fechado!

2021-05-28 14:30 UTC, closed without merging