[12.0][FIX] Exportation of tag ICMSUFDest and calculation of DIFAL
OCA/l10n-brazil pull request #1318
Opened 2021-05-03 13:49 UTC by gabrielcardoso21

This Pull Request fixes the exportation of the tag ICMSUFDest and the calculation of DIFAL values.

2021-05-03 18:52 UTC, renatonlima requested changes
@gabrielcardoso21,

Por favor veja as observações que comentei, um ponto importante é que no método de '_export_fields' você não deve fazer nenhum tipo de calculo, pois isso já é feito e armazenado nos campos icms_ da linha do documento fiscal. O motivo para isso é para não não fragmentar o calculo dos impostos em vários lugares  o que dificultaria consideravelmente a manutenção futura e eliminar os riscos de bugs.

2021-05-03 18:52 UTC, renatonlima commented on l10n_br_nfe/models/document_line.py
> +            if self.document_id.partner_id.state_id.code in [
Esta lógica esta errada, o correto é pegar o percentual do ICMS na UF de destino usando o regulamento do ICMS, pois essas alíquotas são as principais, mas em todos os estados existem aliquotas diferenciadas por exemplo em SP móveis para escritório é tributado 12% e não 17,5%

2021-05-03 18:52 UTC, renatonlima commented on l10n_br_nfe/models/document_line.py
> +            self.nfe40_pICMSInterPart = 100.0
O campo nfe40_pICMSInterPart deveria ser um related do campo https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_fiscal/models/document_fiscal_line_mixin.py#L437

2021-05-03 18:52 UTC, renatonlima commented on l10n_br_nfe/models/document_line.py
>  ICMSSN_CST_CODES_USE_102 = ('102', '103', '300', '400')
Pessoal essas constantes deveriam ficar no módulo l10n_br_fiscal/constants/fiscal.py ou icms.py para pode ser reutilizadas.

2021-05-04 18:10 UTC, gabrielcardoso21 commented
@renatonlima This pull request was a necessary roll back to this commit https://github.com/OCA/l10n-brazil/commit/9b880608dd3e3d9a12d87c906889d6b8744e241b. The new logic implemented does not work, and we had some problems to solve it by the way used to fill the ICMS fields. We need to be careful to implement the exportation of the tag `ICMSUFDest`, because the decision to export it or not is not as simple and direct as other tags in the `Imposto` XML tag. We'll analize the code structure and come up with a solution that agrees with the new way of exporting the XML. Thanks for the feedback.

2021-05-05 17:41 UTC, marcelsavegnago commented
Grande @gabrielcardoso21 ... em um teste recente tive problema com esta tag. Fiz o merge desta PR no ambiente e pelo menos a tag está preenchido 🥳 ... Estou aguardando meu cliente enviar o xml das NFs para eu poder avaliar melhor.

2021-05-08 21:56 UTC, rvalyi commented
a forma correcta foi implementada nesse outro PR https://github.com/OCA/l10n-brazil/pull/1328, por isso fechando esse. Valeu pela proposta.

2021-05-08 21:56 UTC, closed without merging