[12.0][FIX] Grouping by operation_line
OCA/l10n-brazil pull request #1322
Opened 2021-05-06 13:05 UTC by gabrielcardoso21

The grouping by operation line in the picking invoicing was not working properly. This pull request fixes that.

2021-05-06 13:29 UTC, mileo commented
@gabrielcardoso21 Pode fazer essa opção a opção padrão?

2021-05-06 15:45 UTC, mbcosta commented
@gabrielcardoso21 qual erro gerou esse FIX por favor você poderia explicar e colocar um Log com o erro ? O código foi pensando para concatenar/juntar o KEY que vem do modulo stock_picking_invoicing e acredito que isso foi testado.

2021-05-06 16:54 UTC, mileo commented
@mbcosta 

Crie uma venda c/ 1 item, c/ 200 unidades;

Separe no picking 250 unidades;

O resultado na fatura, sera uma fatura/edoc com 2 itens.

2021-05-06 16:55 UTC, mileo commented
@gabrielcardoso21 pode dar uma olhada no travis?

2021-05-06 19:58 UTC, mbcosta commented
@mileo testei esse processo com a branch 12 e dados de demo e está criando apenas uma linha, não seria outro erro ? Por favor verifique se as "branchs" que vocês estão utilizando estão atualizadas e se não há um modulo que vocês estejam utilizando que está sobre escrevendo o método.

![image](https://user-images.githubusercontent.com/6341149/117358108-25564f80-ae8c-11eb-83bf-f16762a8b1ea.png)

![image](https://user-images.githubusercontent.com/6341149/117358162-343d0200-ae8c-11eb-8040-58483be1aac1.png)

![image](https://user-images.githubusercontent.com/6341149/117358205-40c15a80-ae8c-11eb-8f15-d64d29bcdb87.png)

2021-05-14 12:30 UTC, renatonlima commented
@mielo e @gabrielcardoso21

Vocês conseguiram reproduzir esse erro? Porque como o @mbcosta comentou a criação da fatura no picking gera uma linha da fatura para uma stock.move, me parece inválido esse PR eu vou marcar com o label até vocês conseguirem reproduzir o erro.

2021-05-14 13:26 UTC, mileo commented
> @mielo e @gabrielcardoso21
> 
> Vocês conseguiram reproduzir esse erro? Porque como o @mbcosta comentou a criação da fatura no picking gera uma linha da fatura para uma stock.move, me parece inválido esse PR eu vou marcar com o label até vocês conseguirem reproduzir o erro.

Isso esta relacionado com as rotas, fica um pouco difícil de explicar, vou fazer um video.

2021-05-15 02:44 UTC, renatonlima requested changes
Reproduzir o erro mencionado...

2021-05-17 18:44 UTC, bmessiaz commented
OI Gabriel e Pessoal,
 
                                Simulei a situação no runbot Merge PR #1361 into 12.0 OCA-git-bot, está gravado lá.
                                - Instalei o módulo de manufacturing
                                -  Dupliquei um produto "Corner Desk Black (copy)"
                                -  Na aba inventory marquei -> Make To Order, Manufacture
                                -  Informei para ele ter 1 item no Bills of Materials.
                                - Gravei uma produção maior do que a programação 200 --> 210 produzido.
                                - Ao gerar a Invoice.. aparecem os dois itens separados.
                                - Configuração do faturamento está entre as imagens abaixo.
                                - Ordem de Venda SO037
                                - 
![imagem_2021-05-17_153828](https://user-images.githubusercontent.com/44352660/118539554-ed6dc880-b725-11eb-9159-f3f41049a88e.png)

![imagem_2021-05-17_153626](https://user-images.githubusercontent.com/44352660/118539299-a4b60f80-b725-11eb-8451-bc1d197c3194.png)
![imagem_2021-05-17_153654](https://user-images.githubusercontent.com/44352660/118539343-b5668580-b725-11eb-8838-d06d3f68730a.png)

![imagem_2021-05-17_154131](https://user-images.githubusercontent.com/44352660/118539895-5a815e00-b726-11eb-9a8e-9a81e5a1ee2a.png)

2021-05-18 14:35 UTC, bmessiaz commented
@gabrielcardoso21, @mielo e @renatonlima

Simulei no Runbot e funcionou agora a unificação dos itens, a quantidade total dos itens já estavam corretas..só não estavam agrupadas em um só item (produto) <- Reclamação do Cliente .

Replicados as mesmas configurações da minha primeira simulação.
Rodei em --> https://runbot.odoo-community.org/runbot/build/3483591
![imagem_2021-05-18_113413](https://user-images.githubusercontent.com/44352660/118670407-f8c7ff00-b7cc-11eb-929f-bf2a15b741a3.png)

2021-05-19 13:59 UTC, rvalyi commented
pessoal, não sei se é relacionado mas de qualquer forma eu acho bom informar aqui: passando o flake8 no l10n_br_stock_account vi que tinha 2 testes diferente com o mesmo o metodo test_picking_invoicing_by_product2 que estava duplicado. Nisso parece que apenas o segundo test estava rodando:
https://github.com/OCA/l10n-brazil/pull/1372/files#diff-caf48ee2bec2303273698e88862df08897b1c9d17d15d4917b0cf3e06f16db36R251

Quando alterei o segundo metodo test_picking_invoicing_by_product2 para test_picking_invoicing_by_product3, o primeiro test_picking_invoicing_by_product2 passou a ser testado e ta dando erro:
https://travis-ci.com/github/OCA/l10n-brazil/jobs/506295755#L3166

cc @gabrielcardoso21 @mbcosta @renatonlima

2021-05-20 21:59 UTC, renatonlima commented
Pessoal,

Isso não é um problema da localização, é um problema do core eu criei um issue no repo do Odoo explicando o que acontece https://github.com/odoo/odoo/issues/71124 é possível corrigir isso no l10n_br_stock_account com apenas uma linha de código.

Isso acontece apenas se você faz uma venda MTO e gera a NF-e baseada no Picking nas vendas MTS não acontece;
Se a NF-e for gerada através do pedido de venda e as quantidades baseadas nas entregas não acontece.

Fazer esse agrupamento por operação fiscal pode causar mais problemas como por exemplo se você tiver uma venda com a mesma operação fiscal mas com preços unitários diferentes.

2021-05-21 22:06 UTC, bmessiaz commented
@gabrielcardoso21 @mileo @renatonlima 

Fiz o teste no runbot..e funcionou o Wizard a seleção "Partner/Product".

Unificou os itens e as quantidades.


![imagem_2021-05-21_190511](https://user-images.githubusercontent.com/44352660/119202567-77d86400-ba67-11eb-8830-135287269377.png)
![imagem_2021-05-21_190550](https://user-images.githubusercontent.com/44352660/119202628-8e7ebb00-ba67-11eb-8929-0b6796779369.png)
![imagem_2021-05-21_190614](https://user-images.githubusercontent.com/44352660/119202645-9cccd700-ba67-11eb-9c79-3943a53b41ff.png)

2021-05-24 12:17 UTC, closed without merging

2021-05-25 14:37 UTC, renatonlima commented
> @gabrielcardoso21 @mileo @renatonlima
> 
> Fiz o teste no runbot..e funcionou o Wizard a seleção "Partner/Product".
> 
> Unificou os itens e as quantidades.
> 
> ![imagem_2021-05-21_190511](https://user-images.githubusercontent.com/44352660/119202567-77d86400-ba67-11eb-8830-135287269377.png)
> ![imagem_2021-05-21_190550](https://user-images.githubusercontent.com/44352660/119202628-8e7ebb00-ba67-11eb-8929-0b6796779369.png)
> ![imagem_2021-05-21_190614](https://user-images.githubusercontent.com/44352660/119202645-9cccd700-ba67-11eb-9c79-3943a53b41ff.png)

Eu havia esquecido, mas hoje já é possível agrupar por produtos, inclusive existe uma consistência para não permitir agrupar produtos com linhas de operações fiscais diferentes. Então na prática o agrupamento por produtos já faz exatamente o que é proposto neste PR.