12.0 praticas contabeis brasileiras
OCA/l10n-brazil pull request #1324
Opened 2021-05-06 15:43 UTC by bmessiaz

**Na versão 12.1.0.0.0 realizou-se uma revisão detalhada do plano visando uma melhor estruturação das
contas tanto sintéticas como analíticas:**

- Revisão dos grupos de contas corrigindo o sequenciamento em função da sua liquidez, conforme a publicação citada acima;
- Exclusão de grupos de contas não previstas nas normas do IFRS e CPC (Diferido/Realizável a Longo Prazo/Ativo Permanente);
- Atualização de contas analíticas visando uma melhor evidenciação das operações da empresa (Brindes/Venda de Ativo Fixo, etc);
- Criação do Grupo de Compensação, para o controle de remessas/retornos de itens/bens sem valor financeiro, de acordo com as práticas contábeis brasileiras.

Este pull request libera a continuidade do desenvolvimento do #1311

2021-05-06 16:41 UTC, marcelsavegnago commented
@bmessiaz pode verificar os erros do travis ?

2021-05-06 17:50 UTC, mileo commented on l10n_br_coa/data/account_type_data.xml
> +            <field name="internal_group">assets</field>
Deve ser **asset** e não assets

2021-05-06 18:36 UTC, bmessiaz commented on l10n_br_coa/data/account_type_data.xml
> +            <field name="internal_group">assets</field>
Ok Luis, valew.  Obrigado.

2021-05-06 20:36 UTC, renatonlima requested changes, later dismissed
- Tem que fazer squash de alguns commits;
- Tem que conferir as contas de dedução de receita (vendas) https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_coa_generic/data/account_tax_group.xml

2021-05-06 20:36 UTC, renatonlima commented on l10n_br_coa_generic/data/account.account.template.csv
> +coa_generic_111101,"1.1.1.1.01","Caixa Geral",,"coa_generic_1111","account.data_account_type_liquidity","1","l10n_br_coa_generic_template"
Deixa a coluna os valores da coluna id entre "" para aparecer o diff apenas do que foi alterado

2021-05-06 20:36 UTC, renatonlima commented on l10n_br_coa_generic/data/account_group.xml
>      <record id='coa_generic_1' model='account.group'>
Nos XMLs o padrão seria deixar em " ao invés de '

2021-05-07 22:15 UTC, bmessiaz commented on l10n_br_coa_generic/data/account_group.xml
>      <record id='coa_generic_1' model='account.group'>
corrigido.

2021-05-08 02:37 UTC, mileo commented
Corrigi três detalhes: 
- O número da versão que não podia ser 12.1;
- Duas contas que estavam com o número e o id externo iguais;
- A conta de fornecedores que trocou de número.

@bmessiaz parabéns pela contribuição, vai ser muito bom ter um **Contador** contribuindo com a localização.

2021-05-10 13:56 UTC, mileo commented on l10n_br_coa/data/account_type_data.xml
> +            <field name="name">Passivos / Outros / Compensação</field>
Melhor sem o S no final, somente "Passivo"

2021-05-10 14:03 UTC, gabrielcardoso21 approved these changes

2021-05-10 14:56 UTC, mileo approved these changes
LGTM

2021-05-10 16:31 UTC, marcelsavegnago approved these changes
LGTM

2021-05-10 19:35 UTC, mileo commented
/ocabot merge major

2021-05-10 20:32 UTC, merged