[12.0][NEW] Module l10n_br_account_nfe
OCA/l10n-brazil pull request #1378
Opened 2021-05-19 18:03 UTC by mbcosta

New module to integrate l10n_br_account and l10n_br_nfe when both are installed, for now just implement delivery information.

Depends https://github.com/OCA/l10n-brazil/pull/1301

Mapeando os campos do Responsável Fiscal do Frete e alterando o campo da transportadora para ser um res.partner

cc @renatonlima @rvalyi @marcelsavegnago @mileo @gabrielcardoso21

2021-05-21 19:33 UTC, mileo commented
Olá pessoal, eu sou extremamente contra esse tipo de módulo.

Ao meu ver a arquitetura do módulo fiscal foi feita para evitar esse tipo de **glue módule.**

Vou revisar o #1301 tb, mas creio que isso já seja um ponto a considerar na revisão do mesmo.

2021-05-25 20:48 UTC, mbcosta commented
@mileo o modulo foi pensado para permitir a instalação do l10n_br_nfe ou l10n_br_account de forma independente e quando ambos estiverem instalados fazer a integração entre eles, isso já havia sido proposto inicialmente no PR https://github.com/OCA/l10n-brazil/pull/753
 [l10n_br_account_nfe] module to work with NFe along with Odoo invoicing module, just like it used to be the case in the OCA localization till version 10. 

Você acredita que isso deve ser feito de outra forma, qual ? Isso deveria estar dentro do l10n_br_fiscal ? O modulo l10n_br_fiscal deveria ter dependência do delivery ? Porque o delivery tem dependência do sale_stock https://github.com/odoo/odoo/blob/12.0/addons/delivery/__manifest__.py#L16  que tem do stock_account https://github.com/odoo/odoo/blob/12.0/addons/sale_stock/__manifest__.py#L22 e esse do account https://github.com/odoo/odoo/blob/12.0/addons/stock_account/__manifest__.py#L22 então consequentemente o l10n_br_fiscal teria a dependência do account, acredito que a arquitetura foi pensada para não ter essa dependência direta.

cc @rvalyi @renatonlima parece que remoção do modulo l10n_br_account_nfe pelo pessoal da KMEE durante o P&D da NFe no PR https://github.com/OCA/l10n-brazil/pull/753 foi feita pelo motivo que o Luís apontou para bloquear esse PR, precisamos chegar a um consenso sobre essa arquitetura.

2021-08-31 01:03 UTC, renatonlima commented
Pessoal,


Neste caso especifico se faz necessário ter o módulo l10n_br_account_nfe para não quebrar a modularidade da localização.

@mileo,

Alguma sugestão para resolver este PR sem quebrar as dependências dos módulos?

2021-08-31 01:04 UTC, renatonlima commented
@mbcosta,


Você pode fazer um rebase deste PR?

2021-09-24 19:26 UTC, marcelsavegnago approved these changes
LGTM

2021-09-24 20:34 UTC, rvalyi requested changes
Pessoal, eu acho que esse modulo deveria ser chamado de l10n_br_delivery_nfe, porque ate onde eu vejo ele apenas integra campos de delivery com nfe hoje. E eu acho ruim de puxar tanta dependências no l10n_br_account_nfe. O l10n_br_account_nfe deveria depender apenas ou quase apenas de l10n_br_account e l10n_br_nfe.

Aqui estamos puxando nada menos do que:

- sale
- stock
- delivery

São muitas dependências pesadas para ser enfiado num modulo l10n_br_account_nfe, não? Então eu renomearia esse module l10n_br_delivery_nfe que poderia depender ou não de um eventual l10n_br_account_nfe. O que vcs acham?

2021-09-25 16:28 UTC, felipemotter approved these changes
Meus testes ficaram tudo de acordo. PR muito bem vinda e estou completamente de acordo com um módulo extra.

2021-09-25 21:16 UTC, netosjb approved these changes
Concordo com o @rvalyi o nome l10n_br_delivery_nfe se encaixa melhor

2021-09-27 14:03 UTC, marcelsavegnago commented
> Pessoal, eu acho que esse modulo deveria ser chamado de l10n_br_delivery_nfe, porque ate onde eu vejo ele apenas integra campos de delivery com nfe hoje. E eu acho ruim de puxar tanta dependências no l10n_br_account_nfe. O l10n_br_account_nfe deveria depender apenas ou quase apenas de l10n_br_account e l10n_br_nfe.
> 
> Aqui estamos puxando nada menos do que:
> 
> * sale
> * stock
> * delivery
> 
> São muitas dependências pesadas para ser enfiado num modulo l10n_br_account_nfe, não? Então eu renomearia esse module l10n_br_delivery_nfe que poderia depender ou não de um eventual l10n_br_account_nfe. O que vcs acham?

De acordo

2021-09-27 15:36 UTC, rvalyi commented
Pessoal, eu acharia bom o @renatonlima revisar. Por mim por cima ta top mais uma vez. Tb vale a pena mencionar que eu tinha feito um POC de modulo l10n_br_account_nfe não para fazer esse mapping de pagamento, mas quando eu bolei o sistema de _inherits para poder pilotar o documento fiscal pelo invoice Odoo, eu tb tinha prototipado uma forma de importar as NFe's pelo XML que tb importava os invoices: https://github.com/OCA/l10n-brazil/pull/753

Infelizmente depois o Gabriel tentou ajudar no PR mas se embananou com os commits e perdeu meu modulol10n_br_account_nfe . Mas a meu ver essa parte da importaçao que eu tinha bolado teria que ser resgatada nesse modulo l10n_br_account_nfe:
https://github.com/akretion/l10n-brazil/blob/12.0-l10n_br_account_nfe/l10n_br_account_nfe/models/account_invoice.py

Mas tudo bem isso pode ser feito depois. Tb é importante exergar que tem varias melhorias a ser feitas antes de finalizar essa coisa de importaçao de NFe. Tb tem varios niveis de importaçao como ja expliquei: a importaçao sistematica pelos bindings XML, uma camada de UI para lidar com os eventuais depares e uma camada de SOAP. @renatonlima e eu temos varios PR que vão subir para limpar a base da NFe antes de partir para essas camadas de UI e SOAP (o mileo tb prototipou umas coisas nesse sentido). Enfim é apenas para contextualizar as coisas que poderia ter ou não nesse modulo l10n_br_account_nfe depois desse PR.

cc @renatonlima @mbcosta @marcelsavegnago

2021-09-27 17:10 UTC, felipemotter commented
@rvalyi Acredito que você esteja falando do PR #1640 né? Se for o caso e esteja conflitando o escopo já criado, talvez possamos mudar para l10n_br_account_nfe_payment, fica ao critério da comunidade. Só vimos que seria algo importante pra comunidade, já que hoje pelo visto cada um ta fazendo de uma forma.

2021-09-27 17:19 UTC, rvalyi commented
@felipemotter foi mal, copiei o comentario la, valeu.

2021-09-27 18:47 UTC, mbcosta commented
Obrigado a todos pela revisão, o nome do modulo foi alterado para l10n_br_delivery_nfe conforme sugerido pelo @rvalyi

2021-09-27 19:47 UTC, rvalyi requested changes
@mbcosta quase OK. Se puder so fazer a mesma troca de nome no views/nfe_document_view.xml
l10n_br_account_nfe -> l10n_br_delivery_nfe ...

2021-09-27 20:10 UTC, renatonlima approved these changes

2021-09-27 20:10 UTC, rvalyi approved these changes

2021-09-27 20:11 UTC, rvalyi commented
/ocabot merge nobump

2021-09-27 21:24 UTC, merged