[12.0] Fiscal Document UOM and UOT fields
OCA/l10n-brazil pull request #1416
Opened 2021-05-28 12:26 UTC by renatonlima

Pessoal,

O mapeamento dos campos nfe40_uTrib e nfe40_uCom não estão corretos pois estão relacionados ao uom_id do cadastro de produtos, o correto é que esses campos sejam relacionados aos uot_id e uom_id respectivamente da linha do documento fiscal. Também foi feito uma correção no método de conversão de unidade de medida fiscal para manter a unidade fiscal na linha documento fiscal.

2021-05-31 17:30 UTC, gabrielcardoso21 approved these changes

2021-06-01 15:50 UTC, rvalyi requested changes
OK, porem do jeito que esta hoje isso quebra os testes:
https://travis-ci.com/github/OCA/l10n-brazil/jobs/508927938#L2787

2021-06-04 20:35 UTC, renatonlima commented
Resolvi o problema nos testes da unidade de medida e também resolvi uns bugs relacionado a quantidade tributária que na exportação e importação do XML não estava corretos.

2021-06-05 00:22 UTC, marcelsavegnago approved these changes

2021-06-05 15:20 UTC, rvalyi approved these changes

2021-06-05 15:21 UTC, rvalyi commented
/ocabot merge patch

2021-06-05 16:18 UTC, merged