[12.0][FIX] Don't add repeated comments
OCA/l10n-brazil pull request #1471
Opened 2021-06-14 14:23 UTC by gabrielcardoso21

With this pull request, the system doesn't add repeated comments when validating an invoice.

2021-06-14 14:28 UTC, rvalyi commented
Ola @gabrielcardoso21 tem alguma relação de dependencia com #1456 e #1455 ou os 3 PRs sao independentes?

2021-06-14 14:46 UTC, gabrielcardoso21 commented
@rvalyi é independente dos outros. Acabei de fechar o https://github.com/OCA/l10n-brazil/pull/1455 inclusive, porque o https://github.com/OCA/l10n-brazil/pull/1456 está resolvendo o mesmo problema.

2021-06-15 11:43 UTC, mileo requested changes

2021-06-15 11:43 UTC, mileo commented on l10n_br_fiscal/models/document_fiscal_mixin_methods.py
> +            if new_comment not in d.customer_additional_data:
`(d.customer_additional_data or "")`

2021-07-24 21:23 UTC, renatonlima commented
Pessoal,

recentemente o PR #1524 já resolve este problema e faz melhorias, eu vou fechar esse PR.

2021-07-24 21:23 UTC, closed without merging