[12.0][FIX] l10n_br_sale: recalculate the gross amount and get the correct tax series
OCA/l10n-brazil pull request #1511
Opened 2021-07-11 01:01 UTC by marcelsavegnago

- [X] https://github.com/OCA/l10n-brazil/issues/1510
- [X] https://github.com/OCA/l10n-brazil/issues/1508

2021-07-14 20:28 UTC, renatonlima requested changes
- [x] A Correção da série esta correta;
- [ ] Sobre o total o correto seria neste método da localização chamar o método _finalize_invoices como é chamado no core porque mantém a compatibilidade com o core e resolver o problema de recalcular https://github.com/odoo/odoo/blob/12.0/addons/sale/models/sale.py#L659

2021-07-14 20:59 UTC, marcelsavegnago commented
@renatonlima sobre o calculo do campo amount_price_gross acho que está relacionado com o fato dele ser store=true. Precisamos persistir este calculo ou podemos remover o store=true ?

2021-07-22 11:47 UTC, renatonlima commented
@marcelsavegnago,

Eu vou estudar melhor esses casos dos campos calculados no mixin, porque em alguns casos (eu testei em uma base de dados com muitos pedidos de vendas) hoje os campos injetados pelo document.fiscal.mixin são store=False e senti que esta degradando muito a performance, depois de revisar alguns PRs eu vou retomar esse trabalho no PR https://github.com/OCA/l10n-brazil/pull/1411

2021-08-03 18:57 UTC, marcelsavegnago commented
@renatonlima migrei a mudança da serie para a PR #1552  e deixei apenas a parte do calculo dos totais nesta PR.

2023-08-06 12:07 UTC, closed without merging