[FIX] Comment and additional data for document fiscal line
OCA/l10n-brazil pull request #1524
Opened 2021-07-16 00:28 UTC by felipkin

Erros encontrados ao revisar o fluxo de validação do documento fiscal, mais especificamente verificando os “comments” nas linhas do documento fiscal:

- Toda vez que é necessário revalidar um documento fiscal, o comment é adicionado novamente ao campo “additional_data”, sem apagar o anterior.
![repetitivo](https://user-images.githubusercontent.com/6812128/125873857-46434615-e9fd-4aaa-b167-ce66cd6f30d6.png)

- Se houver mais de um “comment” selecionado, um erro é acusado ao validar o documento.
![PR](https://user-images.githubusercontent.com/6812128/125873754-43004d8c-269b-452a-8c52-1d9f33d15d0c.gif)

Este PR pretende resolver este problemas, presumindo que é uma escolha permitir que o usuário possa colocar outras informações manuais diretamente no campo “additional_data” e múltiplos “comment”.

**Sou novo em tudo isso e dicas construtivas sempre são bem vindas, desculpem se fiz alguma besteira.

2021-07-16 00:35 UTC, netosjb approved these changes

2021-07-16 11:51 UTC, rvalyi commented
Ola @felipkin, valeu pela contribuição. Vc poderia por favor analisar e comentar sobre esses 2 outros PRs que pretendem resolver problemas com comentarios?

https://github.com/OCA/l10n-brazil/pull/1471
https://github.com/OCA/l10n-brazil/pull/1456

Eu queria ter certeza que vc esta ciente desses outros PRs e ver se algum é melhor do que o outro ou se eles se completam.

2021-07-16 15:57 UTC, netosjb commented
Pessoal, eu testei a #1471 mas da forma que está não resolve o problema por completo:

1) ainda dá erro se houver mais de um comment para processar.
![image](https://user-images.githubusercontent.com/634278/125974228-b362e9ad-0e62-48ec-b2eb-5c14c8cab5ce.png)

2) as mensagem ficam grudadas, falta um espaço entre elas:
![image](https://user-images.githubusercontent.com/634278/125974498-31c6d390-9432-44a2-b679-370fd84a4c4c.png)

3) se o comment for alterado ou for processado com um valor diferente, o comment anterior não é substituido.
![image](https://user-images.githubusercontent.com/634278/125975544-8ae14a60-af65-414e-b3d0-46cfa7063d63.png)

2021-07-16 18:05 UTC, felipkin commented
É exatamente como o @netosjb descreveu. 

Outra diferença é que aqui focamos apenas "comment" das lines, enquanto os PRs #1471 e #1456 também corrigem os "comment" dos documentos. 

Se for interessante, acredito que daria para abordar os "comment" do documento nesta PR, mas ainda não revisamos esta parte.

2021-07-17 13:57 UTC, netosjb approved these changes

2021-07-18 02:55 UTC, netosjb commented
Quanto ao PR #1456 esse se restringe a corrigir um outro bug, que é a atribuição dos comentários (comments_ids) que estão configurados dentro da operação (fiscal_operation_id.comment_ids) para o documento fiscal. Mas ainda não corrige os problemas proposto por @felipemotter

2021-07-19 18:15 UTC, mbcosta commented on l10n_br_fiscal/models/document_fiscal_line_mixin.py
> +    manual_additional_data = fields.Char(
Ola @felipemotter , qual a necessidade o levou a criar esse terceiro campo para os comentários? Acredito que o additional_data já deveria permitir edição e em caso de se voltar a Fatura/Invoice para Rascunho/Draft as alterações feitas nesses campos de Comentários devem ser preservadas e não incluídas novamente.

2021-07-19 20:52 UTC, felipemotter commented
@mbcosta Observando a disposição dos campos atualmente, onde o campo 'additional_data' pode ser populado sem ser pelos "comment", entendemos que isso foi uma escolha de usabilidade(poder colocar informações manuais diretas). O campo 'manual_additional_data' foi adicionado justamente para manter esse comportamento, sem dar conflito caso os comments precisem ser recarregados.

A lógica atual pega as informações do "additional_data" e concatena com os "comment", o problema: quando uma invoice precisa ser revalidada, ela pega o "addtional_data", já alterado na validação anterior e concatena novamente, repetindo tudo.

Na PR #1471, para corrigir o problema anterior, ele verifica se já existe a string gerada pelo "comment" no "additional_data", caso exista ele não faz a concatenação. O problema aqui, é que se o valor computado dentro do comment mudar, por exemplo impostos, essa string será diferente e o comment será duplicado, informando os valores antigos e novos.

Nesta PR, caso seja necessária uma revalidação da invoice, os campos "manual_additional_data" e "comment" são concatenados para formar um "adittional_data" novo, evitando a duplicação ou adição de dados desatualizados.'

2021-07-20 14:02 UTC, renatonlima requested changes
Realmente acho importante separar a observação manual da gerada automaticamente para preserva-la, só a implementação do código eu melhoraria como revisado no comentário do código.

2021-07-20 14:02 UTC, renatonlima commented on l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
> +                if d.additional_data:
Para deixar mais simples o código eu faria....:

```python
comments = [d.manual_additional_data or ""]
comments.append(d.comment_ids.compute_message(d.__document_comment_vals()))
d.additional_data = ", ".join([c for c in comments if c]
```

2021-07-20 14:18 UTC, renatonlima commented
@felipemotter,

Algumas coisas que eu vi no objeto comment que não estão relacionados com as suas mudanças neste PR mas impacta:

* O método que gera o comentário esta concatenando no final um enter "\n" na string, eu não acho legal, poderia ser espaço ou virgula. https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_fiscal/models/comment.py#L166
* O erro que acontece hoje quando é adicionado dois comentário é por causa desta linha https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_fiscal/models/comment.py#L101 esse método não precisa deste "self.ensure_one" pode ser removido.
* No método "format_amount" tem algumas strings com unicode u"" que não são mais necessários no python3 https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_fiscal/models/comment.py#L111

2021-07-21 02:50 UTC, felipemotter commented
@renatonlima Segui suas dicas e realmente o código fica bem melhor dessa forma.

Eu e o @netosjb chegamos a um entrave novo com essas alterações: o separador só é utilizado entre o comentário manual e o restante dos comentários computados, que por fim ganham os separadores no método format_amount. Achamos um pouco estranho ter a mesma competência dividida em dois lugares diferentes.

Para centralizar a lógica dos separadores, ao invés do método format_amount ter um resultado no formato string, fizemos ele retornar uma lista e então fazer um extend com as informações manuais no método _document_comment.

Como os outros comment(fiscal e comercial) também estão com a mesma falha de repetição ao revalidar a fatura, e já precisaríamos alterar como eles lidam com o novo result do format_amount, decidimos extender a correção para estes.

A solução está funcionando, porém está nos incomodando o código praticamente se repetir em três locais diferente e acreditamos que isto pode ser melhorado. O que vocês acham? Alguma dica para evoluir esse pensamento?

2021-07-21 14:22 UTC, renatonlima commented
@felipemotter e @netosjb,

Uma forma de otimizar seria alterar o método compute_message e adicionar mais argumento para receber a string do comentário manual e retornar a string já concatenada com o comentário manual e os automáticos:

```python
def compute_message(self, vals):
````

Para:

```python
def compute_message(self, vals, manual_comment=None):
````

O retorno deste método retornará uma string já concatenada:

```python
        comments = [manual_comment or ""]
        for record in self:
            template = mako_safe_env.from_string(tools.ustr(record.comment))
            render_result = template.render(vals)
            comments.append(render_result)
        return " - ".join([c for c in comments if c])
```

Neste caso iria simplificar os métodos do documento fiscal e da linha do documento fiscal que chama esse método, um exemplo do _document_comment da linha do documento fiscal:

```python
def _document_comment(self):
    for d in self:
        d.additional_data = d.comment_ids.compute_message(
            d.__document_comment_vals(), 
            d.manual_additional_data
        )
```

OBS: É importante depois você rodar o pre-commit para resolver problemas de pylint e pep8 (pre-commit run --all --show-diff-on-failure --verbose --color always)

2021-07-23 00:51 UTC, felipemotter commented on l10n_br_fiscal/models/comment.py
> +        comments = [manual_comment] if manual_comment else []
Fizemos as alterações, a única coisa que mudamos foi por esse if para o manual comment ao invés do laço for dentro do join.

2021-07-23 00:55 UTC, felipemotter commented
```
comments = [manual_comment] if manual_comment else []
        for record in self:
            template = mako_safe_env.from_string(tools.ustr(record.comment))
            render_result = template.render(vals)
            result += render_result + "\n"
        return result
            comments.append(template.render(vals))
        return " - ".join(comments)
```
Fizemos as alterações, a única coisa que mudamos foi por esse if para o manual comment ao invés do laço for dentro do join.

Demos uma revisada e a princípio está tudo ok, fico no aguardo de considerações.

E aliás, obrigado pela aula =)

2021-07-23 01:01 UTC, netosjb approved these changes

2021-07-23 01:04 UTC, renatonlima approved these changes

2021-07-23 01:05 UTC, marcelsavegnago approved these changes
LGTM

2021-07-23 01:09 UTC, rvalyi approved these changes, later dismissed
é um plebiscito! mandou ver na primeira PR parabens!

2021-07-23 01:10 UTC, rvalyi commented
/ocabot merge minor

2021-07-23 01:14 UTC, rvalyi commented
mandei o merge mas cancelei porque tem um outro merge rodando ja. Hoje a ferramenta de merge queue da OCA nao tem gestao de paralelismo legal. Ai como os testes levam 25 minutos ou mais, depois os builds podem se invalidar um o outro na hora do rebase final e o Travis pode ate ficar um dia inteiro matando as focas do antartica fazendo calor sozinho. Então vamos esperar o outro finalizar primeiro.

Quando a gente vai pular o foco para a v14 (em breve) a situaçao vai melhorar porque os testes serao ate uns 50% mais rapidos por ai.

2021-07-23 01:30 UTC, felipemotter commented
Deu erro em alguns testes, estamos dando uma olhada.

2021-07-23 01:58 UTC, rvalyi commented
> Deu erro em alguns testes, estamos dando uma olhada.

Eu acho que não, os testes do merge sou eu que cancelei mesmo para esperar o outro merge. Mas enfim vamos poder verificar que estão passando logo.

2021-07-23 02:38 UTC, rvalyi commented
/ocabot merge minor

2021-07-23 03:35 UTC, felipemotter commented
Pelo que eu vi, os erros eram realmente originados nesta PR, o na nota paulistana foi simples, porém no sale stock ficou um pouco feia a solução, não sabemos se é o ideal.
![unknown](https://user-images.githubusercontent.com/6812128/126734391-f49105c3-b0f7-4ab8-bdcc-a313db628372.png)

2021-07-23 03:52 UTC, rvalyi commented
> Pelo que eu vi, os erros eram realmente originados nesta PR, o na nota paulistana foi simples, porém no sale stock ficou um pouco feia a solução, não sabemos se é o ideal.
> ![unknown](https://user-images.githubusercontent.com/6812128/126734391-f49105c3-b0f7-4ab8-bdcc-a313db628372.png)

Ah ok, eu acho que tava no build qdo aprovei e passou batido. Vamos aguardar isso então.

2021-07-23 10:44 UTC, felipemotter commented
Não solucionou, amanhã iremos ver isso melhor e sem pressa.

2021-07-23 10:44 UTC, mileo commented
Bom dia Pessoal,

Esse PR vai funcionar e portanto esta correto.

Entretanto estava pensando se não seria melhor criarmos um modelo para armazenar as mensagens, onde cada linha corresponderia a uma mensagem, calculada ou de origem por exemplo:

- manual
- pedido de vendas
- picking


Um breve rascunho:
```
class FiscalDocumentComent(object):

     _name = 'l10n_br_fiscal.document_coment'

     document_id = many2one('l10n_br_fiscal.document')
     document_line_id = many2one('l10n_br_fiscal.document.line')
     origin_id = reference() or text 

     message_id = fields.Many2one('l10n_br_fiscal.comment')

     mensagem = fields.Text()

     mensagem_final = fields.Text(readonly=True)

     def metodos_de_calculo_da_mensagem_movidos_do_fiscal
           [...] a mensagem calculada é salva no mensagem_final, caso não tenha "MAKO templates" salva só o texto.

      def _onchange_message_id()
           # Ao alterar a mensagem o campo "message_id.mensagem" é copiado para mensagem
           [...]
```
Assim temos um controle de onde veio a mensagem.

Se vcs olharem os specs da nf-e verão que é um campo relacional.

2021-07-23 12:47 UTC, netosjb commented
Olá @mileo 

Eu o @felipemotter  também estávamos pensando em uma solução parecida mas achamos que isso vai gerar um refactor muito grande e nossa ideia no momento era só fazer um FIX rápido,  sem mexer muito na arquitetura atual, na verdade essa PR acabou se estendendo mais do que estimamos no começo, nós ainda não temos a experiência necessária para mexer tão a fundo, podemos trabalhar nessa solução, mas terá que ser com mais calma, também não queremos ocupar muito o tempo dos reviews com revisões grandes, a gente sabe que tem assuntos mais importante na pauta do projeto.

Acho que podemos dar continuidade na PR da forma que está, em seguida trabalhar no refactor com mais tempo e calma, o que acha ?

Logo vamo analisar o erros que estão sendo acusado no Trevis.

2021-07-23 12:54 UTC, rvalyi commented
> Bom dia Pessoal,
> 
> Esse PR vai funcionar e portanto esta correto.
> 
> Entretanto estava pensando se não seria melhor criarmos um modelo para armazenar as mensagens, onde cada linha corresponderia a uma mensagem, calculada ou de origem por exemplo:
> 
> * manual
> * pedido de vendas
> * picking
> 
> Um breve rascunho:
> 
> ```
> class FiscalDocumentComent(object):
> 
>      _name = 'l10n_br_fiscal.document_coment'
> 
>      document_id = many2one('l10n_br_fiscal.document')
>      document_line_id = many2one('l10n_br_fiscal.document.line')
>      origin_id = reference() or text 
> 
>      message_id = fields.Many2one('l10n_br_fiscal.comment')
> 
>      mensagem = fields.Text()
> 
>      mensagem_final = fields.Text(readonly=True)
> 
>      def metodos_de_calculo_da_mensagem_movidos_do_fiscal
>            [...] a mensagem calculada é salva no mensagem_final, caso não tenha "MAKO templates" salva só o texto.
> 
>       def _onchange_message_id()
>            # Ao alterar a mensagem o campo "message_id.mensagem" é copiado para mensagem
>            [...]
> ```
> 
> Assim temos um controle de onde veio a mensagem.
> 
> Se vcs olharem os specs da nf-e verão que é um campo relacional.

Ola @mileo, nao é um não definitivo, mas eu diria que não. Pricipalemente porque o custo beneficio nao iria valer a pena. Ja tem muitas empresas que conseguem usar da forma que ta, depois que o @felipemotter refatorou entao vai atender super bem. Entao aumentar mais o codigo do modulo fiscal que ja é o maior modulo da OCA inteira para fazer coisas que nao ha muita necessidade, a meu ver deveria ser evitado. Eu chamaria isso de "premature optimization" fiscal rs. Eu diria que a gente tem muito melhor que fazer. Se vc nao souber o que fazer pode começar a ver esse problema pro examplo, ja seria mais util https://github.com/OCA/l10n-brazil/pull/1533#issuecomment-884569484

Segundo, vc invoca o argumento de como esta no l10n_br_nfe_spec ou seja que reflete na vdd a estrutura do XSD da fazenda. Bom vcs tem que ver que o XSD da fazenda tem seus artificios que sao meramente de validaçao XSD. Por isso que la no XSD vc tem tags especificas para ICMS30 ICMS40 etc... que alias filtrei da spec com uma regexp na geraçao. Entao o que é ComplexType ou nao no XSD é parametro, é artificio de validaçao.
Ficar refazendo classes genericas de tudo que tem no XSD para manter no l10n_br_fiscal e depois talvez para todos os outros documentos fiscais certamente não é uma abordagem sana.

Se as tags XSD continuam como class TransientModel no 10n_br_nfe_spec (fora entao ICMS* e ICMSSN*) é apenas porque assim eu criei uma "lingua franca" na linguagem Odoo dos XSD para poder trablhar e servir de intermediario e de porto seguro para a serializaçao e deserializaçao dos documentos ficais, ja que sua proposta insistante da epoca era alguem ficar mijando esse codigo manualmente  como era no caso no seu fork 
https://github.com/kmee/l10n-brazil/tree/10.0-develop/sped/models
ou na lib de serializaçao da epoca que vc queria enfiar na mara no core do projeto ate que finalmente abandonou (ufa!):
https://github.com/aricaldeira/PySPED/tree/python3/pysped/nfe
ja que tem pessoas novas, é importante as pessoas ficarem apresentadas sem mascara porque o projeto nao tem tempo para mascaras.

Por fim em termo de usabilidade, se vc bota uma class nova, a ediçao ou a consultação seria atraves de uma nova popup a mais, (ou um JOIN a mais) e e eu nao acho isso bom. E alias é por isso que tem codigo no stackedmodel do modulo spec_model_driven para evitar esses artificios de XSD e voltar a falara na linguagem de modelo relacional, denormalizando os documentos fiscais da forma apropriada.

E se vc quiser evitar essas novas popup, teria que adicionar ainda mais codigo, então para mim coisa furada.

Ainda aberto pro debate, mas eu nao iria por esse caminho não.

Valeu.

2021-07-23 13:37 UTC, rvalyi commented
> Olá @mileo
> 
> Eu e o @felipemotter também estávamos pensando em uma solução parecida mas achamos que isso vai gerar um refactor muito grande e nossa ideia no momento era só fazer um FIX rápido, sem mexer muito na arquitetura atual, na verdade essa PR acabou se estendendo mais do que estimamos no começo, nós ainda não temos a experiência necessária para mexer tão a fundo, podemos trabalhar nessa solução, mas terá que ser com mais calma, também não queremos ocupar muito o tempo dos reviews com revisões grandes, a gente sabe que tem assuntos mais importante na pauta do projeto.
> 
> Acho que podemos dar continuidade na PR da forma que está, em seguida trabalhar no refactor com mais tempo e calma, o que acha ?
> 
> Logo vamo analisar o erros que estão sendo acusado no Trevis.

Tb sim fix rapido é mais importante. Pois alem disso se refatorar teria que bolar scripts de migraçao tb, testar eles. Poderia ate se feito se realmente se comprova a superioridade da abordagem, mas de qualquer forma levaria tempo. E novamente eu acho que temos coisas bem mais importante para ver do que isso. Por isso minha sugestao e arrumar os testes apenas. @renatonlima o que vc acha?

2021-07-23 14:05 UTC, mileo commented
> Olá @mileo
> 
> Eu e o @felipemotter também estávamos pensando em uma solução parecida mas achamos que isso vai gerar um refactor muito grande e nossa ideia no momento era só fazer um FIX rápido, sem mexer muito na arquitetura atual, na verdade essa PR acabou se estendendo mais do que estimamos no começo, nós ainda não temos a experiência necessária para mexer tão a fundo, podemos trabalhar nessa solução, mas terá que ser com mais calma, também não queremos ocupar muito o tempo dos reviews com revisões grandes, a gente sabe que tem assuntos mais importante na pauta do projeto.
> 
> Acho que podemos dar continuidade na PR da forma que está, em seguida trabalhar no refactor com mais tempo e calma, o que acha ?
> 
> Logo vamo analisar o erros que estão sendo acusado no Trevis.

Sim, como eu comentei o trecho esta correto, ficou faltando ressaltar que deve ser feito o merge desta forma.

Se quisermos mapear as informações da forma correta e ter mais controle da situação, dei a sugestão de criarmos um modelo, pois ai fica muito mais fácil de administrar/recalcular e ainda melhora a UX.

2021-07-23 14:28 UTC, mileo commented
Outra coisa importante é garantir que no documento fiscal seja possível juntar por exemplo:

- Mensagem manual do pedido de vendas;
- Mensagem manual da separação;
- Mensagem automática do fiscal;
- Mensagem manual digitada no documento fiscal.

Um conceito que podemos explorar é usar os campos relacionais para buscar essas informações e acabar com a transferência/concatenação de dados evitando problemas de mensagens repetidas.

2021-07-23 15:04 UTC, renatonlima commented
> Olá @mileo
> 
> Eu e o @felipemotter também estávamos pensando em uma solução parecida mas achamos que isso vai gerar um refactor muito grande e nossa ideia no momento era só fazer um FIX rápido, sem mexer muito na arquitetura atual, na verdade essa PR acabou se estendendo mais do que estimamos no começo, nós ainda não temos a experiência necessária para mexer tão a fundo, podemos trabalhar nessa solução, mas terá que ser com mais calma, também não queremos ocupar muito o tempo dos reviews com revisões grandes, a gente sabe que tem assuntos mais importante na pauta do projeto.
> 
> Acho que podemos dar continuidade na PR da forma que está, em seguida trabalhar no refactor com mais tempo e calma, o que acha ?
> 
> Logo vamo analisar o erros que estão sendo acusado no Trevis.

Pessoal,

Eu acho que o PR já resolve o FIX e todos os problemas que temos hoje além de melhorar a qualidade do código, então quando for corrigido o erro no Travis, podemos fazer o merge.

Sobre a ideia de ter outro objeto de comentários dos documentos fiscais, eu não acho necessário porque hoje a implementação dos campos manual_fiscal_additional_data, fiscal_additional_data, manual_customer_additional_data, customer_additional_data no documento fiscal estão sendo implementados no mixin, e esses campos são injetados no pedidos de venda (sale.order), pedidos de compras (purchase.order) e picking e como os campos manual_*_additional_data são copiados para o documento fiscal ele vai ser calculado corretamente sem duplicar a concatenação e dá para saber a origem do comentário. Para isso funcionar bastaria colocar os campos manual_*_additional_data na visão do pedido de venda, compras e picking.

@mileo,

Pelo que eu expliquei acima não acho necessário ter um outro objeto, mas se você enxerga algum outro ponto podemos avaliar melhor.

@felipemotter e @netosjb,

Obrigado e parabéns pela contribuição, muito bom ver mais pessoas se engajando e contribuindo com o projeto, assim que vocês corrigirem o erro no travis, podemos fazer o merge.

2021-07-23 16:19 UTC, mbcosta commented
@felipemotter @netosjb 

Sobre os erros no Travis parecem existir três, um deles é esse: 
![image](https://user-images.githubusercontent.com/6341149/126807918-20e0a691-6b0b-4762-8fca-f0940dfe6261.png)

É referente a um teste que adicionei recentemente que valida a copia de campos da Linha do Pedido de Vendas/sale.order.line para a Linha da Fatura/account.invoice.line quando a Fatura é criada baseada na Ordem de Entrega/stock.picking. No wizard que cria a Fatura os campos referentes aos Comentários são passados aqui https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_sale_stock/wizards/stock_invoice_onshipping.py#L28 
![image](https://user-images.githubusercontent.com/6341149/126810383-9c8810f9-3c21-4396-8bd1-23655a9669f5.png)

É preciso avaliar se será necessário fazer alguma alteração no método ou se os Comentários da Fatura realmente podem ser diferentes dos que estão no Pedido de Venda ( nesse caso nos testes pode ser informar os campos que não devem ser validados https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_sale_stock/tests/test_sale_stock.py#L239 ), vejam que nos dados de demo do Pedido de Venda estamos preenchendo os campos para essa validação:

![image](https://user-images.githubusercontent.com/6341149/126810626-2ea16ea4-f9fd-4503-8731-9de4838803d1.png)


Pessoal algumas questões para confirmar, hoje existem os campos Note no Pedido de Venda/sale.order e Notes no Pedido de Compra/purchase.order com a inclusão do campo manual_additional_data esses campos perdem a funcionalidade e se tornam apenas campos de observações internas? Ou deveriam de alguma forma serem integrados com esses campos de comentários da localização como está sendo feito hoje no wizard( segunda imagem )?

2021-07-27 10:50 UTC, netosjb commented
Pessoal, nosso código falhou no codecov/project, adicionamos um teste para tentar aumentar o target mas mesmo assim falhou, alguém tem alguma dica ? Precisamos adicionar mais testes ?

2021-07-27 11:07 UTC, rvalyi commented
> Pessoal, nosso código falhou no codecov/project, adicionamos um teste para tentar aumentar o target mas mesmo assim falhou, alguém tem alguma dica ? Precisamos adicionar mais testes ?

"falhou" porque o test coverage baixou 0.01%, algo que a gente não liga não. Tudo bem outro PR aumentara o coverage 0.05% e ai ta tranquilo. Faço o merge já, valeu pela boa primeira contribuição!

Ah só uma coisa, o modulo l10n_br_fiscal nada menos é do que o maior modulo da OCA inteira e nos tomou 10 anos de trabalho na Akretion (na vdd a gente gostaria de tirar algumas coisas como as contribuições de fechamento ou DFe fora que poderiam muito bem ser outros modulos).
Então, a gente menciona como contribuidores a partir de um certo nível de contribuição um pouco mais importante do que se o modulo tivesse 500 linhas, assim como mencionamos o Luis o ou Marcel nos contribuidores. Isso é para não prostituir o projeto e criar precedente. Porque infelizmente no Brasil as vezes tem algumas empresas que não tem vivencia com open source e ficam de olho grande no projeto, fazem alguns commits pirotécnicos e ja querem se meter em tudo e se apresentar como os donos do projeto. Eh inacreditável, mas não faltou nesses 10 anos e depois é todo mundo que perde quando eles usam isso para fazer besteiras. Mas a gente sempre mentionna os contribuidores aqui https://github.com/OCA/l10n-brazil/graphs/contributors de qualquer forma e em módulos menores a gente menciona os creditos no README de forma mais rapida. Porem a gente não esquece a contribuição claro e isso faz parte da nossa avaliação para uma menção futura eventual. Tudo certo?

2021-07-27 11:09 UTC, rvalyi commented
/ocabot merge minor

2021-07-27 11:16 UTC, rvalyi commented
Opa, ja tinha esse merge https://github.com/OCA/l10n-brazil/pull/1539 sendo feito, vamos esperar ele completar primeiro para os 2 merges nao interferir por horas...

2021-07-27 11:22 UTC, felipemotter commented
A gente entende sim @rvalyi, apesar de estar contribuindo só agora, faz um tempo que acompanhamos as discussões, então sabemos como funciona, um dia a gente chega la kkkkk

Sobre o merge, além da correção do erro, fizemos algumas alterações que o @mbcosta solicitou, para não perder as anotações da cotação. Você chegou a conferir se está dentro do aceito @rvalyi ? Porque foi bastante coisa.

2021-07-27 11:47 UTC, rvalyi commented
Legal @felipemotter me parece OK. @mbcosta ta OK para vc tb do jeito que ficou?

2021-07-27 15:05 UTC, mbcosta commented
Sim @rvalyi tudo certo, parabéns pelo trabalho @felipemotter @netosjb

2021-07-27 15:05 UTC, mbcosta approved these changes

2021-07-27 15:27 UTC, netosjb commented
@rvalyi  @mbcosta  @renatonlima @mileo @marcelsavegnago 
Obrigado pela colaboração de todos vocês!

2021-07-27 16:55 UTC, rvalyi commented
/ocabot merge minor

2021-07-27 18:00 UTC, merged