[12.0][FIX] l10n_br_repair: Ajustes de cálculos e localização do relatório Ordem de Reparo.
OCA/l10n-brazil pull request #1548
Opened 2021-08-02 19:29 UTC by marcelsavegnago

Fiz alguns ajustes no módulo de reparos.

- Alguns métodos foram movidos do arquivo fiscal_line_mixin para repair_fees e repair_line
- Corrige problema quando altera o valor do desconto para zero
- Sobrescrevi alguns métodos para garantir que sejam calculados os campos corretamente
- Sobrescrevi o relatório de ordem de reparo localizando o mesmo para o Brasil
- Adicionei coluna com desconto no relatório de ordem de reparo.

Qualquer dúvida, critica ou sugestão é bem vinda.

2021-08-02 19:51 UTC, rvalyi commented
> Hi @marcelsavegnago! The addon you are improving has no declared maintainer. If you care, you can consider adopting it. To do so, please read the [maintainer role description](https://odoo-community.org/page/maintainer-role) then create a pull request to add your GitHub login to the `maintainers` key of the addon manifest.

![main-qimg-088587e3a6acee9879c97f6717ace74e](https://user-images.githubusercontent.com/16926/127915756-5790840d-eba0-49c4-b7a9-c1a6a2b28c27.jpeg)

2021-08-05 00:23 UTC, rvalyi commented
re-inicei os testes, parece que tinham parado do nada.

2021-08-05 01:14 UTC, rvalyi commented
verdinho...

2021-08-05 12:26 UTC, rvalyi requested changes
@marcelsavegnago vc pode acertar a view para resolver esses warning no Runbot por favor?

```
2021-08-03 19:23:20,304 1287 INFO openerp_test odoo.modules.loading: loading l10n_br_repair/data/res_company.xml
2021-08-03 19:23:20,331 1287 INFO openerp_test odoo.modules.loading: loading l10n_br_repair/security/l10n_br_repair_security.xml
2021-08-03 19:23:21,208 1287 INFO openerp_test odoo.modules.loading: loading l10n_br_repair/views/res_company.xml
2021-08-03 19:23:21,429 1287 INFO openerp_test odoo.modules.loading: loading l10n_br_repair/views/repair_order.xml
2021-08-03 19:23:21,630 1287 INFO openerp_test odoo.modules.loading: loading l10n_br_repair/views/repair_fee.xml
2021-08-03 19:23:21,841 1287 INFO openerp_test odoo.modules.loading: loading l10n_br_repair/views/repair_line.xml
2021-08-03 19:23:22,072 1287 INFO openerp_test odoo.modules.loading: loading l10n_br_repair/report/repair_templates_repair_order.xml
2021-08-03 19:23:22,101 1287 WARNING openerp_test odoo.addons.base.models.ir_ui_view: Error-prone use of @class in view report_repair_order (): use the hasclass(*classes) function to filter elements by their classes
2021-08-03 19:23:22,101 1287 WARNING openerp_test odoo.addons.base.models.ir_ui_view: Error-prone use of @class in view report_repair_order (): use the hasclass(*classes) function to filter elements by their classes
2021-08-03 19:23:22,101 1287 WARNING openerp_test odoo.addons.base.models.ir_ui_view: Error-prone use of @class in view report_repair_order (): use the hasclass(*classes) function to filter elements by their classes
2021-08-03 19:23:22,101 1287 WARNING openerp_test odoo.addons.base.models.ir_ui_view: Error-prone use of @class in view report_repair_order (): use the hasclass(*classes) function to filter elements by their classes
2021-08-03 19:23:22,102 1287 WARNING openerp_test odoo.addons.base.models.ir_ui_view: Error-prone use of @class in view report_repair_order (): use the hasclass(*classes) function to filter elements by their classes
2021-08-03 19:23:22,102 1287 WARNING openerp_test odoo.addons.base.models.ir_ui_view: Error-prone use of @class in view report_repair_order (): use the hasclass(*classes) function to filter elements by their classes
2021-08-03 19:23:22,102 1287 WARNING openerp_test odoo.addons.base.models.ir_ui_view: Error-prone use of @class in view report_repair_order (): use the hasclass(*classes) function to filter elements by their classes
2021-08-03 19:23:22,102 1287 WARNING openerp_test odoo.addons.base.models.ir_ui_view: Error-prone use of @class in view report_repair_order (): use the hasclass(*classes) function to filter elements by their classes
2021-08-03 19:23:22,127 1287 INFO openerp_test odoo.modules.loading: Module l10n_br_repair: loading demo
2021-08-03 19:23:22,128 1287 INFO openerp_test odoo.modules.loading: loading l10n_br_repair/demo/res_company.xml
```

logs completos aqui https://runbot3.odoo-community.org/runbot/static/build/3496504-1548-cac354/logs/job_20_test_all.txt

2021-08-05 17:32 UTC, marcelsavegnago commented
@rvalyi tudo verdinho. :)

ping @mileo @gabrielcardoso21 @luismalta @renatonlima

2021-08-05 17:33 UTC, marcelsavegnago commented
@netosjb @felipemotter se puderem revisar eu agradeço. 

Se tiverem alguma dúvida sobre o processo de revisão, é só dar um toque.

Vlwww

2021-08-05 17:55 UTC, rvalyi commented
@marcelsavegnago pode se botar como mantenedor do modulo https://github.com/OCA/l10n-brazil/pull/1548#issuecomment-891277120 ? (a não ser que vc não queria...)

2021-08-05 17:57 UTC, marcelsavegnago commented
> @marcelsavegnago pode se botar como mantenedor do modulo [#1548 (comment)](https://github.com/OCA/l10n-brazil/pull/1548#issuecomment-891277120) ? (a não ser que vc não queria...)

Eu achei estranho porque estou como mantenedor no manifesto.. dá uma olhada fazendo favor.
https://github.com/OCA/l10n-brazil/blob/6a8be3cf073d135aedd618927629524fa9cf4097/l10n_br_repair/__manifest__.py#L12

2021-08-05 18:04 UTC, rvalyi commented
> > @marcelsavegnago pode se botar como mantenedor do modulo [#1548 (comment)](https://github.com/OCA/l10n-brazil/pull/1548#issuecomment-891277120) ? (a não ser que vc não queria...)
> 
> Eu achei estranho porque estou como mantenedor no manifesto.. dá uma olhada fazendo favor.
> https://github.com/OCA/l10n-brazil/blob/6a8be3cf073d135aedd618927629524fa9cf4097/l10n_br_repair/__manifest__.py#L12

Hum OK foi mal. Bem pode ter sido simplesmente um falso alerta quando o Stéphane Bidoul tava ajustando o ocabot...

2021-08-05 21:16 UTC, rvalyi approved these changes

2021-08-06 02:39 UTC, felipemotter approved these changes
Testamos o código e a princípio está tudo funcionando corretamente.

2021-08-06 02:39 UTC, felipemotter commented on l10n_br_repair/report/repair_templates_repair_order.xml
> +                t-if="doc.company_id.country_id.phone_code == 55"
Não sei se entendi bem o conceito do módulo, mas uma empresa fora do Brasil teria o interesse de instalar o repair da l10n_br?

2021-08-06 03:02 UTC, marcelsavegnago commented on l10n_br_repair/report/repair_templates_repair_order.xml
> +                t-if="doc.company_id.country_id.phone_code == 55"
Segui a mesma lógica do que estava no pedido de venda. Acredito que visa garantir atender em uma mesma instancia tanto uma empresa do grupo dentro do brasil com fora.. O @renatonlima pode falar melhor.

2021-08-06 11:09 UTC, felipemotter commented on l10n_br_repair/report/repair_templates_repair_order.xml
> +                t-if="doc.company_id.country_id.phone_code == 55"
Entendi, realmente faz bastante sentido kkk vou estudar mais o assunto.

2021-08-06 12:20 UTC, rvalyi commented
/ocabot merge major

2021-08-06 13:31 UTC, merged