[12.0][FIX] l10n_br_contract: o método _prepare_br_fiscal está ignorando a quantidade calculada pelo módulo contract_variable_quantity
OCA/l10n-brazil pull request #1565
Opened 2021-08-15 02:56 UTC by marcelsavegnago

Quando é utilizado o módulo contract_variable_quantity o método _prepare_br_fiscal ignora a quantidade calculada.

Cabe a alteração aqui ou seria melhor criar um módulo adicional para localizar o contract_variable_quantity?

ping @renatonlima @rvalyi

2021-08-16 15:03 UTC, renatonlima requested changes
Olá @marcelsavegnago,


Eu acredito que a melhor forma de resolver isso é igual ao l10n_br_purchase e l10n_br_sale e https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_purchase/models/purchase_order_line.py#L51

2021-08-16 16:47 UTC, marcelsavegnago commented
> Olá @marcelsavegnago,
> 
> Eu acredito que a melhor forma de resolver isso é igual ao l10n_br_purchase e l10n_br_sale e https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_purchase/models/purchase_order_line.py#L51

Grande Renato.. Vou dar uma olhada. Obrigado.

2021-08-27 22:43 UTC, marcelsavegnago commented
> https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_purchase/models/purchase_order_line.py#L51

@renatonlima não sei se isso resolve. Pelo que entendi este campo que vc me mostrou foi criado para receber a quantidade do campo product_qty. Mas, neste caso o problema é que o utilizando a quantidade não fica persistido em lugar algum e sim é calculado no momento da preparação dos dados da invoice.

https://github.com/OCA/contract/blob/c79f87ff476c6394bd9d98537b18c4a2815d950e/contract_variable_quantity/models/contract_line.py#L15

https://github.com/OCA/contract/blob/c79f87ff476c6394bd9d98537b18c4a2815d950e/contract/models/contract_line.py#L1325

Pelo que entendi quando chamado o método _prepare_br_fiscal o sistema desconsidera a quantidade que veio no vals e pega a quantidade lah da linha do modelo. Ou estou enganado ?

2021-10-06 19:56 UTC, renatonlima commented
Olá @marcelsavegnago,


Eu olhei o código e realmente o quantidade a ser faturada no contract_variable_quantity não é persistida, então pode ser feito dessa forma...

2021-10-06 19:57 UTC, renatonlima approved these changes

2021-10-06 20:00 UTC, rvalyi approved these changes

2021-10-06 21:04 UTC, rvalyi commented
/ocabot merge patch

2021-10-06 21:36 UTC, merged