[12.0] Chave do documento fiscal sem prefixo
OCA/l10n-brazil pull request #1580
Opened 2021-08-19 20:07 UTC by renatonlima

Recentemente eu fiz um PR https://github.com/erpbrasil/erpbrasil.base/pull/18 na lib erpbrasil.base responsável por criar a sequencia da chave numérica dos documentos fiscais com a finalidade de remover o prefixo e este PR depende do PR da lib para ficar verde.

Também fiz algumas melhorias:

* Adicionado uma mensagem quando a chave não é válida:

<img width="651" alt="Captura de Tela 2021-08-19 às 16 32 28" src="https://user-images.githubusercontent.com/211005/130134284-45714855-2143-4437-b111-8eb56803fb0f.png">

* Atualmente os campos tpEmis, tpImp estavam o o valor default hardcode, agora esses campos tem um valor padrão para ser definido na empresa e ser usado na emissão dos documentos fiscais, também se um XML for importado os valores destes campos serão atualizados pela função inverse.

<img width="1010" alt="Captura de Tela 2021-08-19 às 16 33 10" src="https://user-images.githubusercontent.com/211005/130134692-7c8ae69b-46dc-4a08-8ba3-a1579df64f89.png">

* Correção para permitir relacionar um documento CT-e em uma NF-e

2021-08-19 21:21 UTC, rvalyi requested changes
the pre-commit failed. Also you should publish erpbrasil.base 2.2 on pypi to be able to require it in requirements.txt

2021-09-15 21:59 UTC, rvalyi commented
a questão do erpbrasil.base foi resolvida mas tem erros nos testes Travis...

2021-10-13 21:00 UTC, renatonlima commented
Travis is green!

@rvalyi, @marcelsavegnago @mileo @felipemotter @netosjb

2021-10-13 21:17 UTC, rvalyi requested changes
Quase OK para mim, comentei so algo para mudar no _compute_nfe_data.

Pessoal, vale a pena dizer que a gente ta rodando esse PR em prod ja faz um mes em duas industrias que emitem dezenas de NFe's complexas por dia.

2021-10-13 21:17 UTC, rvalyi commented on l10n_br_nfe/models/document.py
> +                record.nfe40_Id = record.document_type_id.prefix + record.document_key
para evitar erros do tipo CacheMiss, vc tem que afectar um valor desse campo nf40_Id para cada registro, inclusive se nao passar no if, então vc tem que ter um else: com um valor depois, podando ser False. Isso pega na hora da migração para a v14 em especial então é melhor acertar ja.

2021-10-13 22:37 UTC, rvalyi approved these changes

2021-10-13 23:09 UTC, antoniospneto approved these changes

2021-10-13 23:42 UTC, marcelsavegnago commented
@renatonlima Travis is red :(

2021-10-14 10:18 UTC, felipemotter approved these changes

2021-10-14 13:32 UTC, rvalyi commented
> @renatonlima Travis is red :(

o erro no Travis é aquele erro inconsitente no teste do l10n_br_account_payment_order, não é relacionado. Mas re-iniciei o Travis para conferir se passa mesmo.

2021-10-14 14:08 UTC, rvalyi commented
/ocabot merge nobump

2021-10-14 15:21 UTC, merged