[12.0][IMP] BR fields in the Sale Report
OCA/l10n-brazil pull request #1627
Opened 2021-09-13 18:18 UTC by mbcosta

Included BR fields in the sales report.

Incluídos os campos com valores de ICMS, ICMSST, IPI, COFINS, PIS, Frete, Seguro, Outros Valores, Total com Impostos e a possibilidade de Agrupar pelo Tipo Fiscal do Produto, NCM, NBM e CEST.

Teste com os dados de demo da empresa de Lucro Presumido:

![image](https://user-images.githubusercontent.com/6341149/133135261-add7cd11-8c9b-415f-9e9d-453aa3a794fd.png)

OBS.: Na tradução do "Untaxed Amount Invoiced" parece estar faltando o "S" está "Total Faturado em Impostos"

cc @renatonlima @rvalyi

2021-09-13 18:24 UTC, marcelsavegnago commented
> OBS.: Na tradução do "Untaxed Amount Invoiced" parece estar faltando o "S" está "Total Faturado em Impostos"

Falando em tradução, infelizmente ainda está bloqueado a tradução via weblate :(

2021-09-13 18:39 UTC, renatonlima requested changes
@mbcosta Can you run pre-commit?

2021-09-13 19:34 UTC, rvalyi approved these changes

2021-09-13 20:04 UTC, marcelsavegnago approved these changes

2021-09-13 20:22 UTC, netosjb approved these changes

2021-09-13 20:51 UTC, renatonlima approved these changes

2021-09-13 22:22 UTC, renatonlima commented
/ocabot merge nobump

2021-09-13 23:05 UTC, rvalyi commented
/ocabot merge nobump

2021-09-14 00:09 UTC, rvalyi commented
/ocabot merge nobump

2021-09-14 01:14 UTC, merged