[12.0][FIX] Comments
OCA/l10n-brazil pull request #1647
Opened 2021-09-30 13:44 UTC by rvalyi

fiz um amend do fix do @mileo aqui https://github.com/OCA/l10n-brazil/pull/1456 (que tinha sido aprovado) para respeitar o pre-commit.

cc @renatonlima @netosjb @felipemotter @marcelsavegnago @mbcosta

2021-09-30 14:01 UTC, felipemotter approved these changes

2021-09-30 14:42 UTC, netosjb commented
Deu erro no flake8.

flake8...................................................................Failed
- hook id: flake8
- duration: 11.87s
- exit code: 1
l10n_br_account/models/account_invoice.py:422:25: E741 ambiguous variable name 'l'

Acho que tem que trocar o nome da variável para line

2021-09-30 15:00 UTC, antoniospneto requested changes

2021-09-30 15:00 UTC, netosjb commented on l10n_br_account/models/account_invoice.py
> +                            l.comment_ids |= l.fiscal_operation_line_id.comment_ids
```suggestion
                    for line in invoice.invoice_line_ids:
                        if not line.comment_ids and line.fiscal_operation_line_id.comment_ids:
                            line.comment_ids |= line.fiscal_operation_line_id.comment_ids
```

2021-09-30 15:15 UTC, rvalyi commented
foi mal ai, fiz um amend.

2021-09-30 17:39 UTC, netosjb approved these changes
![image](https://user-images.githubusercontent.com/634278/135503983-3b7b0c88-d102-4aae-9af7-876756bc2afd.png)

Tudo certo!

2021-09-30 19:45 UTC, renatonlima approved these changes

2021-09-30 19:45 UTC, renatonlima commented
/ocabot merge nobump

2021-09-30 22:02 UTC, rvalyi commented
deu problema com o l10n_br_currency_rate_update e o servidor do banco central, algo raro felizmente. Iniciando o merge de novo...

2021-09-30 22:02 UTC, rvalyi commented
/ocabot merge nobump

2021-10-01 06:05 UTC, rvalyi commented
/ocabot merge nobump

2021-10-01 07:14 UTC, merged