[12.0][FIX] Data na chave diverge com a data de emissão na NF-e.
OCA/l10n-brazil pull request #1692
Opened 2021-11-01 13:35 UTC by netosjb

Ontem (31/10/2021) estava testando a emissão de nota fiscal em ambiente de homologação e me deparei com o seguinte erro de transmissão:

![image](https://user-images.githubusercontent.com/634278/139677200-edf28704-249b-4dc9-89f2-015dc78908a7.png)

> Fiscal Document: 55 - Nota Fiscal Eletrônica is Rejeitada: 502 - Rejeicao: Erro na Chave de Acesso - Campo ID nao corresponde a concatenacao dos campos correspondentes

Conferindo, vi que o erro estava relacionado a data (AAMM) que faz parte da chave de acesso. Essa data na chave estava divergente da data de emissão do documento, como pode ver a baixo:

![image](https://user-images.githubusercontent.com/634278/139678515-a5e01ec2-3269-4ec1-96a6-18dd26ddc435.png)

Composição da chave:
![image](https://user-images.githubusercontent.com/634278/139678666-ebc68cbf-8487-4eaa-92f4-33ac1f0c8021.png)

Olhando o código percebi que a data usada na chave era a data universal (UTC) e no restante do código o utilizado é o UTC-3 (horário de brasília), como o horário universal está sempre um pouco a frente, ele muda de dia primeiro, e consequentemente de mês primeiro, como a chave só leva a em consideração o ano e mes (AAMM) este BUG só acontece na virada do mês.

Sei que é um bug que vai ser difícil pegar em produção, pois vai acontecer somente algumas horas antes de virar o mês.
Mas se acontecer vai ser bem chato, então é melhor evitar.

2021-11-01 15:34 UTC, renatonlima requested changes
@netosjb,

Me parece que essa solução não esta correta, porque a informação de data e hora no Odoo são sempre gravadas com UTC0 e apresentada de acordo com o timezone do usuário, dessa forma o problema relatado deve estar ou na configuração do timezone do usuário ou em algum ponto do código do spec_driven_model na hora de ler o record sem o contexto do timezone...

2021-11-01 15:34 UTC, rvalyi commented
eu ia comentar a mesma coisa do que o @renatonlima...

2021-11-01 15:38 UTC, netosjb commented
@rvalyi @renatonlima obrigado pelo feedback, vou me aprofundar melhor nessa questão de dados no odoo, vou deixar a pr em rascunho por enquanto.

2021-11-01 15:49 UTC, netosjb commented
@renatonlima @rvalyi 

Acho que o fix pode ser feito então nessa linha:

https://github.com/OCA/l10n-brazil/blob/f346a78d08f141a1e365582a7c018720800b5180/l10n_br_fiscal/models/document_workflow.py#L259

Ali ele tá jogando a data pra chave sem passar pelo timezone

2021-11-01 15:49 UTC, marcos-mendez commented
@netosjb veja se depois do dpkg-reconfigure tzdata não resolveu a situação. Acho que deve ser a divergencia de horários

2021-11-01 15:52 UTC, netosjb commented
@marcos-mendez

> @netosjb veja se depois do dpkg-reconfigure tzdata não resolveu a situação. Acho que deve ser a divergencia de horários

a configuração do horário no servidor está correta já testei,  acho que é só a conversão do UTC para o timezone local mesmo ali naquela parte do código

2021-11-03 17:41 UTC, netosjb commented
Substituído pela pr #1695

2021-11-03 17:41 UTC, closed without merging