[13.0][MIG] l10n_br_crm
OCA/l10n-brazil pull request #1745
Opened 2021-12-21 17:10 UTC by marcelsavegnago

2021-12-22 14:13 UTC, renatonlima requested changes
Parece que no repo da 13.0 existe um problema com a dependência PyOpenSSL https://app.travis-ci.com/github/OCA/l10n-brazil/jobs/553141505#L1716

2021-12-23 14:41 UTC, renatonlima commented
@marcelsavegnago faltou o pre-commit

2021-12-23 20:37 UTC, marcelsavegnago commented
> @marcelsavegnago faltou o pre-commit

@renatonlima https://www.openssl.org/docs/man1.1.1/man3/X509_set1_notBefore.html

2022-01-14 23:16 UTC, marcelsavegnago commented
> Parece que no repo da 13.0 existe um problema com a dependência PyOpenSSL https://app.travis-ci.com/github/OCA/l10n-brazil/jobs/553141505#L1716

ping @mbcosta

2022-04-01 00:01 UTC, netosjb commented
@marcelsavegnago tenta reiniciar o travis e o ruboat que agora o problema do pyopenssl foi resolvido

2022-06-01 19:11 UTC, rvalyi commented
Vou fechar essa PR porque nós da Akretion não temos interesse em finalizar esse PR na 13.0. já tem PR equivalente na 14.0. Pode ser reaberto se alguém se garante para terminar o trabalho na 13.0.

2022-06-01 19:11 UTC, closed without merging