[14.0][MIG] l10n_br_nfse
OCA/l10n-brazil pull request #1750
Opened 2021-12-30 03:36 UTC by marcelsavegnago

2022-01-01 15:22 UTC, rvalyi requested changes

2022-01-01 15:22 UTC, rvalyi commented on l10n_br_nfse/models/document.py
> +def fiter_provedor(record):
Essa função tem uma tipo e nem esta sendo usada por nenhum modulo. pelo git blame foi vc @marcelsavegnago que introduziu essa função em 17 meses atras https://github.com/OCA/l10n-brazil/blame/3effa2f931a246328f3ab824124cf6d2c69a14b8/l10n_br_nfse/models/document.py#L41 refatorando uma função que ja tinha uma tipo. Enfim eu acho que deve ser simplesmente removido. O que vc acha?

2022-01-03 18:52 UTC, marcelsavegnago commented on l10n_br_nfse/models/document.py
> +def fiter_provedor(record):
Na verdade eu apenas renomei na época.
https://github.com/OCA/l10n-brazil/commit/e7daaec563dd00367793c478c521d44fbb6d63ca#diff-32b1e0c1baa158d8aa4f5ff3d815669955cbc722eebb0f18514953c2288003e9L39

Vou dar uma olhada e se de fato não é utilizado.. podemos remover. Vou checar nos módulos issnet e afins.

2022-01-07 19:50 UTC, rvalyi commented on l10n_br_nfse/models/document.py
> +def fiter_provedor(record):
@marcelsavegnago arrumando isso da para matar a migraçao desse modulo rapidinho eu accredito...

2022-01-07 20:58 UTC, marcelsavegnago commented on l10n_br_nfse/models/document.py
> +def fiter_provedor(record):
Vou mexer bem esse final de semana.. quero migrar esse, issnet e paulista.

2022-01-08 16:29 UTC, marcelsavegnago commented on l10n_br_nfse/models/document.py
> +def fiter_provedor(record):
@rvalyi done

2022-01-08 17:03 UTC, rvalyi commented
@marcelsavegnago eu tb acharia justo vc se colocar como co-mantenedor desse modulo l10n_br_nfse se vc quiser. Isso porque:

1. desde 18 meses que o modulo entrou na OCA vc fez a metade ou mais dos commits e PR de manutenção dele.
2. desde uns 10 meses quase so vc manteve esse modulo, não temos noticia ou interação dos outros mantenedores no projeto.
3. vc domina bem o modulo, vc limpou ele muito, sempre deixou ele mais dentro dos padrões de qualidade OCA.

@mileo @gabrielcardoso21 @renatonlima o que vcs acham?

2022-01-08 21:36 UTC, rvalyi approved these changes

2022-01-08 22:08 UTC, rvalyi requested changes
@marcelsavegnago na vdd tem um problema quando vc édita tenta adicionar uma linha de produto na tela da nota fiscal de serviço:

```
  File "/opt/odoo/odoo/models.py", line 1530, in <dictcomp>
    for [v_id, v_type] in views
  File "/mnt/data/odoo-addons-dir/setup/l10n_br_nfse/odoo/addons/l10n_br_nfse/models/document_line.py", line 85, in fields_view_get
    self._name, etree.fromstring(model_view["arch"]), view_id
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 850, in postprocess_and_fields
    arch, name_manager = self._postprocess_view(node, model, validate=validate)
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 857, in _postprocess_view
    self.handle_view_error(_('Model not found: %(model)s', model=model))
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 673, in handle_view_error
    raise ValueError(formatted_message).with_traceback(from_traceback) from from_exception
Exception
```

Veja esse print do Runboat:
![2022-01-08_19-06](https://user-images.githubusercontent.com/16926/148661577-bee88789-8977-4453-b010-38443c1962a1.png)

2022-02-04 23:44 UTC, rvalyi commented
@marcelsavegnago agora esse PR tb precisa de uma adapatçao e rebase para essa mudança https://github.com/OCA/l10n-brazil/pull/1790

2022-02-11 17:36 UTC, marcelsavegnago commented
> @marcelsavegnago na vdd tem um problema quando vc édita tenta adicionar uma linha de produto na tela da nota fiscal de serviço:
> 
> ```
>   File "/opt/odoo/odoo/models.py", line 1530, in <dictcomp>
>     for [v_id, v_type] in views
>   File "/mnt/data/odoo-addons-dir/setup/l10n_br_nfse/odoo/addons/l10n_br_nfse/models/document_line.py", line 85, in fields_view_get
>     self._name, etree.fromstring(model_view["arch"]), view_id
>   File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 850, in postprocess_and_fields
>     arch, name_manager = self._postprocess_view(node, model, validate=validate)
>   File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 857, in _postprocess_view
>     self.handle_view_error(_('Model not found: %(model)s', model=model))
>   File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 673, in handle_view_error
>     raise ValueError(formatted_message).with_traceback(from_traceback) from from_exception
> Exception
> ```
> 
> Veja esse print do Runboat: ![2022-01-08_19-06](https://user-images.githubusercontent.com/16926/148661577-bee88789-8977-4453-b010-38443c1962a1.png)

@rvalyi acredito que resolvi. Se puder criticar este commit https://github.com/OCA/l10n-brazil/pull/1750/commits/4b12381bba15a23b09df8c6f0a5bc3bd9e872143 eu agradeço

2022-02-11 18:16 UTC, rvalyi approved these changes
LGTM. Eu deveria ter me ligado mesmo, o problema que vc resolveu foi devido a mudança que eu tive que fazer no sistema de fields_view_get do l10n_br_fiscal para lidar com os 2 campos line_ids e invoice_line_ids no l10n_br_account. Do restante eu continuo com a sugestão vc de virar co-mantenedor oficial do modulo devido a ampla proporção de fixes que vc fez nele e sendo que vc é quase o único a manter o modulo nos últimos 10 meses.

2022-02-11 18:31 UTC, marcelsavegnago commented
> LGTM. Eu deveria ter me ligado mesmo, o problema que vc resolveu foi devido a mudança que eu tive que fazer no sistema de fields_view_get do l10n_br_fiscal para lidar com os 2 campos line_ids e invoice_line_ids no l10n_br_account. Do restante eu continuo com a sugestão vc de virar co-mantenedor oficial do modulo devido a ampla proporção de fixes que vc fez nele e sendo que vc é quase o único a manter o modulo nos últimos 10 meses.

Feito

2022-02-11 18:43 UTC, netosjb approved these changes
👍🏻

2022-02-12 00:26 UTC, felipemotter approved these changes

2022-02-12 02:40 UTC, rvalyi commented
/ocabot merge nobump

2022-02-12 05:28 UTC, merged