[14.0][FORWARD PORT] #1764 Adicionado índices em alguns campos chaves
OCA/l10n-brazil pull request #1765
Opened 2022-01-05 18:37 UTC by renatonlima

FORWARD PORT PR #1764

2022-01-05 20:12 UTC, marcelsavegnago approved these changes
LGTM

2022-01-05 20:24 UTC, marcos-mendez commented
Pra.mim ta ok mas pq tanto index=true? O qq mudou aqui?

2022-01-05 20:29 UTC, marcelsavegnago commented
> Pra.mim ta ok mas pq tanto index=true? O qq mudou aqui?

https://github.com/OCA/l10n-brazil/pull/1765/commits/022f483826f667f1a7f03d6d0f8fd6d9eb8dd817

2022-01-05 20:30 UTC, marcelsavegnago commented
@marcos-mendez se estiver ok para vc é só dar aquela aprovada basica :)

2022-01-05 20:30 UTC, marcos-mendez commented
Isso eh o que onrenato falou dos mixin da 14?

2022-01-05 20:32 UTC, marcos-mendez approved these changes
TTOKPM

2022-01-05 20:32 UTC, marcelsavegnago commented
> Isso eh o que onrenato falou dos mixin da 14?

São inclusões de indices em alguns campos.

2022-01-06 04:51 UTC, rvalyi requested changes

2022-01-06 04:51 UTC, rvalyi commented on l10n_br_fiscal/models/tax_definition.py
> +        index=True,
ver meu comentario no PR da 12.0 https://github.com/OCA/l10n-brazil/pull/1764#discussion_r779298024

2022-01-06 12:16 UTC, vanderleiromera approved these changes

2022-01-06 13:06 UTC, renatonlima commented on l10n_br_fiscal/models/tax_definition.py
> +        index=True,
Corrigido assim como no PR #1764

2022-01-06 13:39 UTC, netosjb approved these changes

2022-01-07 12:42 UTC, rvalyi commented
ver meus comentarios aqui https://github.com/OCA/l10n-brazil/pull/1764#issuecomment-1007377681

2022-03-07 20:37 UTC, netosjb approved these changes

2022-03-07 21:43 UTC, rvalyi approved these changes

2022-03-07 22:27 UTC, felipemotter approved these changes

2022-03-08 13:28 UTC, marcelsavegnago commented
/ocabot merge minor

2022-03-08 13:55 UTC, merged