[14.0][REF] Geração do Certificado Fake, removido dependência do PyOpenSSL.
OCA/l10n-brazil pull request #1778
Opened 2022-01-16 14:28 UTC by netosjb

O mesmo que #1777 

Porém tem 2 dois commits adicionais:

1) reativei o código comentando que insere os certificado fake nas empresas de demostração. c56815f8b0a7e4f0e1df0811b790907caff44a08

2) Inclui um fix para exibição do nome do arquivo do certificado d4b979ece8b9da8df3cd30893b3691f7a39983d9
vou fazer um back-port desse commit para a v12 também.

Obs: lembrando que ainda precisar ser aprovado o merge no erp.assinatura para remoção dos warning e melhorar compatibilidade das libs com o trevis: https://github.com/erpbrasil/erpbrasil.assinatura/pull/26

2022-01-16 16:00 UTC, felipemotter approved these changes

2022-01-17 14:05 UTC, marcelsavegnago commented
ping @netosjb.. acho que vc já viu

```
2022-01-16 14:42:17,463 166 WARNING openerp_test py.warnings: /.repo_requirements/virtualenv/python3.6/lib/python3.6/site-packages/erpbrasil/assinatura/certificado.py:30: DeprecationWarning: str for passphrase is no longer accepted, use bytes
self._senha)

```

2022-01-17 14:08 UTC, rvalyi commented
> ping @netosjb.. acho que vc já viu
> 
> ```
> 2022-01-16 14:42:17,463 166 WARNING openerp_test py.warnings: /.repo_requirements/virtualenv/python3.6/lib/python3.6/site-packages/erpbrasil/assinatura/certificado.py:30: DeprecationWarning: str for passphrase is no longer accepted, use bytes
> self._senha)
> ```

Pois é foi exactamente por isso que eu tinha comentado a geração dos certificados fakes para a gente pode fazer o merge do l10n_br_fiscal. Isso seria uma boa arrumar esse problema no erpbrasil.assinatura...

2022-01-17 14:13 UTC, netosjb commented
pois é sim, essa pr ainda fica pendente o reparo na erpbrasil.assinatura :/

2022-01-18 00:19 UTC, netosjb commented
> ping @netosjb.. acho que vc já viu
> 
> ```
> 2022-01-16 14:42:17,463 166 WARNING openerp_test py.warnings: /.repo_requirements/virtualenv/python3.6/lib/python3.6/site-packages/erpbrasil/assinatura/certificado.py:30: DeprecationWarning: str for passphrase is no longer accepted, use bytes
> self._senha)
> ```

Abri uma PR trivial no erpbrasil.assinatura corrigindo esse warning: https://github.com/erpbrasil/erpbrasil.assinatura/pull/28
Acho que podemos fazer dessa forma enquanto a mudança do PyOpenSLL está em discussão.

@OCA/local-brazil-maintainers

2022-01-19 14:28 UTC, renatonlima commented
Pessoal, eu comentei o PR erpbrasil/erpbrasil.assinatura#26 e erpbrasil/erpbrasil.assinatura#28

2022-01-19 14:42 UTC, renatonlima requested changes

2022-01-19 14:42 UTC, renatonlima commented on l10n_br_fiscal/tools/misc.py
> +    private_key = rsa.generate_private_key(
Eu havia comentado um tempo atrás que o ideal era portar essa funcionalidade para a lib [erpbrasil.assinatura](https://github.com/erpbrasil/erpbrasil.assinatura) até foi colocado na docstring do método [create_fake_certificate_file](https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_fiscal/tools/misc.py#L68) então eu diria que após a aprovação do PR https://github.com/erpbrasil/erpbrasil.assinatura/pull/26 esse método poderia ser portado e removido os commits de mudança neste arquivo neste PR...

2022-01-19 14:42 UTC, renatonlima commented on requirements.txt
> +cryptography
Fazendo o porte do método create_fake_certificate_file para a erpbrasil.assinatura não precisa especificar essa dependência

2022-01-19 14:54 UTC, antoniospneto commented on l10n_br_fiscal/tools/misc.py
> +    private_key = rsa.generate_private_key(
Concordo Renato, muito melhor se a migração desse código para a lib já acontecer já..  vamos esperar o pessoal aprovar lá então.

2022-03-18 20:28 UTC, rvalyi commented
@netosjb vc conseguiria fazer esse refactor num PR para https://github.com/erpbrasil/erpbrasil.assinatura como o @renatonlima sugeriu?

Renato e eu a gente tem a permissão no repo erpbrasil.assinatura. O que nao temos é a conta no pypi, mas a gente consegue botar o pacote numa outra conta com nom alternativo de boa ate o @mileo resolver isso.

Nisso seria bom ter esse refactor la que a gente já poderia ter esse certificado fake para testar melhor a NFe na v14...

cc @marcelsavegnago @felipemotter @mbcosta

2022-03-18 20:39 UTC, netosjb commented
@rvalyi deixa comigo, vou abrir a pr lá

2022-03-21 13:39 UTC, marcelsavegnago commented
@netosjb se puder fazer um rebase eu agradeço.

2022-03-21 13:46 UTC, marcelsavegnago commented
@netosjb se puder faça o rebase desta tbm fazendo fazendo favor.

2022-03-22 18:11 UTC, netosjb commented
substituído por #1843

2022-03-22 18:11 UTC, closed without merging