[12.0][FIX] nfe40_mod selection -> now supports NFP
OCA/l10n-brazil pull request #1785
Opened 2022-01-20 14:44 UTC by DiegoParadeda

This PR fixes and improves the functions of related document specifically for type NFP.

- FIXED: broken dynamic selection for field nfe40_mod
- FIXED: _compute_nfe_data depend fields
- FIXED: _compute_nfe_data non-electronic documents cannot access field document (not available) -> changed to rec
- IMPROVED: _compute_nfe_data auto completion for fields that come from produtor_partner_id

2022-01-20 15:25 UTC, DiegoParadeda commented
Testado em HML - sefaz

![NFE-HML](https://user-images.githubusercontent.com/12245538/150368594-193b5d28-cb82-4cfe-a7c4-061a317099f5.jpeg)

2022-03-07 18:28 UTC, renatonlima requested changes

2022-03-07 18:28 UTC, renatonlima commented on l10n_br_nfe/models/document_related.py
>          [("nfe40_CNPJ", "CNPJ"), ("nfe40_CPF", "CPF")], "CNPJ/CPF do Produtor"
É importante colocar o nome do argumento selection e string para a definição do campo ficar mais legível.

2022-03-07 18:28 UTC, renatonlima commented on l10n_br_nfe/models/document_related.py
> +            "cpf" if self.produtor_partner_id.type == "person" else "cnpj"
Não existe o valor "person" na seleção do campo type no res.partner, você usar o campo bool is_company que é o que utilizamos para definir se o campo será usado o CNPJ (is_company=True), CPF (is_company=False)

2022-03-21 15:51 UTC, mileo requested changes

2022-03-21 15:51 UTC, mileo commented on l10n_br_nfe/models/document_related.py
> +        self.cpfcnpj_type = ("cnpj" if self.is_company else "cpf") or self.cpfcnpj_type
is company não é um atributo do modelo em questão.

2022-03-21 15:51 UTC, mileo commented
Peguei um erro ao testar no runbot. Você pode dar uma olhada @DiegoParadeda 

![image](https://user-images.githubusercontent.com/1975978/159298882-91c6212b-4d77-4821-bf9c-af86259946dc.png)

2022-04-23 11:48 UTC, mileo commented
@DiegoParadeda novidades?

2023-06-08 13:14 UTC, closed without merging