[14.0][l10n_br_account_due_list][REF] financial_move_line_ids payment_move_line_ids fields
OCA/l10n-brazil pull request #1789
Opened 2022-01-27 13:18 UTC by renatonlima

Corrige os campos as definições dos campos financial_move_line_ids e payment_move_line_ids

2022-01-27 13:24 UTC, antoniospneto commented
@renatonlima vou revisar essa noite ok

2022-01-27 15:23 UTC, rvalyi requested changes
pessoal, ja tou vendo com o @renatonlima mas apenas para deixar claro aqui, não acho bom o que foi feito com o campo payment_move_line_ids, assim nao vai funcionar porque o move_id do account_payment nada tem a ver com a fatura que estaria paga pleo pagamento. Tava correto antes.

2022-01-28 04:21 UTC, netosjb requested changes
Pessoal acho que esse código não está correto, 

Os dados não estão sendo apresentados corretamente, onde era para ser exibido apenas os lançamentos financeiro está aparecendo tudo:

![image](https://user-images.githubusercontent.com/634278/151486229-651ab045-ed34-435a-b433-a17d1717ae57.png)

e na aba de pagamento nada é exibido:
![image](https://user-images.githubusercontent.com/634278/151486338-2b233559-cd8b-4424-99a6-792b47b285f5.png)

Não entendi bem a intenção desta pr pois o código sem essa alteração está funcionando corretamente.

2022-02-07 23:00 UTC, rvalyi requested changes
ta dando esse erro nos logs do Runbot:

```
2022-02-06 00:03:16,080 151 [1;32m[1;49mINFO[0m openerp_template odoo.modules.loading: loading l10n_generic_coa/demo/account_invoice_demo.xml 
2022-02-06 00:03:16,710 151 [1;33m[1;49mWARNING[0m openerp_template odoo.modules.loading: Module l10n_generic_coa demo data failed to install, installed without demo data 
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/.repo_requirements/odoo/odoo/models.py", line 4228, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/.repo_requirements/odoo/odoo/models.py", line 4149, in _load_records_create
    return self.create(values)
  File "<decorator-gen-171>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/.repo_requirements/odoo/addons/account/models/account_move.py", line 1980, in create
    rslt = super(AccountMove, self).create(vals_list)
  File "<decorator-gen-135>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/.repo_requirements/odoo/addons/mail/models/mail_thread.py", line 264, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-64>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/.repo_requirements/odoo/odoo/models.py", line 3877, in create
    records = self._create(data_list)
  File "/.repo_requirements/odoo/odoo/models.py", line 4037, in _create
    for other, data in zip(others, data_list)
  File "/.repo_requirements/odoo/odoo/fields.py", line 3043, in create
    self.write_batch(record_values, True)
  File "/.repo_requirements/odoo/odoo/fields.py", line 3069, in write_batch
    return self.write_real(records_commands_list, create)
  File "/.repo_requirements/odoo/odoo/fields.py", line 3245, in write_real
    flush()
  File "/.repo_requirements/odoo/odoo/fields.py", line 3207, in flush
    comodel.create(to_create)
  File "<decorator-gen-172>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/.repo_requirements/odoo/addons/account/models/account_move.py", line 4104, in create
    moves._check_balanced()
  File "/.repo_requirements/odoo/addons/account/models/account_move.py", line 1816, in _check_balanced
    raise UserError(_("Cannot create unbalanced journal entry. Ids: %s\nDifferences debit - credit: %s") % (ids, sums))
odoo.exceptions.UserError: Cannot create unbalanced journal entry. Ids: [12]
Differences debit - credit: [-30.0]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/modules/loading.py", line 86, in load_demo
    load_data(cr, idref, mode, kind='demo', package=package)
  File "/.repo_requirements/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/.repo_requirements/odoo/odoo/tools/convert.py", line 685, in _tag_root
    )) from e
odoo.tools.convert.ParseError: while parsing /.repo_requirements/odoo/addons/l10n_generic_coa/demo/account_invoice_demo.xml:56, near
<record id="demo_invoice_5" model="account.move">
            <field name="move_type">in_invoice</field>
            <field name="partner_id" ref="base.res_partner_12"/>
            <field name="invoice_user_id" ref="base.user_demo"/>
            <field name="invoice_payment_term_id" ref="account.account_payment_term_end_following_month"/>
            <field name="invoice_date" eval="time.strftime('%Y-%m')+'-01'"/>
            <field name="invoice_line_ids" eval="[                 (0, 0, {'product_id': ref('product.product_delivery_01'), 'price_unit': 10.0, 'quantity': 1}),                 (0, 0, {'product_id': ref('product.product_order_01'), 'price_unit': 4.0, 'quantity': 5}),             ]"/>
        </record>
```

2022-02-07 23:36 UTC, netosjb commented
@renatonlima 

a aba de pagamentos está ok agora, mas a aba onde lista o contas a receber ou apagar ainda está errada:

![image](https://user-images.githubusercontent.com/634278/152889719-49689d2f-daf4-4604-b899-051ab93e639d.png)

Será que o correto não era ativar o _compute_financial de volta ?

2022-09-07 23:33 UTC, netosjb commented
@renatonlima como já está tudo ok na master acho que essa pr pode ser fechada

2022-09-08 00:16 UTC, closed without merging