[14.0] Rename line_ids to fiscal_line_ids in fiscal document
OCA/l10n-brazil pull request #1790
Opened 2022-01-27 19:12 UTC by renatonlima

Como no account.move existe o campo line_ids que é um o2m das account.move.line, o l10n_br_fiscal.document precisa ser alterado o campo line_ids para fiscal_line_ids para evitar problemas

2022-01-27 22:50 UTC, felipemotter approved these changes

2022-01-28 04:25 UTC, netosjb approved these changes

2022-01-28 04:28 UTC, netosjb requested changes
só tem que ver o trevis, acho que faltou fazer as alterações nos arquivos de testes

2022-01-28 20:17 UTC, rvalyi approved these changes
isso é fundamental para a migração do l10n_br_account!

2022-01-28 20:37 UTC, marcelsavegnago approved these changes

2022-01-28 20:39 UTC, netosjb approved these changes

2022-01-28 21:03 UTC, rvalyi commented
/ocabot merge major

2022-01-28 21:22 UTC, merged