Correção para carregar o CST corretamente , qdo operação de entrada.
OCA/l10n-brazil pull request #1795
Opened 2022-02-03 14:08 UTC by crsilveira

2022-02-07 23:40 UTC, netosjb requested changes

2022-02-07 23:40 UTC, antoniospneto commented on l10n_br_fiscal/models/tax_definition.py
> +        if self.tax_group_id:
@crsilveira 

Só tem um problema, nem sempre o modelo **tex_definition** irá ter um **fiscal_operation_line_id**
é o caso quando você tenta configurar os impostos padrões na lá na configuração da empresa, o erro de validação acontece:

![image](https://user-images.githubusercontent.com/634278/152450567-61b1555d-7d76-444b-97f8-b644597a91f5.png)

Precisa adicionar uma verificação se o fiscal_operation_line_id existe antes.

2022-02-15 19:41 UTC, netosjb approved these changes
Ai só acho que poderia melhorar ali o histórico de commits, fazer um squash com o git para unifica-los, isso ajuda a manter a branch principal limpa

2022-02-16 10:59 UTC, felipemotter approved these changes

2022-04-23 11:44 UTC, mileo commented
> Ai só acho que poderia melhorar ali o histórico de commits, fazer um squash com o git para unifica-los, isso ajuda a manter a branch principal limpa

Para uma primeira contribuição acho isso muito complicado. @crsilveira vc sabe fazer?

2022-06-21 14:52 UTC, closed without merging