[12.0][FIX] l10n_br_account: dummy fiscal document line correction
OCA/l10n-brazil pull request #1805
Opened 2022-02-16 12:37 UTC by marcelsavegnago

Quando uma fatura sem tipo de documento fiscal é duplicada, o sistema estava criando novas linhas diferentes da linha do documento fiscal dummy. 

Este problema aumenta exponencialmente a cada duplicação de fatura sem tipo de documento fiscal associado.

2022-02-16 23:22 UTC, netosjb requested changes

2022-02-16 23:22 UTC, netosjb commented on l10n_br_account/models/account_invoice.py
> +            default["line_ids"] = self.line_ids[0]
```suggestion
        default["line_ids"] = False
```

Pelo que testei outra forma de resolver é retirar o if e o else e sempre setar o default["line_ids"] como False.

2022-02-17 13:16 UTC, vanderleiromera commented
Testei local , erro ao duplicar fatura ....

`Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/src/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/src/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/src/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/src/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/src/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/src/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/src/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/src/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo/src/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo/src/addons/web/controllers/main.py", line 963, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/src/addons/web/controllers/main.py", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/src/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo/src/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/external-src/l10n-brazil/l10n_br_account/models/account_invoice.py", line 227, in copy
    default["line_ids"] = self.line_ids[0]
  File "/odoo/src/odoo/models.py", line 5173, in __getitem__
    return self._browse((self._ids[key],), self.env)
IndexError: tuple index out of range`

2022-02-17 13:25 UTC, netosjb commented
@vanderleiromera o teste você fez pelo runboat ou com alguma base sua ?

2022-02-17 14:27 UTC, vanderleiromera commented
> @vanderleiromera o teste você fez pelo runboat ou com alguma base sua ?

Base local @netosjb

2022-02-17 14:33 UTC, antoniospneto commented
> > @vanderleiromera o teste você fez pelo runboat ou com alguma base sua ?
> 
> 
> 
> Base local @netosjb 

Dá uma olhada no seu banco de dados, se vc tem o dummy cadastrado e se ele tem alguma linha, pelo erro parece que não, será que por algum outro motivo ele foi apagado? 

De qualquer forma eu acho que a sugestão que eu fiz ali atende esse caso também

2022-02-17 16:06 UTC, marcelsavegnago commented on l10n_br_account/models/account_invoice.py
> +            default["line_ids"] = self.line_ids[0]
Eu não testei desta forma. Vou testar ainda hoje.

2022-02-17 18:13 UTC, vanderleiromera commented on l10n_br_account/models/account_invoice.py
> +            default["line_ids"] = self.line_ids[0]
> Pelo que testei outra forma de resolver é retirar o if e o else e sempre setar o default["line_ids"] como False.

Esse aqui funcionou, 
ja o código da PR recebo o erro mencionado... @netosjb @marcelsavegnago

2022-02-17 20:43 UTC, marcelsavegnago commented
@vanderleiromera @netosjb desta forma proposta pelo Neto vcs chegaram a monitorar a tabela document_line ?

2022-02-17 20:56 UTC, netosjb commented
> @vanderleiromera @netosjb desta forma proposta pelo Neto vcs chegaram a monitorar a tabela document_line ?

Eu monitorei mas não cresceu a quantidade de linhas associadas ao dummy

2022-02-17 21:08 UTC, vanderleiromera commented
Sim monitorada, nenhum acréscimo ao duplicar.

2022-02-17 23:45 UTC, rvalyi approved these changes
valeu @marcelsavegnago isso resolve um problema bem importante!

2022-02-18 14:52 UTC, rvalyi commented
@marcelsavegnago agora que vc tirou o if/else eu nao entendo mais a logica: se for um invoice com documento fiscal, eu entendo que a copia não deveria apontar para as linhas do documento fiscal original sempre como vc fez agora. A gente quer isso apenas se o documento fiscal apontava na linha do documento fiscal dummy, mas nao no caso geral (o fato de passar False permitia a criaçao den novas linhas de documentos fiscais). Eu perdi alguma coisa? Pode explicar a logica?

2022-02-18 15:23 UTC, marcelsavegnago commented
> @marcelsavegnago agora que vc tirou o if/else eu nao entendo mais a logica: se for um invoice com documento fiscal, eu entendo que a copia não deveria apontar para as linhas do documento fiscal original sempre como vc fez agora. A gente quer isso apenas se o documento fiscal apontava na linha do documento fiscal dummy, mas nao no caso geral (o fato de passar False permitia a criaçao den novas linhas de documentos fiscais). Eu perdi alguma coisa? Pode explicar a logica?

Eu subi este commit para teste mesmo..  eu vou voltar isso como estava e vou testar melhor.

2022-02-18 16:24 UTC, netosjb commented
Sugeri que independente da situação por o **default["line_ids"]** como o **false**, pois tinha testando isso localmente e tinha funcionado bem, aparentemente funcionou com o @vanderleiromera também.

2022-02-22 14:39 UTC, rvalyi commented
Eu aprovo esse fix na medida que vamos para esse tipo de solução onde preservamos a ideia de nao criar documentos fiscais vazios sempre quando criamos invoices nao fiscais (ou seja continuamos a usar os dummy) https://github.com/OCA/l10n-brazil/pull/1816

2022-02-23 19:53 UTC, rvalyi approved these changes

2022-02-23 19:54 UTC, rvalyi commented
/ocabot merge patch

2022-02-23 21:03 UTC, merged