[12.0] Adicionado mapeamento para o local de entrega na NF-e
OCA/l10n-brazil pull request #1812
Opened 2022-02-19 20:51 UTC by renatonlima

2022-02-20 18:26 UTC, netosjb approved these changes
LGTM, só tem que ver o porque o trevis tá reclamando tanto.

2022-02-21 11:21 UTC, mbcosta commented
@renatonlima @netosjb pela mensagem de erro parece que devido a alteração não é possível ter o campo vazio, mas deveria porque a NFe pode ou não conter esse campo  https://app.travis-ci.com/github/OCA/l10n-brazil/jobs/560457404#L4046

![image](https://user-images.githubusercontent.com/6341149/154945565-3d6887d0-0050-4538-898f-5020f6a543db.png)

2022-02-21 16:14 UTC, rvalyi requested changes
o campo partner_shipping_id vem do modulo sale mas l10n_nr_nfe não depende do modulo sale então se instalar o modulo l10n_br_nfe apenas pode não existir esse campo. Então tem que pensar numa outra forma. Talvez poderia ir no modulo l10n_br_delivery_nfe (que depende do delivery que depende do sale)?

2022-02-21 16:16 UTC, netosjb commented
> o campo partner_shipping_id vem do modulo sale mas l10n_nr_nfe não depende do modulo sale então se instalar o modulo l10n_br_nfe apenas pode não existir esse campo. Então tem que pensar numa outra forma. Talvez poderia ir no modulo l10n_br_delivery_nfe (que depende do delivery que depende do sale)?

l10n_br_delivery_nfe acho que seria uma boa 👍🏻

2022-02-21 16:53 UTC, mbcosta commented
Valeu @rvalyi por esclarecer o erro, acredito que o modulo ideal então seria o l10n_br_sale_stock onde já existem testes para esse caso de Endereço de Fatura é diferente do de Entrega e o l10n_br_delivery depende desse modulo https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_delivery/__manifest__.py#L14, por isso mesmo sem o delivery instalado o mapeamento do campo de Endereço de Entrega já deveria funcionar por já ter essa informação vindo do sale.

2022-02-21 23:18 UTC, felipemotter approved these changes

2022-04-01 03:44 UTC, netosjb commented
@mbcosta no l10n_br_sale_stock acho q também seria bom 👍🏻

2022-04-18 14:58 UTC, kmmelcher commented
@netosjb @mbcosta Eu notei que o l10n_br_sale_stock não depende do l10n_br_nfe. Pode ser adicionado no manifest, mas eu acho que seria mais adequado mesmo fazer no l10n_br_delivery_nfe, já que ele sim depende do módulo l10n_br_nfe.

2022-11-29 21:09 UTC, renatonlima commented
Pessoal, eu consegui resolver o problema, na verdade no campo nfe40_entrega e nfe40_retirada estava faltando alterar o comodel_name para definir o objeto res.partner.

2022-11-29 22:38 UTC, rvalyi approved these changes

2022-11-29 22:40 UTC, rvalyi commented
/ocabot merge minor

2022-11-29 23:25 UTC, merged