[14.0][FIX] Dados demo para os campos fiscal_type e icms_origin
OCA/l10n-brazil pull request #1834
Opened 2022-03-16 14:25 UTC by netosjb

Recentemente foi alterado os campos **fiscal_type** e **icms_origin** do produto para serem property (company_dependent)
Porém isso fez com que as empresas de demostração "Simples Nacional" e "Lucro Presumido"  ficassem sem essas informações no produto.  As informações de demostração estavam sendo gerados apenas para a empresa de demostração "Sua Empresa".

Para resolver isso alterei o arquivo demo dos produtos e inclui a parametrização desses campos para cada empresa.
A forma de lidar com os campos property nos arquivos xml não é muito limpa, mas não encontrei outra solução.
Poderia ter feito um SQL para esse fim, mas acho que assim pode ser melhor, pois a edição do arquivo data fica livre para caso mais tarde alguém desejar configurar valores diferente para empresas diferentes.

No fim para facilitar eu fiz um script Jinja, vou deixar o templete gravado aqui caso precisar fazer alguma correção mais tarde.

Caso aprovado faço o backport para 12.0

```
{%- if fiscal_type_value -%}

<record forcecreate="True" id="fiscal_type_{{product_id}}_sn" model="ir.property">
    <field name="name">fiscal_type</field>
    <field name="fields_id" search="[('model','=','product.template'),('name','=','fiscal_type')]" />
    <field name="value">{{fiscal_type_value}}</field>
    <field name="type">selection</field>
    <field eval="'product.template,'+str(ref('product.{{product_id}}'))" name="res_id" />
    <field name="company_id" ref="l10n_br_base.empresa_simples_nacional" />
</record>

<record forcecreate="True" id="fiscal_type_{{product_id}}_lp" model="ir.property">
    <field name="name">fiscal_type</field>
    <field name="fields_id" search="[('model','=','product.template'),('name','=','fiscal_type')]" />
    <field name="value">{{fiscal_type_value}}</field>
    <field name="type">selection</field>
    <field eval="'product.template,'+str(ref('product.{{product_id}}'))" name="res_id" />
    <field name="company_id" ref="l10n_br_base.empresa_lucro_presumido" />
</record>
{%- endif -%}
{% if icms_origin_value %}

<record forcecreate="True" id="icms_origin_{{product_id}}_sn" model="ir.property">
    <field name="name">icms_origin</field>
    <field name="fields_id" search="[('model','=','product.template'),('name','=','icms_origin')]" />
    <field name="value">{{icms_origin_value}}</field>
    <field name="type">selection</field>
    <field eval="'product.template,'+str(ref('product.{{product_id}}'))" name="res_id" />
    <field name="company_id" ref="l10n_br_base.empresa_simples_nacional" />
</record>

<record forcecreate="True" id="icms_origin_{{product_id}}_lp" model="ir.property">
    <field name="name">icms_origin</field>
    <field name="fields_id" search="[('model','=','product.template'),('name','=','icms_origin')]" />
    <field name="value">{{icms_origin_value}}</field>
    <field name="type">selection</field>
    <field eval="'product.template,'+str(ref('product.{{product_id}}'))" name="res_id" />
    <field name="company_id" ref="l10n_br_base.empresa_lucro_presumido" />
</record>
{%- endif -%}
```

2022-03-16 15:36 UTC, felipemotter approved these changes

2022-03-17 20:32 UTC, renatonlima requested changes

2022-03-17 20:32 UTC, renatonlima commented on l10n_br_fiscal/demo/product_demo.xml
>          <field name="fiscal_type">00</field>
Seria bom aproveitar e remover os campos fiscal_type e icms_origin dos records product.product

2022-03-17 20:32 UTC, renatonlima commented on l10n_br_fiscal/demo/product_demo.xml
> +            eval="'product.template,'+str(ref('product.product_delivery_01'))"
Nesse eval o objeto product.template esta correto, mas o ID você não pode usar o ID do objeto product.product porque nem sempre o ID do product.product vai ser igual ao ID do product.template, por exemplo na base de dados de demo:

<img width="422" alt="image" src="https://user-images.githubusercontent.com/211005/158889657-d69c6e24-e9d5-44f8-a46d-279e2d2f83b2.png">


Então nesse caso você deve usar algo assim para ficar com o ID do product.template: 

```xml
<field name="res_id" eval="'product.template,'+str(obj().env.ref('product.product_delivery_01').product_tmpl_id.id)" />
```

2022-03-17 20:35 UTC, netosjb commented on l10n_br_fiscal/demo/product_demo.xml
> +            eval="'product.template,'+str(ref('product.product_delivery_01'))"
boaa renato, eu tava vendo agora que alguns produtos estavam falhando essa informação, deve ser por isso então.
vou fazer as correções obrigado!

2022-03-17 20:39 UTC, netosjb commented on l10n_br_fiscal/demo/product_demo.xml
>          <field name="fiscal_type">00</field>
é que ai eles tão servindo pra popular a empresa "Sua Empresa" será que apago faço da mesma forma então ?

2022-03-17 21:08 UTC, renatonlima commented
@netosjb,

Nos PRs que fiz para passar esses campos para property havia testado em uma base de dados existente e acabou passando esse detalhe dos dados de demo. Você pode fazer as correções e fazer dois commits separados para os properties do fiscal_type e do icms_origin, porque vai ficar mais fácil para fazer cherry-picking nos PRs #1810 # e #1821 na versão 12.0

2022-03-22 12:00 UTC, netosjb commented
@renatonlima 

`+str(obj().env.ref('product.product_delivery_01').product_tmpl_id.id)`

Não consegui utilizar dessa forma, fiz varias tentativas, mas não consigo de jeito nenhum retornar o objeto do produto para poder acessar o id do template, o env.ref só retorna o id (integer) do produto.

Talvez a solução seja apelar pro SQL mesmo

2022-03-22 14:43 UTC, marcelsavegnago commented
> @renatonlima
> 
> `+str(obj().env.ref('product.product_delivery_01').product_tmpl_id.id)`
> 
> Não consegui utilizar dessa forma, fiz varias tentativas, mas não consigo de jeito nenhum retornar o objeto do produto para poder acessar o id do template, o env.ref só retorna o id (integer) do produto.
> 
> Talvez a solução seja apelar pro SQL mesmo

Se tirar o .id não resolve ?

2022-03-22 14:59 UTC, netosjb commented
> > @renatonlima
> > `+str(obj().env.ref('product.product_delivery_01').product_tmpl_id.id)`
> > Não consegui utilizar dessa forma, fiz varias tentativas, mas não consigo de jeito nenhum retornar o objeto do produto para poder acessar o id do template, o env.ref só retorna o id (integer) do produto.
> > Talvez a solução seja apelar pro SQL mesmo
> 
> Se tirar o .id não resolve ?

Não Resolve :/

2022-03-22 15:24 UTC, marcelsavegnago commented
> Não Resolve :/

https://github.com/odoo/odoo/blob/720e2daafa9ba686aefc798370b8216e7e8c18e2/addons/stock_account/data/product_data.xml#L6

https://github.com/odoo/odoo/blob/12.0/addons/stock_account/data/stock_account_data.xml

https://github.com/odoo/odoo/blob/14.0/addons/stock_account/data/stock_account_data.xml

2022-03-22 15:26 UTC, renatonlima commented
@netosjb Se você ver um[exemplo](https://github.com/odoo/odoo/blob/a7f7233e0eae8ee101d745a9813cba930fd03dcb/addons/hr_contract/data/hr_contract_demo.xml#L13) parece que está faltando o atributo model="product.template" aí na tag field

2022-03-23 01:42 UTC, netosjb commented
> @netosjb Se você ver um [exemplo](https://github.com/odoo/odoo/blob/a7f7233e0eae8ee101d745a9813cba930fd03dcb/addons/hr_contract/data/hr_contract_demo.xml#L13) parece que está faltando o atributo model="product.template" aí na tag field

deu certo! era bem isso mesmo que estava faltando, obrigado @renatonlima  e @marcelsavegnago

2022-03-23 11:05 UTC, renatonlima approved these changes

2022-03-23 11:21 UTC, renatonlima requested changes

2022-03-23 11:21 UTC, renatonlima commented on l10n_br_fiscal/demo/product_demo.xml
> +            search="[('model','=','product.template'),('name','=','fiscal_type')]"
Você pode trocar isso esse search pelo ref:

```xml
<field name="fields_id" ref="field_product_template__icms_origin" />
```

2022-03-23 17:49 UTC, antoniospneto commented on l10n_br_fiscal/demo/product_demo.xml
> +            search="[('model','=','product.template'),('name','=','fiscal_type')]"
beleza, vou testar e em seguida atualizo a pr 👍🏻

2022-03-24 02:07 UTC, netosjb commented on l10n_br_fiscal/demo/product_demo.xml
> +            search="[('model','=','product.template'),('name','=','fiscal_type')]"
Feito! funcionou certinho tbm, foi um ótima dica, obrigado de novo @renatonlima

2022-03-24 03:07 UTC, rvalyi approved these changes
valeu @netosjb! Ajuda muito importante.

2022-03-24 04:19 UTC, marcelsavegnago approved these changes

2022-03-24 04:39 UTC, rvalyi commented
/ocabot merge minor

2022-03-24 05:29 UTC, merged