[14.0][FIX] Correct type internal group for accumulated depreciation
OCA/l10n-brazil pull request #1906
Opened 2022-05-11 01:31 UTC by felipemotter

O account.account.type "account.data_account_type_depreciation" originalmente está sendo renomeado para ser referente as contas de Depreciação Acumulada redutoras do ativo.

Já que originalmente é um type do grupo despesas, e isso não é alterado em momento algum, acaba que essa classificação fica divergente do nome.

Existiam duas possibilidades: 

1. Não alterar o type original e criar um totalmente novo com esse intuito
2. Alterar o internal_group do original

Como algumas pessoas talvez já usem esse type e ele já é previsto nas contas de ativo dentro dos planos de conta da localização, a alteração do grupo original me pareceu menos intrusiva e completa.

PS: Junto eu alterei o nome para Depreciação acumulada e aproveitei e também modifiquei o type de Amortização para Amortização Acumulada. Acredito que fica mais legível.

2022-05-11 01:33 UTC, netosjb approved these changes

2022-05-12 01:34 UTC, Bmessiazy commented
Oi Felipe Motter,

Analisei seu ponto, me parece ok. Só fiquei com uma dúvida.
Qual o conceito para essa classificação na origem? Tipo qual o objetivo desse campo?
Porque, depreciação acumulada pertence ao grupo dos Assets. Eh redutora..dele, mas no balanço tem que ficar sob esse grupo entende?
Exemplo:
TangiblesInvestimentsFixed Assets
(-) Accumulated depreciation
Todas essas contas pertencem ao grupo de Assets 
Se vc criar uma só para a depreciação...vai quebrar a totalização.
Tem que analizar como está a versão internacional.
Abraço.
Enviado do Yahoo Mail no Android 
 
  Em qua., 11 11e mai. 11e 2022 às 2:33, Antônio ***@***.***> escreveu:   


@netosjb approved this pull request.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2022-05-12 12:00 UTC, felipemotter commented
@Bmessiazy na forma original, ele conta como se fosse um type de depreciação no período, despesa. Hoje se você ver, ao criar uma conta nova diretamente no odoo, quando você escolhe o tipo, a conta que está descrita dentro do ativo, o odoo tá colocando dentro do grupo de despesas.... É uma classificação padrão dentro dos types.

2022-05-13 21:40 UTC, douglascstd approved these changes
Aprovado.
Vejo melhoria na descrição da conta e ajuste do tipo correto.

2022-05-14 15:47 UTC, rvalyi commented
I have no problem with the rename. However @max3903 I bring this point to your attention because the guy who contributed this originally opted to brute force rename the original `account.account.type` despite the name being translatable. Not a very big deal but this is going to clash with the other charts of accounts in your database. I think we can include this small name adjustment and later think about moving these names to the translations instead.

2022-05-15 08:00 UTC, Bmessiazy commented
Oi Felipe,
              Entendi, concordo com a alteração proposta.
             Abraço.
             

Enviado do Yahoo Mail no Android 
 
  Em sáb., 14 14e mai. 14e 2022 às 16:47, Raphaël ***@***.***> escreveu:   


I have no problem with the rename. However @max3903 I bring this point to your attention because the guy who contributed this originally opted to brute force rename the original account.account.type despite the name being translatable. Not a very big deal but this is going to clash with the other charts of accounts in your database. I think we can include this small name adjustment and later think about moving these names to the translations instead.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-05-17 17:42 UTC, hirokibastos approved these changes

2022-05-19 16:15 UTC, rvalyi requested changes
@felipemotter eu agradeço pela iniciativa. So que eu acho realmente problemático essa questão de alterar o account.account.type nativo. O que eu falei com o @max3903 no comentário antérior é que temos um cliente com eles que é uma multinacional que vai ter varias localizações instaladas no mesmo banco (so falei OK porque vai ser apenas serviço e que vai demorar para chegar ate a contabilidade). Mas enfim esse tipo de mudança iria criar problemas la na frente com as multinacionais.

Mesma coisa com a mudança de nomes. Na época eu tinha sinalizado pro @mileo mas ele quis ir adiante e mudar os nomes nativos... Mas a gente já esta num ponto que precisamos corrigir isso, eu diria antes de criar mais problemas com as outras localizações...

Sobre a questão de alterar os nomes nativos, se alguém realmente quer fazer isso porque acha que fica mais fácil, essas trocas de nomes podem ir num modulo de usabilidade diferente que nem precisa ser da OCA. Mas na OCA é ideia é reter o máximo de compatibilidade com as outras localizações pelo menos nesses módulos centrais então seria melhor já corrigir isso e jogar esses nomes nas traduções...

Do restante a gente acha que fazer código hostil para as multinacionais é um baita de um tiro no pé porque tem muitas empresas no Brasil que ainda estão de bobeira com o Odoo e não estão dispostas a fazer o investimento necessário para implementar ele enquanto que vc já tem umas multinacionais que usam em outros países ou já se tocaram e estão dispostas a investir o que for necessário pro Odoo funcionar no Brasil, mas claro a condição da localização reter o máximo de compatibilidade quando pretendem pelo menos começar com um banco único.

2022-05-19 17:05 UTC, felipemotter commented
Sendo bem sincero @rvalyi eu analisei muito bem e vi que usar esses types da localização mais iriam me atrapalhar do que ajudar. Decidimos que um fork do l10n_br_coa removendo esses types seria mais organizado e diminuiria a chance de incompatibilidade.

Concordo com você que forcar um internal_group aumentaria os problemas. Mas acredito que talvez um refactor nesses types seria necessário.

2022-05-19 17:55 UTC, rvalyi commented
Sendo sincero TB, não fomos nos que foram encher a boca de IFRS e outras exigências legais, pois hoje quando a gente consegue botar o operacional e o financeiro para rodar no Brasil a gente já tá bem orgulhoso...

Nisso na Akretion a gente não quebrou muito a cabeça com esses relatórios legais ainda, então estamos super abertos a sugestões de melhorias, a única coisa que eu vi que dessa forma como tava o PR, alterar o tipo nativo iria acabar atrapalhando mais do que ajudando lá na frente e por isso comentei. Mas se tiver outras sugestões de refator desses tipos, pode mandar a bala...

2022-05-20 01:01 UTC, marcelsavegnago commented
Eh tbm acho que está meio zoado esses tipos de contas.

2022-05-20 01:02 UTC, marcelsavegnago commented
> Sendo bem sincero @rvalyi eu analisei muito bem e vi que usar esses types da localização mais iriam me atrapalhar do que ajudar. Decidimos que um fork do l10n_br_coa removendo esses types seria mais organizado e diminuiria a chance de incompatibilidade.
> 
> Concordo com você que forcar um internal_group aumentaria os problemas. Mas acredito que talvez um refactor nesses types seria necessário.

manda o link do fork para que possamos ver como está.

2022-05-20 02:29 UTC, felipemotter commented
O fork é esse: https://github.com/Engenere/l10n-brazil/tree/14.0-acc-types

É algo simples: eu removo os types criados pela localização e altero para os respectivos types nativos do account.

Acredito que os types devem ser mais gerais para poder se adaptar a planos de contas diferentes e evitar conflitos com outros modulos. 

A maior dificuldade seria no l10n_br_mis_report, mas talvez utilizar os grupos de conta ao invés do type seja uma saída, mas eu precisaria analisar mais

2022-05-20 03:26 UTC, marcelsavegnago commented
> O fork é esse: https://github.com/Engenere/l10n-brazil/tree/14.0-acc-types
> 
> É algo simples: eu removo os types criados pela localização e altero para os respectivos types nativos do account.
> 
> Acredito que os types devem ser mais gerais para poder se adaptar a planos de contas diferentes e evitar conflitos com outros modulos.
> 
> A maior dificuldade seria no l10n_br_mis_report, mas talvez utilizar os grupos de conta ao invés do type seja uma saída, mas eu precisaria analisar mais

boa.. valeu. Acho que cabe a discussão. Quanto mais limpo melhor

2022-06-10 04:22 UTC, rvalyi commented
Essa festa dos account.account.type ja tem hora para acabar de qualquer forma:
https://github.com/odoo/odoo/pull/93212
Agora é so rezar pela nossa senhora do OpenUpgrade...

2022-10-15 12:06 UTC, closed without merging