[12.0][IMP] payment_pagseguro: Parcelamento de cartão de crédito
OCA/l10n-brazil pull request #1916
Opened 2022-05-20 11:44 UTC by kmmelcher

Nesse PR, nosso time da KMEE adicionou a opção de parcelar compras no cartão de crédito pelo pagseguro.
Issues e próximos passos estão no README.

Alguns screenshots das mudanças:

![image](https://user-images.githubusercontent.com/20446656/169520905-17772572-e797-42cb-8c3c-06b77a621b53.png)
![image](https://user-images.githubusercontent.com/20446656/169520981-cf70ec8e-7762-4832-9e29-b56396bbe78d.png)

Encontramos também um problema no .gitignore, que não está relacionado diretamente a Pagseguro.
Ao tentarmos adicionar uma nova lib javascript dentro de static/lib como está com ! no .gitignore não conseguimos.
Isso acontecia porque todo diretório /lib estava excluído pelo .gitignore. Dessa forma, colocamos um * para que somente
os arquivos dentro dos diretórios /lib fossem excluídos. Dessa forma, podemos usar o ! para que as libs sejão uma exceção que possa ser adicionada ao git.

2022-05-20 14:24 UTC, rvalyi requested changes
@kmmelcher eu acho o codigo do PR ok, mas mexer no .gitignore não me parece uma boa, porque pelo menos nas branches mais recentes esse arquivo acaba sendo padronizado e sincronizado por um bot da OCA. Sera se vc não consegue adicionar seus arquivos de lib com `git add -f arquivo`? Veja isso https://stackoverflow.com/questions/8006393/force-add-despite-the-gitignore-file

Tb tem examples de tais arquivos em pastas lib dentro da OCA como https://github.com/OCA/web/tree/14.0/web_timeline/static/lib/vis-timeline sem eles ter mexido no .gitignore.

Da para vc tentar com git add --force e tirar essa alteração do .gitignore então por favor?

2022-05-20 14:47 UTC, rvalyi commented
@kmmelcher outra coisa que é **apenas opinião** no caso: se eu fosse a KMEE eu faria esse tipo de modulo com licença LGPL e não AGPL. A galera que vai fazer site que vai interagir com qualquer um facilmente vai cair na paranoia que vai ter que liberar o código de todas customizaçoes web Odoo dela por conta da margem de interpretação da AGPL. E vc pode contar com a própria Odoo SA para espalhar esse medo (FUD) para vender a versão Enterprise dela.
E ao mesmo tempo sendo AGPL não protege muito de alguém fazer um modulo payment_seguro_enterprise fechado que teria mais coisas e ate se for seria então fácil quebrar um tal modulo botando outro open source equivalente (porque nao teria muita coisa). Eu comentei um pouco de forma geral sobre o tema aqui https://github.com/OCA/l10n-brazil/issues/1374
Mas enfim isso fica a critério de vocês que são os autores deste módulo claro.

2022-05-26 19:30 UTC, rvalyi commented
Ola [kmmelcher](https://github.com/kmmelcher) vc consegue arrumar a questão do .gitignore? 

Vc pode fazer um `rebase -i 31cce866b3dfe1fdbf378c366bd38eeea4eb35fe` por examplo e alterar os commits depois. Ou se vc achar complicado vc cria uma nova branch com `git checkout -b 12.0-payment-pagseguro-credit-2 31cce866b3dfe1fdbf378c366bd38eeea4eb35fe` e depois refaz os commits seguente usando `git cherry-pick sha1` ou manualmente.

Ai depois que tiver tudo certo manda a branch aqui de novo com `git push -f kmee 12.0-payment-pagseguro-credit-2:12.0-payment-pagseguro-credit` por examplo. Alguma duvida? Vc quer que a gente faça?

2022-05-27 16:15 UTC, kmmelcher commented
> Ola [kmmelcher](https://github.com/kmmelcher) vc consegue arrumar a questão do .gitignore?
> 
> Vc pode fazer um `rebase -i 31cce866b3dfe1fdbf378c366bd38eeea4eb35fe` por examplo e alterar os commits depois. Ou se vc achar complicado vc cria uma nova branch com `git checkout -b 12.0-payment-pagseguro-credit-2 31cce866b3dfe1fdbf378c366bd38eeea4eb35fe` e depois refaz os commits seguente usando `git cherry-pick sha1` ou manualmente.
> 
> Ai depois que tiver tudo certo manda a branch aqui de novo com `git push -f kmee 12.0-payment-pagseguro-credit-2:12.0-payment-pagseguro-credit` por examplo. Alguma duvida? Vc quer que a gente faça?

Ok, removi a mudança no .gitignore
Como a lib js já estava lá o arquivo permaneceu. 
Precisa de fazer um rebase?

2022-05-27 17:20 UTC, rvalyi commented
Eu acho que não valeu. Deve ter dado na mesma no final.

2022-05-27 17:26 UTC, kmmelcher commented
> Eu acho que não valeu. Deve ter dado na mesma no final.

O que eu fiz dá na mesma que fazer  git add -f arquivo

2022-05-27 18:13 UTC, kmmelcher commented
> > Eu acho que não valeu. Deve ter dado na mesma no final.
> 
> O que eu fiz dá na mesma que fazer git add -f arquivo

Eu dei o comando:
`git pull -r oca 12.0`
Porém não tem nenhuma mudança para que eu faça um commit,
Não sei se eu fiz o comando errado para forçar um rebase.

2022-05-27 18:14 UTC, kmmelcher commented
> > > Eu acho que não valeu. Deve ter dado na mesma no final.
> > 
> > 
> > O que eu fiz dá na mesma que fazer git add -f arquivo
> 
> Eu dei o comando: `git pull -r oca 12.0` Porém não tem nenhuma mudança para que eu faça um commit, Não sei se eu fiz o comando errado para forçar um rebase.

2022-05-27 18:38 UTC, rvalyi commented on payment_pagseguro/static/lib/pagseguro_templates.js
> +// Copyright 2022 KMEEli
@kmmelcher sem importância, mas eu acho que tem uma tipo aqui

2022-05-27 18:45 UTC, rvalyi approved these changes
OK aprovado parabens pelo código.

Outra coisa que é apenas opinião: vamos dizer ate a v12 era difícil caçar projeto Odoo fazível no Brasil e nisso atrair o olhar da empresa multinacional que já usava Odoo fora do Brasil ou já tava ligado da mudança no mercado era uma boa. Mas eu diria que hoje, em tempo de v14+, a gente já conseguiria encaixar o Odoo meio que na metade das empresas do mercado alvo. Ai nisso, eu usaria ate umas 2 linhas de introdução em inglês, mas o restante eu faria em português mesmo, tipo para bater na pesquisa Google do leigo mesmo. (cc @mbcosta o mesmo comentário vale pros módulos de CNAB). No código quando mais inglês melhor ai sim, porque facilmente pode ter programador de fora.

Mas tanto isso como a questão da licença são coisas que podem ser retrabalhadas la na frente, então por mim já ta OK.

2022-05-28 19:29 UTC, marcelsavegnago approved these changes

2022-05-28 21:23 UTC, rvalyi commented
/ocabot merge major

2022-06-01 14:21 UTC, renatonlima approved these changes

2022-06-01 15:14 UTC, rvalyi commented
esse merge parece travado... Eu iniciei o merge do https://github.com/OCA/l10n-brazil/pull/1924 mesmo assim porque me parece mais urgente para poder integrar os PRs ligados a importação de NFe. Depois vamos iniciar esse merge de novo...

2022-06-01 18:17 UTC, rvalyi commented
/ocabot merge major

2022-06-01 21:49 UTC, merged

2022-06-01 23:30 UTC, marcelsavegnago commented
@kmmelcher se quiser portar isso para a 14 temos uma PR de migração em aberto.. Basta submeter uma PR para o nosso fork. Se tiver um tempinho e puder ajudar no teste da 14.0 eu agradeço tbm apesar de que já tem ajudado bastante.

cc @Eduardolimr