[12.0] Update financial move in fiscal document NFE XML
OCA/l10n-brazil pull request #1923
Opened 2022-05-25 16:07 UTC by renatonlima

Atualmente não é possível alterar os dados de vencimento ou valor das duplicatas de uma NF-e porque a account.move.line é gerada quando a fatura é confirmada e gerado o XML, depois de confirmado e antes de transmitir se for alterado algum dado na account.move.line essa informação não é atualizada no XML da NFe.

Esse PR implementa a atualização do XML na NFe caso os vencimento, referencia ou valor for alterado.

2022-05-25 17:27 UTC, antoniospneto approved these changes

2022-05-26 14:07 UTC, hirokibastos approved these changes

2022-05-26 21:56 UTC, marcelsavegnago approved these changes

2022-05-27 13:26 UTC, rvalyi requested changes

2022-05-27 13:26 UTC, rvalyi commented on l10n_br_account_nfe/models/account_move_line.py
> +                    ):
não se faz muito de botar um if com apenas um if dentro. Neste caso, seria melhor botar apenas um if com mais uma condição and `invoice.fiscal_document_id.id != invoice.company_id.fiscal_dummy_id.id` (podendo ser a primeira condição).

2022-05-27 16:48 UTC, renatonlima commented on l10n_br_account_nfe/models/account_move_line.py
> +                    ):
@rvalyi

Agora não tem nenhum if... rsrsrsrs eu fiz o filtered() no for

2022-05-27 16:54 UTC, mbcosta approved these changes

2022-05-27 17:16 UTC, rvalyi approved these changes

2022-05-27 17:17 UTC, rvalyi commented
/ocabot merge minor

2022-05-27 21:15 UTC, merged