[12.0] l10n_br_nfe: adiciona método match_or_create_m2o para product.product
OCA/l10n-brazil pull request #1986
Opened 2022-06-17 14:30 UTC by hirokibastos

Acomoda mudança requisitada pelo @rvalyi  em #1985

Com a remoção do related de nfe40_xProd, é necessário tratamento especial para match por nome de registros do tipo product.product, este PR cria este tratamento.

2022-06-17 16:03 UTC, rvalyi commented
@hirokibastos era bem por ai, vou olhar com calma. Mas revisões são bem vindas.

2022-06-17 17:13 UTC, mileo requested changes
É necessário consultar a tabela:

https://github.com/odoo/odoo/blob/12.0/addons/product/models/product.py#L749 

_name = "product.supplierinfo"

Ela cruza o produto com o produto do fornecedor.

2022-06-17 18:52 UTC, hirokibastos commented
> É necessário consultar a tabela:
> 
> https://github.com/odoo/odoo/blob/12.0/addons/product/models/product.py#L749
> 
> _name = "product.supplierinfo"
> 
> Ela cruza o produto com o produto do fornecedor.

Meu entendimento era que este tipo de cruzamento de produto interno com produto do fornecer seria adicionado junto com o sistema de depara. Apesar de já haver a criação do product.supplierinfo em #1701, ainda não criei um PR separado pra adicionar esta parte da importação.
Não seria melhor adicionar este tipo de consulta junto com essa outra parte?
Posso adicionar nesse PR caso achem que já vale fazer isso.

2022-06-19 20:39 UTC, rvalyi requested changes

2022-06-19 20:39 UTC, rvalyi commented on l10n_br_nfe/models/product_product.py
> +            domain.append(("barcode", "=", rec_dict.get("barcode")))
seria mais limpo se você usasse expression.OR como aqui https://github.com/OCA/account-reconcile/blob/14.0/account_reconciliation_widget/models/reconciliation_widget.py#L802
Eu sei que nem sempre foi o que usamos na localização mas nunca é tarde. Fica menos críptico do que esse ```if domain: domain.insert(0, "|")```

2022-06-21 03:21 UTC, rvalyi approved these changes
ficou legal @hirokibastos !
@mileo eu não vejo problema em mandar os PRs de depare depois. Realmente o related tava ruim porque ia criar regressoẽs mas esse codigo ja é um ganho e eu acho bom ir de forma iterativa jogando as decisoẽs de depare la para frente. (mas eu concordo com a consulta do supplierinfo depois).

2022-06-21 10:20 UTC, felipemotter approved these changes

2022-06-23 13:55 UTC, rvalyi commented
@hirokibastos @mileo como vcs resolveram isso na KMEE? fazemos o merge disso já ou vcs pretendem subir algo de consulta no supplierinfo nesse mesmo PR?

2022-06-28 14:18 UTC, rvalyi commented
up @mileo @hirokibastos

2022-07-04 12:05 UTC, mileo approved these changes

2022-07-04 12:06 UTC, mileo commented
/ocabot merge minor

2022-07-04 19:51 UTC, rvalyi commented
/ocabot merge minor

2022-07-04 23:13 UTC, rvalyi commented
erro com o serviço de IBPT duas vezes...

2022-07-04 23:14 UTC, rvalyi commented
/ocabot merge minor

2022-07-05 04:25 UTC, merged