[14.0][IMP] l10n_br_nfe: add accountant cnpj_cpf on autXML tag
OCA/l10n-brazil pull request #2040
Opened 2022-07-25 18:32 UTC by marcelsavegnago

Em alguns estados é exigido a informação do cnpj do contador na tag autXML. Acredito que neste caberia também informar o cnpj do responsável técnico também. 

Implementei um compute no campo  nfe40_autXML que por ora atenderia e tentei ser o menos intrusivo possível. 

@rvalyi se puder dar uma olhada e criticar, eu agradeço :)

2022-07-25 19:13 UTC, netosjb commented
Marcel, se é um campo opcional para alguns,  será que não é interessante por um flag na configuração da empresa, perguntando se deseja ou não incluir essa informação na tag ?

2022-07-25 19:27 UTC, marcelsavegnago commented
> Marcel, se é um campo opcional para alguns, será que não é interessante por um flag na configuração da empresa, perguntando se deseja ou não incluir essa informação na tag ? e por padrão trazer false.

Eh uma opcao sim..

2022-07-25 19:27 UTC, netosjb commented
@marcelsavegnago acho que pra não dar os warning de cachemiss vc tem que ser uma valor para o nfe40_autXML se ele não cair nos if, nem que seja um false

2022-07-25 20:37 UTC, marcelsavegnago commented
> @marcelsavegnago acho que pra não dar os warning de cachemiss vc tem que setar um valor para o nfe40_autXML se ele não cair nos if, nem que seja um false

@netosjb resolvido..

Adicionei um novo commit (ainda nao oficial hehehe) incluindo a questão relacionada a inclusão opcional do contador e do suporte tecnico como pessoas autorizadas para fazer o download do xml da nfe

2022-07-26 01:39 UTC, netosjb approved these changes
por mim tá legal assim 👍🏻

2022-07-26 03:06 UTC, felipemotter approved these changes

2022-07-26 17:21 UTC, marcelsavegnago commented
> por mim tá legal assim 👍🏻

Vou reorganizar os commits

2022-07-26 17:35 UTC, marcelsavegnago commented
@rvalyi reorganizei os commits. Vc acha válido seguir este caminho ?

2022-07-26 19:08 UTC, rvalyi commented
@renatonlima vc acha que essa PR funciona legal com nossos casos?

2022-07-26 20:08 UTC, renatonlima commented
@marcelsavegnago e @rvalyi,

É interessante esse recurso principalmente para empresas que faz a contabilidade através de um prestador de serviço externo, dessa forma o prestador pode baixar os arquivos XMLs.

Eu só estou pensando se talvez não seria melhor ao invés de usar um campo nfe40_autXML como calculado, injetar o nfe.40.autxml no res.partner assim como as outras classes https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_nfe/models/res_partner.py#L26, por exemplo hoje a classe nfe.40.tinfresptec já esta injetada no res.partner e relacionado o campo nfe40_infRespTec  no documento fiscal https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_nfe/models/document.py#L512.

Como o campo nfe40_autXML é um One2many não sei se é possível fazer como o campo nfe40_infRespTec que é um Many2one, neste caso uma outra possibilidade é fazer de forma semelhante ao https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_nfe/models/document_related.py#L20, herdar o objeto nfe.40.autxml adicionar o campo partner_id e adicionar por padrão de acordo com a configuração o responsável técnico e o contador, dessa forma além de adicionar o contador e o responsável técnico também seria possível adicionar qualquer parceiro.

2022-07-26 20:11 UTC, renatonlima requested changes
@marcelsavegnago e @rvalyi,

É interessante esse recurso principalmente para empresas que faz a contabilidade através de um prestador de serviço externo, dessa forma o prestador pode baixar os arquivos XMLs.

Eu só estou pensando se talvez não seria melhor ao invés de usar um campo nfe40_autXML como calculado, injetar o nfe.40.autxml no res.partner assim como as outras classes https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_nfe/models/res_partner.py#L26, por exemplo hoje a classe nfe.40.tinfresptec já esta injetada no res.partner e relacionado o campo nfe40_infRespTec no documento fiscal https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_nfe/models/document.py#L512.

Como o campo nfe40_autXML é um One2many não sei se é possível fazer como o campo nfe40_infRespTec que é um Many2one, neste caso uma outra possibilidade é fazer de forma semelhante ao https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_nfe/models/document_related.py#L20, herdar o objeto nfe.40.autxml adicionar o campo partner_id e adicionar por padrão de acordo com a configuração o responsável técnico e o contador, dessa forma além de adicionar o contador e o responsável técnico também seria possível adicionar qualquer parceiro.

Também seria bom adicionar pelo menos dois testes básicos um com um documento adicionando o contador e o responsável técnico e outro sem adicionar.

2022-07-26 20:20 UTC, rvalyi commented
Pode ser que eu não pensei suficientemente ainda, mas minha intuição seria tb de injetar o autXML no res.partner tb. Pois isso me parece tb mais alinhado com o modelo do SPED onde vamos mapear o contador da empresa com o mesmo registro. Poderia ser o mesmo registro do que esse J930 do ECD por examplo https://github.com/akretion/sped-extractor/blob/master/spedextractor/specs/2020/ecd/ecd_pythonsped.json#L4050 ?
Ou eu estou errado?

2022-07-26 20:55 UTC, marcelsavegnago commented
> Também seria bom adicionar pelo menos dois testes básicos um com um documento adicionando o contador e o responsável técnico e outro sem adicionar.

Isso seria bom.. tentei fazer com o store=true mas não deu certo. Vlww

2022-07-27 21:07 UTC, marcelsavegnago commented
> Como o campo nfe40_autXML é um One2many não sei se é possível fazer como o campo nfe40_infRespTec que é um Many2one, neste caso uma outra possibilidade é fazer de forma semelhante ao https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_nfe/models/document_related.py#L20, herdar o objeto nfe.40.autxml adicionar o campo partner_id e adicionar por padrão de acordo com a configuração o responsável técnico e o contador, dessa forma além de adicionar o contador e o responsável técnico também seria possível adicionar qualquer parceiro.

@renatonlima @rvalyi acha que é valido/precisa criar um modelo no fiscal chamado l10n_br_fiscal.document.authorized.partner igual eh o document.related ?

2022-07-27 21:09 UTC, marcelsavegnago commented
Fora isso estou apanhando para popular o campo One2many sem o compute. Consegui fazendo pelo default_get mas ainda não ta legal. Talvez seja valido definir o valor do autXML no onchange do tipo de documento fiscal.

2022-07-28 14:19 UTC, marcelsavegnago commented
Pessoal.. eu havia implementado um modelo de dados no fiscal mas acredito que não precisa. Consegui resolver tbm a questão do valor default do campo. 

Como herdei o objeto autXML no partner, na hora de popular manualmente o campo autXML não tenho a opção de selecionar um parceiro e sim apenas de cadastro de um novo parceiro.

2022-07-28 15:06 UTC, marcelsavegnago commented
> Como herdei o objeto autXML no partner, na hora de popular manualmente o campo autXML não tenho a opção de selecionar um parceiro e sim apenas de cadastro de um novo parceiro.

Aparentemente resolvido. Neste caso usei o widget many2many no campo nfe40_autXML.

2022-07-28 15:06 UTC, rvalyi commented
Eu não digo que eu aprovo ainda. Mas pelo menos olhando por cima parece bem mais legal dessa forma.

2022-07-28 15:08 UTC, marcelsavegnago commented
> Eu não digo que eu aprovo ainda. Mas pelo menos olhando por cima parece bem mais legal dessa forma.

Boa.. vlw.. Ficou bem mais limpo desta forma.

2022-07-28 15:31 UTC, renatonlima commented
@marcelsavegnago,

Você precisa incluir a classe do spec nfe.40.autxml no _force_stack_paths da classe da NFe no l10n_br_nfe/models/document.py para não ser criado a tabela nfe_40_autxml

É isso mesmo @rvalyi?

2022-07-28 15:59 UTC, renatonlima approved these changes

2022-07-28 16:00 UTC, renatonlima commented
LGTM

@marcelsavegnago Você consegue fazer o backport para a 12.0?

2022-07-28 16:02 UTC, marcelsavegnago commented
> LGTM
> 
> @marcelsavegnago Você consegue fazer o backport para a 12.0?

Consigo sim. Já vou preparar aqui.

2022-07-28 16:21 UTC, marcelsavegnago commented
> LGTM
> 
> @marcelsavegnago Você consegue fazer o backport para a 12.0?

feito https://github.com/OCA/l10n-brazil/pull/2048

2022-07-28 16:25 UTC, renatonlima commented
/ocabot merge minor

2022-07-28 17:19 UTC, merged

2022-07-29 11:49 UTC, augustodinizl reviewed
Funciona muito bem, acabei de testar aqui @marcelsavegnago , parabéns!