[12.0][ADD] l10n_br_purchase_request
OCA/l10n-brazil pull request #2091
Opened 2022-08-26 17:43 UTC by marcelsavegnago

2022-08-26 19:42 UTC, rvalyi requested changes

2022-08-26 19:42 UTC, rvalyi commented on l10n_br_purchase_request/wizards/purchase_request_line_make_purchase_order.xml
> +<!--    </record>-->
nâo seria melhor remover esse arquivo se não serve mesmo?

2022-08-26 19:49 UTC, marcelsavegnago commented on l10n_br_purchase_request/wizards/purchase_request_line_make_purchase_order.xml
> +<!--    </record>-->
opa... verdade eu tinha esquecido dele.

2022-08-26 19:50 UTC, marcelsavegnago commented on l10n_br_purchase_request/wizards/purchase_request_line_make_purchase_order.xml
> +<!--    </record>-->
Feito

2022-08-26 20:24 UTC, rvalyi approved these changes

2022-08-28 15:25 UTC, douglascstd approved these changes
APROVADO - Testes Funcionais

![image](https://user-images.githubusercontent.com/20867090/187081736-1d0d5dfb-1c68-4718-9aae-47975343718c.png)

![image](https://user-images.githubusercontent.com/20867090/187081744-3dc233ce-ec72-414a-b66f-bae26bc27dd5.png)

![image](https://user-images.githubusercontent.com/20867090/187081746-c2195415-f1be-4381-a142-05d8f4924627.png)

![image](https://user-images.githubusercontent.com/20867090/187081750-47f3a802-3a0a-4be6-96ab-f181626b5f5f.png)

2022-08-28 15:34 UTC, rvalyi commented
Valeu @douglascstd essas reviews são super valiosas para a gente ter segurança com os merges!

2022-08-28 15:34 UTC, rvalyi commented
/ocabot merge nobump

2022-08-28 16:16 UTC, rvalyi commented
@marcelsavegnago deu pau nos testes na hora do merge e infelizmente ta no seu modulo mesmo. Não teria alguma situação com os outros módulos que os testes não ficariam consistentes? cc @douglascstd 

![2022-08-28_13-14](https://user-images.githubusercontent.com/16926/187083964-f3829f24-b343-4ebb-b952-bad98c6e8020.png)

2022-08-28 18:41 UTC, marcelsavegnago commented
> @marcelsavegnago deu pau nos testes na hora do merge e infelizmente ta no seu modulo mesmo. Não teria alguma situação com os outros módulos que os testes não ficariam consistentes? cc @douglascstd
> 
> ![2022-08-28_13-14](https://user-images.githubusercontent.com/16926/187083964-f3829f24-b343-4ebb-b952-bad98c6e8020.png)

Isso agora eh por conta da mudança que fiz em relação a definicao das taxas.. tenho que rodar passando a empresa na contexto

2022-08-28 18:58 UTC, rvalyi commented
Ok. Lancei umas 3 vezes na 14 e não deu problema lá.

2022-08-29 00:51 UTC, douglascstd commented
Pelo que percebi, os teste que fiz foi na base instalada que ainda não tinha sido aplicada a  #2087  é isso @marcelsavegnago? Se agora estiver aplicado, posso refazer o teste.

2022-08-29 01:44 UTC, rvalyi commented
> Pelo que percebi, os teste que fiz foi na base instalada que ainda não tinha sido aplicada a #2087 é isso @marcelsavegnago? Se agora estiver aplicado, posso refazer o teste.

era apenas inconsistence (as vezes funcionava, as vezes sim). Agora ele corrigiu pelo que eu vi.

2022-08-29 01:45 UTC, rvalyi commented
/ocabot merge nobump

2022-08-29 03:26 UTC, marcelsavegnago commented
@douglascstd se quiser testar via runboat novamente eu agradeço. Dependendo a situação pode ser necessário passar a empresa no contexto para poder pegar os impostos corretamente.

2022-08-29 05:18 UTC, merged