[12.0][ADD] Novo módulo l10n_br_sale_commission_stock
OCA/l10n-brazil pull request #2102
Opened 2022-08-31 22:18 UTC by renatonlima

Esse módulo tem o objetivo de copiar os dados de comissões do pedido de venda para a fatura quando a fatura é gerada através do picking.

2022-08-31 23:30 UTC, rvalyi requested changes

2022-08-31 23:30 UTC, rvalyi commented on l10n_br_sale_commission_stock/__manifest__.py
> +        "l10n_br_stock_account",
l10n_br_sale_stock já depende do l10n_br_stock_account. Na OCA a prática é de não repetir a dependência nesse caso.

2022-09-01 13:39 UTC, rvalyi commented
```
======== Testing test_flake8 ========
l10n_br_sale_commission_stock/tests/test_sale_commission_stock.py:115:89: E501 line too long (93 > 88 characters)
```

2022-09-01 16:25 UTC, rvalyi approved these changes
LGTM

2022-09-01 18:30 UTC, marcelsavegnago approved these changes

2022-09-01 21:38 UTC, rvalyi commented
/ocabot merge nobump

2022-09-01 22:52 UTC, merged