[14.0][MIG] l10n_br_sale_invoice_plan
OCA/l10n-brazil pull request #2108
Opened 2022-09-02 20:05 UTC by marcelsavegnago

2022-09-04 23:46 UTC, rvalyi approved these changes
Eu tb aprovei o seu outro fix upstream porque eu vi o bug qdo eu testei https://github.com/OCA/sale-workflow/pull/2182

2022-09-05 14:15 UTC, douglascstd requested changes
Tem uma divergência entre os valores da SO e das faturas, onde os valores utilizados como valor total, está sendo utilizado o valor líquido sem impostos:
![image](https://user-images.githubusercontent.com/20867090/188469013-b0c2eccd-18d3-4ebe-a0d1-ada0cfa5b5e4.png)

Valor da Fatura:
![image](https://user-images.githubusercontent.com/20867090/188469264-dd7e4d82-ab6b-4274-b923-094c194b92fe.png)
![image](https://user-images.githubusercontent.com/20867090/188469294-560d3caa-a076-48fa-8582-2a350a059123.png)

2022-09-05 14:45 UTC, douglascstd commented
O valor utilizado parece ser o valor líquido sem impostos.

2022-09-05 17:23 UTC, marcelsavegnago commented
@douglascstd se testar no runboat da branch 14.0 vc vai perceber que isto acontece quando eh gerado uma invoice via um pedido de venda (sem sale invoice plan). Ou seja, não seria um entrave para esta PR entendo eu.

2022-09-06 12:29 UTC, douglascstd approved these changes
[APROVADO] Testes funcionais

2022-09-06 12:51 UTC, rvalyi commented
/ocabot merge nobump

2022-09-06 13:16 UTC, merged