[14.0] l10n_br_base, l10n_br_account: Cadastro de chaves PIX no Parceiro.
OCA/l10n-brazil pull request #2123
Opened 2022-09-11 04:11 UTC by netosjb

Adiciona o cadastro da chaves PIX no Parceiro.

![image](https://user-images.githubusercontent.com/634278/189511948-8058ed11-db09-4feb-b320-cd2cef272715.png)
O cadastro fica dentro do cadastro do Parceiro, na aba invoicing a baixo do cadastro das contas bancárias.

As chaves são tratadas e validadas conforme o seu tipo.

PR em rascunho, falta incluir os testes.

2022-09-11 13:24 UTC, felipemotter approved these changes

2022-09-11 16:21 UTC, marcos-mendez approved these changes
Maravilha em parabens

2022-09-12 12:22 UTC, netosjb commented
testes e dados demos incluído ✔️ 
tudo verde ✔️

2022-09-12 12:27 UTC, netosjb commented
ah esqueci de comentar, os commit da pr #2124 estão incluídos aqui, ao fazer o merge deles eu faço o rebase aqui pra eles sumirem.

2022-09-12 12:37 UTC, rvalyi commented
Eu acho tranquilo fazer o merge do https://github.com/OCA/l10n-brazil/pull/2124 porem para esse eu acho bom eu e o @renatonlima revisar com calma. Mas valeu pelo trabalho, vai servir isso ja temos certeza.

2022-09-12 12:42 UTC, vanderleiromera approved these changes

2022-09-12 12:50 UTC, douglascstd approved these changes
[APROVADO] Testes Funcionais, com uma sugestão de melhoria no final deste review.

Screenshots:
![image](https://user-images.githubusercontent.com/20867090/189656787-0b6f64e6-ed8e-4dd5-b996-b59ebb258934.png)

Seleção de n chaves:
![image](https://user-images.githubusercontent.com/20867090/189656872-da170784-6e0d-4026-8fc0-344c170fd8bb.png)

Utilização de uma tabela com relação:
![image](https://user-images.githubusercontent.com/20867090/189656965-8e5ff8f5-d3a2-4472-93a5-0ed341a88f6a.png)

Validação de CPF/CNPJ e email:
![image](https://user-images.githubusercontent.com/20867090/189657071-823f5fc1-7ed1-445f-858f-b16c539476ac.png)
![image](https://user-images.githubusercontent.com/20867090/189657266-f5d25796-435f-40d3-8ba4-d47e13e6fb76.png)
![image](https://user-images.githubusercontent.com/20867090/189657707-b3e28cf3-6c48-45bf-a3b4-3ec6e44b0905.png)

#### **SUGESTÃO:**
Incluir um campo de seleção de qual é a chave Pix PADRÃO para o parceiro. Para que assim seja utilizado em uma execução de pagamento.

2022-09-12 13:03 UTC, antoniospneto commented
Obrigado pela revisão @douglascstd !

Sobre a sugestão, essa implementação já existe, funciona assim:

a listagem ela é ordenável, vc pode arrastar pra cima ou pra baixo, a chave que estiver em primeiro será o preferencial.
é o mesmo funcionamento que é aplicado nas contas bancárias.

Vou incluir uma observação sobre isso no help do campo para deixar claro ;)

2022-09-12 14:11 UTC, marcelsavegnago commented on l10n_br_account/views/res_partner_view.xml
> +                <group
Considerando ambientes de multi localizações eu sugiro que qualquer novo desenvolvimento especifico do brazil sempre leve isso em consideração.

2022-09-12 14:13 UTC, netosjb commented on l10n_br_account/views/res_partner_view.xml
> +                <group
boa marcel, vou adicionar uma verificação.

2022-09-12 14:46 UTC, marcelsavegnago commented
Itens para considerar:

- Possibilidade ser um módulo separado talvez
- Outros meios de pagamento tipo PIX que podem surgir a qualquer momento tanto dentro como fora do país. Talvez seja válido deixar mais generico. Gostei do nome Instant Payment Keys.. talvez caberia um selecition para definir o tipo de chave (generic instant key, pix, xyz...)
- Caberia começar uma base em algum outro módulo/repo ? account_payment_mode ? ou até mesmo implementar um novo módulo no reposítório bank-payment. Exemplo: account_payment_mode_instant_payment com um boolean na tabel de modos de pagamento com valor default igual FALSE para definir se aquele modo de pagamento é instantaneo ou não, cria uma tabela res.partner.payment.instant.key com um campo selection para definir o tipo da chave (pix, generic e afins). Inclusive deixar até configurado na empresa se a mesma trabalha ou não com pagamento intantaneo através de chave afim de definir se deve ou não aparecer a tabela de chaves no cadastro do parceiro.

2022-09-12 15:07 UTC, rvalyi commented
> Itens para considerar:
> 
> * Possibilidade ser um módulo separado talvez

Esse é o X da questão que eu queria avaliar melhor. Talvez vale a pena no mesmo modulo, mas no passado a gente acabou dando mole demais para a enfiação de funcionalidades e por examplo no modulo fiscal ficou abusado e hoje ainda temos trabalho para limpar. Então temos que pensar com calma...

2022-09-12 16:46 UTC, netosjb commented
Sobre por em um módulo separado:
Hoje o PIX já é a forma de pagamento mais utilizada no brasil, acredito por ser comum a todos os negócios do Brasil, poderia ser implementado no base, o que pode ser uma desvantagem é que essa PR adiciona duas dependências externas, caso decidam que é melhor fazer um módulo externo eu me comprometo em fazer a alteração.


> Outros meios de pagamento tipo PIX que podem surgir a qualquer momento tanto dentro como fora do país. Talvez seja válido deixar mais generico. Gostei do nome Instant Payment Keys.. talvez caberia um selecition para definir o tipo de chave (generic instant key, pix, xyz...)

Particularmente eu prefiro ter o modelo bem definido, outro meios de pagamento podem ter seu próprio modelo, pois as regras de negócio podem mudar bastante, por exemplo no pix a tem os tipos, validações e o uso bem especifico.

> Caberia começar uma base em algum outro módulo/repo ? account_payment_mode ? ou até mesmo implementar um novo módulo no reposítório bank-payment. Exemplo: account_payment_mode_instant_payment com um boolean na tabel de modos de pagamento com valor default igual FALSE para definir se aquele modo de pagamento é instantaneo ou não, cria uma tabela res.partner.payment.instant.key com um campo selection para definir o tipo da chave (pix, generic e afins). Inclusive deixar até configurado na empresa se a mesma trabalha ou não com pagamento intantaneo através de chave afim de definir se deve ou não aparecer a tabela de chaves no cadastro do parceiro.

Eu pensei nessas informações como algo básico, assim como pode ser ter o cadastro de contas bancárias no parceiro, podemos ter as chaves pix, mesmo que seja para uso manual, por exemplo um usuário pode consultar no cadastro quando precisar fazer um deposito, mesmo que seja direto no banco dele de forma manual.

2022-09-12 17:36 UTC, marcelsavegnago commented
> Hoje o PIX já é a forma de pagamento mais utilizada no brasil, acredito por ser comum a todos os negócios do Brasil, poderia ser implementado no base, o que pode ser uma desvantagem é que essa PR adiciona duas dependências externas, caso decidam que é melhor fazer um módulo externo eu me comprometo em fazer a alteração.
> 

Show.. acho que considerar como um módulo separado fica mais fácil porque de certa forma fica opcional

2022-09-12 17:40 UTC, rvalyi commented
As vezes não é nem pela questão de ficar opcional, mas sim de deixar as camadas de código separadas, de forma que fica explícito o que depende de que em vez de ficar uma hidra gigantesca. Mas vou olhar melhor ainda logo que eu puder.

2022-09-12 18:13 UTC, netosjb commented
Certo, obrigado pela revisão! aguardo o feedback, se precisar separar em um outro módulo faço sem problemas ;)

2022-09-13 15:07 UTC, renatonlima requested changes

2022-09-13 15:07 UTC, renatonlima commented on l10n_br_base/models/res_partner_pix.py
> +        self.check_vals(vals)
Ao invés de chamar o check_vals nos métodos create e write você pode adicionar a notação  @api.constrains no método check_vals

2022-09-13 15:07 UTC, renatonlima commented on l10n_br_base/models/res_partner_pix.py
> +    key_type = fields.Selection(
Acho que deveria ter uma sql constraint para não permitir valores dos (key_type e key) repetidos

2022-09-13 15:07 UTC, renatonlima commented on l10n_br_base/security/ir.model.access.csv
> +"res_partner_pix_manager","Partner PIX for Manager","model_res_partner_pix","base.group_system",1,1,1,1
Deveria criar uma permissão com todos os acessos para o grupo Gerente da Contabilidade (account.group_account_manager)

2022-09-13 15:42 UTC, renatonlima commented
@netosjb, @rvalyi e @marcelsavegnago,

Eu não vejo problema nas informações de pix ficarem no l10n_br_base porque no módulo base do core do Odoo já existe informações bancárias como a lista de bancos (res.bank) e das contas bancárias (res.partner.bank). Só se justificaria criar outro módulo se nós não quiséssemos deixar a dependência externa do phonenumbers e email_validator" no l10n_br_base, que na minha opinião não vejo problema já que se tratam de dependências de baixa complexidade.

Sobre a criação de um módulo mais genérico a nível da OCA como account_instant_payment, é válido pensar no caso a médio prazo, porque pesquisando rapidamente sobre [pagamento instantâneo em outros países](https://www.monito.com/pt/wiki/pix-em-outros-paises), eu acredito que deveríamos observar se vai ser implementado algo pelo banco central europeu (que provavelmente seria compatível com os países da união europeia), mas como eu falei no inicio deveríamos pensar nisso a medio prazo talvez fazer esse trabalho na 16.0 e na 14.0 implementar algo na nível da localização mesmo.

2022-09-13 18:44 UTC, rvalyi commented
@netosjb uma precaução, vc não iria se opor caso a gente for propor de mudar a licença do modulo l10n_br_base para LGPL no futuro como explicamos aqui https://github.com/OCA/l10n-brazil/issues/1374 ? Seria bom opinar aqui ou isso poderia ser sim um motivo de deixar separado. Feito essa observação eu ainda não olhei bem o código mas eu pretendo fazer logo...

2022-09-18 01:04 UTC, netosjb commented on l10n_br_base/security/ir.model.access.csv
> +"res_partner_pix_manager","Partner PIX for Manager","model_res_partner_pix","base.group_system",1,1,1,1
Esse grupo não dá  pois o base não depende do módulo account, mas alterei a permissão de gerente para esse grupo: 
"base.group_partner_manager" acho que fica bom né? é o mesmo grupo que é usando para poder alterar a conta bancaria (res.partner.bank)

2022-09-18 19:26 UTC, netosjb commented
Alterações solicitadas resolvidas.

Também adicionei mais duas funcionalidades:

**1) Opção de poder relacionar a chave PIX com uma conta bancária.**

é interessante ter essa informação pois o usuário ao fazer uma transferência em PIX, usando uma chave, pode desejar conferir se a informação da conta bate com o do cadastro ao confirmar a transação no app do banco.


**2) Novo campo para definir o tipo de conta transacional no cadastro de conta bancária.**

Para fazer uma Transferência PIX, não é obrigatório informar uma **Chave PIX**, outra opção é fazer informando os dados de uma conta bancária transacional, que para o pix é classificado em três tipos:

**Conta Corrente, Conta Poupança e Conta pagamentos.** 

- Caso o usuário defina o tipo como Conta Corrente ou Conta Poupança, a informação do banco, conta, agencia e digito verificador devem ser informados.
- Caso o tipo seja definido como Conta Pagamento, o banco e o numero da conta devem ser informados.

Screenshots:

![image](https://user-images.githubusercontent.com/634278/190924148-bcebc711-2b9d-4f2e-8650-3acc3cac1b0a.png)
(cadastro no parceiro)

![image](https://user-images.githubusercontent.com/634278/190924887-f3791cda-d000-485c-9d2b-030439b95bec.png)
(cadastro conta bancária)

2022-09-18 19:27 UTC, netosjb commented
A PR está pronta revisão novamente 👍🏻

2022-09-18 19:42 UTC, marcos-mendez approved these changes
@netosjb aqui funcionou ok só mudou a posição mesmo dos campos né? Achei muito legal, se for pro Merge eu vou usar com certeza! OBG!

2022-09-18 20:07 UTC, netosjb commented
> @netosjb aqui funcionou ok só mudou a posição mesmo dos campos né? Achei muito legal, se for pro Merge eu vou usar com certeza! OBG!

Na verdades as chaves pix podem ser cadastradas diretamente da visão do parceiro ou da visão de dentro da conta do bancaria, tem as duas opções agora.

2022-09-19 14:01 UTC, rvalyi commented
Ola @netosjb eu vou revisar assim que eu puder, sobre o ponto da licença que eu levantei aqui, vcs poderiam apenas se posicionar https://github.com/OCA/l10n-brazil/pull/2123#issuecomment-1245819582 ? Isso é importante porque caso vcs tiverem divergência com isso, na minha opinião seria motivo de botar num modulo separado.

2022-09-19 15:01 UTC, netosjb commented
> Ola @netosjb eu vou revisar assim que eu puder, sobre o ponto da licença que eu levantei aqui, vcs poderiam apenas se posicionar https://github.com/OCA/l10n-brazil/pull/2123#issuecomment-1245819582 ? Isso é importante porque caso vcs tiverem divergência com isso, na minha opinião seria motivo de botar num modulo separado.

Opa Raphael, esqueci de comentar esse ponto, nós da Engenere concordamos com isso, somos a favor.

2022-09-19 17:20 UTC, renatonlima commented on l10n_br_base/models/res_partner_pix.py
> +        self.check_vals(vals)
@netosjb, você chegou a ver essa mudança? Daria para usar o api.constraints() no método check_vals e não sobre escrever os método create e write...

2022-09-19 17:27 UTC, antoniospneto commented on l10n_br_base/models/res_partner_pix.py
> +        self.check_vals(vals)
que estranho, eu tinha respondido essa questão, mas meu comentário sumiu.

Sim, eu tentei fazer com a notação, porém no meu uso não deu certo, é que além de fazer a validação eu faço a normalização dos campos que altera o valor do mesmo. pelo fato do valor está sendo alterado, com o api.constraints() o método entra em um loop infinito, fica chamando de forma recursiva até atingir o maximo e estourar uma exception.

2022-09-19 17:28 UTC, netosjb commented on l10n_br_base/models/res_partner_pix.py
> +    key_type = fields.Selection(
resolvido, adicionei a constraint  ( eu já tinha comentando, mas por algum motivo tinha sumido aqui tbm rss )

2022-09-19 21:16 UTC, rvalyi commented
Ola apenas como référença: o @mileo tinha proposto um prototipo de modulo de PIX na 12.0 https://github.com/OCA/l10n-brazil/pull/1040
Faltou um rebase mas o codigo pode ser visto direitamente na branch https://github.com/odoo-brazil/l10n-brazil/tree/12.0-l10n_br_pix/l10n_br_pix

A escolha do @mileo na época foi de fazer um modulo separado que dependia apenas do account. As chaves pix tavam na config mas não nos parceiros. Talvez teria algumas coisas para resgatar na hora de implementar a parte de pagamentos num outro modulo, por examplo essa class https://github.com/odoo-brazil/l10n-brazil/blob/12.0-l10n_br_pix/l10n_br_pix/models/l10n_br_pix_cob.py

Não vi coisas no modulo do @mileo que teria seu lugar aqui no l10n_br_base, mas ainda assim é interessante saber dessa proposta.

2022-09-19 21:19 UTC, mileo commented
Amanhã separo um tempo para revisar e comento
Ar esse pr, assim como fazer o rebase do antigo.

2022-09-19 22:04 UTC, netosjb commented
Pelo que pude verificar o protótipo do mileo visa a implementação para receber pagamentos via pix, qr code, pix conbranca, integração com o pagseguro, Que aí realmente nesse caso seria melhor um módulo separado. 

A implementação que estou propondo nesta pr é apenas para armazenar as informações de chaves pix nos cadastros dos parceiros, com as validações devidas. 

@mileo ficarei grato pela revisão.

2022-09-19 22:09 UTC, rvalyi commented
sim @netosjb foi assim que entendemos tb na Akretion por isso vemos essa PR de forma positiva, mas valeu a pena vc ter explicitado.

2022-09-19 23:00 UTC, mileo commented
Dei uma olhada rápida não testei.

Vocês cogitaram a possibilidade de implementar dentro do modelo res.partner.bank e não implementar o modelo res.partner.pix?

Isso facilitaria a integração com outros módulos que usam o campo conta bancária, obviamente os dados como banco, agencia e outros ficariam em branco.

Mas por exemplo na integração com o account_payment_order funcionaria sem muitos problemas.

@netosjb

2022-09-19 23:37 UTC, netosjb commented
> Dei uma olhada rápida não testei.
> 
> Vocês cogitaram a possibilidade de implementar dentro do modelo res.partner.bank e não implementar o modelo res.partner.pix?
> 
> Isso facilitaria a integração com outros módulos que usam o campo conta bancária, obviamente os dados como banco, agencia e outros ficariam em branco.
> 
> Mas por exemplo na integração com o account_payment_order funcionaria sem muitos problemas.
> 
> @netosjb

Pensamos nessa possibilidade, mas no fim não ajuda muito, com os objetos separado fica melhor de fazer os tratamentos do fluxo e as validações, além que na visão fica um pouco estranho uma conta bancária sem banco e sem numero.

Eu já tenho o tratamento quase pronto para lidar com o PIX no account_payment_order, pretendo submeter logo após a aprovação desta.

2022-09-20 03:15 UTC, antoniospneto commented
> > Dei uma olhada rápida não testei.
> 
> > 
> 
> > Vocês cogitaram a possibilidade de implementar dentro do modelo res.partner.bank e não implementar o modelo res.partner.pix?
> 
> > 
> 
> > Isso facilitaria a integração com outros módulos que usam o campo conta bancária, obviamente os dados como banco, agencia e outros ficariam em branco.
> 
> > 
> 
> > Mas por exemplo na integração com o account_payment_order funcionaria sem muitos problemas.
> 
> > 
> 
> > @netosjb
> 
> 
> 
> Pensamos nessa possibilidade, mas no fim não ajuda muito, com os objetos separado fica melhor de fazer os tratamentos do fluxo e as validações, além que na visão fica um pouco estranho uma conta bancária sem banco e sem numero.
> 
> 
> 
> Eu já tenho o tratamento quase pronto para lidar com o PIX no account_payment_order, pretendo submeter uma PR logo após a aprovação desta.

Outro detalhe, a chave pix pode ser referenciada dentro da conta bancária, porém é opcional, qualquer coisa é só tornar essa relação obrigatória.

2022-09-20 15:47 UTC, douglascstd commented
E vale lembrar que uma das opções de pix é o uso da conta/agencia do destinatário 
Entao o uso vinculado a conta bancária faz sentido

2022-09-29 23:08 UTC, rvalyi commented
@netosjb @felipemotter por mim esta aprovado, mas fiz um PR para incluir o @netosjb nos contribuidores do modulo. Logo apos o merge aprovo aqui.

2022-09-29 23:14 UTC, marcelsavegnago approved these changes

2022-09-30 01:16 UTC, rvalyi approved these changes

2022-09-30 01:17 UTC, renatonlima approved these changes

2022-09-30 01:18 UTC, rvalyi commented
/ocabot merge major

2022-09-30 01:20 UTC, rvalyi commented
(os testes falharam sem motivo por cause do JS nos testes Pagseguro, aqueles bugs inconsistentes, nada de blocar o merge)

2022-09-30 01:41 UTC, merged

2022-09-30 15:06 UTC, mbcosta commented
Pessoal tem um detalhe que parece não ter sido visto é que nos novos arquivos incluídos está faltando o cabeçalho de licença e o autor, acredito que isso é um padrão e consta na maioria dos arquivos python, exceção os __init__.py,  em alguns casos até mesmo nos arquivos XML, por isso @netosjb minha opinião é que isso deve ser corrigido nos seguintes  arquivos:

https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_base/models/res_partner_pix.py#L1
https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_base/tests/test_partner_bank.py#L1
https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_base/tests/test_valid_pix.py#L1

Um exemplo com o formato pode ser visto aqui  https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_account_nfe/models/document_workflow.py#L1

# Copyright (C) 2022-Today - Engenere (<https://engenere.one>).
# @author Antônio S. Pereira Neto <neto@engenere.one>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

2022-09-30 16:42 UTC, netosjb commented
opa! vou fazer a correção, obrigado @mbcosta

2022-10-01 21:49 UTC, netosjb commented
> Pessoal tem um detalhe que parece não ter sido visto é que nos novos arquivos incluídos está faltando o cabeçalho de licença e o autor, acredito que isso é um padrão e consta na maioria dos arquivos python, exceção os **init**.py, em alguns casos até mesmo nos arquivos XML, por isso @netosjb minha opinião é que isso deve ser corrigido nos seguintes arquivos:
> 
> https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_base/models/res_partner_pix.py#L1 https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_base/tests/test_partner_bank.py#L1 https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_base/tests/test_valid_pix.py#L1
> 
> Um exemplo com o formato pode ser visto aqui https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_account_nfe/models/document_workflow.py#L1
> 
> Copyright (C) 2022-Today - Engenere (https://engenere.one). @author Antônio S. Pereira Neto [neto@engenere.one](mailto:neto@engenere.one) License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

Feito #2148

2023-09-29 15:49 UTC, marcelsavegnago commented on l10n_br_base/models/res_partner.py
> +    def _compute_show_l10n_br(self):
@antoniospneto Estou com dúvida sobre este método já que a principio por default os parceiros não tem um company_id definido. Talvez possamos incrementar testando se o pais do parceiro é diferente de BR. Fora isso, acredita que seja válido considerar a empresa selecionada no momento ?

2023-09-29 16:08 UTC, antoniospneto commented on l10n_br_base/models/res_partner.py
> +    def _compute_show_l10n_br(self):
Realmente, a validação que fiz na época não é uma boa.
Acho que o código do país do parceiro vai ser melhor 👍🏻