[14.0][FIX] l10n_br_fiscal: UndefinedFunction: operator does not exist
OCA/l10n-brazil pull request #2159
Opened 2022-10-07 17:57 UTC by crsilveira

...fiscal_comment" WHERE "l10n_br_fiscal_comment".id IN ((2, 'T... Este erro acontece na linha do pedido de Compras, quando tenta selecionar um Comentário.

2022-10-07 18:22 UTC, netosjb approved these changes

2022-10-07 18:25 UTC, netosjb requested changes
ops, aprovei sem querer, logo vou revisar ;)

2022-10-07 18:31 UTC, crsilveira commented
Este erro acontece tbém , obviamente, na Linha da Fatura, aba Extra info, ao clicar para selecionar um Comentário.

2022-10-08 14:48 UTC, rvalyi submitted a review, later dismissed
parabens pela primeira contribuição no projeto @crsilveira !
Poderia fazer um squash dos 2 commits, mas vamos aceitar assim pela primeira.

2022-11-23 10:54 UTC, closed without merging

2022-11-23 10:54 UTC, crsilveira commented
Limpando código.

2022-12-26 18:13 UTC, marcelsavegnago commented
@crsilveira vc conseguiu acertar a questão dos commits em outra PR? nesta PR pelo jeito tem alguns commits que sao de uso seu a principio. Se for o caso, faça uma copia da 14.0 oficial e faça o cherry-pick dos commits que de fato gostaria de enviar por favor.

2022-12-26 18:38 UTC, crsilveira commented
@marcelsavegnago pode excluir o q tem meu, vou estudar o "git" e dai publicar corretamente.

2022-12-26 18:52 UTC, marcelsavegnago commented
@crsilveira eu organizei aqui e enviei em uma PR e mantive seu commit.  https://github.com/OCA/l10n-brazil/pull/2274

2022-12-26 18:53 UTC, marcelsavegnago commented
Este problema começou nos afetar tbm e precisava dar um jeito e aparentemente tua correção resolve.. muito obrigado pela contribuição.