[14.0][l10n_br_fiscal][DEL] extracted experimental DFe features
OCA/l10n-brazil pull request #2166
Opened 2022-10-13 13:27 UTC by rvalyi

raçocino semelhante a esse PR https://github.com/OCA/l10n-brazil/pull/2165 so que dessa vez com as funcionalidades de DFe.

O módulo l10n_br_fiscal esta muito acima do peso médio dos módulos da OCA. Como o Daniel Reis bem explicou nesses OCA Days, é muito melhor ter módulos menores com responsabilidades e dependências bem explicitas: é mais fácil de entender, mais fácil para migrar, mais fácil para substituir ou melhorar algo que não atende vc...

No caso dessas funcionalidades de DFe, são coisas super experimentais e aproximativas que tinham sido contribuído nessa PR https://github.com/OCA/l10n-brazil/pull/928 meio que forçando a barra sem que nem o @renatonlima nem eu que mantemos o módulo aprovasse. Na época do merge o codigo ainda tava bem zoado e sem o menor teste! Alem disso é um código que não esta usado por nenhum modulo ou PR verde no repo. E também pode muito bem ser um modulo extra então não tinha muito motivo de enfiar isso no l10n_br_fiscal. Se precisar de algum hook ou menu apenas a gente pode colocar.

Nesse caso eu não fiz um git mv, porque considero que esse codigo tava muito experimental. Me deu bastante dor de cabeça para migrar ele para a v14 e como vcs podem ver eu tive ate que desativar as views de dfe e mdfe pro pre-commit parar de reclamara. Nisso eu fiz apenas um remove dos códigos e vou adicionar de volta num novo modulo l10n_br_fiscal_dfe que vai ficar de rascunho ate alguem se dar o trabalho de limpar e deixar minimamente testado.

Teve umas branches de NFe que tiveram algum prototipo de DFe mas nunca ficaram verde no repo. Alem disso tinha tb uma branch tb bem aproximativa dentro do erpbrasil.edoc para suportar isso. Considero que com a troca do generateDS pelo xsdata esse tipo de webservice vai ficar muito mais simples e muito mais transparente para gente, então por isso sugiro de dar uma segurada antes de fazer o merge desse modulo extraido l10n_br_fiscal_dfe onde eu joguei o codigo que eu tirei daqui.

Antes:

```
cloc l10n_br_fiscal
     224 text files.
     224 unique files.                                          
       3 files ignored.

github.com/AlDanial/cloc v 1.90  T=0.32 s (695.2 files/s, 235836.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSV                             24              0              0          31069
XML                             82           1155            486          16338
Python                         109           2594            777          12233 
PO File                          1           1525           5276           3300
HTML                             1             86              4            456
reStructuredText                 6            123             45            187
-------------------------------------------------------------------------------
SUM:                           223           5483           6588          63583
-------------------------------------------------------------------------------
```

depois:
```
cloc l10n_br_fiscal
     218 text files.
     218 unique files.                                          
       3 files ignored.

github.com/AlDanial/cloc v 1.90  T=0.66 s (327.5 files/s, 113172.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSV                             24              0              0          31063
XML                             80           1131            470          16009 (-329)
Python                         105           2548            762          11995 (-238)
PO File                          1           1525           5276           3300
HTML                             1             86              4            456
reStructuredText                 6            123             45            187
-------------------------------------------------------------------------------
SUM:                           217           5413           6557          63010
-------------------------------------------------------------------------------

```

ganha umas 500 linhas de código no modulo l10n_br_fiscal. Combinando com o https://github.com/OCA/l10n-brazil/pull/2165 já tira 1000 linhas e nos aproxima de volta das 10 000 linhas que já seria muito pro módulo fiscal. (o mis_builder que é um outro dos modulos grandes tem umas 5300 linhas por examplo)

2022-10-13 14:09 UTC, marcelsavegnago approved these changes
LGTM

2022-10-13 17:32 UTC, netosjb approved these changes

2022-10-14 10:20 UTC, felipemotter approved these changes

2022-10-15 23:01 UTC, mileo requested changes
@hirokibastos pode confirmar se isto há esta funcional em nossos clientes e qual a precisão de acertar os PRs relacionados?

2023-06-26 23:14 UTC, antoniospneto commented
@mileo eu acho que daria de aprovar essa pr, o código ainda vai estar disponível aqui: https://github.com/OCA/l10n-brazil/pull/2167

2023-06-27 00:22 UTC, rvalyi commented
> @mileo eu acho que daria de aprovar essa pr, o código ainda vai estar disponível aqui: #2167

@antoniospneto vamos esperar, o @renatonlima ta dando uma refatorada nisso e deve subir um PR em breve. Eu tb vi que pro caso da dfe, realmente NFe, CTe e MDFe (e talvez NFSe nacional) usam a mesma classe de DFe. Ai essa pode até ficar no modulo fiscal. O que realmente ta zoado é o Manifesto de Destinatario que ficou com o nome mdfe dando para pensar que seria MDFe e que alem disso é algo 100% especifico da NFe.

2023-10-01 04:06 UTC, closed without merging

2023-10-01 04:06 UTC, rvalyi commented
modulo l10n_br_dfe foi extraido aqui https://github.com/OCA/l10n-brazil/pull/2597