[16.0][MIG] l10n_br_zip
OCA/l10n-brazil pull request #2178
Opened 2022-10-20 23:58 UTC by mileo

2022-10-23 21:11 UTC, mileo commented
/ocabot migration l10n_br_zip

2022-10-25 16:29 UTC, gabrielcardoso21 approved these changes

2022-10-25 19:04 UTC, rvalyi requested changes
eu pesquisei com o CEP do teste, porem o numero veio no street_name parece:
![2022-10-25_16-02](https://user-images.githubusercontent.com/16926/197859892-8e53e95c-c665-41fe-ba36-87055df82d31.png)

@renatonlima sera se não rolou essa treta antes? cc @netosjb @marcelsavegnago

2022-10-25 20:15 UTC, mileo commented
> 

Esse teste esta bem esquisito: 
```
curl https://viacep.com.br/ws/01310930/json/ 
{
  "cep": "01310-930",
  "logradouro": "Avenida Paulista",
  "complemento": "2100",
  "bairro": "Bela Vista",
  "localidade": "São Paulo",
  "uf": "SP",
  "ibge": "3550308",
  "gia": "1004",
  "ddd": "11",
  "siafi": "7107"
}
```

![image](https://user-images.githubusercontent.com/1975978/197872054-6e090edb-d20a-480d-8d92-599b21afee19.png)

Se consultarmos os outro CEP da Av Paulsita, temos:

![image](https://user-images.githubusercontent.com/1975978/197872252-f0acd3aa-934b-493b-8bce-53a5453f0a97.png)

```
curl https://viacep.com.br/ws/17560246/json/ 
{
  "cep": "17560-246",
  "logradouro": "Avenida Paulista",
  "complemento": "de 1600/1601 a 1698/1699",
  "bairro": "CECAP",
  "localidade": "Vera Cruz",
  "uf": "SP",
  "ibge": "3556602",
  "gia": "7134",
  "ddd": "14",
  "siafi": "7235"
}
```

**A principal coisa em questão é que nem temos um campo correto para usar essa informação.**, pois o complemento seria somente uma referência, que no fundo nem deveriamos usar.

2022-10-25 20:20 UTC, mileo commented
O mesmo CEP no Odoo:

![image](https://user-images.githubusercontent.com/1975978/197873286-d193d497-9b83-4e76-beb8-028781624d24.png)

Só se quando o número for fixo, que parece ser o caso do 01310-930 colocarmos ele no número direto. E quando retornar um range:   "cep": "17560-246", "logradouro": "Avenida Paulista",  "complemento": "de 1600/1601 a 1698/1699", não preenchemos nada.

2022-10-25 20:24 UTC, netosjb commented
> ** questão é que nem temos um campo correto para usar essa informação.**, pois o complemento seria somente uma referência, que no fundo nem deveriamos usar.

Sim, foi discutido aqui: https://github.com/OCA/l10n-brazil/pull/1774#discussion_r785459246

O problema é que não tem um padrão no retorno das API, cada um trás os dados de uma forma diferente.

2022-10-25 20:26 UTC, marcelsavegnago commented
> > ** questão é que nem temos um campo correto para usar essa informação.**, pois o complemento seria somente uma referência, que no fundo nem deveriamos usar.
> 
> Sim, foi discutido aqui: [#1774 (comment)](https://github.com/OCA/l10n-brazil/pull/1774#discussion_r785459246)
> 
> O problema é que não tem um padrão no retorno das API, cada um trás os dados de uma forma diferente.

https://github.com/OCA/l10n-brazil/issues/1783

2022-10-25 22:10 UTC, rvalyi approved these changes

2022-10-25 22:11 UTC, rvalyi commented
bom então ja que é um problema conhecido que ja temos, nao vale blocar a migração por isso. Depois a gente melhora para as varias branches. Mesmo com essa limitação pode ser usado na maioria dos casos.

2022-10-25 22:11 UTC, rvalyi commented
/ocabot merge nobump

2022-10-25 22:17 UTC, merged