[12.0] spec_driven_model _export_fields dynamic dispatch
OCA/l10n-brazil pull request #2234
Opened 2022-11-29 14:55 UTC by renatonlima

Proposta para alteração no módulo spec_driven_model para implementar um dynamic dispatch para métodos _export_fields_*

Hoje no módulo l10n_br_nfe é utilizado vários métodos _export_* para controlar o fluxo dos campos que serão exportados ou injetados valores para serem exportados. Fazendo o refatoramento do código l10n_br_nfe/models/document_line.py no PR #2000 com a finalidade de simplificar o código que hoje tem uma serie de [if e elif](https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_nfe/models/document_line.py#L514) e também utilizam alguns métodos _export_field, _export_many2one e _export_float_monetary. Eu implementei um dispatch dinamico dentro do método _export_fields que vai verificar se existe algum método **_export_fields_NOME_DA_CLASSE** permitindo atualizar as variaveis xsd_fields e  export_dict para controlar o fluxo de campos que será exportados ou injetar valores que devem ser exportados.

Por exemplo, hoje no método https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_nfe/models/document_line.py#L544:

É possível ver a quantidade excessiva de if, elif e else para controlar o fluxo de exportação dos campos e valores o que gera um grande problema para alterar o fluxo de novos campos ou manter implementação já que por para definir os valores das tags tipi, ipitrib e ipint estão fragmentada pelo código e dentro de vários if de outras tags de outros impostos.

Também eu não acho interessante sobreescrever os métodos específicos  _export_float_monetary e _export_many2one já que eles serão invocados em qualquer classe que herde o spec.export, hoje temos só o modulo l10n_br_nfe, mas futuramente podemos ter outros módulos para outros documentos fiscais como l10n_br_cte e etc...

![image](https://user-images.githubusercontent.com/211005/204558662-4ace17a5-b175-4770-9a7b-f75e5b1e628d.png)

Já com o código proposto é possível controlar o fluxo criando métodos que serão invocados quando o _export_fields for chamado para uma classe especifica o que simplifica a exportação dos campos:

![image](https://user-images.githubusercontent.com/211005/204557615-cb25d8c5-6be9-4948-8e8c-5aa97a752bf2.png)

2022-11-29 14:58 UTC, renatonlima commented
Eu também tenho planos para fazer uma implementação semelhante dentro do método _build_attr melhorar a lógica do fluxo de importação dos documentos fiscais via XML mas isso vai ficar para outro PR

2022-11-29 16:55 UTC, antoniospneto commented
@renatonlima 

Apenas pensando um pouco aqui.. não me aprofundei muito.. 

Mas será que não seria melhor usar um **decorator** para chamar os esses métodos  **_export_fields__*** ? Por exemplo, criar um decorator **@export_field(tag_name)** para anotar em todos os métodos, e depois dentro do método **_export_fields** você resgata todos os métodos a serem executados pelo nome do decorator.

Eu vejo que seria uma vantagem pois o decorator deixa explicito qual é o proposito do método. Essas chamadas do dynamic dispatch eu acho que fica ruim para depois quem está olhando/estudando o código descobrir onde o método está sendo chamado/referenciado, pois se fizer uma pesquisa pelo nome do método não vai encontrar nada, a associação ao método fica implícita.

Me desculpe se eu estiver falando alguma besteira..

2022-12-06 18:21 UTC, mileo requested changes

2022-12-06 18:21 UTC, mileo commented on spec_driven_model/models/spec_export.py
> +        if hasattr(self, export_method_name):
@renatonlima fazer um Try/catch usando o getattr direto é mais rápido do que usar o hasattr e depois o getattr

2022-12-06 18:26 UTC, mileo commented on spec_driven_model/models/spec_export.py
> +        if hasattr(self, export_method_name):
Li isso faz alguns anos em um livro do Luciano Ramalho, estou procurando a referência. Mas segue uma análise alternativa https://stackoverflow.com/a/903238

2022-12-06 18:31 UTC, rvalyi commented on spec_driven_model/models/spec_export.py
> +        if hasattr(self, export_method_name):
Provavelmente isso depende de qual é a proporção de exceções. Quando seria a maioria como aqui eu imagino que não seria mais rápido... 

Mas tb a questão é que não estamos escrevendo algum ray tracer aqui. E mesmo se ganhar 1 ou 2 ms (eu dúvido muito) se vc clica num botão que leva 150 ms dependendo da latência da rede não é algo muito pertinente...

A claridade do código importa mais aqui do que "premature optimization". Tem inúmeros lugares onde tem formas menos cripticas de escrever código no projeto que levam a ganhos bem maiores...

2022-12-06 18:51 UTC, rvalyi commented on spec_driven_model/models/spec_export.py
> +        if hasattr(self, export_method_name):
Sendo sincero @mileo porque infelizmente é longe de ser a primeira vez: qdo vejo vc comentar esse tipo de coisa eu fico arrependido de ter aceitado vc no PSC do projeto, e olha que se passaram vários anos desde esse voto de confiança. Como é que um engenheiro como vc pode querer fazer esse tipo de observação como se isso fosse o código de algum videogame dos anos 80 que a gente tivesse que otimizar a qualquer custo enquanto que no mesmo tempo a sua lib para imprimir o Danfe de cada NFe chama um processo novo com Libreoffice, aquilo que gasta sim sem a menor dúvida várias dezenas de ms para iniciar um processo desse para cada NFe...

2022-12-06 19:25 UTC, rvalyi commented on spec_driven_model/models/spec_export.py
> +        if hasattr(self, export_method_name):
assim, dando um pouco de contexto sobre essas dicas geniais de otimização para não dizer que é implicância minha:

- https://github.com/OCA/queue/pull/269
- https://github.com/OCA/bank-payment/pull/781#issuecomment-796541582
- sendo que sobre coisas de tentar ganhar meio millisecond na serialização de NFe ja chegamos a falar sobre no privado uns 3 anos atras
- sendo que no mesmo link stackoverflow mega velho de 2009 o pessoal ja comenta que é porco usar exceções no fluxo normal da execução https://stackoverflow.com/a/903138 (porque poderia voltar de um AttributeError de qualquer outro lugar por examplo)

Agora o lance dos decoradores isso vale a pena sera olhado, porque talvez o codigo fica mais claro, o que é algo mil vezes mais importante pro projeto se desenvolver do que ir cassando meio ms de qualquer jeito.
Quer ganhar dezenas de ms com as NFe's? Tem muito o que fazer no erpbrasil.edoc.pdf...

2022-12-06 23:34 UTC, antoniospneto approved these changes
Comentei sobre o decorator, mas apenas uma sugestão que pode ser discutida posteriormente, de qualquer forma eu acho essa PR uma boa melhoria.

2022-12-06 23:39 UTC, felipemotter approved these changes

2022-12-07 18:20 UTC, marcelsavegnago approved these changes
LGTM

2022-12-12 15:34 UTC, rvalyi approved these changes

2022-12-12 15:35 UTC, renatonlima commented
@antoniospneto É interessante utilizar decorator, mas neste momento para destravar o PR #2000, seria interessante fazer esse merge já com essa melhoria e depois fazer a implementação do recorator.

2022-12-12 16:51 UTC, rvalyi commented
/ocabot merge minor

2022-12-12 17:18 UTC, merged