[14.0][FIX] l10n_br_account_nfe: o meio de pagamento (tPag) deve ser obrigatório em um faturamento normal
OCA/l10n-brazil pull request #2245
Opened 2022-12-09 02:15 UTC by antoniospneto

Atualmente na localização se por descuido alguém que está emitindo uma nota fiscal esquecer de informar o Modo de Pagamento vai receber esse erro na validação da mesma:

> Schema XML: 225 - Rejeicao: Falha no Schema XML da NFe The element 'detPag' in namespace 'http://www.portalfiscal.inf.br/nfe' has invalid child element 'vPag' in namespace 'http://www.portalfiscal.inf.br/nfe'. List of possible elements expected: 'tPag' in namespace 'http://www.portalfiscal.inf.br/nfe'.

Isso acontece porque o tPag (meio de pagamento) é um campo obrigatório e deve ser sempre ser informado, com exceção dos casos onde a finalidade da nota seja Ajuste ou Devolução.
![image](https://user-images.githubusercontent.com/634278/206607165-81ae34b8-9335-4749-be45-94c3e64337d9.png)

Esta PR altera o código para que exiba um aviso de erro caso não seja informado o modo de pagamento nos casos normais.

2022-12-09 03:13 UTC, felipemotter approved these changes

2022-12-09 05:02 UTC, rvalyi submitted a review, later dismissed

2022-12-09 05:06 UTC, rvalyi requested changes
ta quase bom, mas aparentemente quanto a nota é de entrada esse codigo e teste tb é executado e isso faz um raise da nova exceção quando valida a compra. Ver esse teste por examplo https://github.com/OCA/l10n-brazil/actions/runs/3653837831/jobs/6173705174#step:8:1247

Teria apenas que ajustar para não entrar nesse codigo nas notas de entradas...

2022-12-09 13:21 UTC, antoniospneto commented
> ta quase bom, mas aparentemente quanto a nota é de entrada esse codigo e esse teste tb é executado e isso faz um raise da nova exceção quando valida a compra. Ver esse teste por examplo https://github.com/OCA/l10n-brazil/actions/runs/3653837831/jobs/6173705174#step:8:1247
> 
> Teria apenas que ajustar para não entrar nesse codigo nas notas de entradas...

haha ainda bem temos os testes :D vou adicionar a verificação para não considerar esse caso

2022-12-09 14:12 UTC, rvalyi commented
para ser sinceiro essas coisas de document_workflow.py a gente usa da forma como esta mas a gente não curte muito o design não. Se tiver ideias para melhorar essa parte estão bem vindas...

2022-12-12 13:19 UTC, antoniospneto commented
substituído por https://github.com/OCA/l10n-brazil/pull/2245, porém a pr ainda está em rascunho, em breve vou explicar com mais detalhes a proposta.

2022-12-12 13:19 UTC, closed without merging

2022-12-12 13:33 UTC, rvalyi commented
> substituído por #2245, porém a pr ainda está em rascunho, em breve vou explicar com mais detalhes a proposta.

vc quis escrever substituido por https://github.com/OCA/l10n-brazil/pull/2246