[14.0][REF] l10n_br_account_nfe: create tags in compute methods
OCA/l10n-brazil pull request #2246
Opened 2022-12-10 13:24 UTC by antoniospneto

### Refatoração do módulo l10n_br_account_nfe

- Foi alterado para que as tags da NF-e sejam criadas a partir dos métodos **compute**.
- Desta forma um usuário fiscal pode conferir se as informações estão corretas em "tempo real" nas abas fiscais, não precisa aguardar validar ou enviar a NF-e.
- Mantem o padrão como já é feito na localização em outras partes.

2022-12-11 16:22 UTC, rvalyi commented
Eu acho legal, só teria que arrumar os testes 
, parece que teria apenas que fazer uns testes qdo alguns registros não são do Brasil...

2022-12-13 01:37 UTC, antoniospneto commented on l10n_br_nfe_spec/models/spec_models.py
> +        default=lambda self: self.env.ref("base.BRL"),
@rvalyi já que o compute aqui não está funcionando eu coloquei um default, dessa forma tá funcionando legal
o único problema é que teria que fazer um update nesse valor nos registros antigos do banco de dados que vão estar vazios..

2022-12-14 13:00 UTC, marcelsavegnago commented on l10n_br_nfe_spec/models/spec_models.py
> +        default=lambda self: self.env.ref("base.BRL"),
Será que teria que ter algum script de migração ?

2022-12-14 13:14 UTC, antoniospneto commented on l10n_br_nfe_spec/models/spec_models.py
> +        default=lambda self: self.env.ref("base.BRL"),
acho que dá pra fazer, ai corrige o bug para os registro antigos tbm, atualmente na localização todos brl_currency_id vão estar nulos, pq o compute que tinha antes nunca era chamado.

vou separar essa parte em uma outra PR

2022-12-22 02:50 UTC, rvalyi commented on l10n_br_nfe_spec/models/spec_models.py
> +        default=lambda self: self.env.ref("base.BRL"),
foda que essa parte não ta ideal ainda, dai nem sei se vale a pena mudar: pois a ideia desse brl_currency_id é apenas de deixar os campos Monetary dos mixins feliz, o objetivo não é salvar nada no banco não. Ai dessa forma ele ainda vai criar a coluna (jà que tirou o compute). Na v12 funcionava e era assim: https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_nfe_spec/models/spec_models.py e eu tive que fazer essa gambiarra para funcionar na v14, sendo que seria ideal limpar sim...

Sem essa mudança o PR não passa?

2022-12-22 02:57 UTC, rvalyi requested changes
de uma forma geral eu acho muito top o que vc fez aqui. Tem esse detalhe que eu comentei/perguntei https://github.com/OCA/l10n-brazil/pull/2246#discussion_r1055038302
E tb eu acho legal botar o copyright de vc/vcs no header do document.py. Foi realmente super re-escrito com código muito melhor; eu não faço questão de manter os nossos.

Tb no manifest, que tal botar o modulo de Alpha para Beta e botar vc, o @felipemotter e o @mbcosta como mantenedores do módulo?

2022-12-22 03:21 UTC, antoniospneto commented on l10n_br_nfe_spec/models/spec_models.py
> +        default=lambda self: self.env.ref("base.BRL"),
@rvalyi  passa sim, é mais questão de UX mesmo, sem isso os simbolos da moeada aqui não aparecem:
![image](https://user-images.githubusercontent.com/634278/209048306-f4d6460e-e0a5-46df-8d24-fc10cb749ad6.png)
Eu tbm não entendi porque o compute não funciona ali, ele nunca é chamado, fazendo com que o valor do currency fica sempre em branco, ai o único jeito que consegui foi setando o default .

2022-12-22 03:24 UTC, antoniospneto commented
> de uma forma geral eu acho muito top o que vc fez aqui. Tem esse detalhe que eu comentei/perguntei [#2246 (comment)](https://github.com/OCA/l10n-brazil/pull/2246#discussion_r1055038302) E tb eu acho legal botar o copyright de vc/vcs no header do document.py. Foi realmente super re-escrito com código muito melhor; eu não faço questão de manter os nossos.
> 
> Tb no manifest, que tal botar o modulo de Alpha para Beta e botar vc, o @felipemotter e o @mbcosta como mantenedores do módulo?

Show, vou por a gente como mantedores junto ao @mbcosta, já vou aproveitar e arrumar ali os últimos commits que eu misturei um pouco os módulos no mesmo commit hehe

2022-12-22 03:57 UTC, rvalyi commented on l10n_br_nfe_spec/models/spec_models.py
> +        default=lambda self: self.env.ref("base.BRL"),
entendi. Beleza, vamos integrar essa mudança com o default então pois já melhora um pouco a situação então. Se ainda tiver por aqui de repente deixa algum comentário explicito tipo FIXME para a gente não esquecer de tentar limpar isso mais tarde...

2022-12-22 04:06 UTC, rvalyi commented on l10n_br_nfe_spec/models/spec_models.py
> +        default=lambda self: self.env.ref("base.BRL"),
@antoniospneto alias, uma melhoria que eu tenho na cabeça hoje o xsdata-odoo enfia la esse brl_currency_id mas é um hardcode, fica ruim: não é international. Eu queria botar algo como spec_currency_id e que bota o currency_id da empresa , talvez um pouco como esse company_currency_id do account.move https://github.com/odoo/odoo/blob/14.0/addons/account/models/account_move.py#L177 e usando o self.env.company so que sem ter store=True/related. Alguma opinião? Sei la uma ideia para depois, mas vamos com um passo de cada vez...

2022-12-26 13:43 UTC, antoniospneto commented
@rvalyi 

- Limpei o histórico de commits
- Adicionei os mantedores do módulo
- Coloquei os créditos e licença no arquivo document.py
- Adicionei o FIXME no campo currency.

2022-12-26 19:58 UTC, rvalyi approved these changes
testei um pouco e me parece tudo OK agora. Novamente parabens pelo excelente trabalho!

2022-12-26 20:05 UTC, rvalyi commented
@antoniospneto @felipemotter tem apenas um detalhe: seria bom ter algum account.payment.mode de demo para a empresa lucro presumido ja com o fiscal_payment_mode (Meio de Pagamento da NF) preenchido assim como temos com o Boleto no caso da empresa de demo do simples, facilitaria pros demos/testes. Mas tb não pretendo blocar por causa disso agora.

2022-12-27 18:23 UTC, marcelsavegnago approved these changes

2022-12-27 18:26 UTC, marcelsavegnago commented
Parabéns pessoal.. ficou muito bom. ❤️

2022-12-27 18:40 UTC, rvalyi commented
/ocabot merge major

2022-12-27 19:04 UTC, merged