[14.0][NEW] l10n_br_pos_cfe
OCA/l10n-brazil pull request #2301
Opened 2023-01-17 12:16 UTC by ygcarvalh

Baseado no módulo da localização para o Ponto de Venda, adiciona as funcionalidades necessárias para a emissão do CFe ao realizar o fluxo pelo frontend.

Esse PR foi criado a partir do PR https://github.com/OCA/l10n-brazil/pull/2096.

cc: @mileo @rvalyi @marcelsavegnago @lfdivino @luismalta

2023-02-08 13:04 UTC, mileo commented
@ygcarvalh @luismalta @lfdivino podem fazer o rebase?

2023-02-15 14:28 UTC, rvalyi requested changes

2023-02-15 14:28 UTC, rvalyi commented on l10n_br_pos_cfe/__manifest__.py
> +    "maintainers": ["mileo", "sadamo", "gabrielcardoso21", "lfdivino"],
mesma observação que eu tinha feito no l10n_br_pos: sadamo e gabrielcardoso21 são apenas autores do modulo ou pretendem manter de forma ativa? Pois estão mais de 2 anos sem fazer nada na OCA...

2023-02-15 14:28 UTC, rvalyi commented on l10n_br_pos_cfe/readme/INSTALL.rst
> +Alem disso você vi precisar de um IOT BOX, podendo ser o da Odoo SA ou o Pywebdriver, com os respectivos drivers para CF-E:
substituir:
s/vi/vai/

2023-02-15 14:28 UTC, rvalyi commented on l10n_br_pos_cfe/static/src/xml/Screens/ReceiptScreen/OrderSubtitleReceipt.xml
> +                    > >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> </span>
esses caracteres >>>> estão aqui de proposito? (para que então?)

2023-02-15 16:49 UTC, mileo commented on l10n_br_pos_cfe/static/src/xml/Screens/ReceiptScreen/OrderSubtitleReceipt.xml
> +                    > >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> </span>
Estão sim, fazem parte do cupom emitido em homologação.

2023-02-15 16:51 UTC, mileo commented on l10n_br_pos_cfe/README.rst
> +Integração com equipamento CF-E para emissão de Cupom Fiscal.
@ygcarvalh pode adicionar na descrição que o módulo funciona para os equipamentos SAT (SP) e MF-E (Ceará)

2023-02-16 11:32 UTC, ygcarvalh commented on l10n_br_pos_cfe/static/src/xml/Screens/ReceiptScreen/OrderSubtitleReceipt.xml
> +                    > >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> </span>
Isso mesmo. É uma das necessidades que a documentação pede nesses casos.

2023-02-17 09:46 UTC, mileo approved these changes

2023-02-17 09:48 UTC, mileo commented on l10n_br_pos_cfe/models/pos_payment_method.py
> +    sat_card_accrediting = fields.Selection(CARD_ACQUIRERS, "Card Acquirer")
@ygcarvalh aqui não seria melhor outro nome de variável? 

sat_card_acquirer ?

2023-02-17 11:49 UTC, antoniospneto approved these changes
lgtm

2023-02-17 15:34 UTC, felipemotter approved these changes

2023-02-17 17:04 UTC, rvalyi commented on l10n_br_pos_cfe/models/pos_payment_method.py
> +    sat_card_accrediting = fields.Selection(CARD_ACQUIRERS, "Card Acquirer")
eu TB acho

2023-02-27 22:00 UTC, rvalyi commented
/ocabot merge nobump

2023-02-28 11:47 UTC, ygcarvalh commented
@rvalyi dei um rebase depois daquela correção do Marcel na `l10n_br_account` só por via das dúvidas 😄

2023-02-28 14:46 UTC, rvalyi commented
@ygcarvalh a principio o proprio ocabot merge ja faz o rebase (mas é bom mostrar os testes passando mesmo, no caso agora  foi um problema inconsistente com o servidor de IBPT. Não sei porque o ocabot não fez o merge ontem; vamos ver agora).

/ocabot merge nobump

2023-02-28 15:11 UTC, merged