[14.0][IMP] l10n_br_account_nfe: Not export dup, fat in NFCe xml
OCA/l10n-brazil pull request #2352
Opened 2023-02-23 18:27 UTC by ygcarvalh

O Sefaz não permite que a NFC-e contenha as tags de duplicata e fatura no XML. Com essa pequena condição, essas tags não são exportadas e é possível realizar o processo de autorização da NFC-e.

2023-02-23 18:29 UTC, antoniospneto commented
@ygcarvalh 

essa condição na verdade você pode por dentro do método _need_compute_nfe40_dup

2023-02-23 18:31 UTC, antoniospneto requested changes

2023-02-23 18:31 UTC, antoniospneto commented on l10n_br_account_nfe/models/document.py
> +            if not record.document_type == "65":
na verdade essa nova condição o correto é por dentro do método _need_compute_nfe40_dup que é responsável por fazer a filtragem antes.

2023-02-24 12:00 UTC, antoniospneto approved these changes

2023-02-24 12:20 UTC, felipemotter approved these changes

2023-02-24 14:35 UTC, marcelsavegnago approved these changes

2023-02-24 15:33 UTC, rvalyi approved these changes

2023-02-24 19:44 UTC, renatonlima approved these changes

2023-02-24 19:45 UTC, renatonlima commented
/ocabot merge minor

2023-02-27 17:37 UTC, rvalyi commented
/ocabot merge patch

2023-02-27 17:51 UTC, merged