[14.0][ADD] l10n_br_account_payment_instrument: novo módulo
OCA/l10n-brazil pull request #2389
Opened 2023-03-18 21:12 UTC by antoniospneto

(Em desenvolvimento)

Adiciona um novo modelo para armazenar as informações de um instrumento de pagamento iniciado por alguma instituição financeira brasileira, pode ser um "Boleto" ou um "Pix QR Code"

Essas informações fica associada a um ou mais contas a receber/apagar (account_move_line)

São utilizados para carregar as informações para dentro da ordem de pagamento (arquivo de remessa)

Prints:

![image](https://user-images.githubusercontent.com/634278/226139928-67c5dabf-2e43-4b9e-bc13-9e7995322e19.png)

![image](https://user-images.githubusercontent.com/634278/226140134-f120e04a-dd30-447f-a5d9-76860ecf127e.png)

![image](https://user-images.githubusercontent.com/634278/226140236-afe53c47-c68e-4594-a433-b697e7005a87.png)

![image](https://user-images.githubusercontent.com/634278/226140366-fbb1bf24-54b2-4dcc-ab6d-4dad8441039b.png)

2023-03-20 12:36 UTC, douglascstd commented on l10n_br_account_payment_instrument/models/l10n_br_payment_instrument.py
> +                    _("The barcode/digitable line on the Boleto is invalid.")
Problema na validação.
Código de barras digitado manualemente com os pontos e espaços
![image](https://user-images.githubusercontent.com/20867090/226340164-33bd8b54-c30d-4c14-94b0-2eb52eb033b3.png)

O Wizard consegue interpretar o código e apresenta as informações lidas no código de barras:
![image](https://user-images.githubusercontent.com/20867090/226340293-30d6546d-fccc-4ac1-8717-4a161de49e20.png)

No entanto, ao tentar salvar o código de barras:
![image](https://user-images.githubusercontent.com/20867090/226340351-605d3a39-2fa2-48bf-8c7e-fb752e1b342e.png)

O contorno para isso é retirar os pontos e espaços para que o barcode tenha o comprimento da validação (44 ou 47)

2023-03-20 12:42 UTC, antoniospneto commented on l10n_br_account_payment_instrument/models/l10n_br_payment_instrument.py
> +                    _("The barcode/digitable line on the Boleto is invalid.")
boa @douglascstd, de fato me equivoquei nessa parte, realmente é preciso remover todos caracteres não numéricos ao fazer a validação.

2023-03-20 15:35 UTC, rvalyi commented
@antoniospneto @felipemotter @marcelsavegnago que tal tentar fazer o review e merge desse refactor antes de adicionar esse novo modulo https://github.com/OCA/l10n-brazil/pull/2386 ? (me parece que a gente pode ter o trabalho de limpeza e migração duas vezes talvez se a gente não fizer nessa ordem). Sera se o modulo seria muito independente desse refator?
cc @mbcosta @renatonlima

2023-03-20 16:18 UTC, antoniospneto commented
@rvalyi concordo com você , é melhor esperar o #2386 sim, por enquanto deixamos a pr em rascunho. Valeu!

2023-03-21 15:07 UTC, douglascstd commented
Pontos que melhoram a usabilidade do aplicativo - NÃO IMPACTAM O USO.
1- Botão de Confirmar
![image](https://user-images.githubusercontent.com/20867090/226647575-73c9295d-84af-42fa-a7d7-1b9cdb1b7c48.png)
Os botões inferiores, quando preenche o QRcode, ele apresenta os botões Edit e Create, mas a ação esperada do usuário é Fechar a janela. Sugestão é incluir um botão com "Confirm" e esse botão ser destacado como próxima ação.


2- Ação de Salvar
As linhas de "Payables" são geradas somente após salvar a fatura. E exigindo a navegação do mouse para o botão salvar e depois acessar a guia "Payables". Sugestão é ativar essa geração ou até salvar o registro, na guia "Payables"
![image](https://user-images.githubusercontent.com/20867090/226649474-f70fe4e0-2565-4479-9f33-ed7386897b1b.png)

2023-04-06 17:01 UTC, marcelsavegnago commented
Pessoal.. como comentado pelo Raphael entendo que seria melhor revisar esta PR https://github.com/OCA/l10n-brazil/pull/2386 antes e já entrar com este módulo ajustado. 

cc @antoniospneto @felipemotter @douglascstd

2023-04-08 12:19 UTC, felipemotter commented
@marcelsavegnago eu to com a agenda ferrada, esse mês eu to totalmente sem tempo, já tirei o tempo que eu não tinha proi account. Nas proximas semanas nosso foco virá para ca.

2023-05-29 15:22 UTC, rvalyi commented
@antoniospneto vc poderia fazer um rebase por favor? Pois foi feito o merge do refator do bank lines do account_payment_order...

cc @felipemotter @marcelsavegnago @renatonlima @douglascstd @mbcosta

2023-07-19 00:03 UTC, douglascstd requested changes
[FUNCTIONAL TEST] Need Improves

Realizado teste de entrada com Código de Barras:
1. Ao digitar o código de barras, e pressionar "Enter" não é atualizado a tela e não mostra os detalhes

2. Para que as linhas Payables apareçam é necessário salvar a Fatura, seria interessante a criação destas linhas antes de salvar, ou que o salvar, esteja no formulário para que o fluxo de digitação seja contínuo.

3. O código lido pelo barcode, ele tem o dígito 0 no início:
Leitor: 034198941501500001790001043510049102015000
![image](https://github.com/OCA/l10n-brazil/assets/20867090/02b237d5-0161-471e-9dc5-d05d056be661)
----

Teste de código de barras- OK - Usando a Composição e a Representação numérica:
![image](https://github.com/OCA/l10n-brazil/assets/20867090/48b7f3cf-c4bc-4564-b968-2697253ced0a)
![image](https://github.com/OCA/l10n-brazil/assets/20867090/5946f6f6-abd7-4178-b5eb-083829334779)


Configuração do Código de Barras no boleto:
![Pasted image 20221215203740](https://github.com/OCA/l10n-brazil/assets/20867090/aa3fa7fa-ab3a-405c-84a8-ddb0f0d8ca27)

---
Teste realizado com PIX Pagamento QR Code - OK
![image](https://github.com/OCA/l10n-brazil/assets/20867090/5d2d15ca-5147-4fca-b9d9-90505d66117d)
Teste realizado somente até a leitura do Código QR. Não foi realizado o processo até a finalização do pagamento.
![image](https://github.com/OCA/l10n-brazil/assets/20867090/417a9330-cb30-42f1-97d9-b07c0ad7a9f7)

2023-08-22 18:23 UTC, antoniospneto commented
@douglascstd 

> 1) Ao digitar o código de barras, e pressionar "Enter" não é atualizado a tela e não mostra os detalhes

Esse é o comportamento padrão do Odoo, não é o "Enter" que faz atualizar, você tem que mudar o cursor para fora do campo, você pode fazer usando o "tab" ↹ ou clicando com mouse fora do campo.

> 2) Para que as linhas Payables apareçam é necessário salvar a Fatura, seria interessante a criação destas linhas antes de salvar, ou que o salvar, esteja no formulário para que o fluxo de digitação seja contínuo.

Ok, vou tentar uma abordagem um pouco diferente, em breve atualizo aqui.

> 3) O código lido pelo barcode, ele tem o dígito 0 no início:
> Leitor: 034198941501500001790001043510049102015000

Tem certeza que é sua leitura está fazendo a leitura corretamente ?
Pois o problema aqui não parece ser só zero a esquerda, está faltando digitos nesse barcode.
Sabe me informar qual é a linha digitável relativa a esse barcode ?

2023-09-04 10:51 UTC, marcelsavegnago commented
ping @douglascstd

2023-09-28 17:49 UTC, douglascstd commented
> @douglascstd
> 
> > 1. Ao digitar o código de barras, e pressionar "Enter" não é atualizado a tela e não mostra os detalhes
> 
> Esse é o comportamento padrão do Odoo, não é o "Enter" que faz atualizar, você tem que mudar o cursor para fora do campo, você pode fazer usando o "tab" ↹ ou clicando com mouse fora do campo.
OK entendido
 
> > 2. Para que as linhas Payables apareçam é necessário salvar a Fatura, seria interessante a criação destas linhas antes de salvar, ou que o salvar, esteja no formulário para que o fluxo de digitação seja contínuo.
> 
> Ok, vou tentar uma abordagem um pouco diferente, em breve atualizo aqui.
> 
**Perfeito**

> > 3. O código lido pelo barcode, ele tem o dígito 0 no início:
> >    Leitor: 034198941501500001790001043510049102015000
> 
> Tem certeza que sua leitora está lendo corretamente ? Pois o problema aqui não parece ser só zero a esquerda, está faltando digitos nesse barcode. Sabe me informar qual é a linha digitável relativa a esse barcode ?
Não encontrei mais esse código original. Mas tenho outro que deve servir para o teste:
34194920800004244981482262670912040018950000
![image](https://github.com/OCA/l10n-brazil/assets/20867090/dbfd4d05-f12a-4987-9e59-313218179127)

2023-09-28 18:47 UTC, antoniospneto commented
Oi @douglascstd mas veja bem, antes o código de barras que você passou tinha só 42 caracteres, mas o correto é ter 44 caracteres.

Esse que você passou por ultimo está correto, tem 44 caracteres. o sistema reconheceu sem erros:
![image](https://github.com/OCA/l10n-brazil/assets/634278/6ef890a8-ce8b-415c-8ff2-b6eb1a0dd1d2)

ainda não consegui reproduzir a falha que você mencionou.

2023-09-29 12:52 UTC, douglascstd commented
> ainda não consegui reproduzir a falha que você mencionou.

O erro que mencionei só acontece ao fazer a leitura pelo leitor de código de barras.. o leitor insere esse Zero do lado esquerdo.  E sugiro utilizar somente os 44 digitos a direita que são inseridos no campo.

Pois o processo de leitura é:
- posicionar o cursos (com o mouse) no campo barcode
- executar a leitura do código de barras pelo leitor laser manual
- confirmar

Desta forma, quando o leitor insere esse zero a mais a esquerda, as validações do Odoo não correm corretamente.

2023-09-29 13:22 UTC, antoniospneto commented
> > ainda não consegui reproduzir a falha que você mencionou.
> 
> O erro que mencionei só acontece ao fazer a leitura pelo leitor de código de barras.. o leitor insere esse Zero do lado esquerdo. E sugiro utilizar somente os 44 digitos a direita que são inseridos no campo.
> 
> Pois o processo de leitura é:
> 
> * posicionar o cursos (com o mouse) no campo barcode
> * executar a leitura do código de barras pelo leitor laser manual
> * confirmar
> 
> Desta forma, quando o leitor insere esse zero a mais a esquerda, as validações do Odoo não correm corretamente.

@douglascstd será que esse problema não dá de resolver revisando as configurações do leitor de código de barras ?
Pois esse comportamento não é o normal, se você entrar no internet banking e por o código 
034194920800004244981482262670912040018950000 (com o zero na frente, total de 45 digitos) vai dar erro também, o internet banking só vai processar se remover esse zero extra.

Acho que primeiro podemos tentar solucionar a configuração do leitor, se isso realmente não for possível podemos adicionar uma lógica para tratar esse caso aqui

2024-02-26 12:08 UTC, marcelsavegnago commented
@douglascstd @antoniospneto como ficamos em relação a este assunto ?

2024-07-16 13:07 UTC, marcelsavegnago commented
@douglascstd @antoniospneto como ficamos em relação a este assunto ?

2024-07-16 13:25 UTC, antoniospneto commented
@marcelsavegnago temos em aberto a dificuldade técnica que está acontecendo com o leitor do código de barras utilizados nos testes pelo @douglascstd, a minha impressão é que o leitor não está com a configuração correta. É preciso analisar melhor, fazer mais testes com esse leitor para entender

2024-12-29 12:11 UTC, closed without merging