[15.0] [MIG] l10n_br_hr: Migration to 15.0
OCA/l10n-brazil pull request #2437
Opened 2023-04-13 22:25 UTC by rodrigonevest

2023-04-13 22:28 UTC, marcelsavegnago commented
/ocabot migrate l10n_br_hr

2023-04-13 22:28 UTC, marcelsavegnago commented
/ocabot migration l10n_br_hr

2023-04-13 22:38 UTC, kaynnan approved these changes
LGTM

2023-04-13 23:04 UTC, rvalyi requested changes
@marcelsavegnago @mileo eu acho que seria a oportunidade de começar a dar uma limpa nesses modulos de hr. Na epoca da v8 que foram feitos talvez o scope da OCA era muito menor, mas hoje é meio que um tiro no pé esse modulo de HR ficar re-criando conceitos que ja tem modulos OCA e todo um eco-sistema crescendo por cima.

Então por examplo:

1. tirar hr.employee.dependent ou herdar de https://github.com/OCA/hr/tree/14.0/hr_employee_relative
2. ? usar esse modulo https://github.com/OCA/hr/tree/14.0/hr_employee_ssn ?
3. tirar hr.educational.attainment e usar o modulo do Odoo CE hr_skills ?

De uma forma geral, tem tb muitos campos cadastrais que são para fazer o eSocial. Mas agora com a technologica XML que temos, a gente consegue trazer esses campos pelos XSD do esocial... Então esta OK de ter alguns campos usuais num modulo hr basicão que não tem a pretensão de fazer ele mesmo a porra toda do esocial e não de ter as dependenciais disso. Porem vale a reflexão se nesse modulo ja não estaria tendo alguns campos que ja tem um uso bem avançado orientado esocial e que ai poderiam ser tirado do modulo e trazido apenas na hora de fazer o modulo do esocial.

Por fim eu consigo dar um feedback sobre isso dos mixins abstratos do esocial em questãoes de uns 10 dias. Eu acho que da para temporisar um pouco o merge ate esse feedback. Mas eu acho que ainda assim os outros pontos que eu levantei valem.

2023-04-13 23:10 UTC, marcelsavegnago commented
@rvalyi acho valido sim considerar o uso de outros módulos já maduros na OCA. Sobre o eSocial eu não consigo opinar muito agora.

2023-04-13 23:14 UTC, marcelsavegnago commented
@rvalyi seria melhor na 14 propor um refactor ou trabalhar direto no refactor durante a migracao para 15 ? A principio focariamos em focar na adaptação para usar os módulos da OCA para substituir alguma implantação feita no módulo.

2023-04-13 23:22 UTC, rvalyi commented
então, sobre usar hr_employee_relative ou hr_skills (teria outros?) a gente pode poderia nem botar a dependencia (para não fuder com a modularidade do Odoo por conta da localização; um principio direitor do projeto aqui). Ai sei la a gente poderia apenas sugerir no README de instalar esses modulos para ter esse tipo de funcionalidade. E se la na frente tiver modulos mais orientados e-Social, ai a gente iria sim depender desses modulos e fazer os mappings entre os campos dos XSD e do modulos OCA/Odoo que nem a gente faz no l10n_br_nfe para a NFe.

Mas ai na 14, pro usuario nao perder essas informaçoes, até existir tais modulos de eSocial a gente poderia não remover esses campos, apenas botar um comentario que esta deprecated ou algo assim. E ai qdo tiver modulo de esocial ter um script para migrar esses dados talvez. Mas enfim é considerando isso que a gente vé a importancia de acertar o modelo de dados quanto antes que senão la ne frente vai chover de usuarios/curiosos enchando o saco se deixar para acertar depois.

2024-03-24 14:14 UTC, rvalyi approved these changes
fazendo o merge na 15,0, porem com as ressalvas https://github.com/OCA/l10n-brazil/pull/2437#pullrequestreview-1384358831
que eu acho que devemos considerar se portar o modulo para a v16.

2024-03-24 14:15 UTC, rvalyi commented
/ocabot merge nobump

2024-03-25 13:24 UTC, marcelsavegnago commented
@rvalyi estou refazendo a branch e ja mando novamente

2024-03-25 17:47 UTC, marcelsavegnago commented
/ocabot merge nobump

2024-03-25 18:03 UTC, merged