[14.0][REF] l10n_br_account_payment_order: Campo sequencial "Nosso Número" só pode ser informado no Modo de Pagamento
OCA/l10n-brazil pull request #2452
Opened 2023-04-20 20:19 UTC by mbcosta

Own Number sequence field only can be inform in Payment Mode.

O campo sequencial "Nosso Número" só pode ser informado no Modo de Pagamento, antes desse PR poderia ser informado no cadastro da empresa ou usar o Número da Fatura, mas no caso do cadastro da empresa isso limitava há apenas um CNAB e o caso de usar o Número da Fatura até onde vi ou que foi relatado aqui não parece ser usado, caso exista será importante saber mais informações a respeito desse caso para não ser removido e ser mantido no modulo, isso estava no ROADMAP do modulo desde a versão 12 e resolve o problema do issue https://github.com/OCA/l10n-brazil/issues/2244 

cc @renatonlima @rvalyi @marcelsavegnago @mileo @felipemotter

2023-04-20 20:44 UTC, antoniospneto approved these changes
LGTM

2023-04-20 21:24 UTC, rvalyi approved these changes
LGTM

2023-04-21 13:56 UTC, rvalyi requested changes

2023-04-21 13:56 UTC, rvalyi commented on l10n_br_account_payment_order/models/__init__.py
>  #  Luis Felipe Miléo - mileo@kmee.com.br
@mbcosta vc poderia aproveitar o gancho e dar um amend para tirar a linha de copyright nesse `__init__.py`, è a convenção da OCA não botar linha de copyright quando um `__init__.py` tem apenas import statements.

2023-04-21 16:22 UTC, mbcosta commented on l10n_br_account_payment_order/models/__init__.py
>  #  Luis Felipe Miléo - mileo@kmee.com.br
Feito @rvalyi

2023-04-21 17:48 UTC, rvalyi approved these changes

2023-04-21 22:34 UTC, rvalyi commented
/ocabot merge minor

2023-04-21 22:45 UTC, rvalyi commented
/ocabot merge minor

2023-04-21 23:14 UTC, merged