[14.0][l10n_br_nfe_spec] xsdata nfe mixins
OCA/l10n-brazil pull request #2457
Opened 2023-04-23 07:15 UTC by rvalyi

esse PR é uma pedaço menor do https://github.com/OCA/l10n-brazil/pull/2371
Eu alterei a gereção do xsdata-odoo para incluir o atributo _generateds_type nos mixins Odoo de forma que apesar deles terem sido gerido pelo xsdata-odoo, eles são compativeis com import e export de XML com bindings "legacy" generateDS como temos no nfelib 1.x atual. Ou seja a ideia é de fatiar #2371 com esse primeiro pedaço menor.

Tambem foram incluidos os campos choices relevantes em classes do l10n_br_nfe ja que o xsdata ainda não lida com as tags choices de forma tão completa quanto o generateDS (mas ainda assim é melhor do que o generateDS em inumerosos aspectos).

2023-04-24 14:54 UTC, renatonlima requested changes

2023-04-24 14:54 UTC, renatonlima commented on l10n_br_nfe/models/document_line.py
> +        [
Seria bom para deixar mais legivel o código, colocar o nome do argumento, selection e string

2023-04-24 15:19 UTC, rvalyi commented on l10n_br_nfe_spec/models/v4_0/tipos_basico_v4_00.py
> +    ("2", "None"),
esses "None" não ficam legal, eu acabei de corrigir no xsdata-odoo: https://github.com/akretion/xsdata-odoo/commit/cf97b5c8c93c92dc4a8930b859ab8884979a1af7
eu vou atualizar essa PR...

2023-04-25 21:41 UTC, rvalyi commented on l10n_br_nfe/models/document_line.py
> +        [
corrigido!

2023-04-25 21:41 UTC, rvalyi commented on l10n_br_nfe_spec/models/v4_0/tipos_basico_v4_00.py
> +    ("2", "None"),
corrigido!

2023-05-04 06:07 UTC, rvalyi commented
pessoal, eu gerei de novo os arquivos característicos com o atributo _generateds_type para mostrar que não houve mudança entre

- a antiga geração generateds-odoo https://github.com/OCA/l10n-brazil/commit/e88aa7ac97113e41c7a9e1d8ca7969116c372c72
- e a nova com xsdata-odoo https://github.com/akretion/l10n-brazil/commit/afaadb1ab43ab0fc8ee04e2fecf2351c8f5bacc5

sendo que novamente a forma mais facil de comparar é abrir os 2 arquivos no meld ou ferramenta do tipo.

2023-05-05 21:21 UTC, rvalyi commented
pessoal, recentemente o @renatonlima me falou que ele pensava que essa parte de codigo para injectar um campo choice não era requerida (pois o mesmo campo esta sendo adicionado depois na linha):
![2023-05-05_17-46](https://user-images.githubusercontent.com/16926/236570655-d41fbb24-2e82-41ec-b910-fb1e66223357.png)

Eu testei e realmente não era mais necessario. Por isso eu fiz um force push. Eu acho que agora ta bem OK...

2023-05-06 18:17 UTC, renatonlima approved these changes

2023-05-10 21:29 UTC, marcelsavegnago approved these changes

2023-05-10 23:45 UTC, rvalyi commented
/ocabot merge major

2023-05-11 00:18 UTC, merged

2023-05-11 10:49 UTC, felipemotter commented
Obrigado pelo grande trabalho Raphael!!!

2023-05-11 10:52 UTC, rvalyi commented
Na vdd isso é apenas o início do que vamos aproveitar do xsdata pela frente.