[12.0] Fiscal Tax Benefit
OCA/l10n-brazil pull request #2461
Opened 2023-04-27 14:43 UTC by renatonlima

Relacionada a nota técnica 2019.001 que quando houver a concessão de algum beneficio fiscal do ICMS deve ser informado o código do beneficio fiscal cBenef na NF-e

![Screenshot from 2023-04-27 11-31-26](https://user-images.githubusercontent.com/211005/234895672-d2336aa2-9791-4fbc-bdff-4cf25045eeb1.png)

Para implementar a configuração dos beneficios foi adicionado um objeto tax.benefit que pode conter tax.definitions para implementar as regras do beneficio fiscal

![Screenshot from 2023-04-27 11-37-21](https://user-images.githubusercontent.com/211005/234898452-b5e23138-edee-4186-af45-82dbec4c9d7b.png)

![Screenshot from 2023-04-27 11-39-55](https://user-images.githubusercontent.com/211005/234898549-13c3d802-de36-49a8-b81f-fc60e4928107.png)

2023-04-27 15:25 UTC, rvalyi commented
testes falhando porem https://github.com/OCA/l10n-brazil/actions/runs/4821136753/jobs/8586590820?pr=2461#step:8:1748

2023-05-04 12:52 UTC, nathamysaraiva reviewed
![image](https://user-images.githubusercontent.com/130476560/236208855-4af2eb41-a1cb-4941-b45f-b381abd9bde3.png)
Não, consegui testar a PR,não consigo adicionar uma linha no tax benefit ele não me dá esta opção.

2023-05-04 18:53 UTC, douglascstd reviewed
[FUNCTIONAL TEST]

Realizado configuração de um benefício:
![image](https://user-images.githubusercontent.com/20867090/236297027-8db33c1c-01bf-402b-8e17-33dcae5abead.png)

Incluído na Definição do imposto:
![image](https://user-images.githubusercontent.com/20867090/236297163-5ee16d46-d314-46cd-8ce8-f3d3bab02f50.png)

Realizado uma Fatura, para verificar se o imposto é carregado (um produto com o mesmo ncm da configuração do imposto)
![image](https://user-images.githubusercontent.com/20867090/236297390-72743370-a492-4d2a-9d04-e246c799eb9a.png)
Operação fiscal:Vendas
Linha de Operação fiscal: Revenda

Ajustado a empresa e o parceiro (cliente) para o estado de GO:
![image](https://user-images.githubusercontent.com/20867090/236298050-c20d08f6-a0c9-41b8-af2a-75a46aac192e.png)

A seleção do imposto parece ser sempre pelo imposto da guia: "Interno", pois mesmo indicando um imposto na guia: Tax Benefit, parece que esse imposto não é buscado.
![image](https://user-images.githubusercontent.com/20867090/236301322-6e5eed3d-b9c7-4167-ad9f-81fadb4cba22.png)


Pode ser que eu tenha entendido errado e configurado de maneira errada.

2023-05-18 20:41 UTC, renatonlima commented
@douglascstd,

Eu vi que o Tax Definition que você criou não estava com o status aprovado.

Mas além desse detalhe eu preciso fazer uma correção, porque da forma que eu implementei, o Tax Definition deve estar relacionado ao regulamento do ICMS para funcionar e também deve ser informado o estado de destino:

![Screenshot from 2023-05-18 17-39-03](https://github.com/OCA/l10n-brazil/assets/211005/296a4d87-495c-4b9c-be72-34d00395b066)


Desse forma, funciona:


![Screenshot from 2023-05-18 17-37-36](https://github.com/OCA/l10n-brazil/assets/211005/28a017dd-5e15-4168-8681-9fd11266ca15)

2023-05-18 20:42 UTC, renatonlima commented
Eu vou fazer a correção para permitir ser criado um beneficio fiscal no menu do Tax Benefit e vou adicionar alguns testes

2023-06-16 22:20 UTC, renatonlima commented
Pessoal eu conclui os trabalhos neste PR,

Eu fiz algumas modificações, eu removi o objeto l10n_br_fiscal.fiscal.tax.benefit porque como havia sido implementado, sempre iria precisar de um l10n_br_fiscal.tax.definition, então já que iria utilizar o l10n_br_fiscal.tax.definition eu adicionei o flag is_benefit e alguns campos no l10n_br_fiscal.tax.definition, agora dentro do regulamento do ICMS dá para adicionar os beneficios fiscais.

Também refatorei os métodos de mapeamento do ICMS para diminuir algumas linhas de código.

Adicionei um teste para a funcionalidade do beneficio fiscal.


cc @rvalyi @marcelsavegnago @douglascstd @nathamysaraiva

2023-06-18 22:01 UTC, rvalyi commented on l10n_br_fiscal/tests/test_tax_benefit.py
> +            "Document is not in To Sent state",
s/To Sent/To Send/

2023-06-20 17:50 UTC, rvalyi commented on l10n_br_fiscal/models/tax_definition_benefit.py
> +                                "the type of benefit !"
não deve ter espaço antes do ! na mensagem desses 3 raises acima.

2023-06-20 17:51 UTC, rvalyi requested changes
apenas anotei algo com as mensagens dos raise que seria bom corrigir antes de começar a virar chave de tradução.

2023-06-20 17:51 UTC, rvalyi commented on l10n_br_fiscal/models/tax_definition_benefit.py
> +                                "the type of benefit !"
não deve ter espaço antes do ! na mensagem desses 3 raises acima.

2023-06-20 21:36 UTC, rvalyi approved these changes
LGTM

2023-06-21 23:19 UTC, douglascstd commented
[FUNCTIONAL TEST] **APPROVED**
Não foi possível terminar o teste usando GO - Erro ao acessar o cadastro do Company - Não está sendo possível acessar o res.partner. Não sei dizer se foi impactado pela PR.

1. Configuração de um Benefício para GO
![image](https://github.com/OCA/l10n-brazil/assets/20867090/fe7290c7-bc58-44cc-9218-ad2964e8f929)
![image](https://github.com/OCA/l10n-brazil/assets/20867090/e2bdc5b2-2efc-412f-af9c-bd126d094b3d)

No momento de alterar o endereço da Empresa para fazer uma fatura 
GO >> GO
Obs.: O erro aparece ao tentar acessar qualquer res.partner

apresentou um erro:
![image](https://github.com/OCA/l10n-brazil/assets/20867090/1fcd25d0-ffd8-4f27-8ab7-ef359cdb9c14)

### Erro completo:
```
Error:
TypeError: field is undefined

http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1534
Traceback:
_getFieldWidgetClass@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1534:43
_processField@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1539:240
_processNode@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1553:142
_processArch/<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1539:136
traverse@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:321
traverse/<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:368
_.forEach@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:12:566
traverse@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:331
traverse/<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:368
_.forEach@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:12:566
traverse@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:331
traverse/<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:368
_.forEach@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:12:566
traverse@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:331
traverse/<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:368
_.forEach@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:12:566
traverse@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:331
traverse/<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:368
_.forEach@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:12:566
traverse@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:331
traverse/<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:368
_.forEach@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:12:566
traverse@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:331
_processArch@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1539:95
_processFieldsView@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1550:239
OdooClass.extend/</prototype[name]<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3538:488
init@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1275:667
init@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1533:539
OdooClass.extend/</prototype[name]<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3538:488
init@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:3075:230
OdooClass.extend/Class.include/</prototype[name]@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3541:371
init@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1690:580
OdooClass.extend/</prototype[name]<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3538:488
init@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:3064:143
OdooClass.extend/Class.include/</prototype[name]@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3541:371
Class@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3539:65
_createViewController@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:496:553
newController@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:510:155
_switchController@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:511:163
_onSwitchView@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:520:6
proxy/<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3643:11
trigger@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3641:180
_trigger_up@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3647:378
_trigger_up@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3647:462
trigger_up@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3647:280
_onOpenRecord@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1307:448
proxy/<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3643:11
trigger@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3641:180
_trigger_up@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3647:378
_trigger_up@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b [...]

2023-06-21 23:21 UTC, douglascstd approved these changes
[FUNCTIONAL TEST] **APPROVED**
Não foi possível terminar o teste usando GO - Erro ao acessar o cadastro do Company - Não está sendo possível acessar o res.partner. Não sei dizer se foi impactado pela PR.

1. Configuração de um Benefício para GO
![image](https://github.com/OCA/l10n-brazil/assets/20867090/fe7290c7-bc58-44cc-9218-ad2964e8f929)
![image](https://github.com/OCA/l10n-brazil/assets/20867090/e2bdc5b2-2efc-412f-af9c-bd126d094b3d)

No momento de alterar o endereço da Empresa para fazer uma fatura 
GO >> GO
Obs.: O erro aparece ao tentar acessar qualquer res.partner

apresentou um erro:
![image](https://github.com/OCA/l10n-brazil/assets/20867090/1fcd25d0-ffd8-4f27-8ab7-ef359cdb9c14)

### Erro completo:
```
Error:
TypeError: field is undefined

http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1534
Traceback:
_getFieldWidgetClass@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1534:43
_processField@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1539:240
_processNode@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1553:142
_processArch/<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1539:136
traverse@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:321
traverse/<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:368
_.forEach@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:12:566
traverse@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:331
traverse/<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:368
_.forEach@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:12:566
traverse@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:331
traverse/<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:368
_.forEach@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:12:566
traverse@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:331
traverse/<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:368
_.forEach@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:12:566
traverse@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:331
traverse/<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:368
_.forEach@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:12:566
traverse@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:331
traverse/<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:368
_.forEach@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:12:566
traverse@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3774:331
_processArch@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1539:95
_processFieldsView@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1550:239
OdooClass.extend/</prototype[name]<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3538:488
init@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1275:667
init@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1533:539
OdooClass.extend/</prototype[name]<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3538:488
init@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:3075:230
OdooClass.extend/Class.include/</prototype[name]@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3541:371
init@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1690:580
OdooClass.extend/</prototype[name]<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3538:488
init@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:3064:143
OdooClass.extend/Class.include/</prototype[name]@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3541:371
Class@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3539:65
_createViewController@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:496:553
newController@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:510:155
_switchController@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:511:163
_onSwitchView@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:520:6
proxy/<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3643:11
trigger@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3641:180
_trigger_up@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3647:378
_trigger_up@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3647:462
trigger_up@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3647:280
_onOpenRecord@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/684-bb6ccca/web.assets_backend.js:1307:448
proxy/<@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3643:11
trigger@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3641:180
_trigger_up@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b95/web.assets_common.js:3647:378
_trigger_up@http://oca-l10n-brazil-12-0-pr2461-9d938a0995d9.runboat.odoo-community.org/web/content/683-6ba6b [...]

2023-06-21 23:45 UTC, rvalyi commented
obrigado pelo teste @douglascstd . Esse problema que vc teve na tela do contato, é o mesmo do que aqui https://github.com/OCA/l10n-brazil/issues/2473 a gente hoje resolveu comentando aquela linha da visão automática do módulos spec_driven_model/models/spec_view.py por enquanto. Falta uma solução real, mas eu ainda não tive tempo. vou ter que fazer de qualquer forma na hora de migrar esses pedaço de código para a v14. Mas tb não é algo relacionado a esse PR então eu acho bom fazer o merge dele para já ir integrando a melhoria na v14 e ver esse problema na visão de contato na V12 depois. cc@douglascstd

2023-06-22 13:51 UTC, marcelsavegnago approved these changes

2023-06-22 15:43 UTC, rvalyi commented
/ocabot merge major

2023-06-22 16:08 UTC, merged