[MIG]l10n_br_cnpj: Migration to 14.0
OCA/l10n-brazil pull request #2467
Opened 2023-05-05 18:31 UTC by ODBreno

2023-05-05 19:57 UTC, marcelsavegnago commented
@ODBreno Este módulo está sendo migrado de onde ?

2023-05-05 19:58 UTC, marcelsavegnago commented
Se a PR for apenas teste, por favor deixa ela em rascunho por favor. Aparentemente isso não é uma migração e sim um módulo novo pelo que entendi.

2023-05-05 22:53 UTC, ODBreno commented
Era um PR da 12.0 com esse módulo https://github.com/OCA/l10n-brazil/pull/1282, como o PR da 12.0 não foi aprovado esse seria um novo módulo mesmo, vou colocar em drafted e arrumar.

2023-05-26 16:21 UTC, rvalyi reviewed
Olá, eu sei que ainda é rascunho, porém eu queria comentar que eu acho nome l10_br_cnpj não específico suficiente. Dá para pensar que vc precisa desse módulo para ter um campo CNPJ enquanto ele tá trazido pelo l10_br_base. Não seria melhor chamar o módulo algo como l10n_br_cnpj_information, or some other more explicit name like this?

cc @renatonlima @marcelsavegnago

2023-05-26 17:41 UTC, ODBreno commented
Realmente o nome não estava condizendo com o que o módulo faz @rvalyi, estou mudando para l10n_br_cnpj_search, pois ele procura o cnpj com a API receitaws e/ou serpro.

2023-05-26 17:55 UTC, antoniospneto commented
outra sugestão poderia ser algo como l10n_br_partner_search

2023-05-26 18:17 UTC, ODBreno commented
Como ele busca o cnpj na tela de res.partner e na de res.company eu não sei se l10n_br_partner_search faria tanto sentido.

2023-05-26 19:07 UTC, antoniospneto commented
o res_company é uma extensão do res_partner mas tudo bem tbm, as duas opções são ok

2023-05-26 19:27 UTC, antoniospneto commented
@ODBreno uma duvida esses serviços da receitaws e serpro são pagos ?

2023-05-26 19:51 UTC, ODBreno commented
@antoniospneto o receitaws permite 3 consultas por minuto de forma gratuita, mas também tem versões pagas. O serpro é pago de qualquer forma.

2023-05-29 12:15 UTC, mileo commented
Pode criar a pasta e os arquivos de README?

2023-05-29 12:29 UTC, mileo commented
podem fazer um rebase?

2023-05-29 15:57 UTC, rvalyi requested changes
valeu pelo trabalho, porém eu anotei algumas coisas que teria que mudar, provavelmente tem mais...

2023-05-29 15:57 UTC, rvalyi commented on l10n_br_cnpj_search/__manifest__.py
> +            "erpbrasil.base>=2",
tirar essa dependência, já vem de transitiva pelo l10n_br_base

2023-05-29 15:57 UTC, rvalyi commented on l10n_br_cnpj_search/__manifest__.py
> +        "l10n_br_base",
tirar essa dependência, já vem de forma transitiva pelo l10n_br_fiscal

2023-05-29 15:57 UTC, rvalyi commented on l10n_br_cnpj_search/models/__init__.py
> +# Copyright 2022 KMEE
se eu não me engano, pelos guidelines da OCA arquivos __init__.py não devem ter menção de copyright, já que acaba sendo quase mais linhas de copyright do que de import trivial.

2023-05-29 15:57 UTC, rvalyi commented on l10n_br_cnpj_search/models/receitaws_webservice.py
> +    @staticmethod
a princípio é melhor usar @api.model (e self na assinatura) do que  @staticmethod para esse tipo de coisa nos módulos Odoo, pois vai permitir extender mais facilmente com outros módulos.

2023-05-29 15:57 UTC, rvalyi commented on l10n_br_cnpj_search/models/res_company.py
> +    mobile = fields.Char()
não seria melhor pegar o related to partner_id.mobile?

2023-05-29 15:57 UTC, rvalyi commented on l10n_br_cnpj_search/models/serpro_webservice.py
> +    def serpro_import_data(self, data):
esse tipo de método e outros, deve botar um _ na frente, porque senão é uma falha de segurança, qualquer usuário (e até talvez usuário de portal/site) consegue chamar o método por json RPC e ter accesso dados que ele não deveria...

2023-05-30 12:10 UTC, douglascstd approved these changes
[FUNCIONAL TEST]
Teste realizado somente com o provedor RECEITAWS

Não foi necessário fazer cadastro no site:
https://www.receitaws.com.br/

Apenas selecionar o provedor:
![image](https://github.com/OCA/l10n-brazil/assets/20867090/ef1295bf-9807-4814-a878-fb116b8db473)

E realizar a pesquisa no campo de preenchimento do CNPJ:
![image](https://github.com/OCA/l10n-brazil/assets/20867090/f14b22f0-d91a-49e6-98b1-c3e57a88bb8f)

Com o acionamento do botão (lupa):
![image](https://github.com/OCA/l10n-brazil/assets/20867090/be472226-76fc-4c3a-8474-dcf5ba7c2a41)
Preenche também o Perfil Fiscal:
![image](https://github.com/OCA/l10n-brazil/assets/20867090/0c6a0fbe-c4a6-4983-b532-faf33b6ada99)

2023-05-30 18:23 UTC, marcelsavegnago approved these changes

2023-05-30 20:27 UTC, rvalyi requested changes
Eu revisei novamente, ainda tem uns problemas bastante serios com a qualidade do codigo, vale a pena vc ser auxiliado com pessoas mais experientes na KMEE para arrumar...

2023-05-30 20:27 UTC, rvalyi commented on l10n_br_cnpj_search/models/cnpj_webservice.py
> +    def get_provider(self):
esse metodo não é proprio do registro (ou melhor do recordset de registro) nisso ele tem que ter o decorator @api.model. Porque se vc não bota @api.model, ele vira @api.multi por padrão que é usado apenas quando o metodo é ligado ao recordset (no framework Odoo o @api.model seria um pouco que nem o @staticmethod que vc usou inicialemente)

2023-05-30 20:27 UTC, rvalyi commented on l10n_br_cnpj_search/models/cnpj_webservice.py
> +    def get_api_url(self, cnpj):
mesma coisa aqui

2023-05-30 20:27 UTC, rvalyi commented on l10n_br_cnpj_search/models/cnpj_webservice.py
> +    @staticmethod
aqui deveria ser @api.model. Tem que dar um geral nos metodos dessa class. Vé com o @mileo ele dev saber...

2023-05-30 20:27 UTC, rvalyi commented on l10n_br_cnpj_search/models/cnpj_webservice.py
> +    @staticmethod
tem que dar uma pensada se vale a pena que essa class class CNPJWebservice herde de models.Model. Ou usar um Abstract model ou até herdar apenas de (object) caso não houver nenhum dado a persistir com ela...

2023-05-30 20:27 UTC, rvalyi commented on l10n_br_cnpj_search/models/receitaws_webservice.py
> +    _inherit = "l10n_br_cnpj_search.webservice"
isso ta um pouco ligado a meus comentarios a respeito da class CNPJWebservice: ou vc faz uma herança Python classica, ou vc pode ate usar sim o framework Odoo, mas ai talvez um models.AbstractModel como base.

Mas novamente, um models.Model que tem uma tabela por tras so faz sentido se houver dados para botar nessa tabela, senão é overkill.

2023-05-30 20:27 UTC, rvalyi commented on l10n_br_cnpj_search/models/receitaws_webservice.py
> +    def _receitaws_get_secondary_cnae(self, data):
esse metodos todos sem decorator, são todos @api.multi por padrão, mas não dependem de recordset nennum. Tem que dar uma geral nisso. Novamente o @mileo ou até o @ygcarvalh devem saber te ajudar...

2023-05-30 20:27 UTC, rvalyi commented on l10n_br_cnpj_search/models/res_company.py
> +    )
ja que vc botou um campo capital_social no res.partner aqui teria que ser um related pelo partner_id
tb capital_social não é bem ingles, talvez equity ?

2023-05-30 20:27 UTC, rvalyi commented on l10n_br_cnpj_search/models/res_company.py
> +    natureza_juridica = fields.Char(string="Natureza Jurídica")
mesma coisa deveria ser relatated pelo partner_id
botar um nome de campo ingles

2023-05-30 20:27 UTC, rvalyi commented on l10n_br_cnpj_search/models/res_partner.py
> +    )
mudar para um nome ingles. equity?

2023-05-30 20:27 UTC, rvalyi commented on l10n_br_cnpj_search/models/res_partner.py
> +    natureza_juridica = fields.Char(string="Natureza Jurídica")
botar um nome ingles

2023-05-30 20:27 UTC, rvalyi commented on l10n_br_cnpj_search/models/serpro_webservice.py
> +    _inherit = "l10n_br_cnpj_search.webservice"
ver meus comentarios a respeito dos outros webservices

2023-05-31 14:05 UTC, ygcarvalh commented on l10n_br_cnpj_search/models/receitaws_webservice.py
> +        res = {
Se você está apenas fazendo a atribuição e logo em seguida retornando, não é melhor já retornar essa definição do dict?

2023-05-31 17:45 UTC, marcelsavegnago commented on l10n_br_cnpj_search/models/res_partner.py
> +    )
@mileo importante alinhar com o time esta questão dos campos em ingles e as string em ingles (salvo exceções) porque ai evitamos ter que tratar posteriormente e deixamos bem padronizado. Vlwwww

2023-05-31 17:47 UTC, marcelsavegnago requested changes
Fora as correções indicadas pelo @rvalyi reforço a necessidade de alterar os nomes dos campos e strings para ingles.

2023-06-01 13:29 UTC, ygcarvalh approved these changes
lgtm

2023-06-01 14:15 UTC, rvalyi approved these changes
eu anotei algum detalhe no __manifest__.py se puder resolver mas do restante tá OK para mim. Parabéns pelo trabalho.

2023-06-01 14:15 UTC, rvalyi commented on l10n_br_cnpj_search/__manifest__.py
> +    "external_dependencies": {
remover já que tá vazio

2023-06-01 14:59 UTC, ODBreno commented on l10n_br_cnpj_search/__manifest__.py
> +    "external_dependencies": {
Feito, muito obrigado!

2023-06-01 15:01 UTC, rvalyi commented
/ocabot merge nobump

2023-06-01 15:36 UTC, merged