issue #2450
OCA/l10n-brazil pull request #2531
Opened 2023-06-10 15:44 UTC by pablomatoskmee

Adicionado um domain para que os campos "tax_framework" e "technical_support_id" busquem somente o tipo company.

2023-06-10 20:07 UTC, douglascstd commented
Como ficaria quando o responsável contábil  a ser informado seja um funcionário da própria empresa?
Não deveria ser informado um res.partner PF?

2023-06-10 20:17 UTC, antoniospneto commented
> Como ficaria quando o responsável contábil  a ser informado seja um funcionário da própria empresa?
> Não deveria ser informado um res.partner PF?

Acho que é uma limitação do projeto nfe eles só aceitam cnpj como responsável técnico

2023-06-11 23:46 UTC, antoniospneto commented
> > Como ficaria quando o responsável contábil  a ser informado seja um funcionário da própria empresa?
> > Não deveria ser informado um res.partner PF?
> 
> Acho que é uma limitação do projeto nfe eles só aceitam cnpj como responsável técnico

Desculpa @douglascstd eu respondi quanto ao responsável técnico não quanto ao contador.

O responsavel técnico se for usado para preencher na nota fiscal só é aceito CNPJ:
![image](https://github.com/OCA/l10n-brazil/assets/634278/fb2386b1-d02c-4543-9fba-31e9458056ff)

Quanto ao contador pelo que vi não é informado na NFE mas pode utilizado para informar no SPED 
O CPF é obrigatório, mas o CNPJ é OPCIONAL, como pode ver:
![image](https://github.com/OCA/l10n-brazil/assets/634278/24f4639e-1ab2-4d4c-a4d9-0d6c17879a06)

Então concordo com o @douglascstd  não parece correto limitar o cadastro do contador a uma empresa.

2023-06-11 23:49 UTC, antoniospneto commented
Pensando melhor na questão do contador, o correto é ter um campo para informar o contabilista responsavel (PF)
e também um campo para informar o escritório de contabilidade (PJ)  caso tenha.

2023-06-12 00:05 UTC, antoniospneto commented
> Adicionado um domain para que os campos "tax_framework" e "technical_support_id" busquem somente o tipo company.

onde você disse **tax_framework** você quis dizer **accountant_id** certo ?

2023-06-12 00:10 UTC, antoniospneto requested changes
1. O contador tem que ser um CPF.
2. Um novo campo tem que ser criado para informar o escritório de contabilidade, ai sim esse deve ser um CNPJ.
3. Quanto ao responsável técnico está ok.

2023-06-12 17:21 UTC, pablomatoskmee commented
> > Adicionado um domain para que os campos "tax_framework" e "technical_support_id" busquem somente o tipo company.
> 
> onde você disse `tax_framework` você quis dizer `accountant_id` certo ?

Sim, foi isso mesmo, acabei de corrigir o comentário, obrigado!

2023-06-12 17:22 UTC, pablomatoskmee commented
> 1. O contador tem que ser um CPF.
> 2. Um novo campo tem que ser criado para informar o escritório de contabilidade, ai sim esse deve ser um CNPJ.
> 3. Quanto ao responsável técnico está ok.

Irei fazer essas alterações então

2023-06-15 00:15 UTC, pablomatoskmee commented
@antoniospneto 
![image](https://github.com/OCA/l10n-brazil/assets/123492075/5a8dc7d1-3e2e-4179-b4e7-950c5eef7e82)

Os campos Accounting Office e Technical Support estão limitados a buscar somente company(cnpj), era esse mesmo o objetivo?

2023-06-15 22:35 UTC, antoniospneto commented
> @antoniospneto ![image](https://user-images.githubusercontent.com/123492075/245959943-5a8dc7d1-3e2e-4179-b4e7-950c5eef7e82.png)
> 
> Os campos Accounting Office e Technical Support estão limitados a buscar somente company(cnpj), era esse mesmo o objetivo?

Na minha opnião é isso mesmo, assim os campos ficam de acordo para depois alimentar a NF-e e o SPED.

Agora acho que só falta ajeitar o pre-commit.
Você tem que ter ele instalado na sua maquina que ai no momento que você der o comando do commit ele é executado automaticamente.

Para instalar:

`pip install pre-commit`

Como você já deu o commit, você pode forçar o pre-commit simplesmente chamando o comando `pre-commit` de dentro da pasta l10n_brazil

depois vc dá um `git commit --amend` e depois um `git push --force`

2023-06-15 22:44 UTC, antoniospneto commented
@pablomatoskmee 

Depois você vai precisar arrumar o seu histórico de commit que tá um pouco bagunçado, tem muito commit pra pouca coisa.

você pode dar um `git reset --soft upstream/14.0` que ai as alteração voltam para sua área de trabalho para você poder fazer um novo commit.

2023-06-15 23:02 UTC, rvalyi commented
sim, o @antoniospneto tem razão, para esse tipo de mudança tem que ser 1 ou 2 commits apenas. Vc pode usar combos de git stash/git stash pop com git rebase -i para ajeitar tb qdo vc tiver que limpar PRs mais complexos. Neste caso o que o @antoniospneto falou deve ser suficiente. observar os PRs nos outros repo da OCA é uma forma de adquirir essa cultura das boas práticas...

2023-06-16 01:14 UTC, pablomatoskmee commented
Sim sim, eu realmente acabei fazendo uma bagunça nos commits justamente tentando junta-los em um, me desculpem por isso. Vou corrigir isso agora, queria só ter certeza que tinha cumprido o objetivo da issue antes. Brigadão!

2023-06-16 22:32 UTC, renatonlima approved these changes

2023-06-17 22:04 UTC, antoniospneto approved these changes

2023-06-17 23:12 UTC, rvalyi commented
/ocabot merge minor

2023-06-17 23:52 UTC, merged