[ADD] State Subscription SINTEGRA Search
OCA/l10n-brazil pull request #2555
Opened 2023-06-23 18:13 UTC by ODBreno

Este módulo busca a inscrição estadual referente ao cnpj preenchido, essa ação ocorre ao clicar no botão de busca de cnpj do módulo l10n_br_cnpj_search e o usuário ativou a busca de inscrição estadual e configurou seu token da API nas configurações. Vale ressaltar que é uma API paga.

2023-06-23 19:30 UTC, rvalyi requested changes
seria legal remover o arquivos vazios na pasta readme

2023-06-24 12:52 UTC, antoniospneto commented
sugestão pro nome do módulo: l10n_br_sintegraws

acho que podia deixar claro que é uma integração com o serviço da sintegra**WS** que é de uma empresa privada (terceiros) não uma integração nativa com o sistema do governo SINTEGRA.

2023-06-26 13:12 UTC, mileo commented
Acho mais interessante usar o webservice do próprio sefaz ao invés desse, pois é gratuito e tecnicamente deve devolver o mesmo resultado.

2023-06-26 17:34 UTC, ODBreno commented
Vou mudar pro sefaz, conversei aqui com a equipe e é melhor mesmo aparentemente, vou retirar a opção de ligar a pesquisa de inscrição estadual também, uma vez que, como é gratuito, não vejo motivos pra alguém querer que não preencha sozinho.

2023-06-26 17:41 UTC, antoniospneto commented
> Vou mudar pro sefaz, conversei aqui com a equipe e é melhor mesmo aparentemente, vou retirar a opção de ligar a pesquisa de inscrição estadual também, uma vez que, como é gratuito, não vejo motivos pra alguém querer que não preencha sozinho.

só tem que cuidar que o da sefaz vai exigir o certificado digital, ai tem que tratar caso não tenha no cadastro

2023-07-04 20:00 UTC, renatonlima commented
Pessoal,

Será se vale a pena inegrar a consulta com o sintegraws?

Pois o CCC (Cadastro Centralizado de Contribuintes) https://dfe-portal.svrs.rs.gov.br/NFE/CCC pode ser acessado via WS da SEFAZ gratuito.

2023-07-05 13:11 UTC, ODBreno commented
Estou implementando com ambos os provedores, tanto sintegraws qnt o webservice do sefaz no PR #2582

2023-07-05 13:11 UTC, closed without merging