[14.0][NEW] l10n_br_ie_search
OCA/l10n-brazil pull request #2582
Opened 2023-07-04 18:08 UTC by ODBreno

Como foi discutido no PR #2555, foi feita a implementação da consulta da inscrição estadual pelo sintegraws e pelo sefaz, permitindo que o usuário escolha qual provedor deseja utilizar.

2023-07-07 13:00 UTC, ygcarvalh commented on l10n_br_ie_search/__manifest__.py
> +    "demo": [],
Se não for adicionar dado de demo, pode remover essa chave. Eventualmente podemos adicionar ela caso seja adicionado.

2023-07-07 13:00 UTC, ygcarvalh commented on l10n_br_ie_search/models/sintegra_webservice.py
> +        querystring = {
Como você está declarando e retornando logo em seguida, você já pode fazer o return direto do dict.

2023-07-07 13:00 UTC, ygcarvalh commented on l10n_br_ie_search/models/sintegra_webservice.py
> +        if data.get("status") == "ERROR":
Ele não retorna um código HTTP? Seria melhor do que uma mensagem de erro que pode ser alterada.

2023-07-07 13:00 UTC, ygcarvalh commented on l10n_br_ie_search/models/sintegra_webservice.py
> +        url = SINTEGRA_URL
Pode fazer o retorno direto sem a necessidade de uma declaração.

2023-07-07 13:00 UTC, ygcarvalh commented on l10n_br_ie_search/models/sefaz_webservice.py
> +        if not response.ok:
O que ele espera desse retorno? Um booleano true ou algum valor qualquer?

2023-07-07 13:05 UTC, ODBreno commented on l10n_br_ie_search/models/sefaz_webservice.py
> +        if not response.ok:
um booleano true

2023-07-07 14:03 UTC, ODBreno commented on l10n_br_ie_search/models/sintegra_webservice.py
> +        if data.get("status") == "ERROR":
Ele retorna HTTP, que eu valido no _validate, mas ele tem suas próprias respostas tbm, por isso esse status code: 
![image](https://github.com/OCA/l10n-brazil/assets/92598517/f0f02c02-c8b0-4afb-a633-730202b40d89)

2023-07-10 19:11 UTC, ygcarvalh commented
@rvalyi @marcelsavegnago @antoniospneto podem revisar, por favor?

2023-07-11 11:30 UTC, AndreMarcos approved these changes

2023-07-11 12:31 UTC, ygcarvalh approved these changes

2023-07-11 17:52 UTC, antoniospneto approved these changes

2023-07-11 18:21 UTC, marcelsavegnago approved these changes
LGTM

2023-07-11 23:54 UTC, rvalyi requested changes

2023-07-11 23:54 UTC, rvalyi commented on l10n_br_ie_search/__manifest__.py
> +            "erpbrasil.edoc.nfe",
aqui vc vai ter que repetir as versões mínimas, vê no requirements.txt. Não é muito DRY, mas infelizmente é a forma como funciona hoje.

2023-07-11 23:54 UTC, rvalyi commented on l10n_br_ie_search/tests/test_sefaz.py
> +class TestTestSefaz(HttpCase):
o HTTPCase tem toda uma especialização para iniciar um embedded browser para fazer testes de paginas HTML do Odoo: https://github.com/odoo/odoo/blob/14.0/odoo/tests/common.py#L1379
Mas não é o que vc esta estando aqui, pois os queries HTTP que vc faz é para a Sintegra o a Sefaz. Portando não precisa carregar essa complexidade. A class base vc deve derivar deveria ser a Savepointcase. Mas ja que tem apenas 1 teste por arquivo de teste, pode ser a TestPointCase (que na v16 tem o mesmo funcionamento do que a SavepointCase) e assim vc facilita o port para a v16.

cc @marcelsavegnago @antoniospneto @felipemotter

2023-07-11 23:56 UTC, rvalyi commented on l10n_br_ie_search/tests/test_sintegra.py
> +@tagged("post_install", "-at_install")
mesma coisa do que no meu comentario anterior

2023-07-11 23:56 UTC, rvalyi commented on l10n_br_ie_search/tests/test_sintegra.py
> +        super(TestTestSintegra, self).setUp()
deveria usar super() apenas, nas futuras versões essa forma nem é mais permitida.

2023-07-12 14:14 UTC, ODBreno commented on l10n_br_ie_search/__manifest__.py
> +            "erpbrasil.edoc.nfe",
Resolvido no commit 18cc3ed60736d9cd9b2c580329b003e2ab058e74.

2023-07-12 14:51 UTC, ODBreno commented
@rvalyi ou @marcelsavegnago poderia rodar meu teste de novo? Deu erro no product_contract.

2023-07-12 15:39 UTC, rvalyi commented
Ola @ODBreno , da um um pull da branch 14.0 e faz um rebase da sua branch em cima da 14.0 pois vc vai precisar desse fix pros testes rodar https://github.com/OCA/l10n-brazil/pull/2602

Outra coisa, precisa ajeitar um pouco os commits da sua branch. Por examplo esse ultimo commit é interessante vc fazer um squash dele com algum commit anterior que mexe no mesmo arquivo, esse outro tb https://github.com/OCA/l10n-brazil/pull/2582/commits/5a4dc5e23a52a3ab6d245b2a7ce9c7752c6c2656

Basicamente vc precisa aprender os comandos git rebase -i, git stash/git stash pop, git cherry-pick, pois na OCA tem que evitar de mandar os commit de experimentos que vc teve que fazer no seu computador ate chegar na solução. Ja tem bem demais commit certos no projeto para poluir com isso que depois ferra as ferramentas de sincronização entre as branches ou a busca por explicações ou culpados (git blame). E olha que a gente não é extremista com isso, se fosse um repo que alguém como o Pedro Bazea mantem, ele ia te pedir de juntar tudo isso num commit apenas. Pode ter alguns no caso, mas uns 5 me parece ser o máximo, experimentos não tem que entrar pro repo da OCA.

cc  @marcelsavegnago @renatonlima @antoniospneto

2023-07-17 12:02 UTC, ygcarvalh commented
@rvalyi consegue dar uma olhada? Acho que o Breno fechou as alterações que você havia requisitado.

2023-07-17 13:12 UTC, mileo commented on l10n_br_ie_search/models/l10n_br_base_party_mixin.py
> +        webservice = self.env["l10n_br_cnpj_search.webservice.abstract"]
Vale colocar uma validação aqui, se os campos estado, cnpj estão preenchidos, se não nem chame o webservice.

2023-07-17 13:13 UTC, mileo approved these changes

2023-07-17 19:18 UTC, ODBreno commented on l10n_br_ie_search/models/l10n_br_base_party_mixin.py
> +        webservice = self.env["l10n_br_cnpj_search.webservice.abstract"]
Eu tinha feito uma validação de cnpj aí antes, mas percebi que no super (search cnpj) essa validação já é feita, em teoria não é pra ele nem chamar o ie_search se ele não tiver o cnpj. Quanto ao estado, como ele só vai pro ie_search dps de fazer o search_cnpj, o estado só não estaria preenchido se a empresa não tiver estado cadastrado no webservice ou se a consulta falhar, se a consulta falhar ele não chamaria o ie_search.

2023-07-18 04:29 UTC, rvalyi approved these changes
LGTM

2023-07-18 23:36 UTC, felipemotter approved these changes

2023-07-19 01:39 UTC, rvalyi commented
/ocabot merge nobump

2023-07-19 10:07 UTC, marcelsavegnago commented
/ocabot merge nobump

2023-07-19 14:56 UTC, ODBreno commented
Mockei o teste do sintegraws, eu deveria ter feito isso desde o começo, nunca é bom deixar os testes dependendo de serviços externos. Se puderem tentar dar o merge de novo pra mim, por favor @rvalyi @marcelsavegnago.

2023-07-19 15:24 UTC, marcelsavegnago commented
/ocabot merge nobump

2023-07-19 16:03 UTC, merged