[14.0][ADD] l10n_br_sale_blanket_order: new module
OCA/l10n-brazil pull request #2626
Opened 2023-08-01 14:54 UTC by marcelsavegnago

2023-08-21 22:36 UTC, marcelsavegnago commented
@kaynnan  faz o rebase desa branch por favor

2023-08-29 16:21 UTC, antoniospneto commented on l10n_br_sale_blanket_order/readme/USAGE.rst
> +#. Confirm the Repair
a palavra Repair está correto aqui ?

2023-08-29 17:07 UTC, douglascstd requested changes
[FUNCIONAL TEST] NOT APPROVED
## Testes realizados
1. BO com produtos de venda
2. BO com produto de serviço com retenção

## Teste 1
![image](https://github.com/OCA/l10n-brazil/assets/20867090/e7bc698c-4e8c-49d4-91bb-c65341166d77)
![image](https://github.com/OCA/l10n-brazil/assets/20867090/6f27c84e-0d22-4a36-b4f9-e38e5c208876)

Aparece um checkbox "perdido" sem Rotulo (pode ser que não faça parte desta PR)
![image](https://github.com/OCA/l10n-brazil/assets/20867090/22feed92-75ed-465f-becc-7b0bbf69ef86)
![image](https://github.com/OCA/l10n-brazil/assets/20867090/fa210c7c-22c9-4aaf-862a-3c4e6b6e2590)
![image](https://github.com/OCA/l10n-brazil/assets/20867090/6c492cf6-af82-44ff-b2d1-b9309c22e11c)

## Teste 2 - Não aprovado
![image](https://github.com/OCA/l10n-brazil/assets/20867090/902a83dc-3baf-47f9-bd2e-98159aac507d)
![image](https://github.com/OCA/l10n-brazil/assets/20867090/30c1136b-ece7-40ce-94ef-e76d05104581)

2023-08-29 18:16 UTC, marcelsavegnago commented on l10n_br_sale_blanket_order/readme/USAGE.rst
> +#. Confirm the Repair
nope :D .. vou corrigir. Obrigado

2023-08-29 19:17 UTC, marcelsavegnago commented on l10n_br_sale_blanket_order/readme/USAGE.rst
> +#. Confirm the Repair
resolvido

2023-08-29 19:21 UTC, marcelsavegnago commented
> Aparece um checkbox "perdido" sem Rotulo (pode ser que não faça parte desta PR)
> ![image](https://user-images.githubusercontent.com/20867090/264097908-22feed92-75ed-465f-becc-7b0bbf69ef86.png)

Este ai vem da localização do contrato. Eu registrei uma issue algum tempo atrás mas não tratei.
https://github.com/OCA/l10n-brazil/issues/2617

2023-08-29 19:21 UTC, marcelsavegnago commented
> > Aparece um checkbox "perdido" sem Rotulo (pode ser que não faça parte desta PR)
> > ![image](https://user-images.githubusercontent.com/20867090/264097908-22feed92-75ed-465f-becc-7b0bbf69ef86.png)
> 

@douglascstd  Este ai vem da localização do contrato. Eu registrei uma issue algum tempo atrás mas não tratei. #2617

2023-08-30 15:25 UTC, marcelsavegnago commented
> ![image](https://user-images.githubusercontent.com/20867090/264098203-902a83dc-3baf-47f9-bd2e-98159aac507d.png)

Aparentemente este problema ocorre também quando é criado uma cotação avulsa.

2023-08-30 15:26 UTC, marcelsavegnago commented
> > ![image](https://user-images.githubusercontent.com/20867090/264098203-902a83dc-3baf-47f9-bd2e-98159aac507d.png)
> 

@douglascstd  Aparentemente este problema ocorre também quando é criado uma cotação avulsa.

2023-09-04 18:21 UTC, douglascstd approved these changes
[FUNCIONAL TESTE] APPROVED

![image](https://github.com/OCA/l10n-brazil/assets/20867090/223a9ec3-db77-40f0-894d-fffe18c1d817)
![image](https://github.com/OCA/l10n-brazil/assets/20867090/b4883b77-5153-4bb2-8f5c-c63c0890180c)

2023-09-13 01:37 UTC, marcelsavegnago commented
@douglascstd arrumei a rotina de criação dos pedidos de venda via linha de pedido guarda-chuva. Porém, como a rotina permite selecionar linhas de pedidos guarda-chuva diferentes, adicionei uma regra para verificar se a operacao fiscal dos pedidos guarda-chuva são diferentes e se houver alguma diferente o sistema bloqueia a criação do pedido de venda.

2023-09-13 12:06 UTC, douglascstd approved these changes
[FUNCIONAL TESTE]
Verificação da emissão de pedidos de venda pelas linhas do pedido guarda-chuva

Teste 1 -  Criação de pedido de venda pelas linhas do blanket order
Criação de 1 Blanket Order, com a mesma linha de operação fiscal
![image](https://github.com/OCA/l10n-brazil/assets/20867090/6cb2cdd3-0373-4993-9078-53b5ba0cf084)

Criação pelas linhas:
![image](https://github.com/OCA/l10n-brazil/assets/20867090/cf491f85-e35e-4380-a2ec-9c5d993397ac)

Pedido de Venda criado com sucesso
![image](https://github.com/OCA/l10n-brazil/assets/20867090/88c4fc5e-2a02-45ed-8da4-33887ca4a4cb)

Continuação no fluxo até a fatura:
Fatura criada:
![image](https://github.com/OCA/l10n-brazil/assets/20867090/66df2eaa-c295-49cb-9b5c-26c44971f605)
(Obs. Não entendi por qual motivo a Sequencia utilizada para a fatura foi esse: Teste Unicred CNAB... - Não parece estar vinculado ao módulo testado)

Teste 2 - Criação de pedido de venda utilizando 2 Blanket Order diferentes que contem linhas com Linha de Operação Fiscal também diferentes.
![image](https://github.com/OCA/l10n-brazil/assets/20867090/8de7738b-cd65-4e64-9197-a1eeb22613d6)

Criação do pedido de venda pelas linhas de 2 blanket order diferentes, com linhas de operação fiscal também diferentes:
![image](https://github.com/OCA/l10n-brazil/assets/20867090/542ee27c-368b-4518-a9a6-e6f2f56a394e)

Criação do pedido de venda (Quant 2 e 0,25, de material e serviço respectivamente)
![image](https://github.com/OCA/l10n-brazil/assets/20867090/0a760b8f-199d-4456-8834-da819bb7a561)

Pedido Criado:
![image](https://github.com/OCA/l10n-brazil/assets/20867090/47d045bf-a5d6-421d-9837-e3017f9a206e)

Após o recebimento e submissão da fatura, foi criado 2 faturas diferentes (1 para material de revenda e 1 para serviço prestado) como esperado.
![image](https://github.com/OCA/l10n-brazil/assets/20867090/b144d8be-2f4f-401c-a0de-e08ae1851282)

2023-09-13 16:09 UTC, rvalyi requested changes
só não entendi porque tem 2 arquivos XML de visões com os records comentados.

2023-09-13 16:09 UTC, rvalyi commented on l10n_br_sale_blanket_order/views/sale_blanket_order_line.xml
> +</odoo>
@marcelsavegnago vc poderia explicar o porquê desse arquivo tudo comentado assim?

2023-09-13 16:09 UTC, rvalyi commented on l10n_br_sale_blanket_order/wizards/sale_blanket_order_wizard.xml
> +</odoo>
mesma coisa com esse arquivo.

2023-09-13 17:53 UTC, marcelsavegnago commented on l10n_br_sale_blanket_order/views/sale_blanket_order_line.xml
> +</odoo>
opa.. esqueci de limpar :D

2023-09-13 17:53 UTC, marcelsavegnago commented on l10n_br_sale_blanket_order/wizards/sale_blanket_order_wizard.xml
> +</odoo>
idem.. faltou a limpeza.. sorry

2023-09-13 17:59 UTC, marcelsavegnago commented on l10n_br_sale_blanket_order/wizards/sale_blanket_order_wizard.xml
> +</odoo>
Removido

2023-09-13 17:59 UTC, marcelsavegnago commented on l10n_br_sale_blanket_order/views/sale_blanket_order_line.xml
> +</odoo>
limpo

2023-09-13 20:23 UTC, rvalyi approved these changes

2023-09-13 22:36 UTC, douglascstd approved these changes
[FUNCIONAL TESTE] APPROVED

2023-09-13 23:14 UTC, kaynnan approved these changes
LGTM

2023-09-13 23:58 UTC, rvalyi commented
/ocabot merge nobump

2023-09-14 00:34 UTC, merged