[FIX] erpbrasil.transmissão dependency
OCA/l10n-brazil pull request #2699
Opened 2023-09-14 20:28 UTC by felipezago

Resolvendo issue  https://github.com/OCA/l10n-brazil/issues/2688

2023-09-14 20:39 UTC, rvalyi approved these changes

2023-09-14 20:40 UTC, rvalyi requested changes
na real é melhor separa um commit por módulo, senão complica os cherry-picks na hora de fazer os ports dos módulos. Infelizmente...

2023-09-14 22:18 UTC, mileo approved these changes

2023-09-14 23:53 UTC, antoniospneto approved these changes

2023-09-15 03:20 UTC, rvalyi approved these changes

2023-09-15 03:20 UTC, rvalyi commented
/ocabot merge patch

2023-09-15 05:34 UTC, merged