[ADD] CNPJ Search fiscal e crm
OCA/l10n-brazil pull request #2712
Opened 2023-09-25 21:04 UTC by GCKrauss

Essa alteração remove a dependencia do módulo fiscal no cnpj_search, e adiciona dois novos módulos para que continue funcionando a search no módulo fiscal e no crm.

2023-09-26 01:05 UTC, mileo commented
Não creio que esta seja a melhor implementação, vcs chegaram a ver como o l10n_br_zip é implementado, funcionando tanto no crm.lead quanto no res.partner?

Eu cheguei a comentar com o @ygcarvalh faz uns dias isso, não deu certo?

2023-09-26 10:41 UTC, ygcarvalh commented
Eu cheguei a comentar com o @AndreMarcos e ele até tinha passado para os meninos sobre pesquisar isso. Mas até onde eu vi do código, não vejo porque não daria para ser implementado da mesma forma.

cc: @mileo

2023-09-29 06:38 UTC, AndreMarcos commented
@mileo, a abordagem do l10n_br_zip não deu certo para implementação do crm.lead, pelos seguintes motivos:
1. Se torna necessário criar uma view específica para o crm.lead a partir do momento em que é montada pelo próprio CRM: https://github.com/kmee/l10n-brazil/blob/7974fc2e84b760e0258c047abf06922f931cd5b1/l10n_br_crm/views/crm_lead_view.xml#L24 e https://github.com/odoo/odoo/blob/0bbeba79e7da72d2f85663ea46c020ba1fc4ba4e/addons/crm/views/crm_lead_views.xml#L120.
2. É necessário definir o campo 'cnpj' do crm.lead como related para o 'cnpj_cpf' do partner_id.
3. É possível contornar o que citei utilizando somente o módulo do l10n_br_cnpj_search, porém, ele precisará ficar dependente do l10n_br_crm, fugindo da ideia que temos de deixa-lo o mais independente possível.

Para o fiscal, concordo, refatorei e realizei o teste e está funcionando corretamente no módulo, se tornando necessário somente adicionar o campo "cnae_secondary_ids".

Refatorei o módulo.

Cc: @ygcarvalh @GCKrauss

2023-10-09 12:22 UTC, ygcarvalh requested changes
Por que foi removido o readme do arquivo base? É importante que cada módulo tenha seu readme.

2023-10-09 12:22 UTC, ygcarvalh commented on l10n_br_cnpj_search/__init__.py
> -# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
Não remover a licença se possível

2023-10-09 12:22 UTC, ygcarvalh commented on l10n_br_cnpj_search/__manifest__.py
> +    "name": "L10n_br Cnpj Search",
Por que houve alteração no nome do módulo?

2023-10-09 12:22 UTC, ygcarvalh commented on l10n_br_cnpj_search/models/cnpj_webservice.py
> +        if module and module.state == "installed":
Você consegue fazer o condicional diretamente no retorno, sem a necessidade do `if`

2023-10-09 12:22 UTC, ygcarvalh commented on l10n_br_cnpj_search/views/res_company_view.xml
> +        <field name="name">l10n_br.company.form (in l10n_br_cnpj_search)</field>
Esse nome está correto?

2023-10-09 12:22 UTC, ygcarvalh commented on l10n_br_cnpj_search/views/res_partner_view.xml
> +        <field name="name">l10n_br.partner.form (in l10n_br_cnpj_search)</field>
Esse nome está correto?

2023-10-09 12:22 UTC, ygcarvalh commented on l10n_br_cnpj_search_crm/__manifest__.py
> +    "name": "L10n_br Crm Cnpj Search",
Pode manter o mesmo padrão de nome para esse módulo?

2023-10-09 12:22 UTC, ygcarvalh commented on l10n_br_cnpj_search_crm/views/crm_cnpj_search.xml
> +          <field name="name">l10n_br.leads.form</field>
Esse nome está correto?

2023-10-09 12:22 UTC, ygcarvalh commented on l10n_br_fiscal/models/res_partner.py
> +    cnae_secondary_ids = fields.Many2many(
Remover essa alteração e colocar em um PR a parte.

2023-10-09 22:22 UTC, rvalyi commented on l10n_br_cnpj_search/__init__.py
> -# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
na vdd nós arquivos init, é considerado boa prática na OCA de não botar linhas de licença ou copyright. Pois geralmente tem apenas 3 ou 4 linhas de import, cujo autores podem variar...

2023-10-11 10:39 UTC, ygcarvalh requested changes

2023-10-11 10:39 UTC, ygcarvalh commented on l10n_br_cnpj_search_crm/README.rst
> +=========================================
Tem a forma correta de gerar o Readme, não apenas dando copy paste no arquivo. Você pode ter uma noção de como faz por aqui: https://github.com/OCA/maintainer-tools/blob/master/README.md#readme-generator

2023-10-11 10:39 UTC, ygcarvalh commented on l10n_br_cnpj_search/models/cnpj_webservice.py
> +        if self._check_l10n_br_fiscal_module_installed():
Não é mais fácil verificar antes se o módulo está instalado e, caso não esteja, retornar  `False`?

2023-10-11 10:39 UTC, ygcarvalh commented on l10n_br_cnpj_search/models/cnpj_webservice.py
> +            if code:
O mesmo para o `code`

2023-10-11 10:39 UTC, ygcarvalh commented on l10n_br_cnpj_search_crm/models/l10n_br_base_party_mixin.py
> +        """Search CNPJ by the chosen API"""
Essa função está identica a versão que está no módulo base. Por que não utilizar o conceito de heranças nesse caso e só alterar o que for realmente necessário para o módulo? Se não, fica irrelevante ter algo assim.

2023-10-11 10:39 UTC, ygcarvalh commented on l10n_br_cnpj_search_crm/models/serpro_webservice.py
> +    def _import_additional_info(self, data, schema):
Essa função para estar caindo no mesmo ponto em que a outra. É identica a função pai.

2023-10-11 10:39 UTC, ygcarvalh commented on l10n_br_cnpj_search_crm/views/crm_cnpj_search.xml
> +                        title="Pesquisar CNPJ"
Manter o padrão em inglês do código, se possível

2023-10-11 10:39 UTC, ygcarvalh commented on l10n_br_cnpj_search/__manifest__.py
>      "depends": [
Adicionar os maintainer do módulo.

2024-11-09 16:24 UTC, rvalyi commented
Eu acho que isso pode ser fechado e que foi implementado de forma diferente. @mileo se eu tiver errado, pode re-abrir.

2024-11-09 16:24 UTC, closed without merging