[14.0][IMP] l10n_br_purchase_stock: get analytic account and analytic tags from purchase line
OCA/l10n-brazil pull request #2796
Opened 2023-11-23 18:27 UTC by marcelsavegnago

2023-11-23 19:19 UTC, augustodinizl approved these changes
LGTM

[Functional Review]

![image](https://github.com/OCA/l10n-brazil/assets/25938418/badf2560-c688-44f4-88c0-520427232f11)
![image](https://github.com/OCA/l10n-brazil/assets/25938418/1f9c194c-f0aa-40f3-ac22-7845c5649649)
![image](https://github.com/OCA/l10n-brazil/assets/25938418/e15f56f7-3960-4d72-bf39-5953967dbe5d)

2023-11-23 21:38 UTC, mbcosta approved these changes

2023-11-24 00:04 UTC, antoniospneto requested changes
O `account_analytic_id` é um campo nativo, será que não é mais interessante propor essa alteração diretamente do módulo da oca `stock_picking_invoicing` aqui no [método original](https://github.com/OCA/account-invoicing/blob/012166d786e51f84648b7f32f45078587a8b0a8b/stock_picking_invoicing/wizards/stock_invoice_onshipping.py#L430) ?

2023-11-24 11:37 UTC, marcelsavegnago commented
> O `account_analytic_id` é um campo nativo, será que não é mais interessante propor essa alteração diretamente do módulo da oca `stock_picking_invoicing` aqui no [método original](https://github.com/OCA/account-invoicing/blob/012166d786e51f84648b7f32f45078587a8b0a8b/stock_picking_invoicing/wizards/stock_invoice_onshipping.py#L430) ?

Acredito que não já que toda a principio o moduclo sotkc_picking_invoice não aborda esta questão da fatura de pedido ser via picking ou via sale/purchase order. Porém, posso estar errado.

2023-11-24 13:20 UTC, antoniospneto commented
> > O `account_analytic_id` é um campo nativo, será que não é mais interessante propor essa alteração diretamente do módulo da oca `stock_picking_invoicing` aqui no [método original](https://github.com/OCA/account-invoicing/blob/012166d786e51f84648b7f32f45078587a8b0a8b/stock_picking_invoicing/wizards/stock_invoice_onshipping.py#L430) ?
> 
> @antoniospneto Acredito que não já que a principio o moduclo stock_picking_invoice não aborda esta questão da fatura de pedido ser via picking ou via sale/purchase order. A principio entendo que o objetivo dele é permitir a geração de faturas sem a necessidde do pedido de venda ou compra.

@marcelsavegnago 

Eu imaginei isso, o problema então é o fato de que o módulo `stock_picking_invoice ` que está fora da localização não depende nem do `purschase `nem do `sales`,  ai para dar certo teria que fazer um outro módulo que dependesse deses, entendo que se realmente não é de interesses fora da localização, talvez seja melhor fazer aqui na localização mesmo, obrigado pelas explicações.

2023-11-24 13:21 UTC, antoniospneto approved these changes

2023-11-24 22:16 UTC, rvalyi approved these changes

2023-11-25 15:02 UTC, rvalyi commented
/ocabot merge patch

2023-11-25 15:17 UTC, merged