[14.0][IMP] l10n_br_sale_stock: get analytic account and analytic tags from…
OCA/l10n-brazil pull request #2797
Opened 2023-11-23 18:43 UTC by marcelsavegnago

… sale order

2023-11-23 21:36 UTC, mbcosta approved these changes

2023-11-24 00:22 UTC, antoniospneto requested changes
Ver o comentário: https://github.com/OCA/l10n-brazil/pull/2796#pullrequestreview-1747101708

Será que não vale a pena por essa implementação fora da localização ?

2023-11-24 11:41 UTC, marcelsavegnago commented
> Ver o comentário: [#2796 (review)](https://github.com/OCA/l10n-brazil/pull/2796#pullrequestreview-1747101708)
> 
> Será que não vale a pena por essa implementação fora da localização ?

Não consegui visualizar isso fora da localização porque entendo que a questão da politica de faturamento feito no cadastro da empresa é algo próprio da localização.

2023-11-24 11:44 UTC, marcelsavegnago commented
@antoniospneto sinceramente estive pensando inclusive em não implantar o sistema com a politica de faturamento via picking já comecei a perceber certos problemas. Porém, nossos clientes normalmente estão optando pelo faturamento de pedido de venda e compra pelo picking.

2023-11-24 13:21 UTC, antoniospneto approved these changes

2023-11-24 22:17 UTC, rvalyi approved these changes

2023-11-25 15:27 UTC, rvalyi commented
/ocabot merge patch

2023-11-25 15:42 UTC, merged

2023-11-25 18:24 UTC, mbcosta commented
@antoniospneto alguns pontos sobre o stock_picking_invoicing, como o Marcel disse o objetivo lá é apenas criar Fatura/Invoice a partir do Picking, mas devido a dependência do modulo stock_picking_invoice_link https://github.com/OCA/account-invoicing/blob/14.0/stock_picking_invoicing/__manifest__.py#L10 o sale_stock está sendo instalado https://github.com/OCA/stock-logistics-workflow/blob/14.0/stock_picking_invoice_link/__manifest__.py#L20 acredito que quando foi feita a inclusão do modulo isso acabou passando despercebido e talvez o melhor lá vai ser remover essa dependência, talvez na v16. Em 2021 houve uma tentativa de extração do l10n_br_sale_stock para criar um modulo sale_stock_picking_invoicing no repo account-invoicing https://github.com/OCA/account-invoicing/pull/1025 a ideia seria fazer o mesmo com o l10n_br_purchase_stock, mas o PR ficou em aberto por volta de um ano sem retorno, eu mencionei essa questão na migração do l10n_br_sale_stock  "Havia a ideia de extrair boa parte do modulo para o repo account-invoicing mas é preciso confirmar se existe o interesse dos mantedores lá nesse modulo e hoje acredito que perdemos a "janela" para fazer essa extração e será melhor ver isso na futura v16" https://github.com/OCA/l10n-brazil/pull/1961

@marcelsavegnago sobre "sinceramente estive pensando inclusive em não implantar o sistema com a politica de faturamento via picking porque comecei a perceber certos problemas." eu estou revendo os módulos l10n_br_sale_stock e l10n_br_purchase_stock para manter a compatibilidade com os casos internacionais, mas se existirem outros problemas eu posso ver de resolver, se você achar melhor pode abrir um Issue e me marcar ou mesmo adicionar um Dado de Demonstração com o caso de uso que você encontrou problemas, no caso de Vendas para tentar atender o caso de Comissão e evitar a necessidade de criar um novo modulo intermediário eu chequei a fazer um PR na v12 que buscava de forma dinamica trazer os campos que existissem na criação a partir do Pedido e que faltavam a partir do Picking https://github.com/OCA/l10n-brazil/pull/2002 talvez isso ajude

2023-11-25 18:27 UTC, mbcosta commented on l10n_br_sale_stock/wizards/stock_invoice_onshipping.py
> +                    (6, 0, moves.sale_line_id.analytic_tag_ids.ids)
Uma questão, esses campos sempre vem preenchidos? Pelos testes parece que sim, porque se não pode acabar retornando erro de Bool não tem ID

2023-12-19 20:07 UTC, marcelsavegnago commented on l10n_br_sale_stock/wizards/stock_invoice_onshipping.py
> +                    (6, 0, moves.sale_line_id.analytic_tag_ids.ids)
De fato não viria preenchido sempre. vamos testar