[14.0][IMP] l10n_br_fiscal: Calculo correto da desoneração do ICMS
OCA/l10n-brazil pull request #2801
Opened 2023-11-24 11:46 UTC by ygcarvalh

Percebi que estava com um problema na forma como o arquivo .csv da desoneração do ICMS estava e, na hora de carregar as informações, ele acabava por colocar aspas  nos códigos e nas descrições do motivo. Removi os espaços que haviam entre as vírgulas.

A segunda parte do PR realiza o calculo correto da desoneração do ICMS, além de deixar ser preenchido o motivo quando está entre os CST's habilitados para tal. Por enquanto, o cálculo do ICMS está sendo feito sempre, mesmo que ele não vá ser exportado para a NFe. A ideia é que isso só possa ser calculado quando for selecionado um motivo de desoneração.

cc: @mileo @luismalta @hirokibastos @rvalyi @marcelsavegnago @antoniospneto

2024-03-15 14:40 UTC, mileo requested changes, later dismissed

2024-03-15 14:40 UTC, mileo commented on l10n_br_fiscal/models/tax.py
> +        if cst["code"] in ["20", "30", "40", "41", "50", "70", "90"]:
@ygcarvalh pode usar as contantes pra isso?

2024-03-22 11:44 UTC, mileo commented
@ygcarvalh pode verificar o que houve com os testes?

2024-03-27 13:34 UTC, GCKrauss commented
> @ygcarvalh pode verificar o que houve com os testes?

@mileo tem como rodar os testes de novo?

2024-03-27 14:03 UTC, marcelsavegnago commented
@GCKrauss mandei rodar novamente o teste que falhou

2024-03-28 01:41 UTC, mileo requested changes
@ygcarvalh pode incluir as outras constantes que estão faltando como neste if: 

```
            if cst.code in ICMS_SN_CST_WITH_CREDIT:
                icms_sn_percent = currency.round(
                    company.simplified_tax_percent
                    * (icmssn_range.tax_icms_percent / 100)
                )
```
Fica inclusive mais claro pra que mesta lendo o código.

2024-04-01 14:29 UTC, rvalyi requested changes
me parece que vc não alterou nada no l10n_br_fiscal/data/l10n_br_fiscal.icms.relief.csv a não ser botar espaços. Não se costuma botar espaços no csv do Odoo e não é bom fazer esse tipo de alteração em apenas algumas linhas se não acrescenta nada. Pode dar um amend e restaurar o arquivo l10n_br_fiscal/data/l10n_br_fiscal.icms.relief.csv ?

2024-04-01 16:46 UTC, mileo commented
> me parece que vc não alterou nada no l10n_br_fiscal/data/l10n_br_fiscal.icms.relief.csv a não ser botar espaços. Não se costuma botar espaços no csv do Odoo e não é bom fazer esse tipo de alteração em apenas algumas linhas se não acrescenta nada. Pode dar um amend e restaurar o arquivo l10n_br_fiscal/data/l10n_br_fiscal.icms.relief.csv ?

![image](https://github.com/OCA/l10n-brazil/assets/1975978/de65b15c-b8e7-448b-a3db-af6750c1f64b)

http://oca-l10n-brazil-14-0-7188f65e4167.runboat.odoo-community.org/web#action=214&model=l10n_br_fiscal.icms.relief&view_type=list&cids=1&menu_id=143

Os dados estão incorretos por conta dos espaços.

2024-04-01 17:29 UTC, rvalyi commented
ah ok, vcs tiraram os espaços, pensei que tivesse adicionado. Tudo bem desse arquivo então.

2024-04-01 17:31 UTC, rvalyi approved these changes
LGTM a respeito do código

2024-04-01 18:48 UTC, antoniospneto approved these changes
LGTM

2024-04-01 18:51 UTC, marcelsavegnago approved these changes
LGTM

2024-04-01 19:15 UTC, rvalyi commented
/ocabot merge minor

2024-04-01 19:33 UTC, merged