[14.0][FIX] l10n_br_sale: Possibilidade de incluir uma Seção ou Nota na Linha do Pedido de Vendas
OCA/l10n-brazil pull request #2866
Opened 2024-01-16 18:26 UTC by mbcosta

The possibility of include a Section or Note in Sale lines when Sale Order has Fiscal Operation.

PR simples que resolve o issue https://github.com/OCA/l10n-brazil/issues/2863 que é a possibilidade de incluir uma Seção ou Nota na Linha do Pedido de Vendas no caso que tem Operação Fiscal ou caso internacional

![image](https://github.com/OCA/l10n-brazil/assets/6341149/c9ca923a-a4f0-484c-9da5-35d4a731d36a)

![image](https://github.com/OCA/l10n-brazil/assets/6341149/53c2d6d4-1dc0-4ed1-ba19-e412a89a9e0c)

![image](https://github.com/OCA/l10n-brazil/assets/6341149/9e75150b-3e58-4960-ad8f-34f2b73d3ac8)

![image](https://github.com/OCA/l10n-brazil/assets/6341149/fa00c434-7a9f-4c5f-9de0-3f031c1c5a91)

Para resolver coloquei no atributo de Requerido da Linha de Operação Fiscal o fiscal_operation e o product_id quando não forem Falso

![image](https://github.com/OCA/l10n-brazil/assets/6341149/c0bdc0e8-876c-431e-ba0e-0b07f0ff8f4b)

![image](https://github.com/OCA/l10n-brazil/assets/6341149/a8f41bff-a641-449b-944b-2747418286ee)

![image](https://github.com/OCA/l10n-brazil/assets/6341149/94c13347-8243-49ee-9b22-a8780097ecfe)

cc @renatonlima @rvalyi @marcelsavegnago @mileo @douglascstd @antoniospneto

2024-01-16 18:54 UTC, rvalyi requested changes
certeza se não deveria ser parent.fiscal_operation_id ? tou achando estranho ser apenas fiscal_operation_id pro required e parent.fiscal_operation_id pro invisible. Ta certo mesmo?

2024-01-16 19:06 UTC, mbcosta commented
Valeu @rvalyi alteração feita

2024-01-18 16:29 UTC, rvalyi approved these changes

2024-01-18 16:42 UTC, antoniospneto approved these changes

2024-01-18 23:42 UTC, rvalyi commented
/ocabot merge minor

2024-01-19 00:01 UTC, merged