[14.0][FIX] l10n_br_fiscal: Grupo Usuário NFe e Fiscal deve ter acesso para ver e criar Documentos Fiscais
OCA/l10n-brazil pull request #2902
Opened 2024-02-02 18:01 UTC by mbcosta

Group User NFe and Fiscal should has access to create Fiscal Documents.

PR simples, hoje se o usuário está no Grupo de Usuário NFe ou Fiscal ele não consegue criar ou mesmo acessar uma NFe, isso está ocorrendo porque o objeto l10n_br_fiscal.subsequent_document estava sem o acesso para esses grupo e no caso do l10n_br_fiscal.document e l10n_br_fiscal.document_line o acesso era 1,0,0,0 mas é preciso ser 1,1,1,0 para que esse Grupo possa gerar os Documentos Fiscais, já que não faz muito sentido que o usuário que vai criar um Documento Fiscal deva ter permissão de Gerente/Manager

![image](https://github.com/OCA/l10n-brazil/assets/6341149/663ee0ef-1091-4585-aef2-8a134fd53720)

![image](https://github.com/OCA/l10n-brazil/assets/6341149/75c27fa5-c4ad-41f5-98b7-e3bd3d526d51)

Acessa o account.move mas não o Documento Fiscal

![image](https://github.com/OCA/l10n-brazil/assets/6341149/6d691f1a-588a-4878-baf7-abe3b8b338c6)

![image](https://github.com/OCA/l10n-brazil/assets/6341149/7820b7df-f751-40db-b8aa-98e75de2e27f)
 
Tem um erro pendente de solução, ao clicar em algum dos Painéis

![image](https://github.com/OCA/l10n-brazil/assets/6341149/8eba850e-f7d5-4110-9d0d-ed89e90dba14)

Esse último pode ser contornado com esse PR porque é possível ir pelo Menu.

Também alterei a permissão do Grupo Gerente/Manager no objeto l10n_br_fiscal.document_type de 1,0,0,0 para 1,1,1,1 esse grupo até onde entendo deve ter o acesso total a todos os objetos, acredito que foi apenas um erro mas talvez existe um motivo para isso, alguém saberia dizer?

cc @renatonlima @rvalyi @marcelsavegnago @mileo

2024-02-02 18:49 UTC, antoniospneto approved these changes

2024-02-03 15:32 UTC, renatonlima commented
@mbcosta 

Na verdade a permissão do Fiscal Document Type for Manager não deveria ser alterada, no módulo l10n_br_fiscal além das permissões Fiscal User e Fiscal Manager, existe uma permissão que se chama "Fiscal Maintenance Data" que tem permissão para editar as tabelas fiscais como Document Type, CFOP, CST, CNAE, o objetivo dessa permissão é controlar melhor a edição das tabelas fiscais e não permitir que os  Fiscal User e Fiscal Manager alterem acidentalmente nenhuma tabela fiscal. O Fiscal Maintenance Data já tem permissão para editar o Document Type https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_fiscal/security/ir.model.access.csv#L41

2024-02-03 15:35 UTC, renatonlima requested changes
A alteração dessa permissão pode ser revertida, o grupo Fiscal Maintenance Data já tem essa permissão, os grupos Fiscal User e Fiscal Manager não devem ter permissão de alteração dos dados fiscais só o Fiscal Maintenance Data como meu comentário anterior explica.

2024-02-05 19:28 UTC, mbcosta commented
obrigado pela revisão e explicação @renatonlima , removi a alteração no Fiscal Document Type for Manager, agora tem apenas a permissão para o l10n_br_fiscal.subsequent_document e a alteração do l10n_br_fiscal.document e l10n_br_fiscal.document_line o acesso era 1,0,0,0 mas é preciso ser 1,1,1,0

2024-02-05 19:29 UTC, renatonlima approved these changes

2024-02-05 20:01 UTC, renatonlima commented
@mbcosta,

Você consegue fazer o port desses commits (via cherry-pick) para as branches 15.0 e 16.0?

2024-02-05 20:02 UTC, renatonlima commented
/ocabot merge minor

2024-02-05 20:18 UTC, merged

2024-02-05 20:38 UTC, mbcosta commented
@renatonlima port feito para a 15 https://github.com/OCA/l10n-brazil/pull/2909 e 16 https://github.com/OCA/l10n-brazil/pull/2910