[16.0][MIG][l10n_br_purchase]
OCA/l10n-brazil pull request #2912
Opened 2024-02-06 02:39 UTC by rvalyi

depende de: https://github.com/OCA/l10n-brazil/pull/2865
é construído a partir do PR da migração do l10n_br_purchase para a v15: https://github.com/OCA/l10n-brazil/pull/2817

2024-02-09 13:48 UTC, rvalyi commented
/ocabot migration l10n_br_purchase

2024-03-24 05:28 UTC, rvalyi commented
pelo menos desde que eu fiz depender do PR https://github.com/OCA/l10n-brazil/pull/2974 instala no Runboat. Agora é so ir acertando os testes...
A maioria que não passa é relacionado a necessidade de migrar o compute_amount no PR do l10n_br_account https://github.com/OCA/l10n-brazil/pull/2865

2024-08-23 06:42 UTC, rvalyi commented
@renatonlima @marcelsavegnago @antoniospneto @mbcosta ficou pronto para revisao

2024-08-27 16:00 UTC, rvalyi commented
@renatonlima @marcelsavegnago @antoniospneto @mbcosta 
eu tinha me embanado na sexta mas agora sim ficou pronto para revisao

2024-08-27 16:15 UTC, marcelsavegnago commented
@douglascstd @WesleyOliveira98 podem revisar por favor ? na duvida de como deve ficar os totais e lancamentos contábeis, sugiro fazer no runboat da 14.0 e comparar com o runboat da PR.

2024-08-27 19:12 UTC, WesleyOliveira98 approved these changes
LGTM

2024-08-27 20:50 UTC, douglascstd requested changes
[FUNCTIONAL REVIEW]

## Testes realizados:
### Compra de serviço com retenção (avaliar se os impostos são calculados corretamente e o valor financeiro faz o calculo correto) - CORREÇÃO
![image](https://github.com/user-attachments/assets/a21db455-1a3d-448e-8f7f-4012c472b625)
Não foi possível criar fatura pela PO, pois o lançamento parece estar incorreto:
![image](https://github.com/user-attachments/assets/d2a632b5-5a55-4c0b-b87f-1baf2e80fba4)

### Inclusão de Frete, Seguro e Outros Custos - **OK**
![image](https://github.com/user-attachments/assets/9446c347-de9e-4b80-8dc7-dd8f62130acd)
![image](https://github.com/user-attachments/assets/0f23497d-8a40-4e88-8a99-136cd69dc6f6)

### Tentativa de Criar uma Nota nas linhas do pedido - **CORREÇÃO**
![image](https://github.com/user-attachments/assets/1b5f6577-41da-4a0b-9e4e-d78bc279108f)
Erro, por necessitar de Operação Fiscal. e o Formulário parece estar completo com informações de imposto, o que na v14 não aparece.
Na v14 funciona:
![image](https://github.com/user-attachments/assets/7e536a4d-9153-42fc-9bdb-a538f6ced33a)

### Compra de produto com IPI - CORREÇÃO
![image](https://github.com/user-attachments/assets/10b03ebe-8ee0-4a8c-8fe1-a8d2385dce80)
![image](https://github.com/user-attachments/assets/43ff75a6-e693-49b2-8e10-bee7c168de5b)
![image](https://github.com/user-attachments/assets/1619808d-c8e8-4fe8-a50d-9e075849adbb)
![image](https://github.com/user-attachments/assets/cbb5c77b-be3c-47a0-ae7d-20cddf1161ed)

2024-08-28 14:04 UTC, antoniospneto approved these changes
valeu @rvalyi

2024-09-06 14:35 UTC, marcelsavegnago approved these changes

2024-09-06 16:28 UTC, antoniospneto commented
@rvalyi depois faz um rebase pra rodar o pre-commit atualizado?

2024-09-06 17:19 UTC, rvalyi commented
> @rvalyi depois faz um rebase pra rodar o pre-commit atualizado?

feito. Ajustei o pre-commit tb.

2024-09-06 17:23 UTC, antoniospneto commented
/ocabot merge nobump

2024-09-06 17:41 UTC, merged