[IMP] l10n_br_cnpj_search:
OCA/l10n-brazil pull request #2913
Opened 2024-02-06 03:01 UTC by CristianoMafraJunior

Criação de um wizard para alteração dos campos de contatos, a criação desse wizard visa simplificar e agilizar o processo de alteração dos campos feita pela pesquisa do CNPJ.
Também foi mudado os **test_sefaz** e **test_sintegra** agora usando a biblioteca do **unittest.mock**

![image](https://github.com/OCA/l10n-brazil/assets/142639425/03966fa1-5364-4b2a-a293-2fcb310ec44f)

2024-02-06 10:24 UTC, felipemotter approved these changes
O Cristiano faz parte da nossa equipe, toda a PR foi feita e revisada por mim e pelo @antoniospneto.

2024-02-06 11:02 UTC, antoniospneto commented
Obrigado pelo excelente trabalho realizado!

Gostaria de aproveitar esta oportunidade para apresentar o @CristianoMafraJunior que está começando agora e sendo treinado pela nossa equipe da Engenere. 

Esta melhoria atende a uma necessidade que tínhamos há algum tempo, e se mostrou uma excelente oportunidade de tarefa para o Cristiano. O objetivo é proporcionar ao usuário um maior controle sobre as informações e dados, permitindo-lhes revisar e auditar os dados recebidos do mundo externo. Agora, os usuários também podem optar por excluir dados específicos antes de atualizá-los no sistema do parceiro. Isso é particularmente útil em situações como a atualização de e-mails, onde os dados do cadastro nacional nem sempre refletem os que de fato utilizamos para comunicação com os parceiros. 

Por favor, me deixem saber se acham que essa funcionalidade é útil para a localização.

2024-02-06 16:47 UTC, douglascstd approved these changes
[APPROVED] FUNCTIONAL REVIEW

Testado no Runboat o funcionamento com CNPJ e simulado erros de digitação e troca para Individuo, em todas funcionou corretamente.

2024-02-06 17:35 UTC, antoniospneto approved these changes

2024-02-06 17:52 UTC, mileo commented
Acho que podemos fazer diferente, o que vocês acham de colocar o valor anterior ao lado do novo?

2024-02-06 17:52 UTC, mileo requested changes
Conforme comentário acima.

2024-02-06 17:55 UTC, mileo commented
Vejam como é feito em outro sistema:

![image](https://github.com/OCA/l10n-brazil/assets/1975978/bec21c9f-238d-4b8d-9d65-f50a88e56c44)

2024-02-06 19:25 UTC, antoniospneto commented
> Acho que podemos fazer diferente, o que vocês acham de colocar o valor anterior ao lado do novo?

@mileo a ideia é legal mas acho que isso poderia ficar para uma segunda etapa, talvez deixar uma issue de sugestão em aberto.

2024-02-07 09:10 UTC, mileo commented
> > Acho que podemos fazer diferente, o que vocês acham de colocar o valor anterior ao lado do novo?
> 
> @mileo a ideia é legal mas acho que isso poderia ficar para uma segunda etapa, talvez deixar uma issue de sugestão em aberto.

Será que ficaria legal no wizard aparecer somente os campos com alteração?

2024-02-07 11:04 UTC, felipemotter commented
Opa @mileo a gente também acha que seriam alterações legais, porém a gente está com outras atividades na frente e não tem previsão de voltar a aprofundar essa melhoria. Por isso acredito que seria legal deixar essas ideias em uma issue para caso haja alguém interessado em implementar.

Nós acreditamos que esta proposta esta bem madura e já é um avanço considerável para a forma que está hoje(que na época também já era um avanço). Caso haja algum bug, inconsistência ou retrocesso que tenha passado em branco, podemos corrigir, mas tirando isso fica difícil para nós.

2024-02-07 15:47 UTC, renatonlima requested changes
Só uma cosia, seria interessante deixar o CEP com a formatação atual #####-### ao invés de ##.###-###

2024-02-07 15:48 UTC, renatonlima commented
Pessoal,

Tirando a formação do CEP, eu acho interessante o PR, acho que dá para ser implementada e depois ser feito a melhoria proposta pelo @mileo

2024-02-07 17:10 UTC, mileo approved these changes

2024-02-08 11:57 UTC, CristianoMafraJunior commented
@renatonlima 

Alteração feita para formatação do CEP no padrão atual #####-###, muito grato pela revisão. 


![teste](https://github.com/OCA/l10n-brazil/assets/142639425/6c0a64b2-f762-4af7-ba15-1fe9ea55c7a8)

2024-02-08 11:58 UTC, renatonlima approved these changes

2024-02-08 11:59 UTC, renatonlima commented
/ocabot merge minor

2024-02-08 12:31 UTC, merged