[14.0][REF] l10n_br_nfe: aprimoramento nos testes
OCA/l10n-brazil pull request #2931
Opened 2024-02-29 00:50 UTC by antoniospneto

Proposta de melhoria na qualidade dos testes nos módulo `l10n_br_nfe`.

- O mock agora fica em um nivel mais a baixo, diretamente nas respostas das requisições TTP/HTTPS.
- Movido os xmls das respostas soap para arquivos, para facilitar a leitura para humanos :)

2024-02-29 11:09 UTC, antoniospneto commented
Pessoal, essa pr faz parte de um série de melhorias que pretendo propor o módulo l10n_br_nfe, para garantir que não tenha regressões comecei melhorando um pouco a qualidade dos testes.

Para facilitar a criação dos mock concentrei toda a lógica de criação no arquivo mock_utils.py
Com isso, sempre que precisar fazer o mock de uma resposta do webservice da nfe é só chamar o decorador costumizado nfe_mock e passar como pareamento uma lista de operações com o path do arquivo que contém a resposta mock para tal operação.

2024-03-02 21:20 UTC, rvalyi requested changes
ficou top obrigado @antoniospneto !
Apenas comentei do detalhe do license header num arquivo e tb como vc já fez algumas outras contribuições importantes no modulo l10n_br_nfe como o warning com os erros XML, seria legitimo vc se adicionar como contribuidor no arquivo readme/CONTRIBUTORS.rst

Com isso irei aprovar.

2024-03-02 21:20 UTC, rvalyi commented on l10n_br_nfe/tests/mock_utils.py
> +import os
pode adicionar o seu copyright e a licença aqui?

2024-03-04 11:50 UTC, felipemotter approved these changes

2024-03-04 13:18 UTC, marcelsavegnago approved these changes

2024-03-04 16:41 UTC, antoniospneto commented
@rvalyi feito! 

Obrigado pela revisão e pela consideração.

2024-03-04 16:57 UTC, rvalyi approved these changes

2024-03-04 17:08 UTC, rvalyi commented
completando: o @antoniospneto tb ajudou muito com os testes na hora da migração do generateDS pro xsdata que foi um refator bem importante ( https://github.com/OCA/l10n-brazil/pull/2371 ) ...

2024-03-04 17:13 UTC, rvalyi commented
/ocabot merge patch

2024-03-04 17:29 UTC, merged