[14.0] Melhorias na transmissão da NFE
OCA/l10n-brazil pull request #2945
Opened 2024-03-08 02:05 UTC by antoniospneto

### Trabalho em progresso.

Melhorias propostas nessa PR:

1) Suporte ao envio da nfe no método sincrono.

2) Melhora o processo do envio quando é assincrono. 
É possivel consultar o recibo novamente em caso de falha, os dados da nota enviada não são perdidos.

3) Implementa o wizard de consultar situação para a NF-e.

4) Mais algumas outras pequenas correções de usabilidade.

Depende das melhorias proposta nas libs externas:
nfelib: https://github.com/akretion/nfelib/pull/93
erpbrasil.edoc: https://github.com/erpbrasil/erpbrasil.edoc/pull/74

Nota: Pretendo depois quebrar em PRs menores.

2024-03-08 12:55 UTC, mileo commented
Muito bom!

2024-03-11 12:51 UTC, antoniospneto commented
Pessoal, ontem eu organizei a PR https://github.com/erpbrasil/erpbrasil.edoc/pull/71 e está pronta para revisão, que puder revisar lá eu agradeço, depois de aprovado as PRs no erpbrasil.edoc vou dar continuidade nos trabalhos aqui, valeu!

2024-05-10 15:12 UTC, rvalyi commented
@antoniospneto entraram todas dependencias no nfelib e erpbrasil.edoc, se puder atualizar o PR para a gente ver melhor como fica aqui seria top...

2024-05-10 15:19 UTC, rvalyi requested changes

2024-05-10 15:19 UTC, rvalyi commented on l10n_br_nfe/models/document.py
> +        """
é top a gente começar a se policiar de botar mais docstrings no projeto. Porem é bom a gente faze-lo em ingles como no restante da OCA e até como vc fez nos outros docstrings que vc adicionou neste PR....

2024-05-10 18:23 UTC, antoniospneto commented
os testes estão passando, mas eu vou adicionar mais alguns para evitar regressões e melhorar a cobertura dos testes
vou também quebrar os commits um pouco pra ficar mais explicativo

2024-05-10 18:24 UTC, antoniospneto commented on l10n_br_nfe/models/document.py
> +        """
Feito, valeu!

2024-05-15 14:39 UTC, antoniospneto commented
substituido por #3081

2024-05-15 14:39 UTC, closed without merging