[WIP] Calculo do Crédito de ICMS ST
OCA/l10n-brazil pull request #2993
Opened 2024-04-03 01:02 UTC by mileo

2024-07-08 20:48 UTC, marcelsavegnago commented
@mileo pode fazer um rebase por favor ?

2024-07-08 22:17 UTC, mileo commented
> @mileo pode fazer um rebase por favor ?

feito

2024-07-30 13:31 UTC, mileo commented
@marcelsavegnago @rvalyi @renatonlima @antoniospneto podem revisar plz?

2024-07-30 16:34 UTC, antoniospneto commented
Qual seria o objetivo desses dois campos na linha do documento?

2024-07-31 10:54 UTC, mileo commented
> Qual seria o objetivo desses dois campos na linha do documento?

O crédito do ICMSST entra como uma retenção.

2024-07-31 11:54 UTC, antoniospneto approved these changes
As alterações me parecem tudo ok, mas confesso que não sou especialista em  substituição tributária e não tenho nenhum caso de uso para homologar a funcionalidade, então seria bom aguardar a aprovação do @renatonlima  e @marcelsavegnago tbm.

2024-08-06 15:06 UTC, marcelsavegnago commented
@douglascstd consegue validar ?

2024-08-06 15:21 UTC, WesleyOliveira98 approved these changes
LGTM

2024-08-12 12:50 UTC, marcelsavegnago approved these changes
LGTM

2024-08-13 13:22 UTC, mileo commented
/ocabot merge minor

2024-08-13 13:24 UTC, mileo commented
Vai precisar de um rebase pra entender o pq os testes estão falhando, cancelei o merge.

2024-08-13 13:30 UTC, renatonlima requested changes
Não reveria ter um percentual de retenção no fiscal.tax, ao invés disso deveria ter um imposto icmsst_wh para poder ser usado nos tax.definition

2025-10-12 12:13 UTC, closed without merging