[14.0][REF][POC][l10n_br_fiscal][l10n_br_fiscal_edi] l10n_br_fiscal_edi extraction from l10n_br_fiscal 2/2
OCA/l10n-brazil pull request #3012
Opened 2024-04-12 02:41 UTC by rvalyi

WIP

2024-05-24 21:59 UTC, rvalyi commented
Pessoal, dei um rebase porque o PR do @felipemotter https://github.com/OCA/l10n-brazil/pull/3090 matou a metade dos workarounds dessa PR (ver detalhe dos commits). Nisso a extração do l10n_br_fiscal_edi ta bem facil agora...

2024-07-29 17:13 UTC, renatonlima commented
Olá pessoal,

Há algum tempo atrás eu havia trabalhado para melhorar o suporte aos documentos fiscais principalmente os eletrônicos para implementar algumas funcionalidades faltantes como o MDE, DFE e demais eventos dos documentos fiscais, para isso é necessário primeiro fazer uma organização na estrutura base dos documentos fiscais, porque os objetos e heranças dos documentos fiscais devem, ser simplificado, eu fiz um diagrama atualmente dos objetos dos documentos fiscais:

```mermaid
classDiagram
    FiscalDocumentEletronic <|-- FiscalDocumentWorkflow
    FiscalDocument <|-- FiscalDocumentEletronic
    FiscalDocumentMixin <|-- FiscalDocumentMixinFields
    FiscalDocumentMoveMixin <|-- FiscalDocumentMixinMethods
    FiscalDocumentMixin <|-- FiscalDocumentMixinMethods
    FiscalDocument <|-- FiscalDocumentMoveMixin
    FiscalDocument <|-- FiscalDocumentMixinFields
    FiscalDocument <|-- MailThread
    class FiscalDocumentWorkflow{
        state_edoc = fields.Selection
        state_fiscal = fields.Selection
        cancel_reason = fields.Char
        correction_reason = fields.Char()
        +action_document_confirm()
        +action_document_send()
        +document_back2draft()
        +action_document_back2draft()
        +action_document_cancel()
        +action_document_invalidate()
        +action_document_correction()
    }
    class FiscalDocumentEletronic {
        issuer = fields.Selection
        status_code = fields.Char
        status_name = fields.Char
        status_description = fields.Char  
        authorization_event_id = fields.Many2one
        authorization_date = fields.Datetime
        authorization_protocol = fields.Char
        send_file_id = fields.Many2one
        authorization_file_id = fields.Many2one
        cancel_event_id = fields.Many2one
        cancel_date = fields.Datetime
        cancel_protocol_number = fields.Char
        cancel_file_id = fields.Many2one
        invalidate_event_id = fields.Many2one
        invalidate_date = fields.Datetime
        invalidate_protocol_number = fields.Char
        invalidate_file_id = fields.Many2one
        document_version = fields.Char
        is_edoc_printed = fields.Boolean
        file_report_id = fields.Many2one
        +serialize()
        +view_xml()
        +make_pdf()
        +view_pdf()

    }
```

Alguns objetos e heranças podem ser simplificados eu  comecei a fazer esse trabalho aqui na branch [14.0-rfc-fiscal-document-events](https://github.com/akretion/l10n-brazil/tree/14.0-rfc-fiscal-document-events) onde eu também fiz melhorias na gestão da comunicação com a Sefaz e suporte a outros webservice ainda não implementados no Odoo. Eu vou fazer um rebase e continuar esse trabalho.

cc @rvalyi @antoniospneto @marcelsavegnago @mileo @mbcosta

2024-08-10 19:59 UTC, rvalyi commented
fiz um rebase. Tou agora trabalhando em mover o document_workflow.py tambem pro l10n_br_fiscal_edi e ajustando os testes.
Com isso vamos poder aliviar uns 1500 linhas do l10n_br_fiscal.

Extremamente importante a gente limpar isso antes de aceitar qualquer coisas a mais no l10n_br_fiscal ou antes de botar projetos em prod na v16... Postergar de limpar a bunda sempre vai custar muito mais la na frente do que fazer agora. Os extrapolos com isso ja foram muito alem de qualquer coisa aceitavel na OCA.

cc @renatonlima @mbcosta @antoniospneto @felipemotter @marcelsavegnago

2024-08-14 00:05 UTC, rvalyi commented
passando os testes com o document_workflow.py agora sendo parte do l10n_br_fiscal_edi. As funcionalidades foram quase todas preservadas. Tou vendo agora alguns detalhes mais cosmeticos ou para bater exactamente o mesmo test coverage....

cc @renatonlima @mbcosta @antoniospneto @felipemotter @marcelsavegnago

2024-08-31 21:29 UTC, antoniospneto reviewed
@rvalyi

No novo módulo `l10n_br_fiscal_edi`, acredito que o conteúdo da classe abstrata `DocumentWorkflow` poderia ser integrado diretamente dentro da classe `Document`. Como apenas a classe `Document` herda `DocumentWorkflow`, a separação em uma classe abstrata parece adicionar uma camada de complexidade desnecessária. o que acha?

2024-08-31 21:45 UTC, rvalyi commented
Eu acho que pode ser. Porem neste primeiro momento tentei fazer meio que o passo minimo ainda que extraindo o módulo, por isso nao tentei fazer melhoria nenhuma. Talvez seria melhor a gente ver com calma depois esse tipo de melhoria... Porque com certeza esse codigo no edi ta longe de ser lindo pelos padrões de hoje...

2024-08-31 22:39 UTC, antoniospneto commented
> Eu acho que pode ser. Porem neste primeiro momento tentei fazer meio que o passo minimo ainda que extraindo o módulo, por isso nao tentei fazer melhoria nenhuma. Talvez seria melhor a gente ver com calma depois esse tipo de melhoria... Porque com certeza esse codigo no edi ta longe de ser lindo pelos padrões de hoje...

Entendi, certo, to testando agora em uma copia de uma base de produção, logo eu retorno com o meu feedback

2024-09-01 01:39 UTC, antoniospneto commented on l10n_br_fiscal_edi/views/document_view.xml
> +        <xpath expr="//field[@name='state_edoc']/.." position="after">
Acho que faltou apagar isso aqui

2024-09-01 01:40 UTC, antoniospneto commented on l10n_br_fiscal_edi/views/document_view.xml
> +        </xpath>
```suggestion

```
Acho que faltou apagar isso aqui

2024-09-01 04:17 UTC, antoniospneto requested changes
Propus duas correções aqui: https://github.com/akretion/l10n-brazil/pull/221

2024-09-01 11:44 UTC, rvalyi commented
valeu @antoniospneto . Na real o status_description eu tinha tirado e parece que me embananei num rebase recente e assim ele apareceu de volta. Até recentemente eu tinha uns 2 ou 3 commits a mais no PR que refletia mais detalhadamente as etapas da extração.

Porem dificultava os rebase e foi assim que me embananei. Por  isso, se vc nao ver problema vou fazer o squash do seus commits dentro do commit da extração do l10n_br_fiscal_edi, assim fica algo mais transacional tb para investigar caso der algum problema la na frente. Valeu pelos testes. Vou testar de novo aqui num banco de prod tb.

2024-09-01 22:34 UTC, rvalyi commented
@antoniospneto fiz o merge do seu PR e o merge no primeiro commit do PR assim que eu expliquei. Eu tb testei num banco de prod e deu tudo certo.

@marcelsavegnago algum posicionamento sobre o PR?

2024-09-02 13:31 UTC, antoniospneto approved these changes
Testei em uma base cópia de produção, com as ultimas melhorias mescladas aqui e nenhum erro foi encontrado.
Os módulos foram atualizados com sucesso.

Testei as operações de NF-e em homologação, transmissão de nfe, cancelamaneto, carta de correção e inutilização de número, todas ok.

Obs: não abordei nos meus testes: NFC-e e NFS-e.

Quanto a revisão do código, pelo que vi tá tudo ok, o readme ficou bem claro.
Alguma coisa pode ter passado despercebido, pois é bastante alteração, mas nada que não possa ser corrigido em seguida..

Acho que o importante é todos estarem cientes deste refactor, para que quando forem atualizar a base, atualizar com atenção e homologar os processos antes de por em produção.

Então por mim já pode rolar o merge, valeu @rvalyi, mais uma super contribuição para deixar o localização mais robusta.

2024-09-02 15:17 UTC, marcelsavegnago approved these changes

2024-09-02 15:18 UTC, marcelsavegnago commented
Bora... Quanto mais cedo enfrentar esta questão.. melhor.

2024-09-02 15:49 UTC, rvalyi commented
@renatonlima teve tempo para olhar?

2024-09-07 02:19 UTC, rvalyi commented
/ocabot merge nobump

2024-09-07 03:42 UTC, rvalyi commented
/ocabot merge nobump

2024-09-07 05:15 UTC, merged