[15.0][MIG] l10n_br_account_withholding: Migration to 15.0
OCA/l10n-brazil pull request #3023
Opened 2024-04-19 16:25 UTC by marcelsavegnago

2024-04-19 22:17 UTC, rvalyi approved these changes

2024-04-24 22:08 UTC, rvalyi requested changes
@marcelsavegnago vc poderia fazer o cherry-pick desse tb para não deixar a feature pela metade no l10n_br_account por favor https://github.com/OCA/l10n-brazil/commit/022803e804790bfd93e35edf0fbe21d4392b1c01 ?

2024-04-25 18:12 UTC, marcelsavegnago commented
> @marcelsavegnago vc poderia fazer o cherry-pick desse tb para não deixar a feature pela metade no l10n_br_account por favor [022803e](https://github.com/OCA/l10n-brazil/commit/022803e804790bfd93e35edf0fbe21d4392b1c01) ?

verdade.. puxou só os commits do módulo

2024-05-02 14:15 UTC, rvalyi commented
up @marcelsavegnago consegue matar esse?

2024-05-02 14:23 UTC, marcelsavegnago commented
> up @marcelsavegnago consegue matar esse?

Opa.. está na fila. Estava com uma prioridade alta aqui essa semana.

2024-05-02 14:39 UTC, marcelsavegnago commented
> up @marcelsavegnago consegue matar esse?

Done

2024-05-02 14:45 UTC, rvalyi requested changes
pode apenas dar um amend para dar uma incrementada minor no l10n_br_account ja que o merge vai ser nobump por causa do novo modulo? o restante ta OK para mim...

2024-05-02 14:54 UTC, marcelsavegnago commented
> pode apenas dar um amend para dar uma incrementada minor no l10n_br_account ja que o merge vai ser nobump por causa do novo modulo? o restante ta OK para mim...

Feito.. optei por um commit separado.

2024-05-02 15:45 UTC, rvalyi approved these changes
perfeito

2024-05-02 17:52 UTC, WesleyOliveira98 approved these changes
LGTM

2024-05-02 18:26 UTC, rvalyi commented
/ocabot merge nobump

2024-05-02 18:44 UTC, merged