[14.0][FIX] l10n_br_fiscal: Definir finance_move como verdadeiro para o CFOP 5124 ("Industrialização efetuada para outra empresa")
OCA/l10n-brazil pull request #3029
Opened 2024-04-22 13:13 UTC by rodmad85

[FIX] l10n_br_fiscal: Definir finance_move como verdadeiro para o CFOP 5124 ("Industrialização efetuada para outra empresa")

2024-04-22 16:32 UTC, marcelsavegnago requested changes
Faça o squash dos commits gerando apenas 1 commit por favor.

2024-04-22 18:13 UTC, mileo commented
> [FIX] l10n_br_fiscal: Definir finance_move como verdadeiro para o CFOP 5124 ("Industrialização efetuada para outra empresa")

Para fazer o squash de três commits em um único commit no Git, você pode usar o comando `git rebase` de forma interativa. Aqui estão os passos que você pode seguir:

1. **Iniciar o Rebase Interativo**:
   - Primeiro, você precisa identificar quantos commits você deseja incluir no squash. Para fazer squash dos três últimos commits, você pode usar o seguinte comando:
     ```bash
     git rebase -i HEAD~3
     ```

   Este comando abrirá um editor de texto com uma lista dos últimos três commits.

2. **Escolher os Commits para Squash**:
   - No editor de texto, você verá uma lista de commits, cada um começando com a palavra `pick`. Para fazer o squash dos commits, você deve deixar o primeiro commit da lista como `pick` e mudar a palavra `pick` para `squash` ou `s` nos dois commits subsequentes. Por exemplo:
     ```
     pick e3a1b35 Mensagem do commit mais antigo
     squash 4f3e6de Mensagem do segundo commit
     squash b2d3fec Mensagem do último commit
     ```

   Aqui, `e3a1b35`, `4f3e6de` e `b2d3fec` são exemplos de hashes de commits. Você deverá ver os hashes reais dos seus commits.

3. **Salvar e Fechar o Editor**:
   - Salve as alterações e feche o editor. Git agora começará o processo de rebase, e se os commits selecionados para squash não tiverem conflitos com outros commits, ele pedirá que você consolide as mensagens de commit.

4. **Editar a Mensagem de Commit**:
   - Git abrirá novamente o editor de texto para que você possa editar a mensagem de commit final. Por padrão, ele incluirá todas as mensagens de commit dos commits squashed, mas você pode editar para refletir uma nova mensagem que descreva adequadamente todas as mudanças.
   - Salve e feche o editor após finalizar a mensagem de commit.

5. **Concluir o Rebase**:
   - Uma vez que o editor é fechado, o Git finaliza o rebase. Se tudo estiver correto, seus três commits anteriores serão combinados em um único commit.

6. **Push com Force**:
  - Faça push com Force para a mesma branch: git push -f ....

2024-04-22 19:02 UTC, marcelsavegnago commented
> > [FIX] l10n_br_fiscal: Definir finance_move como verdadeiro para o CFOP 5124 ("Industrialização efetuada para outra empresa")
> 
> Para fazer o squash de três commits em um único commit no Git, você pode usar o comando `git rebase` de forma interativa. Aqui estão os passos que você pode seguir:
> 
> 1. **Iniciar o Rebase Interativo**:
>    
>    * Primeiro, você precisa identificar quantos commits você deseja incluir no squash. Para fazer squash dos três últimos commits, você pode usar o seguinte comando:
>      ```shell
>      git rebase -i HEAD~3
>      ```
>    
>    Este comando abrirá um editor de texto com uma lista dos últimos três commits.
> 2. **Escolher os Commits para Squash**:
>    
>    * No editor de texto, você verá uma lista de commits, cada um começando com a palavra `pick`. Para fazer o squash dos commits, você deve deixar o primeiro commit da lista como `pick` e mudar a palavra `pick` para `squash` ou `s` nos dois commits subsequentes. Por exemplo:
>      ```
>      pick e3a1b35 Mensagem do commit mais antigo
>      squash 4f3e6de Mensagem do segundo commit
>      squash b2d3fec Mensagem do último commit
>      ```
>    
>    Aqui, `e3a1b35`, `4f3e6de` e `b2d3fec` são exemplos de hashes de commits. Você deverá ver os hashes reais dos seus commits.
> 3. **Salvar e Fechar o Editor**:
>    
>    * Salve as alterações e feche o editor. Git agora começará o processo de rebase, e se os commits selecionados para squash não tiverem conflitos com outros commits, ele pedirá que você consolide as mensagens de commit.
> 4. **Editar a Mensagem de Commit**:
>    
>    * Git abrirá novamente o editor de texto para que você possa editar a mensagem de commit final. Por padrão, ele incluirá todas as mensagens de commit dos commits squashed, mas você pode editar para refletir uma nova mensagem que descreva adequadamente todas as mudanças.
>    * Salve e feche o editor após finalizar a mensagem de commit.
> 5. **Concluir o Rebase**:
>    
>    * Uma vez que o editor é fechado, o Git finaliza o rebase. Se tudo estiver correto, seus três commits anteriores serão combinados em um único commit.
> 6. **Push com Force**:
> 
> * Faça push com Force para a mesma branch: git push -f ....

@mileo depois ou consolidar estas instruções em algum lugar :smile:

2024-04-23 23:03 UTC, rvalyi approved these changes
LGTM

2024-04-24 12:33 UTC, antoniospneto commented
> LGTM

acho que só falta o @rodmad85 fazer o squash dos commits

2024-04-24 13:03 UTC, rvalyi commented
@rodmad85 vc consegue fazer ou quer que a gente cuida de refazer seu PR?

2024-04-24 13:21 UTC, rodmad85 commented
Fiz o processo que me falaram do squash, mas daí sumiu aqui no pycharm e não consegui colocar novamente. Se puderem me ajudar nessa, da próxima eu tento ajustar antes de solicitar a PR.

2024-04-24 16:16 UTC, rvalyi commented
Eu fui para te explicar mas até no meu computador local eu teve que dar rebase continue depois do squash ai pensei que ia te perder e optei por refazer o PR aqui [rodmad85](https://github.com/rodmad85)](https://github.com/OCA/l10n-brazil/pull/3036)

Basicamente eu dei um rebase -i no primeiro do 3 commits:
`git rebase -i 90401ebd1011959cbb29d02017b3ec23bd27e676`

e depois eu dei um squash dos 2 primeiros commits:
![2024-04-24_13-07_1](https://github.com/OCA/l10n-brazil/assets/16926/7cef20c0-b3fb-444a-a79e-8fe7da670153)

se liga no git e nos padrões da OCA que vai acabar te servindo: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#git

2024-04-24 16:16 UTC, closed without merging