[14.0][WIP] l10n_br_account: price_total and price_subtotal
OCA/l10n-brazil pull request #3037
Opened 2024-04-24 20:27 UTC by marcelsavegnago

Esta PR trata a questão dos campos price_unit das linhas que não são do tipo invoice. Porém, nesta PR ainda não é resolvido o valor da coluna price_total da linha da fatura #3035

2024-05-08 14:44 UTC, marcelsavegnago commented
Pessoal, esta PR resolve os calculos do price_total e price_subtotal. Sugiro testar funcionalmente tanto criando diretamente um account.move ou através de pedidos de venda, compra e picking.

2024-05-08 14:45 UTC, marcelsavegnago commented
@rvalyi foi ótimo a inclusão dos testes que vc adicionou um tempo atrás no l10n_br_account. Isso tem ajudado muito a identificar os impactos de qq mudança no módulo. Parabens.

2024-05-09 00:48 UTC, felipemotter commented
@marcelsavegnago consegue explicar melhor como chegar no erro? isso seria, como reportado na issue, quando altera o ipi de uma linha?

2024-05-09 01:16 UTC, rvalyi commented
@felipemotter a ajuda de vc nessa revisão vai ser bem util...

2024-05-09 12:17 UTC, marcelsavegnago commented
@felipemotter O primeiro problema que identifiquei foi que os campos price_total e price_subtotal não estavam sendo preenchidos em todas as linhas do lançamento contábil. Fora isso, no create do account.move os métodos de calculo do preço total e subtotal são chamados em várias situações não existe o self, nem contexto e nem nada.

Tem alguns prints aqui 
https://github.com/OCA/l10n-brazil/pull/3030#issuecomment-2073222424
https://github.com/OCA/l10n-brazil/pull/3030#issuecomment-2073302139

E sim, sobre o valor do price_total do item da fatura, sim um exemplo é o da issue #3035 

Se precisar de mais informações me diga.

2024-05-09 12:23 UTC, marcelsavegnago commented
https://github.com/OCA/l10n-brazil/issues/3034

2024-05-09 14:51 UTC, rvalyi commented
olhei rapidamente. Na parte tecnica não vi nada de chocante até agora. Agora é bom analisar fundo a questão funcional...

2024-05-09 22:40 UTC, felipemotter commented
Gente, prometo que amanha pego pra testar, se é o que estou pensando, ja havíamos notado esse problema, mas nunca fui a fundo do que estava gerando.

2024-05-10 11:48 UTC, douglascstd requested changes
[FUNCTIONAL REVIEW]

Verificação da alteração de IPI na linha da fatura de compras - OK conforme esperado
https://github.com/OCA/l10n-brazil/assets/20867090/1ef63f20-0a15-4d68-a450-19cedb7584d7

Não sei se teve interferência desta PR, mas ao salvar a fatura, os impostos selecionados na linha da fatura são apagados, ficando os registros vazios:
https://github.com/OCA/l10n-brazil/assets/20867090/2559f8b9-4244-4e3a-a2b6-6c6cc9e0ea59

Esse foi o teste no Runboat da OCA:  O comportamento de apagar os registros de impostos na linha não é verificado:
https://github.com/OCA/l10n-brazil/assets/20867090/e082dc08-ebdb-4152-bc1c-49064ba99a85

Outra característica é:
Se Salvar a fatura antes de Postar, os lançamentos de impostos permanecem no lançamento de diário
Mas se Postar (sem salvar antes), o lançamento de diário não aparecem impostos
Nas duas situações, os campos de impostos ficam vazios na linha da fatura.

Verificado campos preenchidos - 
OCA - l10n_br
![image](https://github.com/OCA/l10n-brazil/assets/20867090/052466bb-5fb7-4774-abb4-f09876e1cf0d)

Neste PR:
![image](https://github.com/OCA/l10n-brazil/assets/20867090/ac69a673-1be5-42ab-a16d-66609e963cd6)

2024-05-10 21:14 UTC, felipemotter approved these changes
A princípio nenhum retrocesso, a questão do Douglas de sumir os impostos e lançamentos de imposta não consegui simular.

2024-05-10 21:16 UTC, marcelsavegnago commented
> A princípio nenhum retrocesso, a questão do Douglas de sumir os impostos e lançamentos de imposta não consegui simular.

Este problema reportado pelo douglas está sendo tratado na PR 3076... mesclando ela eu faço o rebase aqui.. se puder priorizar a 3076 agora eu agradeço.

2024-05-16 16:23 UTC, marcelsavegnago commented
@douglascstd o problema que estava acontecendo foi resolvido na PR #3077. Agradeço se puder revisar novamente.

2024-05-16 21:23 UTC, rvalyi commented
Pessoal, comecei a revisar um pouco, todo cuidado é pouco...

Uma coisa positiva que eu vi é que os valores price_unit, price_subtotal e price_total dos tax_vals* e term_vals* nos testes ficaram com os valores do debito ou do credito da linha, assim como esta nos testes originais no modulo account:
https://github.com/odoo/odoo/blob/14.0/addons/account/tests/test_account_move_out_invoice.py#L71

**Nisso eu estou OK com o diff na pasta l10n_br_account/tests** e novamente nada me chocou nas outras partes apesar que eu precisar revisar mais fundo.

Eu pretendo revisar as outras coisas em breve, mas é bom que as pessoas competentes revisam mesmo...

2024-05-17 00:18 UTC, rvalyi approved these changes
OK para mim, parabéns pelo trabalho!

2024-05-17 10:31 UTC, mileo approved these changes

2024-05-17 11:56 UTC, rvalyi commented
/ocabot merge minor

2024-05-17 12:12 UTC, merged