[FIX] less to scss
OCA/l10n-brazil pull request #3060
Opened 2024-05-01 18:05 UTC by mileo

Ao mantermos o less faz se necessário a instalação dos pacotes.

npm@9.6.4
less

2024-05-01 18:13 UTC, rvalyi requested changes
@mileo seria melhor fazer então o backport desse commit da 16.0 https://github.com/OCA/l10n-brazil/commit/c09799698e4e69c09342384723b103323d1f8312 e inclusive ter o mesmo nome form.scss padronizado.

2024-05-01 18:17 UTC, mileo commented
> @mileo seria melhor fazer então o backport desse commit da 16.0 [c097996](https://github.com/OCA/l10n-brazil/commit/c09799698e4e69c09342384723b103323d1f8312) e inclusive ter o mesmo nome form.scss padronizado.

Boa não tinha visto

2024-05-01 21:33 UTC, rvalyi approved these changes

2024-05-02 00:37 UTC, marcelsavegnago approved these changes

2024-05-02 11:44 UTC, rvalyi commented
/ocabot merge minor

2024-05-02 11:53 UTC, merged