[14.0][REF] Impressão da DANFE a partir da lib BrazilFiscalReport
OCA/l10n-brazil pull request #3068
Opened 2024-05-07 02:12 UTC by antoniospneto

Adiciona opção de imprimir a DANFE a partir da biblioteca [brazilfiscalreport](https://github.com/Engenere/BrazilFiscalReport)

A biblioteca a ser usada pode ser definido na configuração da empresa:
![image](https://github.com/OCA/l10n-brazil/assets/634278/e1be03c6-ba1e-44bc-8259-435fef012c92)
ainda é possivel configurar para imprimir a DANFE usando o jeito antigo (erpbrasil usando o libreoffice) é bom ter essa opção até que se confirme que a DANFE no BrazilFiscalReport se confirme estavel.

Agora é possivel também imprimir a DANFE usando os menus nativos de relatórios do Odoo:
![image](https://github.com/OCA/l10n-brazil/assets/634278/b390f770-afae-474b-b3d2-90734cdcf686)
Foi implementando tando no modelo `account.move` quanto `l10n_br_fiscal.document`

Exemplos de DANFE geradas podem ser vistas no repositório da biblioteca: https://github.com/Engenere/BrazilFiscalReport/tree/main/tests/generated/danfe

2024-05-07 12:35 UTC, felipemotter commented
Entrando em prod no nosso cliente piloto.

2024-05-07 12:44 UTC, rvalyi commented
@antoniospneto, @felipemotter 
hoje nem temos DANFE na CI porque a gente evita baixar o Libreoffice a cada push para nao abusar com o planeta. Nisso não seria melhor ja botar esse novo engine como padrão nas 3 empresas de demo? Eu acho que ajudaria quem avalia a localização no Runboat a ter uma ideia melhor...

Recentemente esse ponto confundiu o @rodmad85 por examplo e a gente teve que gastar tempo para re-explicar porque nao tem DANFE na CI...

2024-05-07 12:52 UTC, antoniospneto commented
> @antoniospneto, @felipemotter hoje nem temos DANFE na CI porque a gente evita baixar o Libreoffice a cada push para nao abusar com o planeta. Nisso não seria melhor ja botar esse novo engine como padrão nas 3 empresas de demo? Eu acho que ajudaria quem avalia a localização no Runboat a ter uma ideia melhor...
> 
> Recentemente esse ponto confundiu o @rodmad85 por examplo e a gente teve que gastar tempo para re-explicar porque nao tem DANFE na CI...

Então agora temos DANFE no runboat :D
![image](https://github.com/OCA/l10n-brazil/assets/634278/93c25890-3c0c-46a0-8850-f35a3af872e4)
Já vem como padrão o brazilfiscalreport, o adminsitrador do sistema tem a opção de mudar caso queira.

2024-05-07 13:01 UTC, mileo commented
Eu gosto bastante da ideia de tirar o peso do libre office e também a complexidade de manutenção(diffs de PRs) do py3o.

Como esta é uma lib importante eu vejo com bom olhos colocar ela sobe o guarda-chuva da organização do erpbrasil, percebo que integrar esta lib ao erpbrasil facilitaria o acesso e uso das dependências da localização, simplificando a manutenção e a colaboração entre as equipes.

O lib com certeza pode ser mantida separada, assim como a nfelib. No entanto, considero que centralizar nossos recursos sob o mesmo guarda-chuva não apenas aumentaria a confiabilidade e a governança do projetos, mas também reduziria a complexidade para os novos usuários que se juntam à localização.

No longo prazo eu vejo que a ideia é remover o erpbrasil.edoc.pdf

Vejo que vale uma atualização na pagina do https://erpbrasil.github.io/ citando a Engenere e a Escodoo tb. Alem de atualizar algumas referências das libs. Isso poderia alinhar nossas estratégias mantendo a autonomia do projeto.

2024-05-13 21:02 UTC, mbcosta commented
valeu @antoniospneto parabéns pelo trabalho, apenas uma questão inicial vi que o projeto foi baseado em outro https://github.com/edsonbernar/nfe_utils e que vocês colocaram a referencia sobre isso, mas houve alguma tentativa de contato com o autor? Para saber se ele teria algum interesse em passar a colaborar em um projeto único ou no repo dele ou no de vocês ou em algum outro,  erpbrasil como @mileo está sugerindo, já que vocês implementaram documentação e testes que é algo que no original está apenas no ROADMAP

2024-05-13 23:13 UTC, antoniospneto commented
@mbcosta

Isso, o projeto foi criado a partir do fork do nfe_utils, mas, apesar disso, foi todo refatorado. Se for comparar o código, o diff é quase de 100%. Como as alterações foram muito significativas, decidimos manter o nosso próprio fork, mas o autor original do projeto foi contatado sim. Caso haja interesse, ele pode integrar as alterações.

A Engenere pretende se manter como mantenedora do projeto, o que garante que a gente se comprometa bastante com o projeto. Acreditamos que, ao manter a gestão centralizada, podemos assegurar a continuidade e a qualidade do desenvolvimento. Nosso objetivo é proporcionar uma ferramenta robusta e confiável para a comunidade, e estamos comprometidos em fornecer suporte e melhorias contínuas.

No momento, não há interesse em repassar para outro repositório, como o erpbrasil, mas estamos abertos a colaborações e contribuições que possam beneficiar o projeto.

cc @mileo

2024-05-13 23:45 UTC, rvalyi commented
Aproveitando para comentar apenas sobre essa questão: a partir do momento que a P&D da nova lib BrazilFiscalReport foi assumida apenas pela Engenere, não vejo problema em manter a lib num repo da Engenere. Falando em governancia é algo muito mais logico do que pessoas aleatórias que nada fizeram nessa P&D comecar a entrar no meio e dar palpite de engenheiro da obra pronta ou permitir a estagiários que nunca emplacariam PR algum na OCA de comecar a adicionar funcionalidades adicionais aleatórias... Hoje a Engenere certamente tem contribuições no OCA/l10n-brazil com qualidade acima da media então não vejo risco com isso...

Caso algum dia a Engenere abandonasse a manutenção da lib, ai sim alguma org como erpbrasil seria natural para manter um fork ativo, assim como foi feito com erpbrasil.edoc qdo o pysped foi abandonado pelo próprio autor. Lembrando tb que a situação foi diferente com as libs erpbrasil.base ou erpbrasil.assinatura onde foi uma P&D compartilhada da Kmee e da Akretion ai sim fez sentido botar numa org comum. Agora tb essa org erpbrasil, tem muita coisa lá que é bom nem se orgulhar muito não... Se alguém cascudo da OCA olhar o que tem nessa erpbrasil, capaz de sair com medo em vez de achar bacana...

Por fim eu acho que a gente so tem que agradecer a Engenere de ter encabeçado o desafio de fazer essa lib. Pois a lib erpbrasil.edoc.pdf andava meio abandonada pela Kmee e usava o engine py3o que tinha sido abandonado pelo proprio autor, a XCG. Quebrou um bom galho alguns anos (depois da gente ter usado Aeroo e Geraldo...) mas tava um ponto muito fraco das dependencias do OCA/l10n-brazil.

Segue um print dos últimos PRs no erpbrasil.edoc.pdf: mal teve review da Kmee:
![IMG_20240513_203706_219.jpg](https://github.com/OCA/l10n-brazil/assets/16926/83740d41-ec14-4dea-8e66-a949e6f13cfd)

Acho complicado nem conseguir cuidar da propria lib e querer fiscalizar o trabalho dos outros...

Entendo que a Kmee é co-autor do módulo l10n_br_nfe e por isso pode exigir de nao sair prejudicada pelo PR. Porem aqui o PR não é invasivo e mantem a possibilidade de imprimir o DANFE usando erpbrasil.edoc.pdf. Nao vejo grande problema com isso...

2024-06-27 16:49 UTC, marcelsavegnago commented
@antoniospneto pode fazer um rebase por favor ?

2024-06-28 19:55 UTC, antoniospneto commented
Pessoal,

O @felipemotter  fez o rebase e tbm incluimos a possibilidade de fazer algumas configurações na DANFE:

![Imagem do WhatsApp de 2024-06-28 à(s) 14 45 35_69bad563](https://github.com/OCA/l10n-brazil/assets/634278/c6dca9be-33ed-442b-90a6-563e54185629)

A possibilidade de exibir os campos PIS e COFINS foi a pedido do @renatonlima

2024-07-11 16:46 UTC, antoniospneto commented
Após o rebase com a branch principal os testes não estão mais passando, vou verificar o motivo, por enquanto vou deixar a PR em rascunho.

2024-07-12 20:03 UTC, antoniospneto commented
@OCA/local-brazil-maintainers 

Pronto para revisão de volta.

2024-07-17 13:59 UTC, rvalyi requested changes

2024-07-17 13:59 UTC, rvalyi commented on l10n_br_nfe/models/document.py
> +        self.file_report_id = self.env["ir.attachment"].create(attachment_data)
@antoniospneto eu fiquei na duvida, o codigo do make_pdf assim como esta ainda eh compativel com o erpbrasil.edoc.pdf? Perdi algo ou me parece que so esta feito para funcionar com o BrazilFiscalReports aqui. Isso nao seria um problema para manter a compatibilidade?

2024-07-17 14:14 UTC, antoniospneto commented on l10n_br_nfe/models/document.py
> +        self.file_report_id = self.env["ir.attachment"].create(attachment_data)
A lógica que decide qual vai ser a lib utilizada está no método `_render_qweb_pdf` ali no modelo `ir_actions_report`
Essa implementação mantem a conpatibilidade sim, você pode configurar na empresa qual a lib que será utilizado.

2024-07-17 14:16 UTC, rvalyi commented on l10n_br_nfe/models/document.py
> +        self.file_report_id = self.env["ir.attachment"].create(attachment_data)
falei besteira, o suporte ficou encapsulado no action aqui https://github.com/OCA/l10n-brazil/blob/5cc0d87150a0957b2ea404dbc36cab2136f92466/l10n_br_nfe/report/ir_actions_report.py#L69 ta tudo certo.

2024-07-17 14:19 UTC, rvalyi approved these changes
Eu acho bem vinda essa evoluçao. O codigo eh super limpo, o acrescimo de codigo eh minimo para uma funcionalidade super boa. Mantem a compatibilidade com erpbrasil.edoc.pdf. Nisso eu aprovo.

2024-07-17 16:53 UTC, antoniospneto commented
> Eu acho bem vinda essa evoluçao. O codigo eh super limpo, o acrescimo de codigo eh minimo para uma funcionalidade super boa. Mantem a compatibilidade com erpbrasil.edoc.pdf. Nisso eu aprovo.

Ai mais tarde quando a lib BrazilFiscalReport estiver bem testada a gente pode remover a dependencia do eprbrasil.edoc.pdf se for do agrado de todo mundo, simplificando o código.

2024-07-17 20:48 UTC, marcelsavegnago approved these changes

2024-07-18 13:10 UTC, CristianoMafraJunior approved these changes

2024-07-18 13:11 UTC, felipemotter approved these changes

2024-07-21 00:30 UTC, rvalyi commented
(botando merge major pela nova dependencia)

/ocabot merge major

2024-07-21 01:02 UTC, merged