[FIX] l10n_br_account: account move on fiscal wiz
OCA/l10n-brazil pull request #3090
Opened 2024-05-21 18:00 UTC by felipemotter

Com a entreda do PR #2761 , o documento fiscal passou a ser exibido ao consultar os detalhes fiscais, com isso a logica que existe no account não é mais chamada (por que ele verifica se o modelo ativo é o account.move) e por isso o move_id do wizard não é populado. Com isso, ao cancelar um documento, criar uma carta de cerreção ou invalidar uma numeração, a logica no move_id não é realizada. 

Exemplo: se você for uma nfe confirmada e cancela-la (o governo permite em até 24h) a nfe estaria cancelada mas a fatura não, e o pior, devido ao status cancelado do documento, é impossível cancelar a fatura na visão dela.

Como o move_id não é algo que acho que seja comum para todos os wizards e é uma informação nem sempre necessária, decidi mudar um pouco a lógica para não ficar repetindo lógica e também só chamar os move_id quando necessário.

Está em validação. Provável que vou por outro commit para limpar um pouco mais de código morto.

2024-05-23 11:36 UTC, felipemotter commented
Foquei a PR apenas na correção dos wizards... Acredito que o repactor com limpeza do código é um assunto delicado e precisa ser mais discutido.

2024-05-23 12:26 UTC, rvalyi commented
> Foquei a PR apenas na correção dos wizards... 

Mott'er Foquer!
desculpa precisava sair.

2024-05-23 16:26 UTC, felipemotter commented
Até que demorou pra sair essa piada kkkkk

2024-05-24 00:19 UTC, mileo approved these changes

2024-05-24 00:49 UTC, antoniospneto approved these changes

2024-05-24 01:22 UTC, marcelsavegnago approved these changes
LGTM. Não testei :)

2024-05-24 01:22 UTC, marcelsavegnago commented
@rvalyi róla ?

2024-05-24 01:50 UTC, rvalyi requested changes, later dismissed
no geral seu PR é legal, mas sera se precisa desse seu move_message_post  como eu comentei?

2024-05-24 01:50 UTC, rvalyi commented on l10n_br_account/models/fiscal_document.py
> +            record.move_ids.message_post(body=msg)
Sera se esse move_message_post é realmente preciso e o override do message_post que eu tinha botado aqui não seria suficente? 
https://github.com/OCA/l10n-brazil/pull/3032/files

2024-05-24 11:34 UTC, mileo reviewed
Podemos ter a possibilidade também de somente um documento ser cancelado e os outros mantidos?

Mas creio que dessa forma teríamos que "zerar" o item relacionado da invoice ou pensar em alguma outra estratégia.

Isso com certeza aumenta o escopo do PR, mas se for o caso seria legal criar um issue pra resolvermos isso depois.

2024-05-24 11:51 UTC, felipemotter commented
> Podemos ter a possibilidade também de somente um documento ser cancelado e os outros mantidos?
> 
> Mas creio que dessa forma teríamos que "zerar" o item relacionado da invoice ou pensar em alguma outra estratégia.
> 
> Isso com certeza aumenta o escopo do PR, mas se for o caso seria legal criar um issue pra resolvermos isso depois.

Teria que ver a melhor forma de fazer isso, mas acredito que como você falou, valeria uma Issue para discutir melhor o assunto.

2024-05-24 12:44 UTC, rvalyi approved these changes
valeu @felipemotter ficou top. Eh que ja ta va pensando em esses wizards qdo fiz esse metodo... Foi mal a regressão com o cancel.

2024-05-24 12:44 UTC, rvalyi commented
/ocabot merge minor

2024-05-24 12:47 UTC, rvalyi commented
(nao precisa atualizar o banco mas botei merge minor para sinalizar que me parece uma mudança um pouco maior do que patch ja que remove arquivos que talvez alguem poderia herdar numa customizão).

2024-05-24 13:18 UTC, merged