[15.0][MIG] l10n_br_cnpj_search: Migration to 15.0
OCA/l10n-brazil pull request #3112
Opened 2024-06-06 15:53 UTC by renatonlima

l10n_br_cnpj_search: Migration to 15.0

2024-06-06 16:03 UTC, mileo commented
@renatonlima quando puder comentar aquele PR: https://github.com/OCA/l10n-brazil/pull/2635

2024-06-06 23:02 UTC, renatonlima commented
> @renatonlima quando puder comentar aquele PR: #2635

@mileo eu fiz a revisão do PR #2635 e vou acompanhar esse PR de perto

2024-06-08 19:37 UTC, rvalyi requested changes
Tem que substituir o SavepointCase pelo TransactionCase nos tests poque o SavoipointCase ta deprecated na 15.0 e removido na 16.0.

2024-06-10 17:50 UTC, marcelsavegnago approved these changes
LGTM

2024-06-11 13:16 UTC, rvalyi requested changes
- o ultimo commit pode ser removido, nao serve, pois installable; True ja eh o padrao.
- tb eh melhor fazer um squash do commit [db0b8c8](https://github.com/OCA/l10n-brazil/pull/3112/commits/db0b8c8a01cc95e4c0252b867bffeff6adf43e03) dentro do commit de migracao anterior. So eh legal dividir os commits de migracao quando a migracao eh complexa e justifica (como por examplo do l10n_br_account da 12 para a 13).

2024-06-11 16:01 UTC, rvalyi approved these changes
.

2024-06-11 16:02 UTC, rvalyi commented
/ocabot merge migration l10n_br_cnpj_search

2024-06-11 16:02 UTC, rvalyi commented
/ocabot merge nobump

2024-06-11 16:20 UTC, merged