[15.0][MIG] l10n_br_ie_search: Migration to 15.0
OCA/l10n-brazil pull request #3113
Opened 2024-06-06 16:33 UTC by renatonlima

Migration to 15.0

2024-06-08 19:38 UTC, rvalyi requested changes
Tem que substituir o SavepointCase pelo TransactionCase nos tests poque o SavoipointCase ta deprecated na 15.0 e removido na 16.0.

2024-06-10 15:50 UTC, renatonlima commented
This PR depends on #3112

2024-06-11 13:18 UTC, rvalyi requested changes
- o ultimo commit pode ser removido, nao serve, pois installable; True ja eh o padrao.
- tb eh melhor fazer um squash do commit https://github.com/OCA/l10n-brazil/pull/3113/commits/225aaa956c22d6d235035f3421f687f57930dfc3 dentro do commit de migracao anterior. So eh legal dividir os commits de migracao quando a migracao eh complexa e justifica (como por examplo do l10n_br_account da 12 para a 13).

2024-06-11 17:20 UTC, renatonlima commented
O módulo l10n_br_ie_search depende do módulo l10n_br_nfe que ainda não esta migrado https://github.com/OCA/l10n-brazil/pull/2874, então quando for feito o merge eu faço o rebase.

2024-06-11 17:52 UTC, marcelsavegnago commented
/ocabot migration l10n_br_ie_search

2024-07-06 13:09 UTC, mileo commented
@renatonlima pode dar uma olhada nos testes?

2024-07-25 20:07 UTC, antoniospneto approved these changes

2024-07-26 16:40 UTC, marcelsavegnago approved these changes
LGTM

2024-07-26 17:19 UTC, rvalyi commented
/ocabot merge nobump

2024-07-26 17:42 UTC, merged