[12.0] l10n_br_base: Update res.city.csv data
OCA/l10n-brazil pull request #3116
Opened 2024-06-11 16:27 UTC by renatonlima

Atualização dos dados de município baseado nos dados do IBGE

2024-06-11 17:47 UTC, marcelsavegnago approved these changes

2024-06-12 03:23 UTC, rvalyi approved these changes
LGTM. O diff parece gigantao, mas eh porque muitas cidades foram inseridas e tem muitos registros do inicio do arquivo que pularam para depois por examplo. Eu pesquisei alguns desses registros que parecem ser removidos e eles foram simplesmente jogados para depois entao me parece OK.

2024-06-12 16:37 UTC, rvalyi requested changes
ver explicaçoes aqui https://github.com/OCA/l10n-brazil/pull/3117#issuecomment-2163475032

2024-06-12 20:00 UTC, rvalyi approved these changes

2024-06-12 20:01 UTC, rvalyi commented
/ocabot merge minor

2024-06-12 22:36 UTC, rvalyi commented
/ocabot merge minor

2024-06-12 22:59 UTC, merged