[16.0] l10n_br_base: Update res.city.csv data
OCA/l10n-brazil pull request #3119
Opened 2024-06-11 17:13 UTC by renatonlima

Port do PR #3116

2024-06-11 17:47 UTC, marcelsavegnago approved these changes

2024-06-12 10:06 UTC, augustodinizl approved these changes

2024-06-12 16:39 UTC, rvalyi requested changes
ver explicacoes aqui https://github.com/OCA/l10n-brazil/pull/3117#issuecomment-2163475032

2024-06-12 20:02 UTC, rvalyi approved these changes

2024-06-12 20:03 UTC, rvalyi commented
/ocabot merge minor

2024-06-12 23:30 UTC, rvalyi commented
/ocabot merge minor

2024-06-12 23:40 UTC, merged