[IMP] l10n_br_fiscal: Resolvendo o problema de cálculo da estimativa de imposto nacional e importada
OCA/l10n-brazil pull request #3152
Opened 2024-07-02 20:17 UTC by corredato

Os campos estimate_tax_national e estimate_tax_imported dentro dos registros do NCM não estavam sendo calculados corretamente para o cálculo dos impostos estimados na linha da fatura.

2024-07-02 22:24 UTC, mileo approved these changes
Como a NCM não tem o company id, esse valor tem que ser uma property ou não deve ser stored.

Isso impacta o uso do campo quando estamos trabalhando em um ambiente multi company.

2024-07-03 00:18 UTC, antoniospneto approved these changes

2024-07-03 00:20 UTC, antoniospneto requested changes
LGTM, só tem que ver os testes, e o prefixo na mensagem do commit o certo é [FIX] não [RMV]

2024-07-03 00:42 UTC, rvalyi commented
os testes estão falhando no projeto porque ta puxando a nova nfelib 2.1.1 que nao tem mais os bindings legacy generateDS, eu comentei aqui https://github.com/OCA/l10n-brazil/pull/3150
ou seja não tem a ver com o fix. Eu acho que eu consigo arrumar amanhã.

2024-07-03 13:16 UTC, antoniospneto requested changes
Ainda tem que dar uma olhada nos testes, tá falhando no compute dos impostos estimados.

2024-07-03 15:12 UTC, rvalyi commented
@corredato vc poderia dar um rebase da sua branch em cima da 14.0 atualizada e fazer um force push da sua branch. Isso vai resolver o problema dos testes com a versão da nfelib e vai permitir da gente avaliar melhor o seu PR...

2024-07-05 00:42 UTC, mileo commented
Se for pra manter dessa forma vai ser necessário um script de migração.

2024-07-05 00:59 UTC, rvalyi commented
@mileo da para vc dar uma prioridade para se posicionar sobre esse PR por favor? Se trata de bastante codigo bem central... https://github.com/OCA/l10n-brazil/pull/3081

2024-07-10 16:21 UTC, mileo approved these changes

2024-07-11 02:06 UTC, antoniospneto approved these changes
No código me parece tudo OK

2024-07-11 23:18 UTC, renatonlima requested changes

2024-07-11 23:18 UTC, renatonlima commented on l10n_br_fiscal/models/data_ncm_nbs_abstract.py
> +        company_dependent=True,
Esse campo não deve ser um property porque a informação de impostos aproximados pode ser usado por todas as empresas em um ambiente multi company.

2024-07-11 23:18 UTC, renatonlima commented on l10n_br_fiscal/models/data_ncm_nbs_abstract.py
> +        company_dependent=True,
Esse campo não deve ser um property porque a informação de impostos aproximados pode ser usado por todas as empresas em um ambiente multi company.

2024-07-11 23:18 UTC, renatonlima commented on l10n_br_fiscal/tests/test_fiscal_document_generic.py
> +                    "company_id": line.company_id.id,
Os impostos estimados não deveria ter o campo company_id porque esse registro pode ser usado por qualquer empresa em um ambiente multi company, separar por empresa os registros estimados vai multiplicar essas informação para cada empresa cadastrada.

2024-07-12 12:24 UTC, mileo commented on l10n_br_fiscal/models/data_ncm_nbs_abstract.py
> +        company_dependent=True,
@renatonlima company_dependent é o property das versões mais novas.

![image](https://github.com/user-attachments/assets/8817b7b7-fa13-4311-83bf-4320fd088d98)

2024-07-12 12:36 UTC, antoniospneto commented on l10n_br_fiscal/models/data_ncm_nbs_abstract.py
> +        company_dependent=True,
@mileo, talvez a descrição da PR não tenha ficado clara. A ideia desta PR é que cada empresa possa ter regras diferentes para o cálculo dos impostos estimados, certo? Não será o mesmo valor para todas as empresas, correto? Por isso, há a necessidade de ter valores individuais para cada empresa. Consequentemente, o campo deve ser uma propriedade dependente da empresa (property/company_dependent). Pelo menos, foi isso que eu entendi, mas talvez o @renatonlima tenha interpretado de outra forma..

2024-07-12 12:39 UTC, mileo commented on l10n_br_fiscal/tests/test_fiscal_document_generic.py
> +                    "company_id": line.company_id.id,
![image](https://github.com/user-attachments/assets/7b2a1177-dc5d-400b-a5db-d7283209b425)

Quando cadastramos uma empresa no de olho no imposto colocamos dados da sua tributação. Cada empresa tem uma chave de API separada e opções de baixar as tabelas individualmente.

Qual a fonte dessa informação que as tabelas podem ser compartilhadas?

2024-07-12 17:31 UTC, mileo commented on l10n_br_fiscal/models/data_ncm_nbs_abstract.py
> +        company_dependent=True,
Sim, começou com essa descrição pois tinha um bug envolvido e o PR cresceu de tamanho pois o bug não tinha uma solução simples.

No caso multi company o campo não era atualizado.

2024-07-30 13:35 UTC, mileo commented
@renatonlima pode revisar novamente?

2024-07-30 13:47 UTC, antoniospneto commented on l10n_br_fiscal/models/data_ncm_nbs_abstract.py
> +    def update_compute_amount(self, last_estimated):
Aqui o nome do método não seria mais claro assim?

```suggestion
    def update_estimated_taxes(self, last_estimated):
```

2024-07-30 13:51 UTC, antoniospneto reviewed
No geral acho bem vinda essa alteração, realmente a configuração dos impostos estimados tem que ser por empresa, conforme o @mileo explicou.

Minha unica sugestão é alterado nome do método de `update_compute_amount` para  `update_estimated_taxes`

2024-07-30 13:58 UTC, mileo commented
> No geral acho bem vinda essa alteração, realmente a configuração dos impostos estimados tem que ser por empresa, conforme o @mileo explicou.
> 
> Minha unica sugestão é alterar o nome do método de `update_compute_amount` para `update_estimated_taxes`

Feito

2024-07-30 14:20 UTC, antoniospneto commented
@mileo acho que é necessário script de migração também não?

2024-07-30 14:30 UTC, mileo commented
> @mileo acho que é necessário script de migração também não?

Vamos providenciar.

2024-07-30 15:01 UTC, mileo commented
> @mileo acho que é necessário script de migração também não?

Verificando com o time eles já tinham feito, eu acho q eu sobrescrevi a branch :@

2024-07-30 15:43 UTC, mileo commented
> @mileo acho que é necessário script de migração também não?

Pronto para revisão:

@renatonlima @antoniospneto @marcelsavegnago @rvalyi

2024-07-30 16:29 UTC, antoniospneto submitted a review, later dismissed
Me parece tudo ok agora, valeu!

2024-07-31 14:45 UTC, renatonlima commented on l10n_br_fiscal/tests/test_fiscal_document_generic.py
> +                    "company_id": line.company_id.id,
@mileo,


As alíquotas não são diferentes para cada empresa, ou regime tributário, se você tiver três empresas, uma do Simples Nacional, uma do Lucro Presumido e outra do Lucro Real na mesma UF, os dados serão exatamente iguais, então quando eu me referi sobre as mudanças do PR, não é por não saber como definir um campo property, mas porque o design desse PR esta errado, só vai duplicar informações desnecessárias.

No próprio [FAQ](https://deolhonoimposto.ibpt.org.br/Site/Faq) no site do IBPT informa que as alíquotas só são diferentes por UF:

![image](https://github.com/user-attachments/assets/67ab0bc3-9baf-4639-a6d4-cc785b309cf5)

2024-07-31 14:49 UTC, rvalyi commented
pessoal, eh bom verificar a colocaçao do @renatonlima  aqui https://github.com/OCA/l10n-brazil/pull/3152#discussion_r1698647061

2024-07-31 14:50 UTC, renatonlima requested changes
O design desse PR está errado como expliquei no meu contrário anterior, os dados dos impostos aproximados são igual para todos regimes tributário da mesma UF abaixo segue a explicação no FAQ do IBPT

![image](https://github.com/user-attachments/assets/b3b5339d-895f-42d4-ac34-6525d5d3073f)

2024-07-31 15:04 UTC, antoniospneto commented
> O design desse PR está errado como expliquei no meu contrário anterior, os dados dos impostos aproximados são igual para todos regimes tributário da mesma UF abaixo segue a explicação no FAQ do IBPT
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/b3b5339d-895f-42d4-ac34-6525d5d3073f)
> 
> 

Mas e se as empresas forem de estados diferentes? Será que o hoje o sistema suporta esse caso de uso? Será que esse é o seu caso de uso @mileo ?

2024-07-31 15:13 UTC, mileo commented
> > O design desse PR está errado como expliquei no meu contrário anterior, os dados dos impostos aproximados são igual para todos regimes tributário da mesma UF abaixo segue a explicação no FAQ do IBPT
> > ![image](https://private-user-images.githubusercontent.com/211005/353878526-b3b5339d-895f-42d4-ac34-6525d5d3073f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0Mzg3NjcsIm5iZiI6MTcyMjQzODQ2NywicGF0aCI6Ii8yMTEwMDUvMzUzODc4NTI2LWIzYjUzMzlkLTg5NWYtNDJkNC1hYzM0LTY1MjVkNWQzMDczZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxNTA3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTAyYzVjOTdkNzRkZDhmY2E3MTY0YWJlODFmM2UyYzE4NzFkODZjNjg2ZjBjN2E1MWFjOTkzNzU0YWE0Zjg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IpzdjAVT3D3YDKTRjEOYBhbEJXYYhOIBViZrlMkliik)
> 
> Mas e se as empresas forem de estados diferentes? Será que o hoje o sistema suporta esse caso de uso? Será que esse é o seu caso de uso @mileo ?

No inicio começamos resolvendo o **BUG** do multi company, onde uma empresa tinha impostos estimados e a outra ficava com o valor zerado. 

Então separamos a implementação por empresa para facilitar o controle individualmente. 

Conforme entendimento dos comentários acima cada estado pode ter seus totais estimados, então vai ser necessário novas melhorias, não que atualmente esteja errado, só acaba tendo uma certa duplicidade de dados no cenário multi company.

**Podemos fazer o merge desse PR e providenciar essa melhoria posteriormente, ou manter o bug e o PR em aberto até termos tempo de implementar isso.**

2024-07-31 16:16 UTC, renatonlima commented
@antoniospneto e @mileo

O objeto l10n_br_fiscal.tax.estimate tem o campo [state_id](https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_fiscal/models/tax_estimate.py#L16), inclusive existe o campo company_id que poderia ser removido porque esse objeto não tem regra de segurança. (pelo menos não deveria ter)

A ideia de colocar nos objetos l10n_br_fiscal.ncm e l10n_br_fiscal.nbm os campos calculados estimate_tax_national, estimate_tax_imported era para ficar fácil nos cálculos na linha do documento fiscal fazer line.ncm_id. estimate_tax_national e já acessar o último percentual dos impostos aproximados.

Na maioria dos casos quando existe uma empresa ou várias empresas (multi-company) mas na mesma UF vai funcionar, mas se existir empresas em diferentes UFs, isso já não vai funcionar, deixar o campo property até resolveria o problema mas vai duplicar esses valores seja nos casos de empresas na mesma UF ou em UFs diferentes.

Acho que existem dois caminhos:

1. Deixar os campos estimate_tax_national e estimate_tax_imported como campos calculados store=False, (Eu não sinto que seja a melhor solução) porque não sei se isso vai gerar algum impacto significativo na performance, pois sempre que acessar os objetos os campos serão calculados em tempo real.

2. Remover os campos calculados estimate_tax_national e estimate_tax_imported nos objetos l10n_br_fiscal.ncm e l10n_br_fiscal.nbm, no objeto l10n_br_fiscal.tax.estimate remover o campo company_id e implementar um campo active para manter somente o registro atual **visível de cada estado**, dessa forma o usuário vai conseguir visualizar os impostos aproximados de cada UF utilizada no sistema e ter um método nos objetos l10n_br_fiscal.ncm e l10n_br_fiscal.nbm para retornar esses dados no calculo dos impostos.

@mileo,

Não acho bom fazer o merge desse PR da forma como esta agora, pois vai mudar a estrutura de dados, mesmo com o script de migração, depois vai ter que ser feito outro PR e outro script de migração, é mais simples já corrigir de forma adequada o bug e fazer o merge.

2024-09-19 16:18 UTC, closed without merging