[UPD] l10n_br_zip: cep_ws_provide default
OCA/l10n-brazil pull request #3169
Opened 2024-07-10 21:17 UTC by Tiago370

2024-07-10 21:19 UTC, mileo approved these changes

2024-07-10 21:20 UTC, mileo commented
@Tiago370 pode fazer o backport para a v14 e v15 tb ?

2024-07-11 23:05 UTC, renatonlima requested changes
Na minha opinião é melhor deixar por padrão o serviço do webservice dos correios.

2024-07-11 23:13 UTC, renatonlima commented
> Na minha opinião é melhor deixar por padrão o serviço do webservice dos correios.

Eu vi a conversa no PR #3170 o serviço oficial não foi substituído?

2024-07-12 04:54 UTC, Tiago370 commented
Bom dia @renatonlima, o que eu consegui checar é que o serviço do webservice dos correios foi retirado da brazilcep na versão 6.2.0 em outubro do ano passado. Sobre um novo serviço oficial dos correios (ou o antigo) eu não consegui achar nenhuma informação satisfatória. Mandeu um email pro Michell Stuttgart perguntando sobre isso.

2024-07-12 12:53 UTC, antoniospneto commented
Pessoal pelo que pesquisei o sistema aque era utilizado dos correios é o SigepWeb, esses sistema foi descontinuado..

2024-07-12 14:05 UTC, mileo approved these changes

2024-07-12 14:24 UTC, antoniospneto approved these changes

2024-07-12 15:32 UTC, mileo commented
/ocabot merge minor

2024-07-12 15:41 UTC, merged