[14.0][FIX][l10n_br_fiscal] falha no cancelamento de nota fiscal sem retorno
OCA/l10n-brazil pull request #3182
Opened 2024-07-15 20:55 UTC by DiegoParadeda

Acredito que o commit https://github.com/OCA/l10n-brazil/commit/f6d0e9e9cdf061bb03d2b54be4e3f382de59751c tenha trazido resultados não desejados uma vez que o campo justificativa (no cancelamento da nota fiscal) precisa ter no mínimo 15 caracteres.

Essa propriedade passava despercebida e, com o commit, o erro passou a ocorrer sem nenhum tipo de retorno para o usuário.

Esse PR trava o cancelamento da nota fiscal caso o tamanho mínimo da justificativa não tenha sido atendida:

![image](https://github.com/user-attachments/assets/7f5b8de8-b041-4607-a8b5-3ddf96462b90)

2024-07-15 23:09 UTC, antoniospneto requested changes
Será que essa validação não é melhor ser diretamente no módulo da NF-e? considerando que para outros documentos fiscais a regra pode ser outra?  por exemplo na nota fiscal de serviço do provedor Betha, não há minimo,

2024-08-23 13:47 UTC, antoniospneto commented
@DiegoParadeda agora está pronto para revisão?

2024-08-23 19:59 UTC, DiegoParadeda commented
> @DiegoParadeda agora está pronto para revisão?

Sim @antoniospneto!

2024-08-23 20:01 UTC, antoniospneto approved these changes

2024-08-23 20:32 UTC, rvalyi approved these changes
LGTM

2024-08-23 21:47 UTC, marcelsavegnago approved these changes
LGTM

2024-08-23 22:15 UTC, rvalyi commented
/ocabot merge patch

2024-08-23 22:29 UTC, merged

2024-08-27 15:30 UTC, marcelsavegnago commented
@DiegoParadeda pode portar para as versões superiores ?

2024-08-29 02:53 UTC, rvalyi commented
> @DiegoParadeda pode portar para as versões superiores ?

feito em #3323 e #3324