[14.0][FIX] l10n_br_fiscal: fix validation error message
OCA/l10n-brazil pull request #3184
Opened 2024-07-19 19:38 UTC by marcelsavegnago

```
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: unsupported format character '!' (0x21) at index 77
```

2024-07-19 20:04 UTC, antoniospneto approved these changes

2024-07-19 21:02 UTC, kaynnan approved these changes

2024-07-19 21:24 UTC, rvalyi requested changes
Nao sei se essa forma eh boa... Pois assim ele vai tentar traduzir e depois formatar, ou seja pode falhar de acordo com o que tiver na traduçao. A forma como tende a ser feito no Odoo hoje eh:
`
_("blah blah blah %(variable1)s blah blah blah %(variable2)s", variable1=some_value1, variable2=some_value2)`

Ou seja faltou o s depois do %(state) e tb tem que tirar o format.

2024-07-19 22:46 UTC, marcelsavegnago commented
> Nao sei se essa forma eh boa... Pois assim ele vai tentar traduzir e depois formatar, ou seja pode falhar de acordo com o que tiver na traduçao. A forma como tende a ser feito no Odoo hoje eh: ` _("blah blah blah %(variable1)s blah blah blah %(variable2)s", variable1=some_value1, variable2=some_value2)`
> 
> Ou seja faltou o s depois do %(state) e tb tem que tirar o format.

Opa... blzz.. vou corrigir

2024-07-19 22:49 UTC, marcelsavegnago commented
@rvalyi feito

2024-07-20 17:25 UTC, mileo approved these changes

2024-07-20 17:30 UTC, rvalyi commented
nao tem que tirar o format ainda?

2024-07-20 21:03 UTC, marcelsavegnago commented
> nao tem que tirar o format ainda?

Opss

2024-07-22 15:34 UTC, marcelsavegnago commented
@rvalyi feito

2024-07-22 16:54 UTC, antoniospneto approved these changes

2024-07-22 16:56 UTC, rvalyi approved these changes
agora sim

2024-07-22 18:48 UTC, renatonlima approved these changes

2024-07-22 18:48 UTC, renatonlima commented
/ocabot merge minor

2024-07-22 19:21 UTC, merged