[14.0][FIX] l10n_br_fiscal: use correct CFOP type_move for ST returns
OCA/l10n-brazil pull request #3296
Opened 2024-08-20 19:52 UTC by DiegoParadeda

2024-08-22 12:59 UTC, mileo approved these changes

2024-08-22 14:59 UTC, rvalyi commented
@DiegoParadeda o PR ta como rascunho. É rascunho ainda?

2024-08-22 18:05 UTC, mileo commented
> @DiegoParadeda o PR ta como rascunho. É rascunho ainda?

Tem umas CFOPs faltando.

2024-08-23 13:07 UTC, antoniospneto commented
@mileo coloquei em rascunho de volta então, ai quando tiver pronto a gente revisa, valeu!

2024-08-28 12:47 UTC, mileo commented
Vamos deixar o PR dessa forma e no futuro vamos propor outro para as operações triangulares, mas é mais complexo que isso.

2024-08-28 12:48 UTC, mileo approved these changes

2024-08-28 16:47 UTC, antoniospneto requested changes
Qual foi a motivação para essa alteração? Pelo que analisei, essa modificação não parece estar correta. Uma **"devolução de venda"** deveria ser classificada como "**sale_refund**", mesmo que a terminologia na classificação do tipo de movimento possa gerar alguma confusão.

Se você está enfrentando algum problema específico, já considerou a possibilidade de que a causa possa estar em outro ponto do processo?

2024-09-04 19:12 UTC, DiegoParadeda commented
> Qual foi a motivação para essa alteração? Pelo que analisei, essa modificação não parece estar correta. Uma **"devolução de venda"** deveria ser classificada como "**sale_refund**", mesmo que a terminologia na classificação do tipo de movimento possa gerar alguma confusão.
> 
> Se você está enfrentando algum problema específico, já considerou a possibilidade de que a causa possa estar em outro ponto do processo?

@antoniospneto revisei a CFOP e operação que estava utilizando e de fato o código já estava correto, vou fechar o PR, valeu

2024-09-04 19:12 UTC, closed without merging