[14.0][IMP] l10n_br_nfe: set nfe40_IEST
OCA/l10n-brazil pull request #3341
Opened 2024-09-05 15:15 UTC by DiegoParadeda

2024-09-05 15:51 UTC, mileo approved these changes

2024-09-05 17:40 UTC, antoniospneto requested changes
Não sou especialista em ST, mas o campo `state_tax_number_ids` no modelo `res_company ` já não é pra esse proposito?

2024-09-05 17:42 UTC, antoniospneto approved these changes

2024-09-05 20:03 UTC, rvalyi requested changes
Pela assinatura, o self é um recordset, mesmo que sendo chamado aqui com apenas um item. Nisso deveria ter um loop ou então um self.ensure_one()

2024-09-06 17:21 UTC, antoniospneto commented
@DiegoParadeda 

Consegue fazer um squash dos commits? você poderia ter usado git --amend ao invés de criar um novo commit.

2024-09-06 18:48 UTC, rvalyi approved these changes

2024-09-06 18:48 UTC, rvalyi commented
/ocabot merge minor

2024-09-06 18:51 UTC, marcelsavegnago approved these changes
LGTM

2024-09-06 19:18 UTC, merged