[14.0][FIX] l10n_br_nfe: export nfe40_iest to XML and PDF
OCA/l10n-brazil pull request #3359
Opened 2024-09-11 18:54 UTC by DiegoParadeda

Pessoal, acabei tendo um falso-positivo no #3341, na realidade faltou exportar o valor para os documentos XML e PDF.

Durante meus testes estava setando o valor do campo nfe40_iest mais ou menos assim:

```python
self.company_inscr_est_st = iest # escrevendo no l10n_br_fiscal.document
self.nfe40_emit.nfe40_IEST = iest # exportando para XML/PDF
``` 

Mas isso não é legal pois ficaria toda hora sobreescrevendo o valor no ```res.company().nfe40_IEST```.

Nesse PR fiz uma alteração apenas no método do **export** para corrigir o problema e também limpar os caracteres especiais que podem ter sido registrados no cadastro da empresa

2024-09-12 17:00 UTC, DiegoParadeda commented
O f-push foi para garantir compatibilidade com os casos de criação em que a exportação do field nfe40_emit antecede a geração do valor para o campo **company_inscr_est_st**


Configurei no runboat também:
![image](https://github.com/user-attachments/assets/19cef714-2fc3-4e8e-9e17-aaa87a444f59)
![image](https://github.com/user-attachments/assets/96abd257-42db-4e60-9502-2e7c0807ea41)
![image](https://github.com/user-attachments/assets/8b8ac7e4-a34c-44c9-bf91-fab424adb90a)
![image](https://github.com/user-attachments/assets/9c0936a6-78a8-457e-bdba-776a703982cf)

2024-09-15 16:23 UTC, mileo commented on l10n_br_nfe/models/document.py
> +            self._set_nfe40_IEST()
Ao meu ver esse método deve ser refatorado só para retornar o IEST sem setar-lo no company.

2024-09-15 16:28 UTC, mileo requested changes
Da pra melhorar esse PR, a chamada do método: _set_nfe40_IEST esta repetido e o super poderia estar em apenas um local.

2024-09-16 20:24 UTC, mileo approved these changes

2024-09-24 11:12 UTC, rvalyi approved these changes
LGTM

2024-09-24 11:41 UTC, marcelsavegnago approved these changes

2024-09-24 12:37 UTC, rvalyi commented
/ocabot merge partch

2024-09-24 12:42 UTC, marcelsavegnago commented
/ocabot merge patch

2024-09-24 12:57 UTC, merged