[14.0][FIX] l10n_br_account: fix account.move post when there is no fiscal document
OCA/l10n-brazil pull request #3364
Opened 2024-09-13 20:14 UTC by WesleyOliveira98

Resolve #3363 

cc: @marcelsavegnago @kaynnan @douglascstd @rvalyi

2024-09-13 20:17 UTC, rvalyi requested changes

2024-09-13 20:17 UTC, rvalyi commented on l10n_br_account/models/account_move.py
> +        ).action_document_confirm()
Desde https://github.com/OCA/l10n-brazil/pull/2761 seria raro, mas a ideia é que poderia ter varios documentos fiscais ligado ao account.move e ai o_post deveria tentar confirmar todos eles no caso. Esse mapped("fiscal_document_id") pegaria apenas o documento fiscal sendo editado atualmente pelo account.move, entao faltaria tentar confirmar os outros...

2024-09-13 20:26 UTC, WesleyOliveira98 commented on l10n_br_account/models/account_move.py
> +        ).action_document_confirm()
> Esse mapped("fiscal_document_id") pegaria apenas o documento fiscal sendo editado atualmente pelo account.move, entao faltaria tentar confirmar os outros...

Alterado de `fiscal_document_id` para `fiscal_document_ids`

2024-09-13 20:52 UTC, kaynnan approved these changes

2024-09-13 20:57 UTC, kaynnan requested changes
Testei aqui e não teve o comportamento correto

2024-09-13 20:58 UTC, kaynnan requested changes
[REVIEW FUNCTIONAL]

Reprovado

![image](https://github.com/user-attachments/assets/656b9bb8-ddee-4f66-8480-9635a51d89b9)


Etapas para reproduzir:

1. Criar um Journal Entry
2. Postar

2024-09-13 21:36 UTC, WesleyOliveira98 commented
Acho que agora foi, como o erro estava no `_compute_fiscal_document_ids`, eu fiz essa mudança do set e list. Poderiam validar? @kaynnan @rvalyi

2024-09-13 21:45 UTC, kaynnan approved these changes
[REVIEW FUNCTIONAL] - Aprovado

LGTM

![image](https://github.com/user-attachments/assets/a145a4d3-8e2a-460c-810c-180ccab36cb0)

2024-09-13 21:47 UTC, rvalyi approved these changes

2024-09-13 21:52 UTC, marcelsavegnago approved these changes

2024-09-14 03:22 UTC, antoniospneto approved these changes
boa @WesleyOliveira98

2024-09-14 03:25 UTC, antoniospneto commented
hotfix

/ocabot merge patch

2024-09-14 05:01 UTC, merged

2024-09-14 14:17 UTC, marcelsavegnago commented
@WesleyOliveira98 faça o port para 15 e 16 por favor.