[IMP] l10n_br_fiscal: Melhoria no funcionamento dos impostos estimados
OCA/l10n-brazil pull request #3373
Opened 2024-09-19 03:53 UTC by corredato

Esta PR substitui a PR #3152 

@renatonlima Assim que puder, pode fazer a revisão? Fiz a melhoria com base na segunda solução que você propôs no PR #3152 

Resumindo: 

1. Exclusão dos campos estimate_tax_national e estimate_tax_imported
2. Refatoração do método _compute_amount para get_estimated_taxes e algumas mudanças no mesmo
3. Exclusão do company_id do l10n_br_fiscal.tax.estimate e implantação do campo active no objeto

2024-09-19 12:52 UTC, marcelsavegnago commented
@corredato se possível fecha então a PR  #3152

2024-09-25 23:18 UTC, mileo approved these changes

2024-10-07 12:05 UTC, mileo commented
@marcelsavegnago @antoniospneto @rvalyi @renatonlima podem revisar plz.

2024-10-07 12:43 UTC, antoniospneto commented
Pessoal, eu pretendo revisar essa PR com mais calma nos proximos dias.

2024-10-07 13:42 UTC, antoniospneto commented
Coloquei meu token do IBPT no runboat, mas dá esse erro ao tentar atualizar o valor aproximado do imposto:
![image](https://github.com/user-attachments/assets/de6bc88f-32a0-4698-a182-aba459685865)
Alguém pegou esse erro tbm?

2024-10-07 13:45 UTC, mileo commented
Tem um system parameter que foi alterado uns meses atrás e não esta setado por padrão.

@corredato pode incluir isso no seu PR como uma melhoria? ibpt_request_timeout

2024-10-07 15:36 UTC, corredato commented
> Tem um system parameter que foi alterado uns meses atrás e não esta setado por padrão.
> 
> @corredato pode incluir isso no seu PR como uma melhoria? ibpt_request_timeout

Sim, pode deixar

2024-10-08 16:30 UTC, antoniospneto commented on l10n_br_fiscal/models/tax_estimate.py
> +        return estimates
O que motivou a criar esse campo de ativo? não vejo muita necessidade nisso.

2024-10-08 16:34 UTC, antoniospneto commented on l10n_br_fiscal/models/tax_estimate.py
> +        return estimates
Vi que isso foi proposto pelo @renatonlima aqui:
https://github.com/OCA/l10n-brazil/pull/3152#issuecomment-2260892396

Mas tem que ver melhor, da forma que tá sendo feito não tá fazendo diferença..

2024-10-08 16:42 UTC, antoniospneto commented on l10n_br_fiscal/models/tax_estimate.py
> +        return estimates
Pessoal, o que eu acho que dá pra fazer, é manter apenas uma linha de imposto estimado para cada estado no NCM/NBS. não acho necessário fazer um controle de ativo ou desativo. Nem é interessante manter um histórico das taxas antigas, isso só geraria muito lixo no banco de dados, só de NCM temos 40 mil linhas.. pensa no quanto isso pode crescer.

2024-10-08 16:54 UTC, antoniospneto commented on l10n_br_fiscal/models/data_ncm_nbs_abstract.py
> +        )
Aqui eu ainda não consegui coompreender qual vantagem de trocar compute por esse método..
Tem que ver se isso é o que o @renatonlima queria, talvez não era bem isso..

Eu penso que talvez não é o mais seguro buscar o estado de dentro da empresa ativa.
Acho que seria melhor o local que precisar dessa informação informar o estado, por exemplo na Fatura, seria pego o estado de dentro do company_id definido na fatura.

2024-10-08 16:56 UTC, antoniospneto requested changes
Concordo na parte de remover o company_id.
Concordo em por o timeout padrão.

Quanto aos campos computados estimate_tax_national, estimate_tax_imported  que foram substituidos por um método, precisa ser descutido melhor.

Quanto ao controle de estimativas ativas, tbm penso que tem que ser discutido melhor, não tá claro isso.

2024-10-08 17:14 UTC, rvalyi commented on l10n_br_fiscal/models/tax_estimate.py
> +        return estimates
talvez já daria para manter o histórico das mudanças no chatter apenas?

2024-10-08 17:17 UTC, antoniospneto commented on l10n_br_fiscal/models/tax_estimate.py
> +        return estimates
acho que por a data de sincronização na linha do imposto estimado já seria o bastante, se não o chatter vai ficar monstruoso tbm, a configuração padrão é atualizar a cada 15 dias, acho que vai ser muito spam, opnião minha.

2024-10-08 17:38 UTC, rvalyi commented on l10n_br_fiscal/models/tax_estimate.py
> +        return estimates
concordo no módulo l10n_br_fiscal é melhor assim mesmo. Tem como logar isso num módulo extra se alguém quiser. Num projeto eu sobrecarreguei a logica do chatter para conservar apenas os ultimos N mensagens. Mas melhor guardar isso para um modulo extra do que acumular muito mais coisas nesse módulo.

2024-11-09 14:51 UTC, mileo requested changes
ValueError: Invalid field l10n_br_fiscal.tax.estimate.company_id in leaf ('company_id', 'in', [1])

Ta dando um erro estranho, pode verificar?

2025-10-19 12:13 UTC, closed without merging