[16.0][IMP] l10n_br_ie_search: change vcr mocks for unittest mocks.
OCA/l10n-brazil pull request #3448
Opened 2024-10-16 20:17 UTC by Tiago370

Nesse PR trocamos os moks do vcr pelos mocks do unittest.

2024-10-16 22:10 UTC, rvalyi commented on l10n_br_ie_search/tests/test_sefaz.py
> +    # )
Pode remover esse código?

2024-10-16 22:10 UTC, mileo requested changes
pode remover os comentários

2024-10-16 23:41 UTC, Tiago370 commented
@mileo , @rvalyi removi o código comentado.

2024-10-16 23:43 UTC, CristianoMafraJunior approved these changes

2024-10-16 23:59 UTC, antoniospneto approved these changes

2024-10-17 10:31 UTC, mileo approved these changes

2024-10-17 10:32 UTC, mileo commented
/ocabot merge minor

2024-10-17 10:41 UTC, merged