[14.0][WIP][IMP] l10n_br_fiscal: tax_definition add Service Type
OCA/l10n-brazil pull request #3471
Opened 2024-10-28 19:37 UTC by kaynnan

[HT00887]

cc @marcelsavegnago @WesleyOliveira98 @douglascstd

2024-10-28 20:10 UTC, mileo approved these changes

2024-10-29 13:50 UTC, kaynnan commented
Rebase realizado para constar o runboat, ele não estava disponível para os testes

2024-10-30 15:14 UTC, marcelsavegnago approved these changes

2024-10-30 15:26 UTC, douglascstd requested changes
[FUNCIONAL REVIEW] [CHANGE REQUEST]

Teste realizado:
![image](https://github.com/user-attachments/assets/42e3aa6c-93b6-4d5c-aef8-2424299e2771)
![image](https://github.com/user-attachments/assets/0beb1fc9-469d-4f67-b3b3-c1c4efa94253)

Ponto de melhoria:
1. Ao alterar o campo Tipo LC ("Service Type LC 166") não tem o recalculo, e fazia sentido antes desta PR, pois essa informação não entrava na composição. Agora faz sentido esse campo acionar o calculo de impostos
https://github.com/user-attachments/assets/0640fe17-c727-4e92-8e48-74b82f06a121

2024-10-30 15:38 UTC, rvalyi approved these changes

2024-10-30 15:38 UTC, rvalyi commented
/ocabot merge minor

2024-10-30 16:11 UTC, merged