[14.0][IMP] l10n_br_nfe: computed impostoDevol added to nfe
OCA/l10n-brazil pull request #3519
Opened 2024-12-02 19:57 UTC by DiegoParadeda

## Objetivo

Adiciona suporte para a definição dos campos nfe40_vIPIDevol e nfe40_pDevol na linha do documento fiscal. Os valores definidos para esses campos também serão corretamente exportados para o XML da NFe.

2024-12-02 23:43 UTC, mileo commented on l10n_br_nfe/models/document_line.py
> +    def _compute_nfe40_impostoDevol(self):
Será que vale uma validação para verificar se a nota é de devolução? Também colocar condicionalmente o campo na tela somente nesses casos?

Para os casos: Devolução e nota complementar.

2024-12-03 13:01 UTC, antoniospneto requested changes
muito bom, só acho que poderia ser incluindo um pequeno caso de teste para validar esses dois campos, simular uma nota fiscal de devolução a partir da empresa do simples nacional

2024-12-03 15:44 UTC, rvalyi requested changes

2024-12-03 15:44 UTC, rvalyi commented on l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
> +                                </group>
se puder ver a indentação. Não acho bom mexer na indentação toda junto com uma mudança, mas pelo menos vc pode tentar não deixar a indentação pior. Veja o ponto 3 do conceito de "clean code"  https://gist.github.com/wojteklu/73c6914cc446146b8b533c0988cf8d29#general-rules eh algo que é bom aplicar para ser bem visto na OCA...

2024-12-03 20:20 UTC, rvalyi commented on l10n_br_nfe/models/document_line.py
> +                record.nfe40_impostoDevol = impostoDevol
aqui não tem risco de ficar criando os registros ipi_devol e impostoDevol varias vezes se passar no método varias vezes?

2024-12-05 14:48 UTC, DiegoParadeda commented on l10n_br_nfe/models/document_line.py
> +                record.nfe40_impostoDevol = impostoDevol
De fato estava, já corrigi

2024-12-05 21:19 UTC, rvalyi approved these changes

2024-12-05 21:32 UTC, mileo approved these changes

2024-12-06 00:05 UTC, antoniospneto commented
@DiegoParadeda ali você adicionou os dados de demonstração, mas quando eu falei em testes é na verdade o teste unitário em python, esse você pretende fazer?

Off-topic:

Aproveitando, na minha opinião, acho que devemos cuidar para deixar os dados de demonstração mais apresentáveis e bonitos para o usuário final que está conhecendo o Odoo e a nossa localização. É importante simular operações que representem bem uma empresa fictícia. Atualmente, na localização, há muitos dados de demonstração cujo propósito não é demonstrar algo de fato ao usuário, mas apenas servir de base para os testes em Python. Os dados que alimentam os testes poderiam ser criados diretamente nas classes de testes.

2024-12-06 00:58 UTC, DiegoParadeda commented
> @DiegoParadeda ali você adicionou os dados de demonstração, mas quando eu falei em testes é na verdade o teste unitário em python, esse você pretende fazer?
> 
> Off-topic:
> 
> Aproveitando, na minha opinião, acho que devemos cuidar para deixar os dados de demonstração mais apresentáveis e bonitos para o usuário final que está conhecendo o Odoo e a nossa localização. É importante simular operações que representem bem uma empresa fictícia. Atualmente, na localização, há muitos dados de demonstração cujo propósito não é demonstrar algo de fato ao usuário, mas apenas servir de base para os testes em Python. Os dados que alimentam os testes poderiam ser criados diretamente nas classes de testes.

@antoniospneto entendi, faço sim

2024-12-06 01:25 UTC, rvalyi commented
isso realmente é um ponto que teremos que encarar...

Minha preocupação esses anos era bater uns 90% de cobertura de teste para ter um mínimo de confiabilidade.

Mas mas e mais na OCA e na própria Odoo a tendência é permitir rodar testes sem precisar carregar dados de demos. Assim por exemplo vc poderia pegar um banco de prod, instalar sei la os módulos de CNAB e verificar que is testes contonuam passando no banco de prod com os módulos de CNAB...

hoje na localização, por questões históricas temos os testes ainda muito atrelados ao dados de demo...

Na v14 e na v16 dei um duro no l10n_br_accouny e eu consegui evitar isso... Mas seria bom ir deixando os testes independente nos outros módulos tb...

Ai tb como o @mbcosta ja observou, a nossa localização é tão complexa que seria um pouco ilusório pensar em manter testes e dados de demo totalmente separados e manter isso no tempo. A medida que as leis iriam mudar, ou os testes ou os dados de demo iriam deixar de ser realista...

Nisso é importante sim cogitar uma forma dos testes ser capaz de carregar algums dados de demo, seja carregando os arquivos XML, seja chamando metodos que tb seria chamados nos dados de demo... Tem várias possibilidades.

E nisso seria bom sim, idealmente não ir piorando da situação inclusive neste PR.

Por fim tem indícios que la no futuro sera possivel de talvez rodar o CI sem carregar os dados de demo, o que seria mais rapido. Ai sera bom qdo a chegar lá (bota versão 20 talvez) a gente não ter os testes tudo atrelados a demo aqui.

Enfim tem muita coisa mais prioritário mas é bom ter isso na mente...

2024-12-06 19:01 UTC, DiegoParadeda commented
@antoniospneto @rvalyi pessoal, os únicos testes que encontrei aqui pra conseguir comparar o valor do documento com o XML são esses que usam `test_serialize_xml`:

![image](https://github.com/user-attachments/assets/1accdba4-50a3-43fd-88ca-a8522acf69fc)

Porém essa forma ofende as práticas que vocês sugeriram pois requer dados de demo que só servem pra teste (uma vez que não tenho um caso real aqui de nota de devolução com IPI que possa compartilhar aqui no projeto).

O correto seria remover a nota de demo que já está criada no meu teste, é isso? E esse teste pode aguardar até alguém ter algum caso com IPI devolvido? Realmente não encontrei outra forma de testar esse código. 

Outra opção é recriar essa nota que fiz de demo mas via python e só testar o preenchimento do campo, daí não ficaria dado de demo desnecessário no runbot mas também não testaria o XML. O que acham?

2024-12-06 19:19 UTC, antoniospneto commented
> @antoniospneto @rvalyi pessoal, os únicos testes que encontrei aqui pra conseguir comparar o valor do documento com o XML são esses que usam `test_serialize_xml`:
> 
> ![image](https://private-user-images.githubusercontent.com/12245538/393363437-1accdba4-50a3-43fd-88ca-a8522acf69fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MTI1MzMsIm5iZiI6MTczMzUxMjIzMywicGF0aCI6Ii8xMjI0NTUzOC8zOTMzNjM0MzctMWFjY2RiYTQtNTBhMy00M2ZkLTg4Y2EtYTg1MjJhY2Y2OWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDE5MTAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2N2QxNzllMzNkNzI5ZjcwOGRjYWM2Mjk4NjM5MTU3MTNlY2Q3ZGVmMGZhNzIxODU3ZTk2NGZmYmIwMGI3MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fYZ45VtMl5yo_ksXJcEtCmrEUNYpfHQ4pNfpPzQHA5c)
> 
> Porém essa forma ofende as práticas que vocês sugeriram pois requer dados de demo que só servem pra teste (uma vez que não tenho um caso real aqui de nota de devolução com IPI que possa compartilhar aqui no projeto).
> 
> O correto seria remover a nota de demo que já está criada no meu teste, é isso? E esse teste pode aguardar até alguém ter algum caso com IPI devolvido? Realmente não encontrei outra forma de testar esse código.
> 
> Outra opção é recriar essa nota que fiz de demo mas via python e só testar o preenchimento do campo, daí não ficaria dado de demo desnecessário no runbot mas também não testaria o XML. O que acham? (mas aqui ficaria meio bobo fazer campo="valor" > assert(campo == "valor" não?)

eu faria a ultima opção que você mencionou que é criar mesmo documento fiscal porem diretamente no código python, os assert apesar de simples é util para garantir que tudo tá ok, mas ainda sim é possivel compara o xml, vc pode salvar o xml gerado pra comparar no teste.

2024-12-06 19:24 UTC, DiegoParadeda commented
> > @antoniospneto @rvalyi pessoal, os únicos testes que encontrei aqui pra conseguir comparar o valor do documento com o XML são esses que usam `test_serialize_xml`:
> > ![image](https://private-user-images.githubusercontent.com/12245538/393363437-1accdba4-50a3-43fd-88ca-a8522acf69fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MTI1MzMsIm5iZiI6MTczMzUxMjIzMywicGF0aCI6Ii8xMjI0NTUzOC8zOTMzNjM0MzctMWFjY2RiYTQtNTBhMy00M2ZkLTg4Y2EtYTg1MjJhY2Y2OWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDE5MTAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2N2QxNzllMzNkNzI5ZjcwOGRjYWM2Mjk4NjM5MTU3MTNlY2Q3ZGVmMGZhNzIxODU3ZTk2NGZmYmIwMGI3MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fYZ45VtMl5yo_ksXJcEtCmrEUNYpfHQ4pNfpPzQHA5c)
> > Porém essa forma ofende as práticas que vocês sugeriram pois requer dados de demo que só servem pra teste (uma vez que não tenho um caso real aqui de nota de devolução com IPI que possa compartilhar aqui no projeto).
> > O correto seria remover a nota de demo que já está criada no meu teste, é isso? E esse teste pode aguardar até alguém ter algum caso com IPI devolvido? Realmente não encontrei outra forma de testar esse código.
> > Outra opção é recriar essa nota que fiz de demo mas via python e só testar o preenchimento do campo, daí não ficaria dado de demo desnecessário no runbot mas também não testaria o XML. O que acham? (mas aqui ficaria meio bobo fazer campo="valor" > assert(campo == "valor" não?)
> 
> eu faria a ultima opção que você mencionou que é criar mesmo documento fiscal porem diretamente no código python, os assert apesar de simples é util para garantir que tudo tá ok, mas ainda sim é possivel compara o xml, vc pode salvar o xml gerado pra comparar no teste.

Ok, vou fazer dessa forma então, valeu!

2024-12-09 12:28 UTC, mileo commented
/ocabot merge minor

2024-12-09 14:08 UTC, mileo commented
/ocabot merge minor

2024-12-09 14:42 UTC, marcelsavegnago approved these changes

2024-12-09 15:07 UTC, rvalyi commented
/ocabot merge minor

2024-12-10 13:01 UTC, mileo commented
/ocabot merge minor

Não sei se foi uma instabilidade no PIX, vou tentar mais uma vez, se não der providenciamos uma correção.

2024-12-10 13:17 UTC, antoniospneto commented
Esse teste com a API do Bacen poderia ser um mock, o teste real poderia ser acionado mas só via agendamento no CI, uma vez por semana

2024-12-10 13:36 UTC, merged