[WIP][14.0] Refactor Import EDOC
OCA/l10n-brazil pull request #3546
Opened 2024-12-13 00:30 UTC by mileo

Continuando o https://github.com/OCA/l10n-brazil/pull/2781

1. Realizei a refatoração do wizard de importação de documentos fiscais, deixando-o mais simples e compatível com a importação de outros tipos de documentos, sem muitos atritos ou códigos longos.

2. Permitir a importação completa do XML do arquivo, para um documento fiscal, para que o usuário possa visualizar o arquivo de forma completa e tomar decisões (vincular produtos, definir a cfop inversa, operação e etc);

3. Após a importação do documento fiscal, permitir a confirmação da importação;

4. Caso o módulo l10n_br_account esteja instalado, ao confirmar a importação criar o account.move e outros registros relacionados importantes (a definir);

5. Pemitir a geração de um picking ou vinculação com um já existente (https://github.com/OCA/account-invoicing/pull/1827)

Sugestões são bem vindas. 
Testes devem entrar em breve.

2025-02-05 14:26 UTC, DiegoParadeda commented
Fiz um rebase

2025-03-18 18:42 UTC, rvalyi commented
Pessoal aqui tá aliviando um pouco com os projetos na v16 então devo conseguir ver um pouco esse PR nos próximos dias...Mas como sempre é bom ir por etapas pequenas e fazer o merge de #2781 primeiro.

Nesse meio tempo seria bom vcs considerar fazer squash de alguns commits aqui porque não me parece justificado tantos commits. Uma coisa é o processo iterativo que leva vcs a construir a solução,  uma outra coisa é o trabalho que vcs vão dar as pessoas que vão revisar e fazer o port das coisas depois... Em especial essas coisas vão exigir um retrabalho para fazer o port para a v16 então é bom já organizar bem os commits...

2025-04-08 11:22 UTC, mileo commented
Bom dia Pessoal,

Finalizamos as funcionalidades prevista neste PR e ele esta funcional para uso. Esta semana vamos pedir o feedback de quatro clientes sobre a funcionalidade.

Também vamos gravar um vídeo ensinando sobre o uso e colocamos aqui.

Aproveito para pedir o feedback de vocês.

Dei uma olhada no histórico ontem com o @DiegoParadeda e estamos vendo a possibilidade de juntar alguns commits e/ou dividir este PR em outros menores.

@rvalyi o https://github.com/OCA/l10n-brazil/pull/2781 esta com uns commits estranhos no meio, creio que vieram de um rebase de outra branch, pode dar uma olhada?

cc: @marcelsavegnago @renatonlima @antoniospneto @douglascstd @mbcosta @felipemotter

2025-04-08 11:23 UTC, mileo commented
OBS: estamos trabalhando para corrigir e aumentar a cobertura de testes.

2025-04-08 15:12 UTC, rvalyi commented
@mileo @DiegoParadeda seria bom fazer essa simplificação da herança dos modelos fiscais abstratos antes de seguir com essas novas funcionalidades https://github.com/OCA/l10n-brazil/pull/3695

Eu fiz um backport para a 14.0, pelo jeito fuciona bem https://github.com/OCA/l10n-brazil/pull/3700

cc @renatonlima @marcelsavegnago @antoniospneto

2025-04-09 17:12 UTC, DiegoParadeda commented
Pessoal, esses foram os principais pontos desenvolvidos aqui nesse PR:

1. Import wizard minimalista: feito pra poder salvar o progresso da importação - permite que o operador do fiscal importe o XML e aos poucos preencha os dados adicionais e crie/aponte dados relacionais.
2. Busca automática por dados do supplier info: utiliza product code e product name para identificar e aplicar uma linha de supplier info. Esse processo também permite a conversão automática de UoM com a possibilidade de aplicar um fator de conversão.
3. Busca automática por dados do produto: name, default_code, barcode (utilizado na ausência do supplier info).
4. Criação de produtos a partir do import line wizard: feito para requisitar as informações obrigatórias (como tipo fiscal do produto e UoM) e aplicá-las como default para facilitar a criação de um novo produto.
5. Lógica de conversão de duplicatas em termos de pagamentos: Feito sem herdar os métodos do core como **_recompute_payment_terms_lines** em **odoo/addons/account/models/account_move.py** (@rvalyi esse ponto possivelmente conflita com a herança que você criou no #2781 - no vídeo mostrei esse ponto em 9min20seg)

Também fiz um vídeo mostrando:
https://drive.google.com/file/d/1hBc1bNQmXBF4psRdlR4hhpLUPgdMCIQ4/view?usp=sharing

2025-04-10 14:32 UTC, antoniospneto commented
Olá @mileo @DiegoParadeda 

Essa funcionalidade é muito importante para a localização, mas como envolve muitas modificações, acho válido fazermos uma revisão bem detalhada, tranquilo?

A gente da Engenere vai analisar com calma tanto a parte funcional quanto a técnica, em breve retornamos com os feedbeck.

Valeu!

2025-04-10 14:36 UTC, rvalyi commented
@antoniospneto @marcelsavegnago @DiegoParadeda tb para facilitar a sincronia entre as branches eu acharia importante fazer o backport de https://github.com/OCA/l10n-brazil/pull/3700 (apenas preciso renomar o mixin) antes. Então seria bom avaliar bem o impacto desse backport, se puderem testar em algum ambiente de homologação ou até prod...

2025-04-10 17:16 UTC, antoniospneto commented on l10n_br_account/wizards/document_import_wizard_mixin.py
> +    #             }
esse código comentado não poderia ser removido?

2025-04-10 17:18 UTC, CristianoMafraJunior commented on l10n_br_fiscal/wizards/document_line_import_wizard.py
> +    document_uom = fields.Char()
aqui pode colocar string="Document UoM"

2025-04-10 17:18 UTC, CristianoMafraJunior commented on l10n_br_fiscal/wizards/document_line_import_wizard.py
> +    document_ncm_id = fields.Many2one("l10n_br_fiscal.ncm")
aqui também string="Document NCM"

2025-04-10 17:18 UTC, CristianoMafraJunior commented on l10n_br_fiscal/wizards/document_line_import_wizard.py
> +    document_cfop_id = fields.Many2one("l10n_br_fiscal.cfop")
string="Document CFOP"

2025-04-10 17:18 UTC, CristianoMafraJunior commented on l10n_br_fiscal/wizards/document_line_import_wizard.py
> +    import_product_fiscal_type = fields.Selection(
Deixar string em Inglês: Fiscal Type

2025-04-10 17:19 UTC, DiegoParadeda commented
> Olá @mileo @DiegoParadeda
> 
> Essa funcionalidade é muito importante para a localização, mas como envolve muitas modificações, acho válido fazermos uma revisão bem detalhada, tranquilo?
> 
> A gente da Engenere vai analisar com calma tanto a parte funcional quanto a técnica, em breve retornamos com os feedback.
> 
> Valeu!

combinado @antoniospneto, assim que possível avalio o feedback e vou aplicando ajustes necessários

2025-04-10 17:44 UTC, CristianoMafraJunior requested changes
Estava testando aqui importar uma NF-e que não tenho o parceiro cadastrado, sei que agora não pode ter essa funcionalide mas seria interresante ter um UserError pra isso.
Aqui o XML usado para teste:
https://github.com/Engenere/BrazilFiscalReport/blob/main/tests/fixtures/nfe_additional_info_continuation_in_next_page.xml


![UserError](https://github.com/user-attachments/assets/05a77d8f-9723-40e0-b384-38379adafff4)

2025-04-10 18:22 UTC, antoniospneto commented on l10n_br_fiscal/wizards/document_line_import_wizard.py
> +    document_uom = fields.Char()
isso se não na visão vai ser impressão "Document Uom" que fica estranho

2025-04-10 18:26 UTC, antoniospneto commented on l10n_br_fiscal/wizards/document_line_import_wizard.py
> +    document_uom = fields.Char()
só que que ver se não vai acusar aquele Warning de string redundante, não sei se o sistema diferencia caixa alta e caixa baixa, mas dá pra desativar qualquer coisa

2025-04-10 18:28 UTC, CristianoMafraJunior commented on l10n_br_fiscal/wizards/document_line_import_wizard.py
> +    )
Deixar string em Inglês: Fiscal Type

2025-05-07 18:53 UTC, DiegoParadeda commented
Fiz um rebase apenas, ainda não resolvi os pedidos

2025-10-09 17:30 UTC, rvalyi commented
@mileo so I tried to port your PR on the 16.0 branch where the equivalent of #2781 was merged...

But I'm afraid it's almost impossible as it is. So let's dive into this PR: you integrated my ~14 v14.0 commits (from #2781)
and then your second commit is:
https://github.com/OCA/l10n-brazil/pull/3546/commits/027ad22aafe231cd2da9bff8d41bbfa006db31b8

So basically you both rename import_document.py into document_import_wizard.py and changed its content a lot. **You should NEVER rename a file and do major changes inside it as the same commit to start with**.
I mean, compare the original file https://raw.githubusercontent.com/OCA/l10n-brazil/34e5fcd6902c9cf6629d13359a61478082392fbc/l10n_br_nfe/wizards/import_document.py
to your new new file https://raw.githubusercontent.com/OCA/l10n-brazil/027ad22aafe231cd2da9bff8d41bbfa006db31b8/l10n_br_nfe/wizards/document_import_wizard.py in a diff editor (like meld) 

Are you serious??? It's just impossible to compare...

And yet:

1. this is your second commit, **you then added like 30 commits atop of this one** and you expect us to review and who know, may be merge this when just the 1st commit is not suitable at all. 
2. So let's suppose the import_document.py file was all broken. **But I didn't invent that 1st import_document.py version. It came from your KMEE team, was reviewed and approved by YOU**. When I implemented the basic importation in #2781, I almost didn't change this file and there were no constructive review from you about this wizard... If import_document.py was that broken, why did you merge it a few months before in first place?? Why didn't you do separate commits to fix it separately in smaller bits people can actually review??

The problem, @mileo you didn't begin your Odoo journey one year ago, you have been hanging around for more than 12 years, you even claimed to be part of the PSC, so you cannot claim you had no idea PRs are not expected to be done like that in the OCA...

Let me remind you that your initial design of the account.move importation where you wanted to reconstruct the account.move from the imported picking or sale.order was functionally completely broken (because the account.move would then never reflect properly the fiscal document issued by your supplier, breaking legal accounting, no localization/EDI do it this way). Thanks god I could block you from letting KMEE noobs forcing that into the project, I did some initial decent importation design and then you come again with a PR like that expecting we should review and merge it (or why is is not in draft state and why did you promote it else?).

So yes, I put it straight in English in case this need to be escalated in case you play the victim again.

By comparison, only #2781, I divided the original PR it in like 4 sub-PRs, it was a lot of work but I made it easy for people to test it an review it...

So let's see how things from this PR could eventually be ported, but as far as I see, it would be extremely hard to just cherry-pick commits...


cc @OCA/local-brazil-maintainers @DiegoParadeda @corredato

2025-10-16 20:36 UTC, rvalyi requested changes
So here are a few adicional comments:

I worked hard to make a first port of what could be ported to v16 https://github.com/OCA/l10n-brazil/pull/4157 (more could follow, but we have to start with a small reviewable bit).

I mostly agree on the generalization of the l10n_br_fiscal.document.wizard (that I mostly ported) and the idea of a generic l10n_br_fiscal.document.line.wizard (that I left to port for a second later step though).

Sadly as I explained it is not possible to cherry-pick many commits because the second commit https://github.com/OCA/l10n-brazil/commit/027ad22aafe231cd2da9bff8d41bbfa006db31b8 of this PR is too big to compare anything (as it combines a huge change and together with a rename). This is not possible to do a global review either because the overall diff of this PR is +2,564/−909 lines (my original PR was only +353/−25 by comparison, at least I extracted 3 smaller sub-PRs from it during the merge process, yes that's a lot of git rebase work but that's the only way we can have several people working on the same codebase IMHO; no OCA repo would review +2,564/−909 diff I guarantee you).

Also @mileo I think you missed a bit the existing integration between the l10n_br_fiscal.document and the account.move from https://github.com/OCA/l10n-brazil/pull/2781 (already merged in 16.0). It might not be perfect, but it is simple and well tested so just missing the feature to let a beginner build a new one is certainly not an option. Finally in the end of this PR you also tried to address the purchase order and stock.picking conciliation. But again I think that was a bit too much for @DiegoParadeda and this IMHO can be done in a cleaner way this way instead: https://github.com/OCA/stock-logistics-workflow/pull/2057

based on these comments I'll put the PR in draft to avoid polluting the list of ready PRs.

cc @OCA/local-brazil-maintainers

2026-03-22 12:21 UTC, closed without merging