[16.0][REF] l10n_br_account, fiscal: Aperfeiçoamento nos lançamentos contábeis
OCA/l10n-brazil pull request #3558
Opened 2024-12-18 17:18 UTC by antoniospneto

Durante a migração do módulo `l10n_br_sale_stock`, identifiquei falhas na contabilização de faturas em algumas situações específicas. Esta PR tem como objetivo aprimorar os lançamentos contábeis, garantindo maior aderência aos casos específicos da legislação brasileira.

Além disso, foi necessário ajustar alguns testes unitários, pois estavam apresentando falsos positivos. Por exemplo, anteriormente, contas a receber/pagar estavam sendo geradas para notas fiscais de remessa, o que é incorreto, já que essas notas não devem impactar o financeiro. Agora, o comportamento está alinhado ao esperado, garantindo maior precisão no processamento.

2024-12-18 20:18 UTC, rvalyi commented on l10n_br_account/tests/test_account_move_lc.py
> +            "debit": 206.5,
@antoniospneto @marcelsavegnago na v14 tava 0 para esses 2 valores. Tava errado na v14.0 mesmo? 
https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_account/tests/test_account_move_lc.py#L692

2024-12-18 20:26 UTC, antoniospneto commented on l10n_br_account/tests/test_account_move_lc.py
> +            "debit": 206.5,
Tava errado mesmo na v14, até tava conversando com o @marcelsavegnago sobre isso hoje, essa é uma nota fiscal de remessa com lançamento de imposto, ela tem cobrança de imposto , mas ao mesmo tempo não pode gerar financeiro, não pode ter contas a receber ou apagar no caso, e aí agora eu zerei o financeiro, mas de alguma forma ainda precisamos balancear os lançamentos, por isso joguei a diferença pra conta da receita/despesa, dessa forma o lançamento fica balanceado sem precisar gerar o financeiro, que é o correto, no caso uma nota fiscal de remessa com imposto a contra partida para os impostos é uma despesa para a empresa.

2024-12-18 20:30 UTC, rvalyi commented on l10n_br_account/tests/test_account_move_lc.py
> +            "debit": 206.5,
OK, vc jogou a contra-partida dos impostos aqui e tirou das contas a receber...   
![mind-blown-shocked](https://github.com/user-attachments/assets/aed3f79d-2114-4854-8109-345b52c17fb8)

2024-12-18 22:39 UTC, rvalyi commented on l10n_br_account/tests/test_account_move_lc.py
> +            "debit": 206.5,
so para deixar claro: na 14, se as taxas são dedutíveis, os lançamentos de remessas estão OK. Mas se as taxas não são dedutíveis, os lançamento estão errados como neste caso (sera bom a gente botar algum comentário sobre isso na v14). E ai o Antonio solucionou esse caso tb aqui neste PR.

2024-12-18 22:42 UTC, rvalyi requested changes

2024-12-18 22:42 UTC, rvalyi commented on l10n_br_account/models/account_move_line.py
> +                            # de pagamento.
@antoniospneto vc poderia apenas passar este comentário para Inglês? (nos modulos mais centrais é bom botar tudo em inglês). O restante me parece bem OK...

2024-12-23 13:53 UTC, WesleyOliveira98 approved these changes
LGTM

2024-12-31 11:12 UTC, rvalyi approved these changes
bom já vou fazer o merge e veremos o comentário depois, pois esse fix é bem importante...

2024-12-31 11:13 UTC, rvalyi commented
/ocabot merge minor

2024-12-31 11:24 UTC, merged