[14.0][WIP] l10n_br_fiscal, nfe: Adição da tag cBenef no XML
OCA/l10n-brazil pull request #3561
Opened 2024-12-18 23:47 UTC by corredato

Esta PR adiciona a tag cBenef no XML, considerando que, a partir de 01/02/2024, será obrigatório o preenchimento dessa tag no estado de Santa Catarina. Na tag de informações adicionais do produto, deverão ser informados os códigos de benefício fiscal, caso existam mais de um.

Algumas melhorias podem ser feitas futuramente:

1. Controle da visibilidade do campo do código de benefício fiscal se baseando no state_id da empresa e do cst/csosn informado no imposto
2. Introduzir os códigos de benefício fiscal de cada estado que preenche o cBenef (DF, GO, PR, RJ, RS e SC)

2024-12-19 00:30 UTC, rvalyi commented
@corredato eu vejo que vc adiciona esses modelos ao nivel do módulo l10n_br_fiscal. Porem temos mixin geridos para a tag cBenef no módulo l10n_br_nfe_spec que poderia ser extendido no módulo l10n_br_nfe. Sera que não seria melhor implementar isso apenas no módulo l10n_br_nfe? Vai ser usado fora do contexto da NFe esse modelo?   cc @renatonlima @mileo @marcelsavegnago @antoniospneto

2024-12-19 01:40 UTC, corredato commented
> @corredato eu vejo que vc adiciona esses modelos ao nivel do módulo l10n_br_fiscal. Porem temos mixin geridos para a tag cBenef no módulo l10n_br_nfe_spec que poderia ser extendido no módulo l10n_br_nfe. Sera que não seria melhor implementar isso apenas no módulo l10n_br_nfe? Vai ser usado fora do contexto da NFe esse modelo? cc @renatonlima @mileo @marcelsavegnago @antoniospneto

Acho interessante manter a implementação no fiscal por se tratar de uma configuração base para empresas de alguns estados, assim como a configuração de impostos e alíquotas nas linhas das operações, não parece mais intuitivo manter no fiscal?

2024-12-19 01:47 UTC, rvalyi commented
eu diria que o unico critério é se vai usar em outros documentos fiscais sem ser NFe. Se não for o caso tem que ir no l10n_br_nfe. Em termo de ergonomia pode ter exactemente a mesma usabilidade. Mas uma coisa super importante é que o módulo l10n_br_fiscal ja esta MUITO acima do peso, já é disparado o maior módulo dos 3000 módulos da OCA então para enfiar qualquer coisa a mais dentro sem ser outro módulo tem que ter justificativa muito boa...

2024-12-19 01:51 UTC, corredato commented
> eu diria que o unico critério é se vai usar em outros documentos fiscais sem ser NFe. Se não for o caso tem que ir no l10n_br_nfe. Em termo de ergonomia pode ter exactemente a mesma usabilidade. Mas uma coisa super importante é que o módulo l10n_br_fiscal ja esta MUITO acima do peso, já é disparado o maior módulo dos 3000 módulos da OCA então para enfiar qualquer coisa a mais dentro sem ser outro módulo tem que ter justificativa muito boa...

Entendo... A tag do cBenef deve ser preenchida também na NFCe, é o suficiente para manter no fiscal?

2024-12-19 02:12 UTC, rvalyi commented
> > eu diria que o unico critério é se vai usar em outros documentos fiscais sem ser NFe. Se não for o caso tem que ir no l10n_br_nfe. Em termo de ergonomia pode ter exactemente a mesma usabilidade. Mas uma coisa super importante é que o módulo l10n_br_fiscal ja esta MUITO acima do peso, já é disparado o maior módulo dos 3000 módulos da OCA então para enfiar qualquer coisa a mais dentro sem ser outro módulo tem que ter justificativa muito boa...
> 
> Entendo... A tag do cBenef deve ser preenchida também na NFCe, é o suficiente para manter no fiscal?

não! pois o esquema xsd da NFCe é o mesmo da NFe, eu diria que é mais um motivo de botar no módulo l10n_br_nfe (herdando o mixin nfe.40.cbenef que ja existe e vem do módulo l10n_br_nfe_spec)

2024-12-19 11:31 UTC, antoniospneto commented
02/2024 já passou, o @renatonlima ja não tinha feito uma implementação para isso, o cadastro do benefício fiscal fica junto a regulamentação do ICMS, isso na atende o caso de vocês?

2024-12-19 14:28 UTC, rvalyi commented
> 02/2024 já passou, o @renatonlima ja tinha feito uma implementação para isso, o cadastro do benefício fiscal fica junto a regulamentação do ICMS, isso não atende o caso de vocês?

ver #2461 e #3354

2025-01-13 12:55 UTC, mileo requested changes
Favor rever a implementação pois esta incorreta.

Somente uma mensagem fiscal já resolve isso, sem python.

2025-01-13 12:59 UTC, antoniospneto commented
> Favor rever a implementação pois esta incorreta.
> 
> Somente uma mensagem fiscal já resolve isso, sem python.

Se desejar, é possível implementar uma opção no próprio gerador de DANFE para que ele imprima diretamente, nas informações complementares, o conteúdo presente na tag do XML, sem necessidade de repetir essas informações no próprio arquivo.

2025-01-29 12:50 UTC, mileo commented
> Se desejar, é possível implementar uma opção no próprio gerador de DANFE para que ele imprima diretamente, nas informações complementares, o conteúdo presente na tag do XML, sem necessidade de repetir essas informações no próprio arquivo.

É uma boa ideia, colocarmos isso no report.

2025-01-29 13:46 UTC, antoniospneto commented
> > Se desejar, é possível implementar uma opção no próprio gerador de DANFE para que ele imprima diretamente, nas informações complementares, o conteúdo presente na tag do XML, sem necessidade de repetir essas informações no próprio arquivo.
> 
> É uma boa ideia, colocarmos isso no report.

se precisar de ajuda pra abrir a pr no brazilfiscalreport avisa

2025-01-29 15:14 UTC, corredato commented
> > > Se desejar, é possível implementar uma opção no próprio gerador de DANFE para que ele imprima diretamente, nas informações complementares, o conteúdo presente na tag do XML, sem necessidade de repetir essas informações no próprio arquivo.
> > 
> > 
> > É uma boa ideia, colocarmos isso no report.
> 
> se precisar de ajuda pra abrir a pr no brazilfiscalreport avisa

Dei um fork lá e abri, valeu

2025-01-29 17:01 UTC, corredato commented
Essa PR foi substituída pela https://github.com/Engenere/BrazilFiscalReport/pull/58

2025-01-29 17:01 UTC, closed without merging