Akretion migration10/l10n br account
OCA/l10n-brazil pull request #500
Opened 2016-12-15 21:14 UTC by renatonlima

Descrição do problema/nova funcionalidade deste Pull Resquest(PR):
------------------------------------------------------------------

Migração para a versão 10.0 do módulo l10n_br_account
-
-
-

Comportamento atual antes do PR:
--------------------------------

Comportamento esperado depois do PR:
------------------------------------

- [ ] Esta mudança não altera a estrutura do banco de dados, portanto não precisa de script de migração.

--
Eu confirmo que eu assinei a CLA e li as recomendações de como contribuir:
- https://odoo-community.org/page/cla
- https://odoo-community.org/page/Contribute

2017-01-09 13:05 UTC, sadamo requested changes
the Fiscal Position Rule mapping is not working properly.

2017-01-09 13:05 UTC, sadamo commented on l10n_br_account/views/res_company_view.xml
> +                            <page string="Regine Normal" name="regine_normal" attrs="{'invisible': [('fiscal_type', '!=', '3')]}">
Typo. Should be "Regime Normal".

2017-01-09 13:05 UTC, sadamo commented on l10n_br_account/models/account_invoice.py
> +            raise except_orm(
except_orm not imported. Btw, the convention continues to be "from odoo.exceptions import Warning as UserError"?

2017-01-09 13:05 UTC, sadamo commented on l10n_br_account/account_fiscal_position_workflow.xml
> -            <field name="signal">fiscal_category_approved</field>
Without the workflow, we can't aprove the Fiscal Category

2017-01-09 13:07 UTC, danimaribeiro commented on l10n_br_account/models/account_invoice.py
> +            raise except_orm(
"from odoo.exceptions import UserError"

2017-01-14 22:00 UTC, mileo approved these changes
Considerada as considerações do @sadamo e @danimaribeiro esta ok!

2017-01-14 22:22 UTC, mileo commented
FYC:

Fiz o merge desta branch em https://github.com/odoo-brazil/l10n-brazil-wip/tree/develop e estarei trabalhando em uma feature ref aos lançamentos contábeis da invoice.

2017-01-20 12:32 UTC, mileo commented
Please cherry pick this commit https://github.com/OCA/l10n-brazil/pull/515/commits/0250c7db2aedaf3f9399e073f170c7f5c42f2ff5

2017-01-20 12:44 UTC, mileo commented
Replace: https://github.com/OCA/l10n-brazil/pull/516

2017-10-04 14:13 UTC, mileo commented
Como este PR já esta parado faz muito tempo vou fecha-lo. Por favor caso a haja interesse favor reabrir o mesmo.

2017-10-04 14:13 UTC, closed without merging