[8.0][FIX] allow group "Faturamento & Pagamento" create invoice
OCA/l10n-brazil pull request #546
Opened 2017-06-08 20:55 UTC by mbcosta

Descrição do problema/nova funcionalidade deste Pull Resquest(PR):
------------------------------------------------------------------

- Usuários que pertencem ao grupo "Faturamento & Pagamento" por falta de permissão de acesso não conseguem criar Faturas
- Users who belong to group "Faturamento & Pagamento"  by lack of access can't create Invoice

Comportamento esperado depois do PR:
------------------------------------

- Permitir usuários do grupo "Faturamento & Pagamento" criar Faturas
- Allow users belong to group "Faturamento & Pagamento" create Invoice

--
Eu confirmo que eu assinei a CLA e li as recomendações de como contribuir:
- https://odoo-community.org/page/cla
- https://odoo-community.org/page/Contribute

2017-06-09 01:02 UTC, mileo approved these changes

2017-06-09 01:06 UTC, mileo requested changes
Magno não seria melhor aproveitar e dar permissão de cancelamento e carta de correção ao usuário dp grupo group_account_invoice

2017-06-09 14:28 UTC, mbcosta commented
Ola @mileo fiz a correção porém sem permissão de exclusão, acredito que isso só pode ser feito por um gerente não por um operador, certo ?

2017-06-11 18:49 UTC, mileo requested changes

2017-06-11 18:49 UTC, mileo commented on l10n_br_account/security/ir.model.access.csv
>  "l10n_br_account_invoice_cancel_user","l10n_br_account_invoice.cancel","model_l10n_br_account_invoice_cancel","account.group_account_invoice",1,0,0,0
Acredito que faltou o cancelamento ( estou no celular a visualização não é das melhores )

2017-06-13 14:37 UTC, mbcosta commented
ola @mileo adicionei a permissão de cancelamento e atualizei a descrição do PR, procurei por outros objetos que deveriam ter a permissão alterada mas não encontrei, se puder veja se existe mais algum

2017-06-13 17:25 UTC, mileo approved these changes

2017-06-19 12:53 UTC, renatonlima approved these changes

2017-06-19 12:54 UTC, merged