10.0 l10n br resource
OCA/l10n-brazil pull request #567
Opened 2017-10-02 16:12 UTC by rvalyi

should be equivalent of https://github.com/OCA/l10n-brazil/pull/551
but extracting the last commits from https://github.com/kmee/odoo-brazil-hr

also see comments on https://github.com/OCA/l10n-brazil/pull/564

cc @mileo @renatonlima @Hendrixcosta @mbcosta @wagnerpereirasp @sadamo @lfdivino

2018-05-02 11:03 UTC, mileo requested changes

2018-05-02 11:03 UTC, mileo commented on l10n_br_resource/README.rst
> +* Firstname Lastname <email.address@example.org>
Corrigir o email dos autores

2018-05-11 11:58 UTC, mileo approved these changes

2018-08-23 00:57 UTC, the-bmb commented
@hendrixcosta você pode revisar por favor?

2018-08-23 11:47 UTC, hendrixcosta requested changes

2018-08-23 11:47 UTC, hendrixcosta commented on l10n_br_resource/models/resource_calendar.py
> +        return 30 - data_from.day + 1
Essa fórmula não funciona para admissão.
Se o funcionário for admitido no dia 20/05 , deverá ser remunerado 12 dias.

2018-08-23 11:50 UTC, hendrixcosta commented on l10n_br_resource/models/resource_calendar.py
> +        return 30 - data_from.day + 1
https://github.com/abgfbr/odoo-brazil-hr/blob/8.0/l10n_br_resource/models/resource_calendar.py#L216

2018-08-23 17:23 UTC, sadamo requested changes
Erro ao tentar importar um feriado.
```
Traceback (most recent call last):
  File "/home/sadamo/projetos/kmee/v10/parts/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/sadamo/projetos/kmee/v10/parts/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/home/sadamo/projetos/kmee/v10/parts/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/sadamo/projetos/kmee/v10/parts/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/sadamo/projetos/kmee/v10/parts/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/sadamo/projetos/kmee/v10/parts/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/home/sadamo/projetos/kmee/v10/parts/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/sadamo/projetos/kmee/v10/parts/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/sadamo/projetos/kmee/v10/parts/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/sadamo/projetos/kmee/v10/parts/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/sadamo/projetos/kmee/v10/parts/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/sadamo/projetos/kmee/v10/parts/l10n-brazil/l10n_br_resource/wizard/workalendar_holiday_import.py", line 176, in holiday_import
    work_time = self.get_calendar_for_state(holiday)
  File "/home/sadamo/projetos/kmee/v10/parts/l10n-brazil/l10n_br_resource/wizard/workalendar_holiday_import.py", line 91, in get_calendar_for_state
    state = self.get_state_from_calendar(holiday)
  File "/home/sadamo/projetos/kmee/v10/parts/l10n-brazil/l10n_br_resource/wizard/workalendar_holiday_import.py", line 66, in get_state_from_calendar
    [('ibge_code', '=', holiday.calendar_id.state_id.ibge_code)])
AttributeError: 'Feriado' object has no attribute 'calendar_id'
```

2018-08-23 17:23 UTC, sadamo commented on l10n_br_resource/models/resource_calendar.py
> +    _parent_store = True
A linha 38 deveria estar logo abaixo da declaração da classe, não é? Parece que foi alterada em algum rebase ou algo do tipo.

2018-08-24 02:39 UTC, hendrixcosta commented on l10n_br_resource/models/resource_calendar.py
> +    _parent_store = True
"holiday" é uma instância de uma classe da pybrasil. Essa classe "Feriado" não tem um campo chamado calendar_id

2018-08-24 02:39 UTC, hendrixcosta requested changes
Ajustar campos da classe de feriados

2018-08-24 02:41 UTC, hendrixcosta commented
O wizard de importação ficou estranho
![image](https://user-images.githubusercontent.com/7250580/44562025-ef99c880-a72d-11e8-8146-0be1c42d98a2.png)

2018-09-03 12:47 UTC, mbcosta commented on l10n_br_resource/models/resource_calendar.py
> +    parent_id = fields.Many2one(
olá pessoal, vocês poderiam explicar qual necessidade levou a criação de uma "hierarquia" de calendarios ?

2018-09-03 13:00 UTC, mileo commented on l10n_br_resource/models/resource_calendar.py
> +    parent_id = fields.Many2one(
Pois o calendário municipal herda do estadual q herda do federal.

2018-09-03 13:07 UTC, mbcosta commented on l10n_br_resource/models/resource_calendar.py
> +    parent_id = fields.Many2one(
Certo, mas qual razão de não colocar todos os feriados em um só calendário ? O que impediu isso ou qual problema vocês encontraram que levou a isso ?

2018-09-03 16:49 UTC, lfdivino commented on l10n_br_resource/models/resource_calendar.py
> +    parent_id = fields.Many2one(
@mbcosta Levando-se em consideração a questão de 'Recursos Humanos' se uma empresa possuir varias filiais será preciso tratar de forma diferenciada os feriados municipais e/ou federais, como por exemplo a realização do pagamento da folha, se no municipio de uma das filiais for feriado é preciso adiantar para o dia util anterior.

2018-09-03 17:58 UTC, mbcosta commented on l10n_br_resource/models/resource_calendar.py
> +    parent_id = fields.Many2one(
Mas pelo código que está nesse PR já está sendo adicionado no objeto 'resource.calendar.leaves' as informações de País, Estado e Município, isso já não seria suficiente ? Quer dizer se já será criado uma 'Folga' ( 'resource.calendar.leaves' ) com essas informações porque é necessário criar um calendário do município ou do estado se o próprio cadastro já possui isso ?

2018-09-05 10:30 UTC, mileo commented on l10n_br_resource/models/resource_calendar.py
> +    parent_id = fields.Many2one(
Pois cada recurso (usuário/empresa/maquina) tem um calendário. E quando se consulta esse calendário são retornados diversos dados.... Por exemplo se ele estará produzindo/folgando/etc ou não em determinado dia.

Mas uma máquina não tem normalmente um cadastro com cidade /estado/pais.

Por isso tem essa relação.

2018-09-05 13:19 UTC, mbcosta commented on l10n_br_resource/models/resource_calendar.py
> +    parent_id = fields.Many2one(
No 'core' isso parece ter sido resolvido de outra forma, existe o campo 
'resource_id' dentro do objeto 'resource.calendar.leaves' https://github.com/odoo/odoo/blob/10.0/addons/resource/models/resource.py#L765 veja a definição do objeto 'resource.resource' https://github.com/odoo/odoo/blob/10.0/addons/resource/models/resource.py#L691 veja que dentro desse objeto você pode definir tanto a Empresa ( 'company_id' ) quanto o tipo de recurso( 'resource_type' ) se humano ou máquina, isso não seria suficiente ? Pergunto porque de uma maneira geral é melhor implementar e estender o código do 'core' até para permitir uma melhor compatibilidade com outros módulos que possam utilizar as informações geradas pelo 'resource'

2019-04-25 09:58 UTC, hendrixcosta commented
@mbcosta parece funcionar.. Mas todo o resto da folha de pagamento foi construído em cima dessa abordagem.. 
O que acha de seguimos com o merge e abrir uma issue para melhoria?
Vamos dar continuidade à migração e em seguida atacamos as melhorias.
Abraço

2019-04-25 16:52 UTC, mbcosta commented
ola @hendrixcosta 
Minha crítica na época é que a implementação deveria seguir o que é feito nos módulos do Odoo ( "core" ), herdando métodos, campos e visões porque sem isso a integração com outros módulos tanto do "core" quanto da OCA podem ser tornar inviáveis e assim todos os módulos que forem relacionados ao "resource"  teriam que ser adaptados para a abordagem que está sendo proposta.

Hoje mantenho essa crítica, mas acredito que : 
* Versão 8 só devem ser feitos correções de Bugs ou implementações referentes a NFe 4.00
* Versão 10 somente a migração do código da 8 ( em outro PR o Raphael comentou que algumas alterações poderiam entrar )
* Versão 12 implementações e melhorias de código

Temos menos de 10 desenvolvedores ativos no projeto, pretendemos implementar o SPED ( algo que já foi debatido e mais de uma abordagem já foi considerada ) então eu julgo que idealmente deveríamos focar novas implementações na 12 ( algo importante é que lembro que a Odoo iria refatorar o "resource" preciso confirmar se na 12 já foi feito ou se vai entrar na nova versão ), se não vamos acabar vendo isso agora na 10 e depois revendo/refatorando na 12, será que vale a pena gastar horas de desenvolvimento/revisão de algo que já não existe na localização e depois mais horas revendo e refazendo ? Não seria melhor otimizar nosso tempo ? Veja que dentro dos repositórios da OCA existe uma exigência tanto no código quanto na revisão, não seria melhor manter esse modulo fora da OCA para ter mais liberdade e agilidade e adapta-lo ao "core" ? Porque depois dele incluído o processo aqui de refatorar/revisão se torna mais demorado do que em outros repositórios como o odoo-brasil

Minha opinião é que esse PR deveria ser encerrado e refeito para a versão 12 se baseando na implementação do "core", mas a decisão final cabe aos PSCs,  o @mileo parece já concordar portanto você vai ter que convencer o @renatonlima e o @rvalyi

2019-04-25 19:22 UTC, mileo commented
Sou a favor da abordagem mais rápida e simples. 

Fazer o merge deste módulo, que já esta com cobertura de testes na v10 parece razoável. Na sequência alguém analisa essas questões e faz o port para v12.

Agora o PR ficar parado desde 2 Oct 2017, não faz sentido, sendo que já poderia estar trazendo benefícios para os usuários da localização.

2019-04-25 19:22 UTC, mileo commented
OBS: fechei sem querer ao comentar

2019-04-26 14:40 UTC, sadamo approved these changes

2019-04-30 14:45 UTC, renatonlima requested changes

2019-04-30 14:45 UTC, renatonlima commented on l10n_br_resource/views/resource_calendar_leaves.xml
> +<?xml version="1.0" encoding="utf-8"?>
Seguir o OCA guideline, renomear este arquivo resource_calendar_leaves_views.xml, trocar tag openerp por odoo e remover a tag data.

2019-04-30 14:45 UTC, renatonlima commented on l10n_br_resource/wizard/__init__.py
> +# -*- coding: utf-8 -*-
Seguir o OCA guideline, renomear a pasta wizard para wizards

2019-04-30 14:45 UTC, renatonlima commented on l10n_br_resource/wizard/workalendar_holiday_import.py
> +from openerp import api, fields, models
Corrigir import openerp por import odoo

2019-04-30 14:45 UTC, renatonlima commented on l10n_br_resource/wizard/workalendar_holiday_import.xml
> +<?xml version='1.0' encoding='UTF-8'?>
Seguir o OCA guideline, renomear este arquivo workalendar_holiday_import_views.xml, trocar tag openerp por odoo e remover a tag data.

2019-04-30 14:45 UTC, renatonlima commented on l10n_br_resource/tests/test_resource_calendar.py
> +from openerp import fields
Corrigir import, openerp por odoo

2019-04-30 14:45 UTC, renatonlima commented on l10n_br_resource/models/resource_calendar_leaves.py
> +from openerp import fields, models
Corrigir import openerp por odoo

2019-04-30 14:45 UTC, renatonlima commented on l10n_br_resource/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
Colocar as informações de readme seguindo o novo formato do OCA guideline

2019-04-30 15:07 UTC, renatonlima commented
@mileo e @hendrixcosta,

Este módulo não é uma migração mas uma nova feature, hoje estamos procurando dar continuidade nas features já existentes na localização. Vocês tem expertise na parte de RH então eu diria que vocês que devem tomar as decisões sobre a melhor abordagem e arquitetura relacionadas aos módulos de RH, porém eu diria que deveríamos ter em mente:

1. Sobre o comentário do @mbcosta sobre o calendário, devemos adotar uma abordagem alinhada a abordagem do core para manter uma compatibilidade entre as features da localização e outros módulos do core que possuem dependência com a feature que esta sendo localizada.

2. A dependências pybrasil, hoje na v10.0 já temos esta dependência por causa do pysped, mas na versão 12.0 a ideia é eliminar, pois esta lib (pybrasil) é muito grande, com muitas dependência complexas, e sem testes, seria bom extrair em libs especificas as features necessarias do pybrasil usada neste modulo.

Eu diria que para este PR na 10.0 deveria ser feito as correções que eu fiz no último review do código e ser aceito, sobre os 2 pontos acima deve estar no roadmap ser discutidos na migração da versão 12.0.

cc @rvalyi

2019-04-30 15:19 UTC, rvalyi commented
Ola pessoal, minha opinião esta perfeitamente alinhada no que o @renatonlima falou no ultimo comentário acima. Acertando o que o @renatonlima revisou podemos aceitar o merge na v10 como primeiro passo. Para v12 sera preciso levar os outros pontos levantados pelo @mbcosta em consideração.

Nesse projeto sempre existiu uma pressão para colocar mais funcionalidades sem a massa critica de ajuda nas coisas centrais. E ate muitas vezes (não nesse caso), rolou hipocrisia total nisso para tentar desestabilizar a liderança do projeto com esse papo furado. Muito importante a gente ter essa necessidade de coerência na mente, senão a galera da comunidade e ate os próprios account managers da Odoo SA viajam e se ferram com qualquer promessa "populista" da vez que nao leva em lugar algum a médio prazo qdo finalmente o cara ingenuo começa finalmente a entender o eco-sistema.

2019-05-14 14:11 UTC, rvalyi commented on l10n_br_resource/readme/DESCRIPTION.rst
> +This module extend core resource to create important brazilian informations. Define a Brazilian calendar and some tools to compute dates used in financial and payroll modules
Thanks for the fixes. There are a few English errors here. I propose instead:
"This module extends the core resource module to add data for Brazil. It defines a Brazilian calendar and some tools to compute dates used in financial and payroll modules."

2019-05-14 17:59 UTC, rvalyi commented
I cannot formally approve with Github as it's me who created the PR, but I do approve the PR now. @renatonlima OK for you now? Let's gor for the merge?

2019-05-14 18:02 UTC, renatonlima approved these changes

2019-05-14 18:11 UTC, merged