10.0 oca/l10n br base
OCA/l10n-brazil pull request #600
Opened 2018-04-13 04:33 UTC by mileo

Diversas melhorias módulo base

2018-05-09 17:25 UTC, lfdivino approved these changes

2018-05-10 00:19 UTC, sadamo requested changes
Alguns pontos levantados:
* Formatação incorreta do endereço do parceiro (já corrigidos na branch https://github.com/kmee/l10n-brazil/tree/10-oca-fix/cadastro-clientes-produtos)
* Dados incompletos em cadastros de cidade, estado e país (pode ser que sejam campos que não são utilizados)
* Campo regime tributário do cadastro de parceiros deveria ter um valor default?
* Falta de preenchimento do campo 'contribuinte' no cadastro dos parceiros dos dados de demonstração 
* Poderia haver validação de CPF caso o cliente seja uma pessoa física
* Não consegui utilizar algumas validações dentro de 'Cadastro -> Configuração -> Configurações Cadastrais'

2018-05-14 02:01 UTC, hendrixcosta commented
* O modelo do res.bank está sendo alterado por herança no módulo l10n_br_base, mas as views não estão implementadas por lá. Repensar se esta no lugar certo, para então mover de lugar.

2018-05-14 02:14 UTC, hendrixcosta requested changes

2018-05-14 02:14 UTC, hendrixcosta commented on l10n_br_base/models/res_company.py
> +    legal_name = fields.Char(
Campo Duplicado.

2018-05-14 02:33 UTC, hendrixcosta commented
@sadamo fiz cherry-pick da Formatação do endereço do parceiro. 
É isso mesmo?

2018-05-14 03:16 UTC, hendrixcosta commented
@sadamo Ajuste nos dados de demonstração também.

2018-05-14 03:46 UTC, hendrixcosta commented
Para a validação funcionar tem que setar a cidade e indicar se eh empresa ou individual antes de preencher o campo da IE @sadamo @mileo

2018-05-17 11:18 UTC, hendrixcosta commented on l10n_br_base/models/res_company.py
> +    legal_name = fields.Char(
@mileo

2018-05-17 11:19 UTC, hendrixcosta commented on l10n_br_base/models/res_company.py
> +        company.inscr_est = vals.get('inscr_est')
Se o valor esta dentro do dict, nao esta criando o objeto com o valor ja setado?

2018-05-17 17:59 UTC, rvalyi commented
thanks for the contrib @mileo. We will look at this soon. However please notice that this is new features and we still have PR's for migrating l10n_br_account and l10n_br_account_product which represent the base of the migration and should be dealt in priority before adding new features or making important changes.

2019-04-04 13:51 UTC, hendrixcosta commented
@mileo  Esse módulo ja foi migrado para a branch 10, certo?

2019-04-10 14:23 UTC, mileo commented
Esse PR tem várias features importantes que foram ignoradas.

É importante fazermos um rebase / roadmap destas funcionalidades.

2019-04-10 19:22 UTC, mbcosta commented
Ola @mileo @rvalyi @renatonlima 

    Acredito que na versão 10 deveríamos apenas migrar o código existente na 8, e fazer apenas correções de BUGs ou implementações simples que faltaram da NFe 4.00, qualquer refatoração e melhoria no código deveria ser feita na versão 12, porque e a versão mais atual e provavelmente a versão 10 será usada apenas para fazer a migração dos dados, além de que se pretende refatorar a parte fiscal baseado nos módulos criados pelo generateDS.

Quer dizer por que fazer alterações na versão 10 se teremos que fazer muitas alterações, até de estrutura de módulos, na 12 ?  Não seria melhor migrar o código existente e discutir isso já na última versão e com o modulo pelo menos da NFe já usando o generateDS ?

Se não corremos o risco de acabar tendo que discutir implementações/refatorações na 10 que será pouco usada e voltarmos a discutir na 12, acredito que isso seria um desperdício de tempo/trabalho
penso que temos poucos recursos e tempo para isso.

2019-04-11 02:34 UTC, rvalyi commented
@mbcosta olha que o fato de usar os mixins do generateDS na v12 nao deve impactar o l10n_br_base, pois ele pode ser usado mesmo que sem NFe ou seja vai permanecer com os campos fiscais que ele ja traz, esses apenas terão um mapping no modulo l10n_br_account_nfe (ex l10n_br_account_product). O O l10n_br_accounttb nao sera afetado pelos mixins pelo mesmo motivo mas esse ultimo sera impactado pela extracção do modulo fiscal pelo Renato. Portanto se tem PRs limpos no l10n_br_base, separados por funcionalidade acrescentada, nao necessariamente isso nos atrasa e fazer um cherry pick para a v12 sera mole.

2019-12-17 20:39 UTC, rvalyi commented
@mileo @renatonlima  ainda faz sentido deixar esse PR aberto? Nao poderia ser fechado?

2019-12-17 20:41 UTC, mileo commented
> @mileo @renatonlima ainda faz sentido deixar esse PR aberto? Nao poderia ser fechado?

Por mim pode fechar, mas seria ótimo ver se tem algo de útil nele para não esquecermos

2019-12-17 21:07 UTC, renatonlima commented
Pessoal,

Eu analisei este PR, e eu criei um Issue com o que poderia ser implementado no 12.0/l10n_br_base #762, então eu vou fechar esse PR e deixar o Issue aberto para futuramente poder ser implementado.

2019-12-17 21:07 UTC, closed without merging