[WIP] migrate l10n br account product
OCA/l10n-brazil pull request #602
Opened 2018-05-11 19:31 UTC by renatonlima

2018-08-22 15:12 UTC, mbcosta commented
Implementar https://github.com/OCA/l10n-brazil/pull/615 ( Outras IE ) na criação da NFe

2019-02-18 14:22 UTC, mbcosta commented
Ola @renatonlima resolvi o erro que mostrei na semana passada, em uma empresa (object res.company ) já existente e com os campos Estado e Inscrição Estadual já prenchidos ao tentar alterar qualquer um desses campos ocorria erro de validação do IE no objeto res.partner relacionado ao res.company o erro ocorria porque o campo IE no res.partner ainda tinha o valor antigo, tentei resolver com os metodos inversos nos campos, "onchange" fazendo um "write" no campo mas sem sucesso, o que fiz foi criar um onchange tanto no res.company quanto do res.partner do campo state_id para apagar o inscr_est quando o primeiro for alterado e remover da "constraint" do IE o state_id, por favor verifique se está tudo certo https://github.com/OCA/l10n-brazil/pull/602/commits/8d18d458b4f544131823240b58e8f026a5c0bca7 

Hi Renato I solved the error that showed to you in the last week, at a company ( object res.company ) already existent and with fields State and "Inscrição Estadual"  informed when you tried to change one of this fields occours error in the validation of  "Inscrição Estadual" in object res.partner related to res.company, the error happening because at the moment the program will validation "Inscrição Estadual" the value is the old, I tried to solve with inverse methods in fields, onchange making write in the field but without success, what I doing to solve is create onchange to state_id in res.partner and res.company to clean "Inscrição Estadual" and remove from constraint the field state_id, please take a look on the change  https://github.com/OCA/l10n-brazil/pull/602/commits/8d18d458b4f544131823240b58e8f026a5c0bca7

2019-02-18 14:34 UTC, mbcosta commented
Hi all
    I believe we need to decide if we keep or remove the code that create a NFe TXT file from account.invoice, anyone still use ? Its seems no, because after the changes included in NFe 4.00 layout we don't receive PRs or even issue was open about it, what do you think ?

Ola a todos,
       Eu acredito que precisamos decidir se vamos manter o código que gera o arquivo TXT da NFe a partir do account.invoice, alguém ainda usa ? Aparentemente não, porque depois das mudanças incluídas no leiute da NFe 4.00 nos não recebemos "PRs" ou mesmo um "issue" foi aberto sobre isso, o que pensam ?

cc @renatonlima @rvalyi @mileo

2019-02-18 15:37 UTC, mbcosta commented
Hi PSCs
    The error that make PyLint don't pass is "warning: refname 'origin/10.0' is ambiguous." https://travis-ci.org/OCA/l10n-brazil/jobs/494178898#L771 , seems related with the name of the one of the branchs used, https://stackoverflow.com/questions/12224773/git-refname-master-is-ambiguous . Do have any ideias or tips to solve ?

2019-04-04 14:18 UTC, hendrixcosta requested changes

2019-04-04 14:18 UTC, hendrixcosta commented on l10n_br_zip/__manifest__.py
> +        'demo/l10n_br_zip_demo.xml',
Não ficaria melhor em PR separado?

2019-04-04 14:18 UTC, hendrixcosta commented on l10n_br_sale_product/models/account_invoice_payment.py
> +    _inherit = 'account.invoice.payment'
Acho que alterações desse módulo  l10n_br_sale_product também poderia ficar em PR's separados, ficaria mais fácil revisar.. Ou eu estou viajando?

2019-04-04 14:52 UTC, mbcosta commented on l10n_br_zip/__manifest__.py
> +        'demo/l10n_br_zip_demo.xml',
Olá @hendrixcosta , pelo que lembro, os dados de demo e testes do l10n_br_account_product causavam erro no l10n_br_zip, acredito que gerava erro nos testes de validação do IE por isso foi preciso altera-los aqui, o ideal realmente seria ter feito outro PR

2019-04-04 15:36 UTC, renatonlima commented on l10n_br_sale_product/models/account_invoice_payment.py
> +    _inherit = 'account.invoice.payment'
No PR https://github.com/akretion/l10n-brazil/pull/80 o @gabrielcardoso21 fez algumas tarefas de migração deste PR e sincronizou os trabalhos da NF-e 4.00 feito pelo @mbcosta porém também implementou um desenvolvimento de registro de pagamentos que ainda não estava estável e eu removi esta feature neste PR, mas parece que ficou alguns commits, eu estou revisando agora essa feature não deveria ser implementada na migração já que não estava estável e ser implementada após a migração.

2019-04-05 19:38 UTC, renatonlima commented
@hendrixcosta Sobre a mudança no módulo l10n_br_sale_product eu removi os commits para não sujar o PR

cc @mileo @mbcosta @rvalyi

2019-04-05 19:40 UTC, rvalyi commented
tamos testando aqui com o Clemente para revisar, feedback logo. Parabens pelo enorme trabalho!

2019-04-05 20:54 UTC, mbcosta approved these changes

2019-04-07 15:03 UTC, hendrixcosta requested changes

2019-04-07 15:03 UTC, hendrixcosta commented on l10n_br_account_product/models/account_invoice.py
> +                if self.fiscal_category_id.account_payment_term_id:
Nessa linha deu erro quando tentou acessar ```account_payment_term_id```

Acho que faltou a declaração desse campo no parts/l10n-brazil-wip/l10n_br_account_product/models/l10n_br_account_fiscal_category.py

![image](https://user-images.githubusercontent.com/7250580/55685448-caf50880-592c-11e9-9dcb-0fa80e8f17c5.png)

2019-04-08 02:03 UTC, renatonlima commented on l10n_br_account_product/models/account_invoice.py
> +                if self.fiscal_category_id.account_payment_term_id:
Olá @hendrixcosta na verdade havia um problema de conflito quando removi alguns commits, eu fiz a correção.

2019-04-10 03:03 UTC, hendrixcosta commented
@renatonlima  Ok!
Parabéns pelo trabalho

2019-04-10 03:04 UTC, hendrixcosta approved these changes

2019-04-11 00:16 UTC, rvalyi requested changes
Ola @renatonlima
Novamente parabens pelo enorme trabalho. So vi uns detalhes que seria legal acertar antes do merge:

- vc accrescentou a dependencia do l10n_br_generic no l10n_br_account porem vc usa ele apenas nos dados de demo do modulo l10n_br_account_product (o que eh legal) para os testes. Nao seria melhor entao botar a dependencia no l10n_br_account_product e nao no l10n_br_account?
- o @mbcosta converteu quase todos tests yaml para Python. Porem faltou a conversao do test do refund https://github.com/OCA/l10n-brazil/blob/8.0/l10n_br_account_product/test/account_invoice_refund.yml Accredito que seja facil acrescenta-lo e seria bom nao ter certeza que nao temos regressao nisso. Depois de botar o test, seria legal apagar a antiga pasta test.
- a pasta wizard tem que se chamar wizards https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#14directories isso se resolve com um git mv
- tem um arquivo escondido lixo na pasta security: `.~lock.ir.model.access.csv#`
- o `.travis.yml` deveria ser mais simples. Pois ja tem um `pip install -r requirements.txt` na linha 36. os comandos pip install depois nao deveriam existir, deveria se alterar corretamente o arquivo requirements.txt em vez disso e deveria ser suficente.

Fazendo isso nao tem nada do meu ponto de vista estamos melhor do que a v8 e ja passando os criterios da OCA entao por mim fariamos o merge e as melhorias depois, principalmente na v12 com os mixins do generateDS.

2019-04-13 01:05 UTC, hendrixcosta commented
@rvalyi o que acha de fazer o merge e abrir uma issue para cada item desse?

2019-04-13 13:54 UTC, renatonlima commented
@hendrixcosta O @mbcosta esta fazendo as alterações neste PR, é melhor fazer nesta branch mesmo já que este PR altera estes arquivos.

Só o item 1 eu não será feito, pois a ideia do l10n_br_generic depender do l10n_br_account e que poderia ser carregado o plano de contas e utilizar a contabilidade sem a necessidade de instalar o módulo l10n_br_account_product.

2019-04-15 19:40 UTC, rvalyi approved these changes
All right, thanks @mbcosta !

2019-04-15 20:05 UTC, merged