[12.0] mig l10n br crm
OCA/l10n-brazil pull request #655
Opened 2018-12-28 04:28 UTC by renatonlima

Descrição do problema/nova funcionalidade deste Pull Resquest(PR):
------------------------------------------------------------------

-
-
-

Comportamento atual antes do PR:
--------------------------------

Comportamento esperado depois do PR:
------------------------------------

- [ ] Esta mudança não altera a estrutura do banco de dados, portanto não precisa de script de migração.

--
Eu confirmo que eu assinei a CLA e li as recomendações de como contribuir:
- https://odoo-community.org/page/cla
- https://odoo-community.org/page/Contribute

2019-01-17 13:00 UTC, mbcosta commented
Depends https://github.com/OCA/l10n-brazil/pull/652

2019-02-01 14:57 UTC, BiancaBartolomei approved these changes

2019-02-07 13:11 UTC, BiancaBartolomei commented
Revisei o código, os testes e testei a interface e está tudo correto. No entanto, o travis continua falhando.

2019-02-07 13:27 UTC, rvalyi commented
@BiancaBartolomei obrigado pela sua revisao. Eh normal que o Travis falha, pois nao tem o modulo l10n_br_base nesse PR. Sera preciso um rebase depois que faremos esse merge: https://github.com/OCA/l10n-brazil/pull/652

2019-03-20 04:48 UTC, rvalyi commented
please rebase as we merged l10n_br_base

2019-03-20 05:48 UTC, renatonlima commented
rebased!

2019-04-01 12:58 UTC, rvalyi requested changes
minor Pylint fixes required: https://travis-ci.org/OCA/l10n-brazil/jobs/508758666#L724

2019-04-01 13:40 UTC, hendrixcosta commented
@rvalyi Fiz um PR com as correções que apontou.
https://github.com/akretion/l10n-brazil/pull/83/files

2019-04-01 13:50 UTC, rvalyi commented
@hendrixcosta valeu por contribuir! Fiz o merged na branch da Akretion, vamos ver se estamos verde aqui agora.

Se vc conseguir contribuir, um PR que seria legal acertar eh esse: https://github.com/OCA/l10n-brazil/pull/618
Pois a principio da para acertar ele para a v10 e depois fazer um port trivial na v12 que logo logo essa semana vamos ter o l10n_br_account OK na v12. Entao acertar ele na v10 enquanto isso super adianta.

2019-04-01 13:59 UTC, rvalyi approved these changes

2019-04-01 13:59 UTC, merged

2019-04-01 14:40 UTC, hendrixcosta commented
Obrigado!
De noite vou tentar fazer isso

2019-04-02 01:37 UTC, hendrixcosta commented
@rvalyi O PR #618 da Migração do l10n br account payment mode depende do #602.

Na branch 10.0 o módulo l10n_br_account_product que é dependência do  l10n_br_account_payment_mode nem esta instalável.

Vamos tentar fazer o merge do #602 primeiro?

2019-04-02 02:14 UTC, rvalyi commented
@hendrixcosta hum entendi. Uma pergunta, vc sabe se realmente eh normal ele depender do l10n_br_account_product? Ele nao poderia apenas depender do l10n_br_account? (tou perguntando apenas, eu nao sei).

Outra coisa, depois de um trabalho enorme nos testes, o @renatonlima acabou de botar o Travis verde hoje no #602.

Porem o coverage baixou para 70%. O motivo principal eh que para nao depender do pysped, os testes envolvendo a serializacao dos XMLs das NFe's foram desabilitado.

Ai existem varias possibilidades:

1. ou a gente deixa com esses testes dos XMLs desabilitados por enquanto e foca no outros modulos e na v12 (por mim e pelo @renatonlima pode ser).
2. ou a gente re-habilita os testes com pysped e se vira para deixar o Travis verde.
3. ou a gente anticipa a v12 onde a gente quer permitir o uso de pysped com modulo adicional mas nao quer depender dele mais no l10n_br_account_product (que sera renomeado l10n_br_account_nfe apenas para ficar mais claro). Ai iremos depender de uma lib minimalista que pode ser re-generada com um comando apenas com o generateDS quando aparece uma atualizacao fiscal dos esquemas (vs dias de trabalho manual com o pysped e zero teste). Tou ainda bolando um prototipo que faz o import/export das NFe's no Odoo tudo automatico usando os mixins da NFe daquele PR: https://github.com/OCA/l10n-brazil/pull/658
Isso pode levar ainda umas 3 semanas para estabilizar. E tb estamos focando na v12 e Python 3 para isso.
Agora para anticipar as pegadinhas e testar mais a ideia, o @mbcosta trabalhou em substituir o pysped usando a lib nfelib https://github.com/akretion/nfelib que eh apenas uma parte desse meu trabalho com os XSD's dos documentos fiscais https://github.com/akretion/edoc-gends.
O trabalho do @mbcosta ficou como work in progress aqui: https://github.com/akretion/l10n-brazil/tree/10.0-replace_pysped_for_nfelib
Nele ele usa nfelib em vez de pysped mas ainda faz o mapping com codigo manual do mesmo jeito (enquanto ficara automatico na v12 depois de usar os campos fiscais dos mixins). Seria possivel dar tb mais uma acertada nesse trabalho do Magno e fazer o merge usando nfelib. Sendo que realmente a gente nao quer atrapalhar ninguem que prefere usar o pysped na v10 entao tem que ficar facil de sobre-carregar numa boa.

Pode parecer idiota fazer esses acertos na v10. Porem, temos muitos clientes importantes na v8 ainda e pela minha experiencia com OpenUpgrade, vai ficar bem mais razoavel migrar da v8 para a v10, fazer alguns testes e acertos de dados nos modulos do core e da localizacao e depois da v10 para a v12 do que tentar da v8 para a v12 direito que vai ficar inviavel porque dificil demais de engulir numa etapa apenas. De repente nao eh preciso acertar todos modulos na v10, mas ate esses modulos l10n_br_account_product e  l10n_br_account_payment_mode vale a pena sim. Por fim, a migracao das NFe's pode parecer uma coisa super dificil se a gente passa a mudar muito para usar os mixins na v12. Mas nao eh! Pois a partir do momento que vai suportar o import das NFe's para migrar os dados fiscais da notas do l10n_br_account_product precisara apenas rodar um import do XML das notas. Tou fazendo testes com isso, nao eh mistificação nao.

cc @mileo

2019-04-04 01:47 UTC, hendrixcosta commented
@rvalyi Depende do módulo "l10n_br_account_product" pra colocar o payment_mode na invoice.

Concordo com vocês em desabilitar os teste por agora e focar em outros módulos e na v12, desde que na v12 o código volte a ficar bem coberto com testes.

Seria legal concluirmos a migração de alguns módulos na v10 justamente para preparar para a v12.

2019-04-04 03:06 UTC, rvalyi commented
@hendrixcosta o Magno acertou os testes com pysped na branch do l10n_br_account. Agora tem que revisar. O objetivo eh ficar um pouco mais limpo do que a V8, mas as mudanças grandes mesmo vamos deixar para a v12. Podendo ter backports depois se alguém tiver interessado nisso. O lance do payment não me parece muito legal depender da NF-e só para isso. De repente a gente consegue botar um código condicional e remover a dependência. Tem que ficar simples para uma pequena empresa que só quer nfse e boletos por exemplo, não deve trazer sempre a NF-e. Vou olhar isso...

2019-04-04 14:19 UTC, hendrixcosta commented
@rvalyi 
Dei uma olhado no PR #602  e fiz algumas considerações lá.
Seria esse PR que você falou ali em cima?