pep8
OCA/l10n-brazil pull request #656
Opened 2019-01-26 20:30 UTC by renatonlima

Descrição do problema/nova funcionalidade deste Pull Resquest(PR):
------------------------------------------------------------------

-
-
-

Comportamento atual antes do PR:
--------------------------------

Comportamento esperado depois do PR:
------------------------------------

- [ ] Esta mudança não altera a estrutura do banco de dados, portanto não precisa de script de migração.

--
Eu confirmo que eu assinei a CLA e li as recomendações de como contribuir:
- https://odoo-community.org/page/cla
- https://odoo-community.org/page/Contribute

2019-03-20 19:36 UTC, rvalyi approved these changes

2019-04-04 14:25 UTC, hendrixcosta commented on l10n_br_hr/views/hr_employee_view.xml
> +                                    <!-- <field name="identity_type_id"/> -->
Como já esta atuando no PEP8 poderia remover esse código comentado.

2019-04-04 14:27 UTC, hendrixcosta requested changes

2019-04-04 14:27 UTC, hendrixcosta commented on l10n_br_zip/wizard/l10n_br_zip_search_view.xml
>                          <!-- <separator colspan="8" string="Pesquisar Endereço"/>  -->
Remover código comentado.

2019-05-01 17:59 UTC, renatonlima commented
Os commits deste PR foram importados no PR #602

2019-05-01 17:59 UTC, closed without merging