12.0 mig l10n br account product
OCA/l10n-brazil pull request #657
Opened 2019-03-19 05:29 UTC by renatonlima

Migration l10n_br_account and l10n_br_account_product modules

2019-09-11 20:42 UTC, rvalyi requested changes
There are many things to rewiew. But may be something structuring I can already comment: I suggest to create 2 fiscal user groups:

* simples nacional
* regime normal

eventually the admin user belong to both groups by default (and this could be changed with some profile module later) so he can debug and see everything. Now the benefit would be that a fiscal manager would only see and configure what is important for him: simples or normal regimes.
Moreover is some data is heavy and is required only for the normal regime, then we can load it only when a chart of account for the normal regime is created.

Should we also create some group for users that will only emit NFSe and no NFe under the complex normal regime (to make it simpler then)?

What do you think?

2019-09-19 05:32 UTC, rvalyi requested changes
2 small changes asked for now.

2019-09-19 05:32 UTC, rvalyi commented on l10n_br_fiscal/models/document_abstract.py
> +        required=True)
document_type_id is required however, below the field document_serie_id is required too and the document serie will also carry the l10n_br_fiscal.document.type through the document_type_id required field.
So the model is hyper-constrained. If document_type_id on document.serie is mandatory, then document_type_id on the  l10n_br_fiscal.document object should be a related field.

2019-09-19 05:32 UTC, rvalyi commented on l10n_br_fiscal/hooks.py
> +    from odoo.tools import convert_file
it's better to import outside of the method

2019-09-19 06:40 UTC, rvalyi requested changes
We have a problem with the required fields in l10n_br_fiscal.document:
*  document_serie_id
*  document_type_id
*  key
*  number

You have to think we will soon have in the l10n_br_account module:
```
class AccountInvoice(models.Model):
    _inherit = 'account.invoice'
    _inherits = {'l10n_br_fiscal.document': 'fiscal_document_id'}
```

So with non Brazilian and possibly existing invoices or even draft invoices this will clash!
So unless you have a good default to set for these invoices, then these fields should not be required at the model level. They should be required at the view level and have a python or SQL constraint instead (like when state='open' or only if some field has a certain value).
Note: it's okay to have partner_id required as invoice have it required too.

2019-11-20 16:19 UTC, rvalyi requested changes

2019-11-20 16:19 UTC, rvalyi commented on l10n_br_base/__init__.py
> +def _auto_install_niled(cr, registry):
method name is inappropriate

2020-03-04 19:17 UTC, renatonlima commented
Pessoal,

Acabei de atualizar este PR!

1. Fiz o rebase com a branch OCA/12.0 para atualizar o l10n_br_fiscal
2. E tive que tirar um commit dessa branch que alterava o l10n_br_base/__init__ e que já havia feito o PR #780

Eu acabei vendo que no PR akretion/l10n-brazil/pull/92 teve alguns problema no rebase que corrigi:

- No document.line.abstract o método _set_default_taxes já havia sido removido
- Foi alterado o método _compute_amount que já havia sido refatorado.
- _onchange_product_id não existia mais no document.line.abstract 
- No fiscal.tax deixado alguns comentário (imagino que foi colocando durante os testes com a NF-e) não deveria estar no PR.

Também fez algumas correções:

- A herança dos documentos fiscais estão erradas:

	Deve ser:

	Fiscal Document (Fiscal Document Abstract, Fiscal Document Mixin, Fiscal 	Document Workflow, Document Eletronic)

- Existem campos duplicados no objeto Fiscal Document Eletronic que existiam como is_eletronic, deveria ser usado o fiscal_document_eletronic que já existe no Documento Fiscal.

- Alguns campos que estavam no fiscal.document foram movidos para o fiscal.docment.workflow, como Number, issuer, key, date, mas esses campos deveriam ficar no fiscal.document mesmo.

- Refatorei os wizards do módulo l10n_br_fiscal, vai precisar atualiza-los no l10n_br_nfe, logo eu faço o commit deste wizards lá

2020-03-04 19:30 UTC, mileo commented
Referente aos campos do eletronic, existem documentos que são eletrônicos e não são fiscais. Mas um documento fiscal sempre será um documento eletrônico. 

Mas essas alterações podem ser feitas depois, da pra seguir assim tranquilo e na hora H, refatoramos.

2020-03-06 13:55 UTC, renatonlima commented
Fiscal
------
Fiscal line mixin
----------------

Inserido um campo many2many com o objeto l10n_fiscal.tax para relacionar todos os impostos brasileiros aplicados;
Mover os campos de base de cálculo, percentual, cst, impostos do document.line para o mixin;
Adicionar Campos: Código da receita, código base do PIS e Cofins;
Account tax

Calcular no compute_all os impostos brasileiros;
Fiscal tax

Retenção de impostos, ter os campos:
É retenção;
Data de recolhimento (definido no tax.group)?
Acumular valor?
Valor mínimo para incidência;
Valor máximo para incidência;
Agrupar por valor por parceiro (cnpj);
Definir percentual de recuperação de crédito do ICMS quando simples nacional.
Operation e Operation Line

Operation line mapear os impostos corretamente, retomar os fiscal.tax e os dados fiscais (cst, base, percentual, tipo de base e etc.);
Melhorar filtro para regra de linha de operação fiscal;
Operações subsequentes;

ICMS Regulation
-----------------

 Para cada estado definir valor de ICMS interestadual para produtos nacionais (ICMS 7% e ICMS 12%);
Valor padrão para ICMS Interestadual (ICMS 4%);
Imposto padrão para ICMS interno (ICMS 16%, 17%, 18% e etc.);
Permitir definir com um tax.definition, alíquotas específicas de ICMS interno;
Permitir especificar com um tax.definition os ICMS ST por estados.
Informar o valor do FCP (Fundo de combate de pobreza) por estados, alguns dos estados têm somente uma alíquota FCP outros tem mais de uma;
Company

No create e write do res.company atualizar os tax.definition;

2020-03-07 14:14 UTC, mileo commented
```
2020-03-06 23:49:09,542 175 WARNING openerp_test odoo.models: The model l10n_br_fiscal.document_event has no _description
2020-03-06 23:49:09,551 175 WARNING openerp_test odoo.models: The model l10n_br_fiscal.wizard_document_cancel has no _description
2020-03-06 23:49:09,552 175 WARNING openerp_test odoo.models: The model l10n_br_fiscal.wizard_document_correction has no _description
2020-03-06 23:49:09,645 175 WARNING openerp_test odoo.fields: Field l10n_br_fiscal.document.electronic.cancel_document_event_id with unknown comodel_name 'l10n_br_account.invoice.cancel'
2020-03-06 23:49:09,673 175 WARNING openerp_test odoo.fields: Field l10n_br_fiscal.document.cancel_document_event_id with unknown comodel_name 'l10n_br_account.invoice.cancel'
2020-03-06 23:49:09,796 175 WARNING openerp_test odoo.fields: Field l10n_br_fiscal.document_event.cancel_document_event_id with unknown comodel_name 'l10n_br_account.invoice.cancel'
2020-03-06 23:49:09,796 175 WARNING openerp_test odoo.fields: Field l10n_br_fiscal.document_event.invalid_number_document_event_id with unknown comodel_name 'l10n_br_account.invoice.invalid.number'
2020-03-06 23:49:11,776 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (operation_name, operation_id) of l10n_br_fiscal.document() have the same label: Operation.
2020-03-06 23:49:11,776 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (state_edoc, state) of l10n_br_fiscal.document() have the same label: SituaÃ§Ã£o e-doc.

2020-03-06 23:49:21,179 175 WARNING openerp_test odoo.models: @onchange('icmsfcp_base', 'icmsfcp_percent', 'icmsfcp_reduction', 'icmsfcp_value') parameters must be field names
2020-03-06 23:49:21,179 175 WARNING openerp_test odoo.models: @onchange('icmsfcp_base', 'icmsfcp_percent', 'icmsfcp_reduction', 'icmsfcp_value') parameters must be field names
2020-03-06 23:49:21,179 175 WARNING openerp_test odoo.models: @onchange('icmsfcp_base', 'icmsfcp_percent', 'icmsfcp_reduction', 'icmsfcp_value') parameters must be field names
2020-03-06 23:49:21,179 175 WARNING openerp_test odoo.models: @onchange('icmsfcp_base', 'icmsfcp_percent', 'icmsfcp_reduction', 'icmsfcp_value') parameters must be field names
2020-03-06 23:49:21,179 175 WARNING openerp_test odoo.models: @onchange('icmsst_base', 'icmsst_percent', 'icmsst_reduction', 'icmsst_value') parameters must be field names
2020-03-06 23:49:21,179 175 WARNING openerp_test odoo.models: @onchange('icmsst_base', 'icmsst_percent', 'icmsst_reduction', 'icmsst_value') parameters must be field names
2020-03-06 23:49:21,179 175 WARNING openerp_test odoo.models: @onchange('icmsst_base', 'icmsst_percent', 'icmsst_reduction', 'icmsst_value') parameters must be field names
2020-03-06 23:49:21,179 175 WARNING openerp_test odoo.models: @onchange('icmsst_base', 'icmsst_percent', 'icmsst_reduction', 'icmsst_value') parameters must be field names

2020-03-06 23:49:21,363 175 WARNING openerp_test odoo.models: @onchange('icmsfcp_base', 'icmsfcp_percent', 'icmsfcp_reduction', 'icmsfcp_value') parameters must be field names
2020-03-06 23:49:21,364 175 WARNING openerp_test odoo.models: @onchange('icmsfcp_base', 'icmsfcp_percent', 'icmsfcp_reduction', 'icmsfcp_value') parameters must be field names
2020-03-06 23:49:21,364 175 WARNING openerp_test odoo.models: @onchange('icmsfcp_base', 'icmsfcp_percent', 'icmsfcp_reduction', 'icmsfcp_value') parameters must be field names
2020-03-06 23:49:21,364 175 WARNING openerp_test odoo.models: @onchange('icmsfcp_base', 'icmsfcp_percent', 'icmsfcp_reduction', 'icmsfcp_value') parameters must be field names
2020-03-06 23:49:21,364 175 WARNING openerp_test odoo.models: @onchange('icmsst_base', 'icmsst_percent', 'icmsst_reduction', 'icmsst_value') parameters must be field names
2020-03-06 23:49:21,364 175 WARNING openerp_test odoo.models: @onchange('icmsst_base', 'icmsst_percent', 'icmsst_reduction', 'icmsst_value') parameters must be field names
2020-03-06 23:49:21,364 175 WARNING openerp_test odoo.models: @onchange('icmsst_base', 'icmsst_percent', 'icmsst_reduction', 'icmsst_value') parameters must be field names
2020-03-06 23:49:21,364 175 WARNING openerp_test odoo.models: @onchange('icmsst_base', 'icmsst_percent', 'icmsst_reduction', 'icmsst_value') parameters must be field names

2020-03-06 23:54:45,729 175 WARNING openerp_test odoo.fields: Field l10n_br_fiscal.document.cancel_document_event_id with unknown comodel_name 'l10n_br_account.invoice.cancel'

2020-03-06 23:54:46,797 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (operation_name, operation_id) of l10n_br_fiscal.document() have the same label: Operation.
2020-03-06 23:54:46,797 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (state_edoc, state) of l10n_br_fiscal.document() have the same label: SituaÃ§Ã£o e-doc.
2020-03-06 23:54:46,797 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (fiscal_doc_partner_id, partner_id) of l10n_br_fiscal.document() have the same label: Partner.
2020-03-06 23:54:46,797 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (fiscal_doc_date, date) of l10n_br_fiscal.document() have the same label: Date.
2020-03-06 23:54:46,797 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (fiscal_doc_company_id, company_id) of l10n_br_fiscal.document() have the same label: Company.
2020-03-06 23:54:46,798 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (fiscal_doc_state, state) of l10n_br_fiscal.document() have the same label: SituaÃ§Ã£o e-doc.
2020-03-06 23:54:46,798 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (currency_id, fiscal_doc_currency_id) of l10n_br_fiscal.document() have the same label: Currency.
2020-03-06 23:54:46,839 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (fiscal_doc_line_name, name) of l10n_br_fiscal.document.line() have the same label: Name.
2020-03-06 23:54:46,839 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (fiscal_doc_line_partner_id, partner_id) of l10n_br_fiscal.document.line() have the same label: Partner.
2020-03-06 23:54:46,840 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (fiscal_doc_line_company_id, company_id) of l10n_br_fiscal.document.line() have the same label: Company.
2020-03-06 23:54:46,840 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (fiscal_doc_line_currency_id, currency_id) of l10n_br_fiscal.document.line() have the same label: 

2020-03-06 23:54:46,840 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (fiscal_doc_line_product_id, product_id) of l10n_br_fiscal.document.line() have the same label: Product.
2020-03-06 23:54:46,840 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (fiscal_doc_line_uom_id, uom_id) of l10n_br_fiscal.document.line() have the same label: UOM.
2020-03-06 23:54:46,840 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (fiscal_doc_line_quantity, quantity) of l10n_br_fiscal.document.line() have the same label: Quantity.
2020-03-06 23:54:46,840 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (fiscal_doc_line_price, price) of l10n_br_fiscal.document.line() have the same label: Price Unit.
2020-03-06 23:54:46,840 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (fiscal_doc_line_discount, discount_value) of l10n_br_fiscal.document.line() have the same label: Discoun

2020-03-06 23:54:46,916 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (fiscal_doc_partner_id, partner_id) of account.invoice() have the same label: Partner.
2020-03-06 23:54:46,916 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (fiscal_doc_company_id, company_id) of account.invoice() have the same label: Company.
2020-03-06 23:54:46,916 175 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (operation_name, operation_i [...]

2020-03-07 14:17 UTC, mileo commented
Pessoal sobre os warnings, acho melhor aguardar o @renatonlima finalizar a questão da FCP e o @gabrielcardoso21 finalizar a questão dos wizards para evitar conflitos.

Vou conversar com o Gabriel na segunda para ele verificar os warnings da parte que ele esta atuando. @renatonlima se vc for trabalhar no FCP esse fds e puder ver isso, se não deixa que vemos na segunda.

2020-03-26 04:38 UTC, rvalyi requested changes
Some English mistakes:
change `DocumentFiscalMixin` to `FiscalDocumentMixin` https://github.com/akretion/l10n-brazil/blob/12.0-mig-l10n_br_account_product/l10n_br_fiscal/models/document_fiscal_mixin.py#L11

Same with the line:
change `DocumentFiscalLineMixin` to `FiscalDocumentLineMixin`
https://github.com/akretion/l10n-brazil/blob/12.0-mig-l10n_br_account_product/l10n_br_fiscal/models/document_fiscal_line_mixin.py

I have no problem with the file names and _name attributes.

In the dashboard, the word `Receivement` doesn't exist. I suggest changing it to `Vendor` in the same logic as the Odoo `Vendor bills` for suppliers. But may be somebody has a better name...

2020-03-26 18:32 UTC, mileo commented
> Some English mistakes:
> change `DocumentFiscalMixin` to `FiscalDocumentMixin` https://github.com/akretion/l10n-brazil/blob/12.0-mig-l10n_br_account_product/l10n_br_fiscal/models/document_fiscal_mixin.py#L11
> 
> Same with the line:
> change `DocumentFiscalLineMixin` to `FiscalDocumentLineMixin`
> https://github.com/akretion/l10n-brazil/blob/12.0-mig-l10n_br_account_product/l10n_br_fiscal/models/document_fiscal_line_mixin.py
> 
> I have no problem with the file names and _name attributes.
> 
> In the dashboard, the word `Receivement` doesn't exist. I suggest changing it to `Vendor` in the same logic as the Odoo `Vendor bills` for suppliers. But may be somebody has a better name...

Raphael, no caso não estamos agrupando clientes e fornecedores.

E sim entrada (compras e devolução de venda) e saída (vendas e devoluções de compra).

Concordo contigo que a palavra Receivement não existe. Qual seria a palavra correta para colocar no lugar? Não vale a pena deixar em português?

2020-03-26 19:06 UTC, rvalyi commented
> Raphael, no caso não estamos agrupando clientes e fornecedores.
> 
> E sim entrada (compras e devolução de venda) e saída (vendas e devoluções de compra).

Mas as notas de demo nao se enquadram nisso? Nao deveriam pelo menos? Eu acho meio estranho instalar o modulo com dados de demo e nao encontrar nada nesse Dashboard. Isso de fuçar com os dados de demo, vai ser a forma que muita gente vai testar o modulo, ver se tem aderência... Não teria como melhorar isso?

> 
> Concordo contigo que a palavra Receivement não existe. Qual seria a palavra correta para colocar no lugar? Não vale a pena deixar em português?

Concordo, na ausência de um termo inglês bom, fica melhor deixar em portugues.

2020-03-26 20:01 UTC, mileo commented
> > Raphael, no caso não estamos agrupando clientes e fornecedores.
> > E sim entrada (compras e devolução de venda) e saída (vendas e devoluções de compra).
> 
> Mas as notas de demo nao se enquadram nisso? Nao deveriam pelo menos? Eu acho meio estranho instalar o modulo com dados de demo e nao encontrar nada nesse Dashboard. Isso de fuçar com os dados de demo, vai ser a forma que muita gente vai testar o modulo, ver se tem aderência... Não teria como melhorar isso?
> 
> > Concordo contigo que a palavra Receivement não existe. Qual seria a palavra correta para colocar no lugar? Não vale a pena deixar em português?
> 
> Concordo, na ausência de um termo inglês bom, fica melhor deixar em portugues.

Quanto aos dados de demo esqueci de te responder, vou pedir para o @gabrielcardoso21 olhar isso.

2020-04-03 20:49 UTC, clementmbr commented
@renatonlima I tried the l10n_br_fiscal yesterday and it looks really cool ! 
Just one detail, the `fiscal_genre_id` in products is called "Fiscal Genre" whereas in the menu Fiscal > Configuration it's called "Product Genre"... It might be better to use the same name for the same object in the whole module.

Thank you !

2020-04-04 23:14 UTC, renatonlima commented on l10n_br_base/__init__.py
> +def _auto_install_niled(cr, registry):
I removed this commit

2020-04-04 23:16 UTC, renatonlima commented
@clementmbr 

Thank you for your review, I named this object to Fiscal Genre.

2020-04-07 01:01 UTC, mileo approved these changes

2020-04-07 01:05 UTC, rvalyi approved these changes
Kudos for this huge piece of work!!!

2020-04-07 01:06 UTC, rvalyi commented
/ocabot merge

2020-04-07 01:07 UTC, hendrixcosta approved these changes

2020-04-07 01:08 UTC, hendrixcosta commented
Parabens pelo trabalho, pessoal

2020-04-07 01:26 UTC, gabrielcardoso21 approved these changes

2020-04-07 01:55 UTC, rvalyi commented
/ocabot merge

2020-04-07 03:07 UTC, rvalyi commented
So, all Ocabot tests are passing but for some unknown reason the merge does not occur despite 2 attempts.
I could find recent example of Ocabot merges that worked some 13 hours before our try:
https://github.com/OCA/purchase-workflow/pull/886
and I could also find another example were the merge didn't happen in a similar way, 5 days before:
https://github.com/OCA/purchase-workflow/pull/881

So instead of keeping hunting for the problem with the Ocabot, I'll merge this manually then. All Ocabot tasks are expected to run nightly anyway. The merge command is really more of a guard to prevent from merging stuff that doesn't pass tests, specially when stuff is merged just before, which will not be our case here. Hopefully we find out later what the problem is.

2020-04-07 03:07 UTC, merged

2020-04-07 05:21 UTC, rvalyi commented
Hum, so actually Travis and Runbot tests passed with Ocabot, but we had a .pot generation issue during the i18n msgmerge attempt: 
https://travis-ci.org/github/OCA/l10n-brazil/jobs/671928547#L2273
```
2020-04-07 04:15:36,183 7009 ERROR openerp_test click_odoo.env_options: exception 
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click_odoo/env_options.py", line 214, in _invoke
    return self.org_invoke(ctx)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click_odoo_contrib/makepot.py", line 122, in main
    commit_message,
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click_odoo_contrib/makepot.py", line 70, in export_pot
    raise click.ClickException("%d invalid .po file(s) found" % invalid_po)
click.exceptions.ClickException: 1 invalid .po file(s) found
Error: 1 invalid .po file(s) found
```
Hopefuly this is an easy fix.

It is also unclear to me what the exact status of the portal test:
https://travis-ci.org/github/OCA/l10n-brazil/jobs/671928547#L2070