[10.0][MIG] l10n_br_account_payment_mode
OCA/l10n-brazil pull request #684
Opened 2019-05-14 13:58 UTC by mbcosta

Replace PR https://github.com/OCA/l10n-brazil/pull/618 because Odoo-Brazil is a common repository where people from different companies can work together.

2019-05-16 16:33 UTC, mbcosta commented
Para quem for fazer a revisão desse modulo mais importante do que o código e as visões em si o principal a ser visto são as mudanças que ocorreram nos módulos dependentes no https://github.com/OCA/bank-payment/tree/10.0 reestrutura dos módulos e campos alterados/excluídos:

* Campo payment_order_type agora é payment_type, e configurado dentro do objeto account.payment.method e dentro do objeto account.payment.mode possui um campo "related"

* Modulo account_banking_payment_export foi unificado com o account_payment no account_payment_order https://github.com/OCA/bank-payment/issues/222

* Campo ir_model_id ( 'Select the Payment Wizard for payments of this type. Leave empty for manual
 processing' ) do antigo objeto payment.mode.type excluído

* Campos sale_ok e purchase_ok removidos https://github.com/OCA/bank-payment/blob/10.0/account_payment_mode/models/account_payment_mode.py#L55

# I dropped sale_ok and purchase_ok fields, because it is replaced by
# payment_type = 'inbound' or 'outbound'
# In fact, with the new v9 datamodel, you MUST create 2 payment modes
# for wire transfer : one for wire transfer from your customers (inbound)
# and one for wire transfer to your suppliers (outbound)

* Campo journal no objeto account.payment.mode substituido por fixed_journal_id e variable_journal
_ids

Conversando com o @renatonlima sobre essa reestrutura do módulos, chegamos a conclusão que o melhor será reestruturar os módulos na localização também:

*  Movendo o que for referente ao Método de Pagamento para o l10n_br_account_product e adicionando nesse modulo a dependência do account_payment_mode ( https://github.com/OCA/bank-payment/tree/10.0/account_payment_mode )

* Juntar os modulos l10n_br_account_banking_payment e esse modulo l10n_br_account_payment_mode em um novo modulo l10n_br_account_payment_order seguindo a mesma estrutura dos módulos no repositório bank-payment

Pretendo fazer isso em outro PR para facilitar a revisão deste.

cc @rvalyi @mileo

2019-05-16 16:38 UTC, renatonlima commented
LGTM

Como este módulo vai ser juntar com o atual l10n_br_bank_payment (futuro l10n_br_account_payment_order) algumas mudanças serão feitas no PR de refactoring.

2019-05-16 16:38 UTC, renatonlima approved these changes

2019-05-16 19:01 UTC, mileo requested changes
@mbcosta qual a diferença entre type_sale_payment e type_payment? E por que o label dos dois campos é o mesmo?

2019-05-16 19:21 UTC, mbcosta commented
ola @mileo , obrigado pela revisão

Na verdade isso veio ainda dos modulos extraídos do repo no odoo-brazil-banking https://github.com/odoo-brazil/odoo-brazil-banking/blob/8.0/l10n_br_account_payment_mode/models/payment_mode.py#L39 https://github.com/odoo-brazil/odoo-brazil-banking/blob/8.0/l10n_br_account_payment_mode/models/payment_mode.py#L44 pelo que vi esse campo é na verdade esse https://github.com/OCA/l10n-brazil/blob/10.0/l10n_br_account_product/models/account_payment_mode.py#L12 portanto no PR que irá juntar os modulos esses dois campos serão apagados, eu posso já apaga-los agora, o que acha ?

2019-05-16 19:44 UTC, mileo commented
@mbcosta na verdade este campo deve ser mantido e renomeado.

http://sped.rfb.gov.br/estatico/AE/B0DEF8D93F24CB4EEFE8AD1443A14E7E8F4319/GUIA%20PR%c3%81TICO%20EFD%20ICMS%20IPI%20-%20Vers%c3%a3o%203.01.pdf

![image](https://user-images.githubusercontent.com/1975978/57882200-8bf28680-77f9-11e9-98c2-086f96ccdd99.png)

E no futuro ainda temos que considerar: https://github.com/odoo-brazil/odoo-brazil-hr/tree/develop/l10n_br_hr_payment_order

Por mim vc pode renomear ele e já remover o campo logo a baixo.

2019-05-17 15:34 UTC, renatonlima commented
@mileo,

Você ver alguma funcionalidade neste campo na implementação neste módulo? Porque pelo que eu vi deveria estar apenas um campo type_payment como a informação do Tipo de pagamento da NFe que é usado para a criação da NFe. O campo type_sale_payment que contém o "Indicador do tipo de titulo de crédito" é um campo do layout do SPED e não é usado no layout da NFe e em nenhum outro lugar, não vejo sentido de ter este campo neste módulo ou no módulo l10n_br_account_payment_order. Também me parece que tem um erro de designer https://github.com/OCA/l10n-brazil/pull/684/files#diff-4c23780d1f885b410635a122d63bbc5eR24 Dentro da aba de cobrança tem informações base do CNAB e tem abas com o valores deste campo, como cheque, recibo, nota promissória. Mas essas questões podem ser tratada no refactoring que o Magno esta trabalhando, pois esse PR estamos tratando apenas a migração do código.

2019-05-17 19:35 UTC, mbcosta commented
ola @mileo 
Removi os dois campos, conforme você e o @renatonlima comentaram esses campos são usados somente nos documentos do SPED e não na NFe, portanto acredito que o melhor será implementa-los em outro modulo e objeto na versão 12 se baseando nos modulos de SPED que serão criados.

2019-05-17 20:58 UTC, mileo approved these changes

2019-05-17 20:59 UTC, merged