[FIX] Travis error of l10n_br_resource
OCA/l10n-brazil pull request #689
Opened 2019-05-15 15:51 UTC by mileo

Signed-off-by: Luis Felipe Mileo <mileo@kmee.com.br>

2019-05-15 16:31 UTC, renatonlima approved these changes

2019-05-15 18:57 UTC, hendrixcosta approved these changes

2019-05-16 03:07 UTC, rvalyi requested changes
It looks like Travis is unhappy https://travis-ci.org/OCA/l10n-brazil/jobs/532887301
I'm not too sure, but it looks it's because of the ```unicode_literals``` import that some str objects are changed into unicode and makes the test runner unhappy.
```
File "/usr/lib/python2.7/unittest/runner.py", line 44, in getDescription
doc_first_line = test.shortDescription()
File "/home/travis/odoo-10.0/odoo/tests/common.py", line 135, in shortDescription
return doc and ' '.join(filter(None, map(str.strip, doc.splitlines()))) or None
TypeError: descriptor 'strip' requires a 'str' object but received a 'unicode'
```

2019-05-16 14:10 UTC, hendrixcosta approved these changes

2019-05-16 14:15 UTC, rvalyi approved these changes

2019-05-16 14:16 UTC, renatonlima approved these changes

2019-05-16 14:17 UTC, merged