[12.0][MIG] l10n_br_account_payment_order
OCA/l10n-brazil pull request #702
Opened 2019-06-06 18:46 UTC by mbcosta

Migration of module l10n_br_account_payment_order

cc @renatonlima @rvalyi @mileo

2019-06-06 18:59 UTC, renatonlima requested changes

2019-06-06 18:59 UTC, renatonlima commented on l10n_br_account_payment_order/README.rst
> +* account_payment_order
Please, update depedencies

2019-06-06 18:59 UTC, renatonlima commented on l10n_br_account_payment_order/__init__.py
> +# -*- coding: utf-8 -*-
This comment is not necessary in Python 3

2019-06-06 18:59 UTC, renatonlima commented on l10n_br_account_payment_order/__manifest__.py
> +        'l10n_br',
This depedency is not necessary because a Company can create own chart of account

2019-06-06 18:59 UTC, renatonlima commented on l10n_br_account_payment_order/models/account_payment_line.py
> +# -*- coding: utf-8 -*-
This comment is not necessary in Python 3

2019-06-06 18:59 UTC, renatonlima commented on l10n_br_account_payment_order/models/account_move_line.py
> +# -*- coding: utf-8 -*-
This comment is not necessary in Python 3

2019-06-06 18:59 UTC, renatonlima commented on l10n_br_account_payment_order/models/__init__.py
> +# -*- coding: utf-8 -*-
This comment is not necessary in Python 3

2019-06-06 18:59 UTC, renatonlima commented on l10n_br_account_payment_order/models/account_payment_mode.py
> +# -*- coding: utf-8 -*-
This comment is not necessary in Python 3

2019-06-06 18:59 UTC, renatonlima commented on l10n_br_account_payment_order/models/account_payment_mode.py
> +    internal_sequence_id = fields.Many2one('ir.sequence', u'Sequência')
You can remove character u in strings, it's not necessary in Python 3

2019-06-06 18:59 UTC, renatonlima commented on l10n_br_account_payment_order/models/res_partner_bank.py
> +# -*- coding: utf-8 -*-
This comment is not necessary in Python 3

2019-06-06 18:59 UTC, renatonlima commented on l10n_br_account_payment_order/tests/__init__.py
> +# -*- coding: utf-8 -*-
This comment is not necessary in Python 3

2019-06-06 18:59 UTC, renatonlima commented on l10n_br_account_payment_order/tests/test_payment_order.py
> +# -*- coding: utf-8 -*-
This comment is not necessary in Python 3

2019-06-06 18:59 UTC, renatonlima commented on l10n_br_account_payment_order/views/account_payment_line.xml
> +        <record id="l10n_br_banking_account_payment_line_form" model="ir.ui.view">
I think you can update this id, now this modulo's name is l10n_br_account_payment_order

2019-06-06 19:21 UTC, rvalyi requested changes
thanks. You should alter the oca_dependencies.txt and add the bank-payment OCA repo for Travis to stop complaining about the missing account_payment_order module.

2019-06-06 20:27 UTC, mbcosta commented
Thanks for review @renatonlima @rvalyi 

I fixed what you pointed, there only one remains dependency from l10n_br I'm looking a way to remove, log with error: 

  File "/odoo/src/addons/account/models/account_invoice.py", line 802, in _onchange_partner_id
    raise RedirectWarning(msg, action.id, _('Go to the configuration panel'))
odoo.tools.convert.ParseError: "Não foi possível encontrar um plano de contas para essa empresa, Você deve configurar um. Vá a Configuração Contábil.
225
Vá para o painel de configuração" while parsing /odoo/external-src/l10n-brasil-payment_order/l10n_br_account_payment_order/demo/account_payment_order_demo.xml:15

2019-12-17 16:34 UTC, renatonlima commented
@mbcosta 

Can you fix and rebase this PR?

2019-12-18 13:00 UTC, mileo commented
@mbcosta por favor da uma olhada nesses 4 commits https://github.com/OCA/l10n-brazil/pull/765

2019-12-18 17:14 UTC, mbcosta commented
Ola @mileo , ok estou aguardando o merge para fazer o "cherry picking" .

Vendo o código com o @renatonlima alteramos o retorno campo journal_entry_ref ( tipo "compute" ) na revisão seria importante confirmar se ainda está de acordo com o esperado.

2019-12-18 17:26 UTC, rvalyi commented
@mbcosta o merge do #765 ja foi feito essa manha...

2019-12-18 18:21 UTC, mbcosta commented
@mileo os commits que você pediu foram incluídos.

ola @rvalyi , aprovamos pela manhã mas o merge só ocorreu a cerca de uma hora

![image](https://user-images.githubusercontent.com/6341149/71112260-e0a01a80-21a9-11ea-9c5d-4030044adcdf.png)

2019-12-18 18:31 UTC, mileo approved these changes

2019-12-18 18:34 UTC, renatonlima approved these changes

2019-12-18 18:48 UTC, luismalta approved these changes

2019-12-18 19:05 UTC, renatonlima requested changes

2019-12-18 19:05 UTC, renatonlima commented on l10n_br_account_payment_order/views/account_payment_order_menu_views.xml
> +    <menuitem id="account_payment_order.account_payment_order_outbound_menu"
tem que adicionar o atributo action, porque senão a descrição do menu vai ficar errada

2019-12-18 19:43 UTC, mbcosta commented on l10n_br_account_payment_order/views/account_payment_order_menu_views.xml
> +    <menuitem id="account_payment_order.account_payment_order_outbound_menu"
Valeu @renatonlima , corrigido

2019-12-18 19:44 UTC, mileo approved these changes

2019-12-18 19:57 UTC, renatonlima approved these changes

2019-12-18 21:21 UTC, sadamo approved these changes

2019-12-18 21:30 UTC, sadamo commented
/ocabot-merge

2019-12-18 21:41 UTC, renatonlima commented
/ocabot merge

2019-12-18 21:44 UTC, rvalyi commented
:pizza: 
:pizza: 
:pizza:

2019-12-18 21:50 UTC, rvalyi approved these changes

2019-12-18 21:54 UTC, merged