Adiciona a lib erpbrasil.base
OCA/l10n-brazil pull request #705
Opened 2019-07-24 19:56 UTC by mileo

Recentemente movi os códigos da pasta tools para uma lib chamada: https://github.com/erpbrasil/erpbrasil.base mantendo todos os copyrights. 

Enumero alguns benefícios e objetivos desta mudança:

1. - Criar uma base sólida para criarmos novas libs que dependam de validações de cpf, cnpj e etc;
2. - Facilitar a contribuição, pessoas que encontrem a biblioteca e posteriormente encontrem a localização;
3. - Remover os testes python (não Odoo) e deixar eles por conta da biblioteca, aumentando a velocidade dos nosso travis;

OBS: Caso estejam trabalhando com a migração e utilize algum código da pasta tools fiquem atentos pois ela é removida neste PR.

2019-08-15 14:35 UTC, renatonlima commented
Um teste de inscrição estadual falhou [https://travis-ci.org/OCA/l10n-brazil/jobs/563252336#L1185](https://travis-ci.org/OCA/l10n-brazil/jobs/563252336#L1185)

2019-08-15 14:37 UTC, renatonlima requested changes
Tem um erro em um dos testes de inscrição estadual [https://travis-ci.org/OCA/l10n-brazil/jobs/563252336#L1185](https://travis-ci.org/OCA/l10n-brazil/jobs/563252336#L1185)

2019-08-30 18:20 UTC, rvalyi commented
@mileo alguma posição sobre esse erro? Parece algo simples... E seria bom a gente acertar logo esse merge...

2019-09-03 17:05 UTC, mileo commented
@rvalyi Quando realizei o port verifiquei que algumas validações não estavam boas. Estavam retornando um falso positivo e comentei os testes https://github.com/erpbrasil/erpbrasil.base/blob/master/tests/test_base_validate_ie.py

Isso esta ocorrendo justamente neste caso.

2019-09-03 17:59 UTC, mileo commented
> @rvalyi Quando realizei o port verifiquei que algumas validações não estavam boas. Estavam retornando um falso positivo e comentei os testes https://github.com/erpbrasil/erpbrasil.base/blob/master/tests/test_base_validate_ie.py
> 
> Isso esta ocorrendo justamente neste caso.

@rvalyi mas já coloquei alguém para corrigir esses falsos positivos.

2019-09-03 22:10 UTC, mileo commented
@rvalyi @renatonlima alguma ideia do que seja esse erro no lint?

2019-09-04 13:30 UTC, mileo commented
@renatonlima @rvalyi corrigido a validação da IE: https://github.com/erpbrasil/erpbrasil.base/pull/2

2019-09-07 19:18 UTC, renatonlima commented
@mileo, please rebase the branch to we review this PR because last merge in 12.0 (featured pycep) this PR will have a conflicts to resolve manually.

2019-09-10 12:02 UTC, mileo commented
@renatonlima 

git pull -r oca 12.0 
From github.com:oca/l10n-brazil
 * branch              12.0       -> FETCH_HEAD
Current branch 12.0-erpbrasil-base is up to date.

2019-09-10 18:49 UTC, rvalyi requested changes
@mileo great overall. However you are adding the l10n_br_zip_correios folder again and that module was killed as it was integrated in l10n_br_zip. Can you make sure you delete it entirely in this PR? Hopefully it may also prevent Weblate to rescucitate it as it happened recently in 12.0.
cc @renatonlima

2019-09-11 13:12 UTC, gabrielcardoso21 commented
@rvalyi Removi o commit com o módulo l10n_br_zip_correios.

2019-09-11 13:53 UTC, renatonlima approved these changes

2019-09-11 14:29 UTC, rvalyi approved these changes

2019-09-11 14:30 UTC, rvalyi commented
/ocabot merge

2019-09-11 15:05 UTC, renatonlima commented
@gabrielcardoso21 Can you remove this file https://github.com/kmee/l10n-brazil/blob/12.0-erpbrasil-base/l10n_br_zip_correios/i18n/l10n_br_zip_correios.pot

2019-09-11 17:02 UTC, gabrielcardoso21 commented
@renatonlima fiz um commit de remoção do arquivo que você pediu.

2019-09-11 17:19 UTC, rvalyi commented
/ocabot sudo hadouken!

2019-09-11 17:21 UTC, rvalyi commented
/ocabot merge

2019-09-13 19:48 UTC, rvalyi commented
se alguem consegue entender o erro na geracao dos .po
https://travis-ci.org/OCA/l10n-brazil/jobs/583767067#L1429
fique a vontade...

2019-09-13 20:30 UTC, mileo commented
@rvalyi 
Fiz um PR https://github.com/OCA/l10n-brazil/pull/714/files para remover o arquivo de tradução perdido, podemos tentar fazer o merge dele antes e depois o rebase.

2019-09-13 20:34 UTC, mileo commented
@rvalyi rebased

2019-09-13 20:35 UTC, rvalyi commented
/ocabot merge

2019-09-13 20:55 UTC, rvalyi commented
still no luck :-(
https://travis-ci.org/OCA/l10n-brazil/jobs/584763662#L1428

2019-09-16 17:52 UTC, renatonlima commented
Hi Guys,

I saw those two files are outdated: l10n_br_crm/i18n/pt_BR.po and l10n_br_zip/i18n/pt_BR.po, I removed those files and created one new PR to replace it

2019-09-16 18:28 UTC, merged

2019-09-16 18:31 UTC, renatonlima commented
Victory! 🥇