[12.0] Migration l10n_br_hr
OCA/l10n-brazil pull request #713
Opened 2019-09-13 19:30 UTC by luismalta

- [ ] Tornar o modulo instalável na versão 12.0 
- [ ] Up port funcionalidades https://github.com/abgfbr/l10n-brazil/tree/8.0/l10n_br_hr
- [ ] Separar os modelos em arquivos independentes

2019-09-13 20:26 UTC, rvalyi commented
Ola @luismalta. Valeu pela contribuição! Porem, tem uns erros de pep8, ve aqui
https://travis-ci.org/OCA/l10n-brazil/jobs/584741887#L516
seguindo os guidelines da OCA, vc nao deveria ter esses erros:
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#tasks-to-do-in-the-migration

Como vc esta migrando da v10 para a v12, vc tem que seguir as instrucoes da migracao para a v11:
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0
e para a v12:
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

Tem uns errors nos tests tb https://travis-ci.org/OCA/l10n-brazil/jobs/584741888#L1296

2019-09-16 19:48 UTC, mileo commented
@luismalta the yml files are deprecated, please migrate the test to a xml file.

2019-09-18 20:20 UTC, mileo commented
@luismalta esta função não existe mais https://travis-ci.org/OCA/l10n-brazil/jobs/586680983#L1288

foi movida para esta lib https://github.com/erpbrasil/erpbrasil.base/tree/master/src/erpbrasil/base

2019-09-23 18:54 UTC, rvalyi commented
@mileo, tou vendo os ultimos commits. Tou vendo muitos modelos que parecem que estão ai para satisfazer o esocial. Se for para o esocial, a meu ver tem que dar uma pensadinha, porque da mesma forma do que para a nfe, eh possivel gerir todos objetos e campos a partir dos esquemas do e-social. Principlamente na v12 que vamos usar isso para varios documentos electronicos e talvez todos.
Pode ser que tou me enganando que nao olhei muito ainda. Mas apenas eu queria deixar o aviso.
Olha aqui por examplo os modelos que vem do e-social:
https://github.com/OCA/l10n-brazil/pull/665/files

Na minha opiniao tem que fazer que nem na nfe, tem que focar apenas nos objetos que tem um significado forte no Odoo ou na OCA, os outros que sao apenas da papelaria fiscal, da para usar os modelos geridos que ai, vc tem importação e exportação tudo automatico sem dor de cabeçá e quase sem custo de manutenção.

Os mixins do esocial tem a especificidade de que os labels dos campos nao estão definidos legal nos esquemas. Mas ai eu penso definir um hook no plugin gerador que le um csv com os nomes que vc quiser definir melhor. No caso, com camelot, acho que eh facil fazer um script de 20 linhas que vai ler o pdf do manual do escosial e criar um csv de labels ja legal para usar no gerador. Assim como faco no caso dos arquivos do SPED. Posso mostrar qual eh a ideia se for o caso.

2019-09-26 19:15 UTC, rvalyi commented
Pessoal, pretendo revisar essa questao dos novos objetos que foram accrescentados no modulo esses dias. Numa olhada rapida parecem simples, porem eu pretendo checar melhor. Novamente eu queria evitar da gente sobre-carregar de codigo manual que poderia vir do gerador generateDS na hora que alguem quiser fazer o e-social. Realmente se todos novos modelos sao simples nao cria divida tecnologica mas pretendo apenas verificar ainda...

2019-10-10 13:33 UTC, rvalyi commented
@luismalta poderia dar um rebase rebase em cima da 12.0 atualizada aqui por favor? (para acertar o Runbot)

2019-10-10 14:13 UTC, mileo commented
> @luismalta poderia dar um rebase rebase em cima da 12.0 atualizada aqui por favor? (para acertar o Runbot)

@rvalyi 

Foi justamente o que ele fez hoje cedo, eu tinha pedido pra ele fazer na daily mas acabei nas postando aqui.

O runbot subiu mas seu status não esta legal, vc sabe o por que? https://runbot.odoo-community.org/runbot/build/3390295

2019-10-10 14:17 UTC, mileo commented
@rvalyi Outra coisa... 

Reforçando o que comentei contigo mês passado, preferimos não utilizar o mixin do GenerateDS no e-social por enquanto, vamos trabalhar na migração e aumentar a cobertura de testes e também na  refatoração do motor de folha de pagamento.

Isso deve dar trabalho suficiente para muito tempo, pois os calculus são muito complexos e os casos de uso mais ainda.

E não gostaríamos de fazer duas mudanças ao mesmo tempo.

Pode ser o caso apenas de utilizar o GenerateDS na serialização.

Então nas novas versões vamos utiliza-lo para montar os objetos, mas para isso já teremos casos de uso com testes de acordo.

2019-10-10 17:50 UTC, hendrixcosta requested changes

2019-10-10 17:50 UTC, hendrixcosta commented on l10n_br_hr/models/hr_employee.py
> +    cpf = fields.Char(
Esse campo não deveria ficar centralizado no partner? ou pelo menos um related

2019-10-10 17:51 UTC, hendrixcosta requested changes

2019-10-10 17:51 UTC, hendrixcosta commented on l10n_br_hr/models/hr_job.py
> +        comodel_name='l10n_br_hr.cbo')
Não falta um name para o modelo ?

2019-10-10 18:43 UTC, rvalyi commented
Ola @mileo eu realmente nao sei dizer o porque do status do Runbot deu ruim. Mas eh capaz que seja um problema mesmo de analise dos logs do Runbot, A gente pode imaginar que seja por causa dos WARNING no log aqui https://runbot3.odoo-community.org/runbot/static/build/3390295-713-1c722d/logs/job_20_test_all.txt pois ao meu ver so isso que mudou comparando com antes...

Sobre o generateDS, eu realmente entendo de nao querer aumentar a dificuldade nisso na v12. A unica coisa que eu queria ter certeza eh que o cara que pensa fazer bem de instalar o l10n_br_hr nao cria sem saber uma divida tecnologica nas migracoes futuras e depois vem reclamar da OCA com razao. Por examplo na v8 e v10, era um modulo simples que nao criava divida tecnologica. A gente tem apenas que pensar em deixar a parte da divida tecnologica com o e-social fora do modulo basico, dessa forma, so vai instalar quem se garantir para migrar depois, ou sera possivel tirar a parte do e-social facilmente sem tirar todos cadastros basicos de HR... Alias, vou subir o meu PR de nfe com generateDS ja ja viu.

2019-10-10 20:23 UTC, mileo commented
> Ola @mileo eu realmente nao sei dizer o porque do status do Runbot deu ruim. Mas eh capaz que seja um problema mesmo de analise dos logs do Runbot, A gente pode imaginar que seja por causa dos WARNING no log aqui https://runbot3.odoo-community.org/runbot/static/build/3390295-713-1c722d/logs/job_20_test_all.txt pois ao meu ver so isso que mudou comparando com antes...
> 
> Sobre o generateDS, eu realmente entendo de nao querer aumentar a dificuldade nisso na v12. A unica coisa que eu queria ter certeza eh que o cara que pensa fazer bem de instalar o l10n_br_hr nao cria sem saber uma divida tecnologica nas migracoes futuras e depois vem reclamar da OCA com razao. Por examplo na v8 e v10, era um modulo simples que nao criava divida tecnologica. A gente tem apenas que pensar em deixar a parte da divida tecnologica com o e-social fora do modulo basico, dessa forma, so vai instalar quem se garantir para migrar depois, ou sera possivel tirar a parte do e-social facilmente sem tirar todos cadastros basicos de HR... Alias, vou subir o meu PR de nfe com generateDS ja ja viu.

Vamos cuidar da migração dos módulos do HR, pode ficar tranquilo.

2019-10-10 20:27 UTC, mileo commented
@luismalta 

Corrija as sugestões enviadas pelo @hendrixcosta e os WARNINGS:

```
2019-10-10 12:46:06,415 166 WARNING openerp_test odoo.models: The model hr.chronic.disease has no _description
2019-10-10 12:46:06,415 166 WARNING openerp_test odoo.models: The model hr.civil.certificate.type has no _description
2019-10-10 12:46:06,416 166 WARNING openerp_test odoo.models: The model hr.deficiency has no _description
2019-10-10 12:46:06,416 166 WARNING openerp_test odoo.models: The model hr.dependent.type has no _description
2019-10-10 12:46:06,417 166 WARNING openerp_test odoo.models: The model hr.educational.attainment has no _description
2019-10-10 12:46:06,417 166 WARNING openerp_test odoo.models: The model hr.ethnicity has no _description
2019-10-10 12:46:06,418 166 WARNING openerp_test odoo.models: The model hr.identity.type has no _description
2019-10-10 12:46:06,418 166 WARNING openerp_test odoo.models: The model hr.nationality.code has no _description
2019-10-10 12:46:07,482 166 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (name, dependent_name) of hr.employee.dependent() have the same label: Name.
2019-10-10 12:46:07,483 166 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (employee, employee_id) of hr.employee.dependent() have the same label: Employee.
```

[]s

2019-10-11 22:41 UTC, mileo approved these changes

2019-10-11 22:41 UTC, mileo commented on l10n_br_hr/README.rst
> +Brazil Localization for HR module
@luismalta 

Traduzir o texto para o português e colocar mais detalhes do que o módulo faz como neste exemplo: 

https://github.com/OCA/l10n-brazil/tree/12.0/l10n_br_base

2019-10-11 22:44 UTC, mileo requested changes

2019-10-11 22:44 UTC, mileo commented on l10n_br_hr/models/hr_employee.py
> +        store=True,
Seria melhor colocar um readonly=False

2019-10-11 22:44 UTC, mileo commented on l10n_br_hr/models/hr_employee.py
> +        store=True,
Pois o campo é requerido e não aparece na visão de criação do endereço

2019-10-12 00:09 UTC, rvalyi commented on l10n_br_hr/models/hr_employee.py
> +        store=True,
eu ia comentar exactamente esse tipo de coisa. Alem disso a gente tem que pensar em deixar usar modulos basicos da localizacao num ERP com outras localizacoes, entao seria bom nao ter required=True nos cadastros que estao usados fora do Brasil tb.

2019-10-12 23:36 UTC, mileo commented on l10n_br_hr/models/hr_employee.py
> +        store=True,
> eu ia comentar exactamente esse tipo de coisa. Alem disso a gente tem que pensar em deixar usar modulos basicos da localizacao num ERP com outras localizacoes, entao seria bom nao ter required=True nos cadastros que estao usados fora do Brasil tb.

Bom mas isso é algo que tem que reser resolvido no l10n_br_base visto que é um campo de lá.

2019-10-12 23:36 UTC, mileo approved these changes

2019-10-13 00:34 UTC, rvalyi commented on l10n_br_hr/models/hr_employee.py
> +        store=True,
entao, na v12, (e eu acho ate na v10) a gente teve esse cuidado no l10n_br_base, os campos do Brasil nao saoo obrigatorios nos objetos ou tabelas. E a gente ta tendo nos outros modulos, ate a NFe pelo menos...

2019-10-13 00:46 UTC, mileo commented on l10n_br_hr/models/hr_employee.py
> +        store=True,
Sim, o único campo que tem requerido é o tipo, mas tem um default: https://github.com/OCA/l10n-brazil/pull/713/files#diff-9c19ee61274c897435374ecc0988436eR205

2019-10-13 01:12 UTC, rvalyi commented on l10n_br_hr/models/hr_employee.py
> +        store=True,
Sim na vdd, tou quase aprovando ja. Nao tenho problema com o tipo pelo fato de ter um default e tb de ser um campo facil de se colocar ate nos outros paises. Alisa nisso que ja revisei pude realmente ver que aesar de ter feito mais um passo na direcao do e-social o codigo do modulo ficou bem simples entao era infundado o pe atras que eu tinha a respeito disso quando vi apenas chegar os novos commits.

A respeito do cpf, parece mais sutil, EU realmente chequei no l10n_br_base e o campo nao tem obrigatoriedade nao.

Ser se eh por causa do framework e por causa do ```@api.constrains('cpf')``` no hr_employee.py?

Aproveitando que vc ta por ai. Umas considerações de menor importância. Que tal um link pro erpbrasil.base no README? Quem sabe se faz a lib subir (deveriamos ter feito no l10n_br_base tb). Outra coisa, como ja conversamos, eu acho que quando algum modulo da OCA eh claramente da autoria de alguma empresa como eh o caso com esse modulo de vcs, eu acho que temos que valorisar isso no appstore colocar dados de demo que explicitam a empresa que fez o modulo e da ate para mostrar em screenshot no README.
Por examplo, a CampToCamp com o connector Magento ou Acsone com o mis_builder nao deixam a duvida do que sao os lideres desses modulos, eu acho que eh apenas justo...

2019-10-13 01:39 UTC, rvalyi requested changes
Overal, kudos for the module, it really looks clean. There is a small overlap with https://github.com/OCA/hr/tree/12.0/hr_employee_relative but that is small code and why not if the one of l10n_br_hr fits better for the e-social later on.

I only request we remove the required=True here in the hr.employee view https://github.com/OCA/l10n-brazil/blob/ec7c45d56b07d5ae5cdfe39fdfca888ef6d069af/l10n_br_hr/views/hr_employee_view.xml#L18
to play nicer when the module is used in companies operating also outside from Brazil. This can be added later on, as a more usability oriented module, or in some e-social oriented module...

2019-10-13 01:51 UTC, rvalyi approved these changes

2019-10-13 01:54 UTC, mileo commented
Não creui q

> Overal, kudos for the module, it really looks clean. There is a small overlap with https://github.com/OCA/hr/tree/12.0/hr_employee_relative but that is small code and why not if the one of l10n_br_hr fits better for the e-social later on.
> 
> I only request we remove the required=True here in the hr.employee view
> 
> https://github.com/OCA/l10n-brazil/blob/ec7c45d56b07d5ae5cdfe39fdfca888ef6d069af/l10n_br_hr/views/hr_employee_view.xml#L18
> 
> 
> to play nicer when the module is used in companies operating also outside from Brazil. This can be added later on, as a more usability oriented module, or in some e-social oriented module...

Não creio que vala a pena depender deste modulo, visto que é uma coisa bem simples e tem muita complexidade que depende desta tabela:
1. Beneficios (VR/VR, seguro saúde, vale transporte e etc);
2. Pagamento de pensão;
3. Integração com CNAB;

2019-10-13 01:57 UTC, mileo commented on l10n_br_hr/models/hr_employee.py
> +        store=True,
Depois falo pra alguém do nosso time fazer isso em outro PR.
CC: @ananiasfilho

2019-10-13 01:57 UTC, mileo commented
/ocabot merge

2019-10-13 02:10 UTC, merged

2021-10-02 18:21 UTC, 4devs-net-br commented
https://4devs.net.br/gerador-cpf