[12.0] Migration l10n_br_hr_contract
OCA/l10n-brazil pull request #723
Opened 2019-09-26 13:41 UTC by luismalta

2019-10-10 13:31 UTC, rvalyi commented
@luismalta legal vc estar trabalhando na migraçao da localizaçao. Mas sera se vc poderia fazer um rebase de todos os seus PR's da v12 em cima do head da 12.0 para a gente ter o Runbot funcionando? Pois isso ajuda para revisar... Iremos fazer o mesmo na Akretion e logo solucionar o Runbot na v13 tb.

2019-10-14 12:20 UTC, hendrixcosta requested changes

2019-10-14 12:20 UTC, hendrixcosta commented on l10n_br_hr_contract/models/hr_contract.py
> +        string='Union CNPJ')
Se tem um relacionamento com partner para indicar o sindicato, não precisaria desses campos para atributos que ja tem no partner..

2019-10-14 12:24 UTC, mileo commented on l10n_br_hr_contract/models/hr_contract.py
> +        string='Union CNPJ')
Seria interessante apenas manter um related readonly para não quebrar outros módulos que devem estar usando este campo.

2019-10-15 13:27 UTC, hendrixcosta commented on l10n_br_hr_contract/models/hr_contract.py
> +        string='Union CNPJ')
Acho mais válido remover esse campo.
Mas para não criar obstáculos nesse momento, criar um related readonly e uma issue para não sair do radar.

2019-10-15 20:48 UTC, rvalyi approved these changes
LGTM

2019-10-16 11:41 UTC, hendrixcosta requested changes

2019-10-16 11:41 UTC, hendrixcosta commented on l10n_br_hr_contract/models/hr_contract.py
> +            ('rpps', u'Regime Próprio da Previdência Social')])
Faltando a opção de 3 - Regime de Previdência Social no Exterior.

2019-10-16 11:41 UTC, hendrixcosta commented on l10n_br_hr_contract/models/hr_contract.py
> +        help='e-Social: S2300 - tpRegPrev')
Esse help é dp campo que indica o Tipo de regime previdenciário

2019-10-16 11:41 UTC, hendrixcosta commented on l10n_br_hr_contract/models/hr_contract.py
> +    by_death = fields.Char(
Não vejo muito sentido pra esse campo

2019-10-16 11:41 UTC, hendrixcosta commented on l10n_br_hr_contract/models/hr_contract.py
> +        selection=MONTHS)
Qual função desse campo?

2019-10-16 11:43 UTC, hendrixcosta commented
O PR parece funcional, mas tenho algumas sugestões para deixar o código mais clean.
Não sei se é o momento de fazermos essa limpeza/refactory ou vai ficar pra v13?

2019-10-16 14:37 UTC, rvalyi commented
@hendrixcosta faça suas sugestões, depois a gente avalia (sendo que deixamos a palavra final para KMEE nessa questão de HR, ja que são eles que estão na frente nisso). De uma forma geral, eu diria que se tem refator facil que evita que varios modulos que dependem disso seja arquiteturados de forma errada e dificil de migrar depois, a gente tem que refatorar quanto antes. Agora se não for criar divida tecnológica, pode ser depois...

2019-11-05 12:00 UTC, hendrixcosta approved these changes

2019-12-04 12:21 UTC, luismalta commented
Pessoal, poderiam revisar por favor? Vou continuar a migração da folha e depende desse PR

2019-12-04 12:37 UTC, mileo approved these changes

2019-12-08 15:21 UTC, rvalyi commented
pessoal, eu já tinha aprovado um tempo atras. Revisei de novo e continuo aprovando, parabens!

2019-12-08 15:21 UTC, rvalyi commented
/ocabot merge

2019-12-08 15:32 UTC, merged