[FIX] Port nationality code to res_country
OCA/l10n-brazil pull request #741
Opened 2019-10-18 14:59 UTC by hendrixcosta

2019-10-18 15:00 UTC, hendrixcosta commented
Issue: https://github.com/OCA/l10n-brazil/issues/739

2019-10-21 11:11 UTC, renatonlima approved these changes

2019-10-22 11:53 UTC, rvalyi approved these changes

2019-10-22 12:49 UTC, mileo requested changes
Os dados da tabela l10n_br_hr/data/hr_employee_nationality_code_data.xml não deveriam ser inseridos no l10n_br_base, seja no próprio módulo ou através do módulo do l10n_br_hr?

Então creio que a modificação poderia ser efetuada apenas no l10n_br_hr, removendo a tabela e extendendo o res.contry

2019-10-22 12:49 UTC, mileo commented on l10n_br_hr/models/hr_employee.py
> -    nationality_code = fields.Many2one(
Isto não deveria se mantido, mas com um comodel name de res.contry?

2019-10-22 12:58 UTC, hendrixcosta commented on l10n_br_hr/models/hr_employee.py
> -    nationality_code = fields.Many2one(
Onde eh utilizado essa informação? Porque temos que ter essa informação?

2019-10-23 13:33 UTC, mileo approved these changes

2019-10-23 13:33 UTC, mileo commented
@hendrixcosta pode resolver o conflito para fazermos o merge?

2019-10-23 14:13 UTC, mileo commented
/ocabot merge

2019-10-23 15:05 UTC, merged