Check Filled Variables in l10n_br_base
OCA/l10n-brazil pull request #752
Opened 2019-11-29 20:18 UTC by luismalta

2019-12-02 13:15 UTC, mileo approved these changes

2019-12-03 03:51 UTC, rvalyi commented
eu tenho uma sugestão para resolver um bug nesse código. Amanha eu faço.

2019-12-03 12:22 UTC, mileo commented
> eu tenho uma sugestão para resolver um bug nesse código. Amanha eu faço.

Não é mais facil vc falar?

2019-12-04 19:43 UTC, rvalyi requested changes
Thanks. It fixes some issues I have seen with the possible empty contry_id but there is a small issue left I think  if you can fix it...

2019-12-04 19:43 UTC, rvalyi commented on l10n_br_base/models/res_partner.py
>              country_code = record.country_id.code or ""
country_id can be empty, so record.country_id.code wouldn't work

2019-12-06 13:58 UTC, mileo approved these changes

2019-12-09 14:48 UTC, rvalyi requested changes

2019-12-09 14:48 UTC, rvalyi commented on l10n_br_base/models/res_partner.py
> +                country_code = record.country_id.code or ""
nao eh algo critico, mas esse ultimo `or ""` eh inutil ja que nao vai fazer nada com o country_code caso ele for vazio depois.

2019-12-09 19:29 UTC, rvalyi approved these changes

2019-12-09 19:30 UTC, rvalyi commented
/ocabot merge

2019-12-09 19:44 UTC, merged