Parâmetrização para habilitar ou desabilitar as validações dos campos de CPF/CNPJ e IE
OCA/l10n-brazil pull request #775
Opened 2019-12-19 02:48 UTC by mliell

2019-12-19 13:42 UTC, mileo commented
@m1k3lm agora falta vc colocar essa checagem nos métodos que fazem a validação né?

2019-12-19 14:19 UTC, mliell commented
Isso, falta fazer a checagem.

2019-12-19 19:36 UTC, renatonlima requested changes

2019-12-19 19:36 UTC, renatonlima commented on l10n_br_base/models/res_config_settings.py
> +    module_l10n_br_validate_cpf_cnpj_ie = fields.Boolean(string="Allow CPF, CNPJ and IE validation")
Este campo deve ser um ir.paramenter

2019-12-20 16:49 UTC, renatonlima requested changes

2019-12-20 16:49 UTC, renatonlima commented on l10n_br_base/models/res_config_settings.py
> +    module_l10n_br_validate_cpf_cnpj_ie = fields.Boolean(string="Allow CPF, CNPJ and IE validation")
O nome do campo poderia ser: l10n_br_validate_cpf_cnpj_ie, Os campos que começam com o prefixo module, são campos que ao ser true instala um módulo com o nome sem o prefixo, por exemplo: module_l10n_br_zip ao marcar esse campo como true, o sistema ira instalar o módulo l10n_br_zip.

2019-12-20 16:49 UTC, renatonlima commented on l10n_br_base/models/res_config_settings.py
> +    def set_values(self):
Agora os campos que armazenam o parametro no ir.parameter não precisam mais ter os métodos set_values e get_values, agora você pode usar o atributo config_parameter e automaticamente será recuperado e salvo o parametro na tabela ir.paramneter, você pode ver um exemplo aqui: https://github.com/odoo/odoo/blob/12.0/addons/sale/models/res_config_settings.py#L18

2019-12-20 16:49 UTC, renatonlima commented on l10n_br_base/models/res_partner.py
> +            validate_cpf_cnpj_ie = record.env["ir.config_parameter"].get_param(
é bom você buscar o parametro usando o sudo() para não ter problema de leitura caso um usuário não tiver acesso a leitura a este tabela, tem um exemplo aqui: https://github.com/odoo/odoo/blob/9c303bfd4f8eeb1c6892349c59f70347a11ff71f/addons/sale/models/sale.py#L27

2019-12-20 16:52 UTC, renatonlima commented
@mliell obrigado pela sua contribuição,

Eu pensei também que ao invés de termos um 'único parâmetro para desabilitar as validações de CNPJ/CPF e IE, talvez seria interessante ter dois, parâmetros uma para desabilitar a validação do CNPJ/CPF e outro a IE.

2019-12-20 16:55 UTC, renatonlima commented
Eu inverteria a lógica do parâmetro, ao invés de ser ativar validação eu deixaria desativar validação, desta forma por padrão será feita as validações.

2019-12-20 20:53 UTC, mliell commented
@renatonlima, apliquei as sugestões. Porém, a questão da remoção dos métodos set_values e get_values, e a inclusão somente do atributo config_parameter fez com que a atualização do ir.parameter parasse de funcionar. 
Se puder dar uma conferida no que fiz errado, agradeço.

2020-01-02 19:41 UTC, mliell commented
As devidas correções estão feitas.

2020-01-02 20:24 UTC, mileo commented
Poderia verificar os erros do travis? https://travis-ci.org/OCA/l10n-brazil/jobs/632002780

2020-02-17 19:52 UTC, mileo approved these changes

2020-02-17 20:29 UTC, sadamo approved these changes

2020-02-17 20:33 UTC, mileo commented
@mliell Você já assinou o CLA e enviou no email solicitado? Só falta isso para podermos aprovar sua contribuição.

Alias obrigado.

2020-02-19 17:09 UTC, mileo commented
\ocabot merge

2020-02-19 17:09 UTC, mileo commented
/ocabot merge

2020-02-19 17:28 UTC, merged