[NEW] l10n_br_portal base
OCA/l10n-brazil pull request #777
Opened 2019-12-27 12:37 UTC by mileo

2020-01-04 01:44 UTC, marcelsavegnago approved these changes

2020-01-04 01:58 UTC, mileo commented
@marcelsavegnago obrigado, estou tentando arrumar os testes para manter o coverage. 

Mas esta foda, pois não consigo rodar na minha maquina o teste do JS....

2020-01-06 13:33 UTC, sadamo approved these changes

2020-01-22 19:24 UTC, rvalyi approved these changes
Looks all great! thanks for this new module!

2020-01-22 19:38 UTC, renatonlima requested changes

2020-01-22 19:38 UTC, renatonlima commented on l10n_br_portal/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
Please, create readme folder and its files to auto generate this file.

2020-01-22 19:38 UTC, renatonlima commented on l10n_br_portal/__manifest__.py
> +    'demo': [
You can remove empty keys in manifest.

2020-01-22 19:38 UTC, renatonlima commented on l10n_br_portal/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
Please, create readme folder and its files to auto generate this file.

2020-01-22 19:38 UTC, renatonlima commented on l10n_br_portal/__manifest__.py
> +    'demo': [
You can remove empty keys from module manifest.

2020-01-27 16:50 UTC, renatonlima approved these changes

2020-01-27 16:51 UTC, renatonlima commented
/ocabot merge

2020-01-27 17:11 UTC, merged