[ADD] Partner Order and Partner Order Line in Fiscal Document Line Mixin
OCA/l10n-brazil pull request #814
Opened 2020-04-13 20:55 UTC by renatonlima

2020-04-13 21:27 UTC, rvalyi commented
os mixins da NFe ja trazem esses campos. Sera se algum outro documento fiscal usa eles? Se nao for o caso, melhor usar os campos dos mixins dos XSD do que duplicar eles.

2020-04-14 00:26 UTC, mileo submitted a review, later dismissed

2020-04-15 20:29 UTC, rvalyi commented
Eu pesquisei rapidamente nos esquemas de NFSe (ABRASF), CTe e MDFe e eu NAO ENCONTREI compos equivalente ao nItemPed e xPed da NFe, aquilo que vc chamou de partner_order e partner_order_line. Sera se eh interessante mesmo ter eles nesse modulo generico?
cc @renatonlima

2020-04-15 21:31 UTC, renatonlima commented
Eu deixei esse campo genérico no Mixin da linha do documento fiscal porque precisamos deste campo nas linhas do documento fiscal, pedido de venda e pedido de compra. Eu dei uma olhada esse campo hoje só existe na NF-e e NFC-e (que tem o mesmo schema), futuramente talvez possa existir em outros documentos fiscais.

Podemos deixar estes campos no l10n_br_fiscal, mas futuramente talvez os campos da NF-e das classes dos mixins do módulo l10n_br_nfe possam ser injetados no FiscalDocumentMixin como os campos dos impostos e etc.

2020-04-16 04:51 UTC, rvalyi approved these changes
realmente para ter os campos no mixin e usar em vendas ou compras de forma simples, faz sentido ter os campos nesse modulo. Nisso eu aprovo.

2020-04-16 13:33 UTC, mileo commented on l10n_br_fiscal/models/document_line.py
> -    icms_base_type = fields.Selection(
Por que vc esta tirando esse campo?

@gabrielcardoso21 Pode confirmar, mas tenho certeza que ele é necessário na nf-e.

2020-04-17 19:54 UTC, gabrielcardoso21 requested changes

2020-04-17 19:54 UTC, gabrielcardoso21 commented on l10n_br_fiscal/models/document_line.py
> -    icms_base_type = fields.Selection(
Sim, esse campo é necessário na exportação e na transmissão da NF-e.

2020-04-17 19:54 UTC, gabrielcardoso21 commented on l10n_br_fiscal/models/document.py
> -    ind_pres = fields.Selection(
Esse campo também é necessário na exportação e transmissão da NF-e.

2020-04-17 20:48 UTC, rvalyi commented on l10n_br_fiscal/models/document.py
> -    ind_pres = fields.Selection(
eh que esse em partiular o @renatonlima mudou ele de lugar pro fiscal.document.mixin. A vantagem eh que vc vai ter ele nas sale.order.line de graça. Foi ao migrar o l10n_br_sale que a gente se tocou disso. Veja:
 https://github.com/OCA/l10n-brazil/pull/814/files#diff-d58b3eb5dbe8cbe4c1047dd6a290256fR44

2020-04-18 17:17 UTC, renatonlima commented on l10n_br_fiscal/models/document.py
> -    ind_pres = fields.Selection(
@gabrielcardoso21 

Como o @rvalyi falou esse campo foi removido porque já esta sendo adicionado pelo Fiscal Document Line Mixin e vai ser adicionado nos objetos sale.order, purchase.order, stock.picking, fiscal.document e etc...

2020-04-18 17:19 UTC, renatonlima commented on l10n_br_fiscal/models/document_line.py
> -    icms_base_type = fields.Selection(
@mileo,

Esse campo estava duplicado, pois já existia o mesmo no Fiscal Document Line Mixin https://github.com/akretion/l10n-brazil/blob/feature/l10n_br_fiscal-customer-order/l10n_br_fiscal/models/document_fiscal_line_mixin.py#L326

2020-04-18 17:19 UTC, renatonlima commented on l10n_br_fiscal/views/document_line_view.xml
> -                        <field name="icms_base_type"/>
Este campo tbm foi removido da view por que estava duplicado.

2020-04-23 15:37 UTC, mileo approved these changes

2020-04-23 18:23 UTC, rvalyi approved these changes

2020-04-23 18:27 UTC, rvalyi requested changes
There is a bug here https://github.com/akretion/l10n-brazil/blob/feature/l10n_br_fiscal-customer-order/l10n_br_account/models/fiscal_tax.py#L42
with account_tax_group_id that is now undefined.

This has been caught by flake8 https://travis-ci.org/github/OCA/l10n-brazil/jobs/678658928#L455

2020-04-23 19:35 UTC, rvalyi approved these changes

2020-04-23 19:46 UTC, mbcosta approved these changes

2020-04-23 21:35 UTC, rvalyi commented
/ocabot merge

2020-04-23 21:36 UTC, rvalyi commented
/ocabot merge nobump

2020-04-23 21:37 UTC, rvalyi commented
(botando nobump porque a gente ainda nao promoveu muito o modulo, a gente apenas fez o merge rapidamente para destravar os outros PRs que dependem dele, depois que a gente considerar o modulo mais OK, encaixando alguns dos modulos que dependem dele, a gente realmente pode passar a ter mais rigor na gestao de versao)

2020-04-23 22:09 UTC, merged