Feature/payment in fiscal
OCA/l10n-brazil pull request #820
Opened 2020-04-28 04:41 UTC by mileo

2020-04-28 17:26 UTC, marcelsavegnago requested changes
Como sugestão.
- Remover o field payment_term _id conforme comentário na view do documento fiscal.
- Não sei se cabe no momento mas talvez seja importante sinalizar quando o montante configurado para pagamento/recebimento for maior que do documento fiscal.

2020-04-28 17:26 UTC, marcelsavegnago commented on l10n_br_fiscal/views/document_view.xml
> +                      <field name="payment_term_id"/>
Acredito que pode retirar este trecho.
![image](https://user-images.githubusercontent.com/3595132/80512434-da8a2980-8953-11ea-98bb-172b57346191.png)

2020-04-28 17:26 UTC, marcelsavegnago commented on l10n_br_fiscal/views/payment_view.xml
> +                            <field name="amount" required="1"/>
Este campo traz sempre o valor cheio da nota fiscal sem levar em consideração o valor dos demais tipos de pagamento já definidos. Não que precise mudar aqui mas senti falta de algum tipo de sinalização quando for configurado um montante de pagamento/recebimento superior ao valor total da nota fiscal.

2020-04-28 17:26 UTC, marcelsavegnago commented on l10n_br_fiscal/views/document_view.xml
> +                          <field name="amount" sum="amount"/>
Senti falta de algum tipo de sinalização quando o valor for superior ao da NF conforme citado em comentários abaixo.

2020-05-05 00:39 UTC, mileo commented
@luismalta 

Encontrei um bug:

![image](https://user-images.githubusercontent.com/1975978/81026227-bcd72b80-8e4f-11ea-8f3b-d9ec43549c53.png)

2020-05-06 15:17 UTC, marcelsavegnago approved these changes

2020-05-06 15:30 UTC, marcelsavegnago commented
Erro após inclusão da condição de pagamento e tentar salvar o documento.

![image](https://user-images.githubusercontent.com/3595132/81196223-290f7780-8f95-11ea-97f8-b8a85ed071ab.png)

2020-05-06 15:37 UTC, marcelsavegnago commented
Não entendi o propósito destes dois campos. Menos ainda a série do documento fiscal neste form.

![image](https://user-images.githubusercontent.com/3595132/81197185-5b6da480-8f96-11ea-8f07-fae6d05a8fbb.png)

2020-05-06 15:57 UTC, mileo commented
@marcelsavegnago ainda estamos trabalhando, pra resolver os últimos detalhes. Assim que ficar pronto eu te mando uma msg.

2020-05-06 15:58 UTC, marcelsavegnago commented
> @marcelsavegnago ainda estamos trabalhando, pra resolver os últimos detalhes. Assim que ficar pronto eu te mando uma msg.

Blzz.. dá um toque e testamos aqui. Vlw

2020-05-06 16:06 UTC, rvalyi commented
Pessoal, só para deixar claro, o @renatonlima e eu estamos muito com pé atras sobre esse PR.

Basicamente a gente pensa que muita coisa poderia ser feito ao nível do l10n_br_account porque quando começa a se considerar a questão financeira a nossa ideia e usar o modulo account, mesmo que tendo sim um espaço para provisão puramente financeira através desse modulo da OCA popular e de qualidade mis_builder_cash_flow https://github.com/OCA/account-financial-reporting/tree/12.0/mis_builder_cash_flow 

A gente pode ate tolerar outra forma de fazer o financeiro no repo OCA/l10n-brazil, mas certamente não embutida nesses módulos super centrais que devem ser mais agnósticos com isso). Enfim nada de definitivo, falta a gente olhar no detalhe, mas eh só um toque adiantado para evitar trabalho inútil, tendo já tanta coisa útil para finalizar...

2020-05-06 16:42 UTC, marcelsavegnago commented
> Pessoal, só para deixar claro, o @renatonlima e eu estamos muito com pé atras sobre esse PR.
> 
> Basicamente a gente pensa que muita coisa poderia ser feito ao nível do l10n_br_account (ou módulos que dependeriam dele ainda) porque quando começa a se considerar a questão financeira a nossa ideia e usar o modulo account, mesmo que tendo sim um espaço para provisão puramente financeira através desse modulo da OCA popular e de qualidade mis_builder_cash_flow https://github.com/OCA/account-financial-reporting/tree/12.0/mis_builder_cash_flow (mas repara que ele depende do modulo account. Sugeri pro @mileo se ele queria tentar extrair algo para não depender do account qdo foi migrado para a v12 mas não foi feito e tb na Akretion não achamos isso um problema assumir a dependência do account para isso).
> 
> A gente pode ate tolerar outra forma de fazer o financeiro no repo OCA/l10n-brazil, mas certamente não embutida nesses módulos super centrais que devem ser mais agnósticos com isso. Enfim nada de definitivo, falta a gente olhar no detalhe, mas eh só um toque adiantado para evitar trabalho inútil, tendo já tanta coisa útil para finalizar...

Sinceramente eu prefiro que fique tenha o maior alinhamento possível com o account. O MIS Builder me parece bem poderoso. Uns dois dias atrás fizemos alguns testes no mis_builder_cash_flow e adicionamos uma linha para considerar as notas fiscais de fatura que ainda estão no modo provisório e pareceu uma forma interessante de ter uma previsão de entradas e saídas bem dinâmicas sem a necessidade de usar as linhas manuais.

2020-05-06 16:53 UTC, marcelsavegnago commented
@rvalyi Se seguir esta linha de um outro módulo financeiro isto não vai impactar em relatórios baseados Regime de Caixa ?

2020-05-06 18:27 UTC, rvalyi commented
> @rvalyi Se seguir esta linha de um outro módulo financeiro isto não vai impactar relatórios como Fluxo de Caixa por Regime de Caixa e demais relatórios contábeis?

@marcelsavegnago o lance eh que a KMEE tinha feito um trabalho bem extenso no financeiro fora da OCA e pouco alinhado com o modulo account (e muito menos mis_builder_cash_flow) na v10 focando mais em implementar um determinado backlog do que se integrar ao ecosistema OCA ou nativo do Odoo (fraco no financeiro conveniamos). Foi depois sobemetido para a OCA mas como vc pode ver ninguem deu bola https://github.com/OCA/account-financial-tools/pull/805

Do lado da Akretion a gente ja sabe como fazer tudo que a gente precisa em cima do account e mis_builder_cash_flow com pouco codigo adicional. Eu nao posso garantir que a gente vai chegar num denominador comum aqui. Porem, o que parece razoavel, eh que os modulos l10n_br_fiscal e l10n_br_account que sao bem centrais e "estruturadores" da localizacao seja o mais agnoticos possiveis com isso para nao impor algo que foge do que ja funciona legal na OCA (e que praticamos bastante na Franca onde a Akretion tem uma filial muito forte). Fiscal eh super especifico do Brasil mas contabilidade e financeiro são bem mais padronizados e queremos evitar de reinventar a roda sempre que for possível. 

Ai ou a gente chega num denominador comum na parte financeira ou entao existira 1 modulo financeiro da KMEE e outro da AKRETION no repo. Eu nao vejo isso como grande problema a partir do momento que desenhamos os modulos l10n_br_fiscal e l10n_br_account cuidadosamente para permitir isso sem impor divida tecnológica para ninguem. Eu tenho certeza que conseguimos esse resultados. Sobre ter 1 ou 2 modulos financeiros eu nao posso dizer ainda, ira depender das conversas que teremos com o Luis la na frente. Porem hoje focamos em finalizar a migracao dos modulos da 10 para 12. NFe e NFSe...

2020-05-06 19:49 UTC, marcelsavegnago commented
> > @rvalyi Se seguir esta linha de um outro módulo financeiro isto não vai impactar relatórios como Fluxo de Caixa por Regime de Caixa e demais relatórios contábeis?
> 
> @marcelsavegnago o lance eh que a KMEE tinha feito um trabalho bem extenso no financeiro fora da OCA e pouco alinhado com o modulo account (e muito menos mis_builder_cash_flow) na v10 focando mais em implementar um determinado backlog do que se integrar ao ecosistema OCA ou nativo do Odoo (fraco no financeiro conveniamos). Foi depois submetido para a OCA mas como vc pode ver ninguem deu bola [OCA/account-financial-tools#805](https://github.com/OCA/account-financial-tools/pull/805)

Quando vi o MIS_Builder achei bem interessante mas não peguei para mexer nele. Na segunda-feira que o João Carassato (parceiro meu) fez algumas adaptações no cashflow e ficou apaixonado hehehehe.

Sinceramente estou gostando bastante do ecossistema OCA e nativo do Odoo então vou sempre prezar pelo máximo possível de alinhamento.

> 
> Do lado da Akretion a gente ja sabe como fazer tudo que a gente precisa em cima do account e mis_builder_cash_flow com pouco codigo adicional. Eu nao posso garantir que a gente vai chegar num denominador comum aqui. Porem, o que parece razoavel, eh que os modulos l10n_br_fiscal e l10n_br_account que sao bem centrais e "estruturadores" da localização sejam o mais agnoticos possivel com isso para não impor algo que foge do que já funciona legal na OCA (e que praticamos bastante na Franca onde a Akretion tem uma filial muito forte). Fiscal eh super especifico do Brasil mas contabilidade e financeiro são bem mais padronizados e queremos evitar de reinventar a roda sempre que for possível.

Sim. Contabilidade e Financeiro pode até ter algumas particularidades mas entendo que é algo mais padrão e não acho válido reinventar a roda em momento algum. Como experiência pessoal  eu agradeci por não ser um desenvolvedor python quando comecei a explorar o Odoo já  que conta disso me forço a entender mais ainda o funcionamento do Odoo e o ecossistema (cada dia aprendendo algo novo).

> 
> Ai ou a gente chega num denominador comum na parte financeira ou entao existira 1 modulo financeiro da KMEE e outro da AKRETION no repo. Eu nao vejo isso como grande problema a partir do momento que desenhamos os modulos l10n_br_fiscal e l10n_br_account cuidadosamente para permitir isso sem impor divida tecnológica para ninguem. Eu tenho certeza que conseguimos esse resultados. Sobre ter 1 ou 2 modulos financeiros eu nao posso dizer ainda, ira depender das conversas que teremos com o Luis la na frente. Porem hoje focamos em finalizar a migracao dos modulos da 10 para 12. NFe e NFSe...

Como um dos interessados no projeto eu entendo que não seja vantagem para ninguém ter trabalho redundante. Se na ideia tanto da KMEE como da Akretion o objetivo é usar como fonte de dados do financeiro o account, então me parece mais simples ter um mis_builder _cash_flow conseguindo gerar um fluxo de caixa por regime de competência e um por regime de caixa (algo que apresente alguma coisa próxima do relatório cashflow do Enterprise), manter o time focado  nos demais módulos NFe, NFSe, boleto, fiscal e etc e após esta etapa se necessário alinhar próximos passos para o financeiro.

2020-05-20 16:42 UTC, rvalyi requested changes
Thank you for the work @mileo .
The idea of a **financial mixin** to deal with the split payment terms that are so important in Latin America is great (but not new we did it in 6.1…) and **the idea to attach it to the fiscal document line mixin is great** too as the OCA/l10n-brazil already takes care of injecting this mixin in sale.order.line, purchase.order.line, draft account.invoice.line and draft fiscal document lines where financial provisions make sense.

**However, I’m sorry the proposed implementation can not be accepted the way it is and inside the l10n_br_fiscal module**. We see no reason to add these features inside our already big fiscal module and your choice not to depend on the account module makes the implementation twice as compex now and to maintain with no benefit we can think about.

Insead if there is really such a basic core cashflow set of features that can really be isolated we recommend you to include this (with the asked refactor then) **inside the l10n_br_account module instead**.

**General considerations:**

**First of all, fundamentally why do you want to be able to do financial cashflow projections without depending on the account module?** 
As one can see the accepted way to do financial proojections in the OCA is https://github.com/OCA/account-financial-reporting/tree/13.0/mis_builder_cash_flow and it depends on account.

1 year ago before it was merged to v12 I even asked you privately if you would like to convince the authors to move out the mis.cash_flow.forecast_line model in a module that wouldn’t depend on account and you could reuse but you didn’t manifest yourself:
https://github.com/OCA/account-financial-reporting/pull/621#issuecomment-537117976

As for us at Akretion (and I talked with Frederic Clementi from CampToCamp about it), it doesn’t shock us that financial analysis depends on the account module as very easily you will want to mix provisional amounts with accounting amounts, which means the account module.

Moreover one year ago when you tried to push your financial without accounting vision in the OCA it was received with incredulity instead of traction:
https://github.com/OCA/account-financial-tools/pull/805
(Regarding my comments in the above PR, I think some concepts are interesting but no need to avoid depending on account if it means reinventing the wheel (seem comments below) and mis_builder_cash_flow already does a large part of the work).


**More in details now:**

**l10n_br_fiscal.payment.term**
Assumingly a copy of account.payment.term with the only difference being the abstract model
L10n_br_fiscal.payment.term.abstract is injected.
and line_ids pointing to l10n_br_fiscal.payment.term.line
And also table being 
_table = 'account_payment_term'

=> depend on account module for financial analysis and just use account.payment.term instead and just inject what you need inside.


**l10n_br_fiscal.payment.term.line**
Assumingly a copy of account.payment.term.line
_table = 'account_payment_term_line'

=> depend on account module for financial analysis and just use account.payment.term.line instead.



**l10n_br_fiscal.payment.term.abstract**
forma_pagamento, bandeira_cartao, integracao_cartao, partner_id
You should use account.payment.method from the account module and the OCA /bank_payment/**account_payment_mode** module that is already popular and well integrated in the OCA: https://github.com/OCA/bank-payment/tree/12.0/account_payment_mode
And like it was in 8.0: https://github.com/OCA/l10n-brazil/blob/8.0/l10n_br_account_payment_mode/models/payment_mode.py


**l10n_br_fiscal.payment.line**
This is very similar to the mis.cash_flow.forecast_line object from the mis_builder_cash_flow module: 
https://github.com/OCA/account-financial-reporting/blob/12.0/mis_builder_cash_flow/models/mis_cash_flow_forecast_line.py
Given that you didn’t take care of trying to get this object extracted in a submodule when it was still time, I would say you should adapt to it instead of re-inventing the wheel and bloating the fiscal module with this duplicate.
If you were to propose the same kind of feature again in l10n_br_account, please use the same mis.cash_flow.forecast_line object (that you can extend) so when you use mis_builder_cash_flow it is compatible.

2020-05-26 14:57 UTC, rvalyi commented
So as an update, @mileo  convinced me on Telegram you could eventually have such simple Odoo installations with modules like l10n_br_nfe and l10n_br_sat installed (hence l10n_br_fiscal) and account not installed and eventually having them share the same object for payment.term might be interresting. So duplicating account.payment.term and account.payment.term.line objects from account is not soo expensive (working simple code) and could be an acceptable trade-off.

I'm yet to review the generate_financial method and I'm specially a bit skeptical about the hardcoded new table where it will write the payment lines (hardcoding something different than account_move_line here seems involved). I will test it more review it in more details later in the day.

2020-05-26 20:52 UTC, rvalyi commented
so para constar, tou olhando bastante a parte generate_financial(). Vou ter uma reuniao daqui pouco mas mais a noite eu do retorno.

2020-05-28 16:11 UTC, mileo commented
@gabrielcardoso21  Por favor faça um rebase ou resolva os conflitos pela interface.

Lembrar tb do #806

2020-05-29 18:12 UTC, rvalyi commented
Pessoal, ainda toi checando um pouco para evitar de ter que migrar depois. De noite vou poder testar melhor. Uma coisa importante era esse refator https://github.com/OCA/l10n-brazil/pull/881 que eu gostaria de ter antes para poder reusar melhor o mixin da geracao de financeiro (de forma opcional claro).

2020-06-15 16:48 UTC, rvalyi submitted a review, later dismissed
a few things that need to be done (possibly more than just this):

1. rebase
2. move the `check_financial` and `generate_financial` methods to the `l10n_br_fiscal.document.mixin.methods` object so it can be reused for financial provisions right from invoices that have not been validated yet (and possibly even other Odoo business documents according to each business need).

2020-06-16 18:15 UTC, renatonlima submitted a review, later dismissed
Também além dos objetos relacionados a duplicatas e pagamentos no módulo fiscal os respectivos objetos devem ter integração no módulo l10n_br_account com os objetos do Odoo

2020-06-16 18:15 UTC, renatonlima commented on l10n_br_fiscal/data/payment_term_data.xml
> +        <field name="forma_pagamento">01</field>
@mileo,

Eu não acho interessante vincular no l10n_br_fiscal.payment.term a forma de pagamento, porque isso vai fazer com que seja necessário criar a mesma condição de pagamento mais de uma vez, por exemplo: 12 vezes Boleto, 12 vezes Cartão, A vista Dinheiro, A vista Cartão...

2020-06-16 18:15 UTC, renatonlima commented on l10n_br_fiscal/models/payment_line.py
> +    _name = 'l10n_br_fiscal.payment.line'
Esse objeto é o correspondente a duplicatas, eu colocaria o nome dele de l10n_br_fiscal.move.line para se relacionar com o account.move.line no módulo l10n_br_account

2020-06-16 18:15 UTC, renatonlima commented on l10n_br_fiscal/data/payment_term_data.xml
> +        <field name="forma_pagamento">01</field>
Também aqui deveria ter o campo indPag que indica a condição de pagamento, 0=Pagamento à vista; 1=Pagamento a prazo; 2=Outros.

2020-06-16 18:20 UTC, renatonlima commented
Uma coisa que é muito importante destacar, as informação de condição de pagamento (prazo e parcelas) isso esta correto da forma que implementada, mas o objeto l10n_br_fiscal.payment.line deveria estar ligado ao account.move.line no l10n_br_account. Os objetos e linhas de pagamento não há uma forma de relaciona-la com a condição de pagamento, porque neste caso sempre iria se repetir, o que poderia ser feito era no wizard de pagamento ou do payment no account, adicionar essas informações e permitir gerar os payments de acordo com o que for registrado no pagamento. Ou ter um terceiro objeto para vincular a relação entre condição e forma de pagamento e a definição por linhas de cada parcela...

2020-06-16 18:36 UTC, renatonlima commented on l10n_br_fiscal/constants/payment.py
> +FORMA_PAGAMENTO = (
Talvez esse selection deveria ser um objeto se facilitar a geração de pagamentos pre-configuradas...

2020-06-21 23:32 UTC, mileo commented
> Também além dos objetos relacionados a duplicatas e pagamentos no módulo fiscal os respectivos objetos devem ter integração no módulo l10n_br_account com os objetos do Odoo

@renatonlima isto esta sendo em progresso no PR https://github.com/OCA/l10n-brazil/pull/806 e não faz parte do escopo desta alteração, que só visa modificar o l10n_br_fiscal.

2020-06-21 23:33 UTC, mileo commented
> a few things that need to be done (possibly more than just this):
> 
> 1. rebase
> 2. move the `check_financial` and `generate_financial` methods to the `l10n_br_fiscal.document.mixin.methods` object so it can be reused for financial provisions right from invoices that have not been validated yet (and possibly even other Odoo business documents according to each business need).

Alteração realizada, poderia revisar novamente? Abs

2020-06-21 23:37 UTC, mileo commented
> Uma coisa que é muito importante destacar, as informação de condição de pagamento (prazo e parcelas) isso esta correto da forma que implementada, mas o objeto l10n_br_fiscal.payment.line deveria estar ligado ao account.move.line no l10n_br_account. Os objetos e linhas de pagamento não há uma forma de relaciona-la com a condição de pagamento, porque neste caso sempre iria se repetir, o que poderia ser feito era no wizard de pagamento ou do payment no account, adicionar essas informações e permitir gerar os payments de acordo com o que for registrado no pagamento. Ou ter um terceiro objeto para vincular a relação entre condição e forma de pagamento e a definição por linhas de cada parcela...

Pode explicar um pouco melhor isso?

Reitero que ainda sou a favor de manter a relação direta da forma e do modo de pagamento. Podemos fazer uma call esta semana para falar dos detalhes deste PR e do #806?

2020-06-30 16:35 UTC, marcelsavegnago commented on l10n_br_fiscal/models/payment_condition.py
> +class FiscalPaymentCondition(models.Model):
@mileo A ideia é um outro objeto além de payment_term, payment_method e payment_mode ? O payment_term não é a condição de pagamento ?

2020-06-30 16:38 UTC, marcelsavegnago requested changes
@mileo A ideia é um outro objeto além de payment_term, payment_method e payment_mode ? O payment_term não é a condição de pagamento ? Isso não vai gerar incompatibilidade com outros módulos ? (gerei o comentário como sugestão de mudança para mudar o flag de aprovado que eu havia colocado no passado)

2020-06-30 17:15 UTC, mileo commented
> ? Isso não vai gerar incompatibilidade com outros módulos ? (gerei o comentário como sugestão de mudança para mudar o flag de aprovado que eu havia colocado no passado)

payment_term é a forma de pagamento.

Comecei a escrever uma RFC sobre isso https://docs.google.com/document/d/1Wzs-5hExWs08osE4r-XZ0QW6uMX5flVkz5a7oQNUy-0/edit mas mas ainda não finalizei, se quiser já dar uma lida e comentar agradeço.

2020-07-09 12:43 UTC, jpcarassato commented
Bom dia!

Efetuando testes na base que o @mileo disponibilizou no Telegram, criei o Sales Order e ao tentar criar a Invoice emite o seguinte erro:

![image](https://user-images.githubusercontent.com/52328080/87041335-75ab4500-c1c8-11ea-887b-ddd9b5a1a0c7.png)

2020-08-29 23:23 UTC, marcelsavegnago reviewed
Empresa Lucro Presumido, na linha da parcela ao tentar abrir para consulta ou edição a forma de pagamento

![image](https://user-images.githubusercontent.com/3595132/91647800-53e67580-ea35-11ea-82ca-65eaac26f314.png)

2020-08-29 23:30 UTC, marcelsavegnago reviewed
Ao adicionar uma linha de pagamento, é duplicado as linhas existentes na grid financeiro 

![image](https://user-images.githubusercontent.com/3595132/91647860-6dd48800-ea36-11ea-8f49-a62d0b699347.png)

2020-08-29 23:32 UTC, marcelsavegnago reviewed
Quando edita uma linha de pagamento e salva, o sistema está incluindo a 1a linha de pagamento novamente na grid financeiro

![image](https://user-images.githubusercontent.com/3595132/91647882-c015a900-ea36-11ea-9aed-c3addc9775d0.png)

2020-08-31 11:50 UTC, mileo commented
Bom dia @marcelsavegnago, obrigado pela revisão. 

Vou dar uma repassada nos fluxos e corrigir esses problemas, o rebase foi complicado.

2020-08-31 12:47 UTC, marcelsavegnago commented
> Bom dia @marcelsavegnago, obrigado pela revisão. 
> 
> Vou dar uma repassada nos fluxos e corrigir esses problemas, o rebase foi complicado.

Imagino, com certeza teve muito coisa para organizar.

2020-08-31 16:15 UTC, rvalyi submitted a review, later dismissed
Pessoal, sou contra fazer merge desse PR da forma como esta. No inicio do PR @mileo ate falei que a gente podia abrir uma exceção de copiar um pouco de codigo (payment.term) do modulo oficial account pro uso excepcional onde não se instalaria o modulo Odoo account. Afinal, a geração dos payment lines do modulo account nao atende legal para fazer as projeções financeira, eh algo importante na America Latina onde tudo eh comprado/pago parcial. Entao teria que refazer esse codigo e bem ou mal a gente tava OK em enfiar isso no modulo l10n_br_fiscal por pragmatismo.

So que @mileo, quando falamos disso, falei que ja tava muito borderline e vc me prometeu que nao iria mais engordar o modulo fiscal com funcionalidade que nada tem a ver com coisas fiscais. So que de la para ca, esse PR engordou uns 200% ainda!

Umas semanas atras, vc queria alterar completamente os conceitos de payment mode e payment type nativos para fazer essa sua condição de pagamento. Quando vc nos perguntou no privado, te respondi que eramos contra isso para nao perder a comparatibilidade com o core e a OCA. So que ao mesmo tempo, fui claro e te aconselhei fazer isso num modulo extra.

So que vc jogou tudo nesse PR! No fim da contas tem quase 2000 linhas a mais no modulo l10n_br_fiscal que ate que seja provado o contrario ja deve ser o maior modulo da OCA inteira. Para ganhar medalha no projeto tem que conseguir modularizar o modulo fiscal, nao engordar ele ainda mais...

Afinal, uns 30% das funcionalidades desse PR nao tem uso se vc instalar o modulo account ou l10n_br_account (a copia das conceitos de payment.term, mode e type). Essa coisa de condicao de pagamento, talvez uns outros 30%, eh algo que em 10 anos no mercado nunca precisamos na Akretion. 

Nao digo que eh algo 100% inutil, consigo imaginar alguns usos, em e-commerce pro exemplo. Mas para mim a conta custo beneficio do PR nao fecha, deveria extrair no minimo a metade do codigo desse PR, essa coisas de condição de pagamento no minimo e jogar em outro modulo opcional. Inclusive seria uma funcionalidade que poderia ser usada fora do l10n-brazil talvez. So que se um dia alguem fizer ou fizer na OCA, a gente so deixa a migracao do modulo l10n_br_fiscal mais engessada se a gente junta tudo dessa forma...

cc @marcelsavegnago @renatonlima

2020-08-31 17:05 UTC, marcelsavegnago commented
@rvalyi 

- Sobre o tamanho do fiscal eu concordo que está muito grande e o caminho seria começara  modularizar mais 
- Sobre a compatibilidade com a OCA eu sou totalmente contra qualquer ação que gere este tipo de risco.
- Sobre o desenvolvimento de módulos que visam adicionar funcionalidades no financeiro que possam ser usados por outros eu submeteria para outro repositório tbm e no máximo localizaria o módulo em seguida para atender as necessidades do Brasil

O principal motivo de fazer questão de usar a OCA é pela compatibilidade que existe em uma gama gigante de módulos e por isso não faço mais questão de olha nem a loja de apps da Odoo já que a mesma não tem como garantir a compatibilidade entre os módulos desenvolvidos por parceiros e afins (oq acontece tbm com SAP e outras ERPs que permitem este tipo de atuação). Ou seja, a compatibilidade OCA é um ponto extremamente positivo tanto para nosso trabalho como para própria venda de serviço Odoo para os clientes que prospectamos. Recentemente uma das questões de um cliente foi exatamente sobre este cenário de falta de compatibilidade entre os módulos de parceiros SAP.

2020-08-31 17:13 UTC, mileo commented
@rvalyi quando conversei com o @renatonlima em uma call esses dias ele comentou que esta ok esta questão das condições comerciais.

Mas quando implementei essas modificações 4 Jul também fiz uma abordagem que ela ficava de fora: 
https://github.com/odoo-brazil/l10n-brazil/tree/feature/payment_in_fiscal_rem_conditions
https://github.com/odoo-brazil/l10n-brazil/commit/2d2e6e887aa180bed296060a4676b015bc72ceaa
https://github.com/odoo-brazil/l10n-brazil/commit/b05c5d3367022c5554372584b0537dee4ce6fef3

Por mim tanto faz, da pra implementar isso em um módulo separado. E quanto as outras questões você tem algum comentário?

2020-09-03 04:31 UTC, rvalyi commented
@mileo eu estou OK para ter merge do payment.term(.line) e generate_financial no l10n_br_fiscal, mas ter as outras coisas como modulo opcional. Segue o raciocínio:

1. eu accredito que vai muita `opiniao` na questao desse objeto `l10n_br_fiscal.payment.condition` que vc criou. Pode servir sim, mas tb parece inutil em muitos casos (todos nossos projetos ate agora por examplo). Nao achamos bom impor ao usuario da localizacao de ter que divergir tanto dos conceitos basicos documentados no Odoo nativo ou na OCA. Ja temos a localizacao a mais complexa da OCA inteira para apenas emitir qualquer NFe... Depois enquanto a localização OCA tem cara de super complexa, isso eh um prato cheio para empresas criticar isso da OCA e tentar levar os pequenos para módulos hyper simplificados como a Trust faz e isso acaba dividindo a comunidade a toa.

Eh melhor que isso seja uma escolha projeto por projeto caso a pessoa quer. Escolher isso, tem implicacoes por tras com a compatibilidade com o ecosistema OCA, a propagacao disso a partir de venda, compra (tem modulos OCA que propagam o payment_mode mas nao vao propagar seu l10n_br_fiscal.payment.condition)... E tb iria aumentar o trabalho na migracao depois quando Odoo SA toca nesses assuntos como nesse PR da v15: https://github.com/odoo/odoo/pull/56187
Lembrando que a OCA procura juntar o que pode ser compartilhado entre contribuidores importantes e procura deixar o mais possível as questões de opinioes em modulos anexos (por examplo a Akretion nao procura enfiar os modulos usability dela na OCA apesar de que quase todos nossos projetos usam, mas empresas como C2C por examplo vao preferir vender Odoo EE em muitos projetos em vez de usar isso).

2. eu accredito que isso pode ser implementado em modulo anexo sem qualquer problema e como eu ja falei, o modulo fiscal ja ta bem acima do peso, nao fica legal ir acumulando coisas que poderia ir num outro modulo e nao faz parte dos conceitos fiscais atuais do modulo. A gente sabe bem que quando a gente nao obriga a dependencias explicitas os conceitos acabam se misturando dentro de um modulo depois de algumas contribuicoes e que depois fica muito complicado modularizar de novo...

3. A respeito dos payment.term(.line) e generate_financial a situação eh diferente: basicamente a gente concorda que no Brasil a gestao das parcelas de pagamento eh essencial. Concordamos que a geracao dos account.move.line das parcelas no modulo account nao atende legal para gerenciar provisoes financeiras que nao sao account.move.line. Nisso teria que ser re-escrito de qualquer forma. Idealmente seria no modulo l10n_br_account, mas bom, ja que vc tem casos de uso onde instalariam o l10n_br_fiscal sem o modulo account (nem l10n_br_account), concordamos em mover a funcionalidade aqui no l10n_br_fiscal em vez de ser mais um modulo so para isso apenas. Tambem concordamos que isso permite melhorar a unificacao da gestao das parcelas nos modulos como l10n_br_nfe, l10n_br_nfse, sat etc sem ter que compatibilizar isso ao nivel do account ou em modulos adicionais... E por fim concordamos que eh muito conveniente ter esse generate_financial dentro do mixin fiscal ja que o restante da localizacao trata de injecta-lo nas invoices rascunho, vendas e compras, que sao objetos interessantes de se considerar em projeções financeiras.


Essa eh a minha opiniao sobre esse PR. Mas eu acho que vale a pena ter do @renatonlima tb. Por fim @mileo vc poderia por favor gerir um PR com rebase com essa branch simplificada https://github.com/odoo-brazil/l10n-brazil/tree/feature/payment_in_fiscal_rem_conditions para a gente poder avaliar melhor a questao do payment.term(.line) e generate_financial ?

2020-10-23 02:05 UTC, mileo commented
@renatonlima @rvalyi @marcelsavegnago @mbcosta 

Feito o rebase e algumas correções. Qualquer coisa estou a disposição.

2020-10-23 02:08 UTC, mileo commented
Extraído o conceito do account_payment_condition -> https://github.com/OCA/bank-payment/pull/747 quem sabe usamos no futuro.

2020-10-23 03:21 UTC, mileo commented
@gabrielcardoso21 se puder revisar novamente tb, pois o rebase foi complicado. 

OBS: Amanhã eu vou olhar com calma e corrigir os testes.

2020-10-23 18:06 UTC, gabrielcardoso21 approved these changes

2020-10-23 21:24 UTC, mileo commented
Testes corrigidos

2020-10-31 18:49 UTC, mileo commented
@renatonlima @rvalyi @marcelsavegnago Este PR esta pronto para revisão, se puderem dar uma olhada.

Nos últimos commits desta branch: https://github.com/kmee/l10n-brazil/tree/12.0.2.0-staging/l10n_br_nfe/models vcs podem encontrar a integração com a NF-e.

2020-11-02 03:33 UTC, rvalyi commented
@mileo vou voltar a avaliar esse PR. Porem antes de acumular novas funcionalidades no modulo l10n_br_fiscal que ja é o maior da OCA, eu prefiro que a gente limpa as coisas que foram recentemente adicionadas no modulo pela KMEE primeiro, ou seja esse outro PR https://github.com/OCA/l10n-brazil/pull/983 depois eu vejo esse. Se a gente não tiver essa disciplina e olhar apenas do lado das funcionalidades, logo a gente cria um novo monstro. Tem tb varias coisas da v8/v10 que precisa finalizar de migrar antes de pensar em coisas novas nesse modulo...

2020-12-02 23:09 UTC, marcelsavegnago commented
@gabrielcardoso21 sabe o que pode ser este erro do travis ? https://travis-ci.com/github/OCA/l10n-brazil/jobs/451443623#L3249

2020-12-04 13:28 UTC, gabrielcardoso21 commented
> @gabrielcardoso21 sabe o que pode ser este erro do travis ? https://travis-ci.com/github/OCA/l10n-brazil/jobs/451443623#L3249

Está dando o mesmo erro num outro PR, ambos acontecendo após dar um rebase na 12.0 da oca. Vou ter que dar uma olhada mais a fundo para ver como corrigir.

2020-12-28 14:26 UTC, marcelsavegnago approved these changes
@gabrielcardoso21 acredito que se fizer um novo push o travis deve ficar verde

2020-12-28 18:42 UTC, mileo commented
/ocabot merge minor

2020-12-28 19:16 UTC, renatonlima commented
@mileo Você deveria responder os comentários que fiz no PR e esperar eu aprovar porque existe alguns problemas neste PR que precisam ser resolvidos

2020-12-28 19:16 UTC, merged

2020-12-28 19:40 UTC, rvalyi commented
@mileo como vc me faz um merge que adiciona mais de 1300 linhas de codigo com so 6-7 linhas de teste num modulo que ja é enorme, - o maior da OCA toda - feito uns 90% pelo @renatonlima e eu e vc nao espera uma aprovaçao dele??? Ainda com uma copia de 200 linhas de codigo da Odoo SA mas atribuindo os copyrights a vc sem pena.
Me diz em que outro repo da OCA vc enfiaria qualquer codigo sem aprovaçao dos autores assim?

Ja tive a ocasião de comentar Luis: esse PR é muito borderline: vc quer enfiar coisas de financeiro no fiscal. A maior parte disso deve ser feito pelos modulos account e l10n_ br_account. Ai vc fala que quer harmonizar o financeiro dos documentos fiscais sem ter que instalar o modulo account. A intençao é muito borderline ja que hoje em dia o modulo account da Odoo SA so pretende gerenciar faturas, mas poderia ate ser. Se vc precisasse de 200 linhas para fazer isso a gente poderia ver. Mas 1300 linhas velho... Sendo que em 90% dos casos de uso, 80% dessas linhas se torna inuteis porque o codigo do modulo account passa a fazer...

Nao digo que é um não categórico. Mas no minimo acho um super abuso vc não ter a validaçao do @renatonlima para fazer isso. A ultima vez, que conversamos sobre, te falei que a gente tava ainda ocupado em concertar as merdas que vc tinha feito a ultima vez que fez assim um merge no modulo l10n_br_fiscal sem ter aprovaçao nossa que foi nesse PR: https://github.com/OCA/l10n-brazil/pull/928
e que o @renatonlima ainda ta ocupado de limpar aqui: https://github.com/OCA/l10n-brazil/pull/983

Complicado bicho...

2020-12-28 20:41 UTC, renatonlima commented
Eu fiz o revert deste merge e abri um novo PR #1058  para ser corrigido e revisado... Eu atualmente estou trabalhando no refatoramento do objetos e wizards dos documentos fiscais #983