mixin method extraction, inclusion in invoice line and synchro fixes
OCA/l10n-brazil pull request #839
Opened 2020-05-13 08:08 UTC by rvalyi

WORK IN PROGRESS DO NOT MERGE YET

Entao hoje sale.order.line, purchase.order.line e stock.move estao tendo o mixin fiscal incluido e que ta comecando a funcionar nos PR de sale, purchase, stock_account...

So que hoje o mixin fiscal nao esta sendo injectado no invoice.line e isso eh um problema!! Pois a ideia eh que pelo _inherits, vc edita o document fiscal pelo invoice sempre que for possivel. Senao claro, iriam aparecer dados mal sincronisados entre o invoice e o documento fiscal, tudo que a a gente **NAO QUER**.

Ai vc poderia pensar, bom, basta injectar o mixin no invoice.line. Porem isso nao vai dar certo porque:

1. o invoice.line tem uns 10 campos com nome igual do l10n_br_fiscal.document.fiscal.line (felizmente eles tem exactamente o mesmo papel)
2. o invoice.line **JA HERDA TODOS OS CAMPOS** do l10n_br_fiscal.document.fiscal.line pelo _inherits

Entao eh inutil e problematico herdar os campos do 10n_br_fiscal.document.fiscal.line de novo. Por isso eu separei o document line mixin em 2: extraindo:

1. `l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py` que tem todos os metodos do mixin
2. `l10n_br_fiscal/models/document_fiscal_line_mixin.py` que tem apenas os campos e herda os metodos do primeiro

Assim vira possivel injectar o `l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py` no invoice.line sem neurose!

Alem disso eu sobrecarreguei os metodos write e create do invoice.line para sincronisar as linhas de documento fiscal correctemente.

Eu ainda nao fiz nada a respeito do mixin do documento fiscal. Mas talvez nao seja necessario de tao mais simples que ele eh.

cc @renatonlima @gabrielcardoso21

2020-05-13 15:32 UTC, rvalyi commented
Eu estou compartilhando esse fix quanto antes. Porem no momento eu estou avaliando se isso vai simplificar (eh o que eu quero) a importacao de documentos fiscais (na branch do @gabrielcardoso21 e tb no meu PR que mostrava como importar um invoice completo aqui https://github.com/akretion/l10n-brazil/blob/12.0-l10n_br_account_nfe/l10n_br_account_nfe/models/account_invoice.py#L36
https://github.com/OCA/l10n-brazil/pull/753

A minha prioridade eh essa, mas logo eu considero subir uns testes desse PR e da sincronisacao entre invoice e documento fiscal. Vou poder faze-los antes do merge.

2020-05-13 15:34 UTC, rvalyi commented on l10n_br_account/models/account_invoice.py
> +        default=False)  # TODO hack for PR demo
isso vai sair antes do merge, mas deixa mais facil de avaliar o PR por enquanto pois senao teria que botar outros modulos como l10_n_br_sale ou l10_n_br_purchase na jogada.

2020-05-13 15:46 UTC, rvalyi commented
Como o arquivo l10n_br_fiscal/models/document_fiscal_line_mixin.py eh grande, quando eu cortei ele em 2, nao ficou claro no diff que alem de cortar ele em 2, eu tb  accrescentei esse novo metodo `_prepare_br_fiscal_dict`
https://github.com/akretion/l10n-brazil/blob/12.0-fiscal-mixin-fixes/l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py#L122

Ele deve ser usado quando o objetivo eh transferir a informacao fiscal de um objeto onde foi injectado o mixin `l10n_br_fiscal.document.line.mixin` (como sale.order.line, purchase.order.line... ou ate account.invoice.line pelo _inherits) quando vc quer gerir um `account.invoice.line` e entao uma linha de documento fiscal por tras pelo _inherits. Geralmente Odoo da uns hooks _prepare_* que a gente sobrecarrega na localizacao. Agora teria que chamar esse novo metodo `_prepare_br_fiscal_dict` nesses overrides.

Quando se trata editar ou criar um `account.invoice.line` o problema eh diferente pois dessa vez o sistema com _inherits escreve direitamente nos campos do `l10n_br_fiscal.document.line` de forma transparente.

Porem, nem todos campos estavam sincronisados de forma transparente pois alguns 10 campos tinham o mesmo nome no `l10n_br_fiscal.document.line` e `account.invoice.line`  como explicado aqui: https://github.com/akretion/l10n-brazil/blob/12.0-fiscal-mixin-fixes/l10n_br_account/models/account_invoice_line.py#L7

Ai para sincronisar esses campos em especiais, fiz um novo metodo `_prepare_shadowed_fields_dict` https://github.com/akretion/l10n-brazil/blob/12.0-fiscal-mixin-fixes/l10n_br_account/models/account_invoice_line.py#L44

Ele esta sendo usado no write e no create do `account.invoice.line` para que vc nao precisa faze-lo:
https://github.com/akretion/l10n-brazil/blob/12.0-fiscal-mixin-fixes/l10n_br_account/models/account_invoice_line.py#L52
https://github.com/akretion/l10n-brazil/blob/12.0-fiscal-mixin-fixes/l10n_br_account/models/account_invoice_line.py#L63

2020-05-16 02:18 UTC, renatonlima requested changes

2020-05-16 02:18 UTC, renatonlima commented on l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
> +class FiscalDocumentLineMixin(models.AbstractModel):
O nome da classe deveria ser FiscalDocumentLineMixinMethods

2020-05-19 18:53 UTC, mileo approved these changes

2020-05-19 18:54 UTC, gabrielcardoso21 approved these changes

2020-05-19 19:30 UTC, renatonlima approved these changes

2020-05-19 19:36 UTC, renatonlima commented
/ocabot merge nobump

2020-05-19 20:12 UTC, merged