[12.0][MIG] Cupom Fiscal Eletrônico (SAT e MDF-E) através do Backend
OCA/l10n-brazil pull request #849
Opened 2020-05-22 01:02 UTC by mileo

2021-02-10 03:20 UTC, mileo commented
Pessoal já é possível testar o módulo. Ainda tem os seguintes detalhes para corrigir:

- [ ] Verificar se é possível emitir SAT para cliente extrangeiro;
- [ ] Revisar e refatorar rotinas do Ceará:
- [ ]     - Validador Fiscal;
- [ ]     - Validador de Pagamentos;
- [ ] Implementar a consulta de sessão
- [ ] Reimplementar fluxo de impressão, após a autorização e o cancelamento;
- [ ] Enviar dados do Cupom por email caso o cliente esteja identificado;
- [ ] Alguns impostos não estão implementados;
- [ ] Implementar al_efetiva_icms_proprio;
- [ ] Refatorar as informações adicionais;
- [ ] Implementar testes;
- [ ] Melhorar a visão do documento fiscal.

Mas o envio e o cancelamento já esta funcionando.

2021-02-10 14:09 UTC, rvalyi requested changes
os arquivos

- views/fiscal_operation_cfe_.xml.xml e
- views/web_asset_backend_template.xml
 
nao estao usados no manifest, entao nao devem ficar no modulo, vc pode detonar eles?

Seria bom ter testes na hora do merge.

Sobre a questao de como integrar os pagamentos de forma limpa sem engordar o fiscal copiando parte do codigo modulo account da Odoo SA, a gente vai te propor uma alternativa assim que der tempo (depois do merge da NFe vai dar mais folego).

2021-02-10 14:57 UTC, mileo commented
> Seria bom ter testes na hora do merge.

- fiscal_operation_cfe_.xml.xml não esta sendo usado mesmo e já foi removido.

- web_asset_backend_template.xml conforme comentado no próprio arquivo ele deve ficar para ser ativado em uma segunda versão, junto com os arquivos JS, pois eles permitem o uso do SAT no Backend s/ VPN ou o servidor instalado fisicamente na mesma rede da loja. Mas isso vai ficar para um segundo momento.

- Referente aos testes estou verificando a melhor forma de fazer isso.

Sobre os pagamentos vou comentar no respectivo PR.

2021-06-11 19:40 UTC, marcelsavegnago commented
@mileo pode fazer um rebase ?

2021-06-11 20:22 UTC, mileo commented
> @mileo pode fazer um rebase ?

Sim, lembrando que esse PR depende do #1125

2021-06-23 16:27 UTC, marcelsavegnago commented
@mileo pergunta boba, por ora não consegue tirar a dependência da PR 1125 ?

2022-10-09 12:10 UTC, closed without merging