[12.0] Defini fiscal document serie method
OCA/l10n-brazil pull request #877
Opened 2020-05-25 20:45 UTC by renatonlima

Cria uma método no objeto Documento Fiscal, para buscar a Série do documento fiscal, primeiro se a operação fiscal tiver uma série especifica ou se existe uma série padrão, existe um método  que pode ser sobre escrito pelos módulos l10n_br_nfe, l10n_br_nfse e etc que caso adicione um campo no res.company para a série padrão do documento.

2020-05-26 12:47 UTC, gabrielcardoso21 approved these changes

2020-06-01 15:02 UTC, marcelsavegnago commented on l10n_br_fiscal/models/document.py
> +                self.company_id, self.fiscal_operation_id)
File "/.repo_requirements/odoo/odoo/models.py", line 5533, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/.repo_requirements/odoo/odoo/models.py", line 5377, in _onchange_eval
    method_res = method(self)
  File "/home/odoo/build/OCA/l10n-brazil/l10n_br_fiscal/models/document.py", line 811, in _onchange_document_type_id
    self.company_id, self.fiscal_operation_id)
  File "/.repo_requirements/odoo/odoo/fields.py", line 1027, in __set__
    value = self.convert_to_cache(value, record)
  File "/.repo_requirements/odoo/odoo/fields.py", line 2178, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for l10n_br_fiscal.document.document_serie_id: l10n_br_fiscal.document.serie(1, 4)

2020-06-01 15:02 UTC, marcelsavegnago commented on l10n_br_fiscal/models/document.py
> +                self.company_id, self.fiscal_operation_id)
Este erro ocorreu quando criei uma segunda série

![image](https://user-images.githubusercontent.com/3595132/82850018-0d7ef900-9ed1-11ea-9c91-2cfd87e51f7c.png)

2020-06-11 20:04 UTC, renatonlima commented on l10n_br_fiscal/models/document.py
> +                self.company_id, self.fiscal_operation_id)
@marcelofrare eu corrigi esse problema refatorando o método _get_default_document_serie e também corrigi um outro problema relacionado a definição da série na operação fiscal!

2020-06-11 20:51 UTC, marcelofrare commented on l10n_br_fiscal/models/document.py
> +                self.company_id, self.fiscal_operation_id)
@renatonlima ? 
I think you are wrong name ;-)

2020-06-11 20:56 UTC, renatonlima commented on l10n_br_fiscal/models/document.py
> +                self.company_id, self.fiscal_operation_id)
@marcelofrare Sorry... ;-) @marcelsavegnago

2020-06-12 02:00 UTC, marcelsavegnago commented on l10n_br_fiscal/models/document.py
> +                self.company_id, self.fiscal_operation_id)
@renatonlima no recebimento de documentos, operação Compra o esperado é trazer a mesma série utilizada na emissão de documentos? 

![image](https://user-images.githubusercontent.com/3595132/84456780-404a2080-ac37-11ea-873c-2303a12f4820.png)

2020-06-12 10:36 UTC, mileo requested changes

2020-06-12 10:36 UTC, mileo commented on l10n_br_fiscal/models/document_serie.py
>              'implementation': 'no_gap',
Utilizar a sequências sem gap é um pesadelo em implementações com muitas emissões de nota fiscal, principalmente com múltiplos usuários.

O processo de inutilização foi feito para mitigar o problema de locks constantes no banco de dados.

Na minha opinião é melhor deixar as sequências com buracos e melhorarmos o processo de inutilização.

Criar um cron que diariamente revise as sequencias, sugerindo inutilizacoes ou alguma outra forma.

2020-06-12 15:29 UTC, renatonlima commented on l10n_br_fiscal/models/document.py
> +                self.company_id, self.fiscal_operation_id)
@marcelsavegnago Caso o emitente seja seja seu parceiro (fornecedor) não será preenchido o document_serie_id, somente o document_serie, caso o emitente seja a empresa, será usada a séria e preenchido o campo document_serie_id

2020-06-12 18:36 UTC, renatonlima commented on l10n_br_fiscal/models/document_serie.py
>              'implementation': 'no_gap',
Por padrão se ao criar uma série sem uma sequencia sequencia, será gerada uma sequencia automaticamente, do tipo "No Gap", porque a maioria dos casos não há problema, mas isso pode ser alterado facilmente, na sequencia...

Eu tirei a geração da numeração no create do documento fiscal e esta só no workflow quanto do documento fiscal é criado.

Não foi mudado a rotina de inutilização, só foi refatorada para deixar esses métodos "encapsulado" no objeto de série do documento fiscal e ser utilizado pela função de numeração na série do documento fiscal.

2020-06-22 00:22 UTC, mileo requested changes
Conforme comentado no telegram o método de calculo da chave deve ser genérico, pois pode ser aplicado em outros documentos fiscais.

https://www.oobj.com.br/bc/article/como-%C3%A9-formada-a-chave-de-acesso-de-uma-nf-e-nfc-e-de-um-ct-e-e-um-mdf-e-281.html

2020-06-22 00:23 UTC, mileo commented
> Conforme comentado no telegram o método de calculo da chave deve ser genérico, pois pode ser aplicado em outros documentos fiscais.
> 
> https://www.oobj.com.br/bc/article/como-%C3%A9-formada-a-chave-de-acesso-de-uma-nf-e-nfc-e-de-um-ct-e-e-um-mdf-e-281.html

Referente ao outro comentário, da sequência tudo bem, vou pensar posteriormente em uma forma de deixar isso claro para o usuário.

2020-06-23 17:49 UTC, mileo approved these changes

2020-06-23 17:50 UTC, mileo commented
/ocabot merge nobump

2020-06-23 18:12 UTC, merged