[12.0][REF] Change class of Fiscal Comments
OCA/l10n-brazil pull request #880
Opened 2020-05-28 17:36 UTC by mbcosta

Changed class of Fiscal Comments to can use it on inherit models like Sale and Purchase

cc @renatonlima @rvalyi @mileo

2020-05-28 23:04 UTC, rvalyi approved these changes
LGTM

2020-05-29 06:30 UTC, rvalyi commented
tb se alguem tem duvida, nao precisa de script de migracao, pois se um documento ou uma linha de documento ja tiver um comentario com uma chave document_(line_)id apontando para eles, vao continuar com os campos comments pelos mixin e eles vao ainda apontar nos documentos (ou linhas) certas.

2020-05-29 17:50 UTC, mbcosta commented
Depends https://github.com/OCA/l10n-brazil/pull/881 , because the PR simplify necessity of inherit methods

2020-05-29 19:16 UTC, renatonlima approved these changes

2020-05-29 19:27 UTC, renatonlima requested changes

2020-05-29 19:27 UTC, renatonlima commented on l10n_br_fiscal/models/document_fiscal_line_mixin.py
> +        column1='document_line_mixin_id',
Uma coisa que esta faltando aqui seria um domain no campo object para pegar apenas registros com a seleção 'l10n_br_fiscal.document.line'

2020-05-29 19:27 UTC, renatonlima commented on l10n_br_fiscal/models/document_fiscal_mixin.py
> +        column1='document_mixin_id',
Uma coisa que esta faltando aqui seria um domain no campo object para pegar apenas registros com a seleção 'l10n_br_fiscal.document'

2020-05-29 19:27 UTC, renatonlima commented on l10n_br_fiscal/models/document_fiscal_line_mixin.py
> +        string='Comments',
Você também pode criar uma constante no fiscal.py FISCAL_COMMENT_OBJECTS para trocar os valores deste selection https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_fiscal/models/comment.py#L39 e criar as constantes FISCAL_COMMENT_DOCUMENT e FISCAL_COMMENT_LINE e usa-lo nestes domains

2020-06-11 19:40 UTC, renatonlima approved these changes

2020-06-11 19:50 UTC, mileo commented
/ocabot merge nobump

2020-06-11 20:09 UTC, merged