[12.0] Padronização README e INDEX l10n_br_account
OCA/l10n-brazil pull request #902
Opened 2020-06-14 08:40 UTC by marcelsavegnago

Padronização pasta README, README.rst e Index.html

2020-09-28 20:23 UTC, renatonlima approved these changes

2020-09-28 22:19 UTC, mileo approved these changes

2020-09-28 22:21 UTC, mileo requested changes, later dismissed
Fix runbot please

2020-09-28 22:22 UTC, mileo commented
Será que conseguimos fazer alguma padronização dos contribuidores?

Algo como: 

```
(oca12) [mileo@mileo-xps l10n-brazil]$ git log --pretty=format:"%an%x09" l10n_br_account | sort | uniq
Carlos Almeida  
cma     
Daniel Furcht   
Daniel-Furcht   
Danimar Ribeiro 
Developer       
Fabio Negrini   
fernandomr      
Florian da Costa        
Gabriel Cardoso de Faria        
Hendrix Costa   
Leonardo Santagada      
Luis Felipe Mileo       
Luis Felipe Miléo       
Magno   
Magno Costa     
Magno Costa - Akretion  
Marcel Savegnago        
Matheus Felix   
Maurício Liell  
Michell Stuttgart       
mileo   
mstuttgart      
MStuttgart      
nvi-openerp     
OCA-git-bot     
OCA Transbot    
oca-travis      
Raphael Valyi   
Raphaël Valyi   
renato  
Renato  
Renato Lima     
sadamo  
Stéphane Bidoul 
Vinicius Dittgen        
Yogesh Kushwaha 
```

2020-09-28 22:26 UTC, mileo commented
Ou algo relacionado ao percentual em relação ao código?

```
(oca12) [mileo@mileo-xps l10n_br_account]$ git ls-files -z | xargs -0n1 git blame -w | perl -n -e '/^.*\((.*?)\s*[\d]{4}/; print $1,"\n"' | sort -f | uniq -c | sort -n
      1 "base"), [500.0, 550.0,
      1 �B!���p:�)qD:f.��m�6"�
      1 OCA-git-bot
      1 r��y��0���
                  �v;
      1 sadamo
      2 Maurício Liell
      4 Luis Felipe Miléo
      8 Hendrix Costa
      8 Stéphane Bidoul
     13 Developer
     21 C)
     31 renato
     44 oca-travis
     45 Gabriel Cardoso de Faria
     51 Magno
     58 Magno Costa - Akretion
     72 Raphaël Valyi
     94 OCA Transbot
    419 Luis Felipe Mileo
    609 Renato
   1207 Renato Lima
```

2020-09-29 01:08 UTC, rvalyi commented
> Será que conseguimos fazer alguma padronização dos contribuidores?
> 
> Algo como:
> 
> ```
> (oca12) [mileo@mileo-xps l10n-brazil]$ git log --pretty=format:"%an%x09" l10n_br_account | sort | uniq
> Carlos Almeida  
> cma     
> Daniel Furcht   
> ...

Eu acho que no global temos isso aqui e apontamo isso no README do projeto e vamos contina-fazendo lo que eh a coisa mais próximo da realidade https://github.com/OCA/l10n-brazil/graphs/contributors

Sobre as contribuicoes de cada modulo: nao tem padrao na OCA. Mas a nossa posicao pros modulos liderados pela Akretion eh que queremos ter o control de dizer quando uma contribuicao merece ser mencionada ou nao. Nao eh apenas pelo numero de commits. Eh comum na OCA alguem rejeitar uma contribuicao que o cara so migrou um modulo. Para um modulo de 50 linhas, se vc fizer 20 eh de boa fazer ser contribuidor ou co-autor, agora se o modulo faz 5000 linhas nao eh de boa vc ser contribuidor com 20 linhazinhas.

Se a gente abrir a perna com isso, isso manda o sinal errado para empresas com olho grande (nao faltam) que podem ir trollando no projeto e vao conseguir se promover sem ajudar de vdd o projeto. Eu acho que como cada autor de modulo temos a liberdade de decidir como queremos isso nos modulos que a genet fez e maintem. Se vc vai la no OCA-mis-builder propor regras pros modulos deles eles tem todo direito de nao te atender tb. E da mesma forma, nos modulos que a KMEE lidera que seja de RH ou alguns outros modulos fiscais, vcs tem toda liberdade para implementar politicas diferentes, so nao eh legal vcs querer decidir em modulos que foram feito 90% pela Akretion.

Lembrando que se vc @mileo  nao fez mais no projeto, o motivo principal, alem de ter chegado 4 anos depois eh que uns 5 anos atras vcs se equivocaram com no fork do Ary. Vcs seguraram nele apesar das nossas criticas categóricas, apesar de nao ter teste ou qualidade de OCA, nem modularidade, nem a menor continuidade com os 5 anos anteriores. Mas vc segurou nisso ate nao der mais, ate se tocar que nao vingaria quando vc viu o trabalho que eu tinha feito no generateDS ou o Renato no fiscal e voltar a contribuir na OCA depois da gente ter feito o grosso da migracao para a v10 (com o refator do modulo account) e antes do Renato sozinho fazer as funcionalidades do modulo fiscal que vc exigia sem ter proposto com PRs da forma correcta. Entao enquanto vcs tavam ganhando dinheiro (com o projeto que a gente se recusou a vender) fazendo projeto que nao teria como atender com qualidade de OCA, a gente tava se lascando fazendo o trabalho da forma correcta na OCA dentro dos padroes de qualidade, com modularidade, sem burlar o modulo account e sem mandar um foda se para quem tinha apostado na OCA antes. Nao adianta querer re-escrever o passado agora.

2020-09-29 01:55 UTC, rvalyi commented
pessoal, dito isso, como a pessoa que bolou o sistema de _inherits (e os mixins relacionados) para criar documentos fiscais de forma transparente lidando apenas com os invoices nos fluxos padrao da OCA e do Odoo que eh o sistema chave da arquitetura da v12 com o modulo l10n_br_fiscal extraido eu acho que tenho que ser mecionado como contribuidor (nao tou aqui fazendo juiz se tem que ter outros).

2020-09-29 02:43 UTC, rvalyi commented
Mais um comentario: @mileo por ser o modulo que depende do account e casa a parte fiscal com o account, o modulo se chama igual antes e acaba (pelo modulo fiscal) fazendo as mesmas coisas que antes e mais na vdd. So que vc tem que ver que depois do refator do modulo l10n_br_account na v10 (devido ao refator do account do Odoo da v9) e da extracao do modulo fiscal com um sistema de gestao de taxas completamente diferente, nao sobrou nehnum pedaco de codigo das coisas do l10n_br_account. Eh importante manter o historico da evoluicao (e com o historico dos commits), mas realmente acabou sendo re-escrito desde a v8. Porem com continuidade conceitual de usar o account.invoive, o account.move.line, o account_move_create, o account.fiscal.tax, account.fiscal.position etc...

2020-10-06 23:04 UTC, marcelsavegnago commented
> Fix runbot please

@mileo Done!

2020-10-09 17:50 UTC, rvalyi commented
como eu falei, como eu bolei o sistema do inherits para pilotar os fiscal doc e fiscal doc line pelo invoice que eh uma parte critica da arquitetura e que foi aquilo que permitiu extrair o modulo fiscal (comparando com as versões anteriores tb sem partir pro Frankenstein de burlar o account) do modulo eu acho que eu tenho que estar nos contribuidores...

2020-10-09 18:02 UTC, marcelsavegnago commented
> como eu falei, como eu bolei o sistema do inherits para pilotar os fiscal doc e fiscal doc line pelo invoice que eh uma parte critica da arquitetura e que foi aquilo que permitiu extrair o modulo fiscal (comparando com as versões anteriores tb sem partir pro Frankenstein de burlar o account) do modulo eu acho que eu tenho que estar nos contribuidores...

Blzz.. já faço a alteração

2020-10-09 18:40 UTC, rvalyi approved these changes

2020-11-12 18:25 UTC, rvalyi commented
/ocabot merge nobump

2020-11-12 18:41 UTC, merged