[NEW] PagSeguro
OCA/l10n-brazil pull request #917
Opened 2020-06-28 19:06 UTC by mileo

Signed-off-by: Luis Felipe Mileo <mileo@kmee.com.br>

2020-07-01 18:55 UTC, marcelsavegnago commented
@mileo primeiramente parabéns pelo trabalho. Estava aqui tratando outros assuntos e veio algo em relação a esta integração. Enfim, minha dúvida é se a integração com o pagseguro deveria ser feita a nível da localização Brasil ou se deveria ser submetida para outro projeto OCA como o account-payment por exemplo.

O que acha ?

2020-07-01 20:09 UTC, mileo commented
> @mileo primeiramente parabéns pelo trabalho. Estava aqui tratando outros assuntos e veio algo em relação a esta integração. Enfim, minha dúvida é se a integração com o pagseguro deveria ser feita a nível da localização Brasil ou se deveria ser submetida para outro projeto OCA como o account-payment por exemplo.
> 
> >

Sabe me dizer se o pagseguro é aceito em outros países? 

OBS: Ainda tem um longo trabalho para finalizar esse módulo, só fiz a casca.

2020-07-01 21:36 UTC, marcelsavegnago commented
> > @mileo primeiramente parabéns pelo trabalho. Estava aqui tratando outros assuntos e veio algo em relação a esta integração. Enfim, minha dúvida é se a integração com o pagseguro deveria ser feita a nível da localização Brasil ou se deveria ser submetida para outro projeto OCA como o account-payment por exemplo.
> > >
> 
> Sabe me dizer se o pagseguro é aceito em outros países?
> 
> OBS: Ainda tem um longo trabalho para finalizar esse módulo, só fiz a casca.

Verdade, por hora me parece que atende somente o Brasil. Vi um exemplo de um modulo de pagamento dentro de um repositório de localização, no caso no l10n-spain e talvez iria sugerir retirar o l10n_br do nome do módulo deixando apenas payment_pagseguro_oca (já existe um payment_pagseguro na loja da Odoo). Porém, se tecnicamente for possível utilizar o módulo sem depender da localização brasileira eu consideraria submeter para account-payment (avaliando claro se teria alguma restrição do projeto account-payment quando a área de atuação atual do pagseguro)

Exemplo de payment_redsys na l10n-spain: https://github.com/OCA/l10n-spain/tree/12.0/payment_redsys
Módulo payment_pagseguro: https://apps.odoo.com/apps/modules/12.0/payment_pagseguro/

2020-07-01 22:00 UTC, rvalyi commented
Muito louco,acabei de fuçar no appstore da OCA e eu simplesmente não consigo encontrar nenhum gateway de pagamento (procurando acquirer tb) na OCA!!! Esse payment_redsys eh a unica que eu achei. A meu ver isso ja fala bastante sobre a tal maturidade do ecommerce do Odoo se nenhum cascudo da OCA se arriscou com isso... Nisso nao vejo problema em deixar o modulo na OCA ja que so funciona no Brasil e que não tem lugar melhor hoje (account-payment nao tem gateway nao...) ja que pelo jeito so o pessoal desse repo vai poder avaliar e usar basicamente...

Na Akretion a gente tem projetos commerces bastantes puxados e entao refizemos alguns gateways mais robustos do que os oficiais (talvez a Odoo SA consolida os deles), botamos num repo fora da OCA por enquanto https://github.com/shopinvader/odoo-shopinvader-payment, hoje elas dependem do modulo Shopinvader.

2020-07-01 22:05 UTC, augustodinizl commented
galera, pra v12, o pessoal da argentina fez aqui: https://github.com/ctmil , acredito que seja um ponto de partida...

2020-07-01 22:08 UTC, marcelsavegnago commented
> https://github.com/ctmil

@augustodinizl legal.. vi o módulo do mercadopago lah

2020-07-01 22:12 UTC, marcelsavegnago commented
> Muito louco,acabei de fuçar no appstore da OCA e eu simplesmente não consigo encontrar nenhum gateway de pagamento (procurando acquirer tb) na OCA!!! Esse payment_redsys eh a unica que eu achei. A meu ver isso ja fala bastante sobre a tal maturidade do ecommerce do Odoo se nenhum cascudo da OCA se arriscou com isso... Nisso nao vejo problema em deixar o modulo na OCA ja que so funciona no Brasil e que não tem lugar melhor hoje (account-payment nao tem gateway nao...) ja que pelo jeito so o pessoal desse repo vai poder avaliar e usar basicamente...
> 
> Na Akretion a gente tem projetos commerces bastantes puxados e entao refizemos alguns gateways mais robustos do que os oficiais (talvez a Odoo SA consolida os deles), botamos num repo fora da OCA por enquanto https://github.com/shopinvader/odoo-shopinvader-payment (elas dependem do modulo Shopinvader porem).

@rvalyi então.. tbm não achei nenhum modulo do account-payment apesar da descrição do projeto citar a gestão de paypal, ogone e outros. Enfim, se não for interessante submeter pra lah, sugiro apenas a mudança do nome para payment_pagseguro_oca já que pra mim não se trata de um módulo de localização e tbm por não ter dependência de nada da localização por hora.

2020-07-01 22:30 UTC, rvalyi commented
> 
> @rvalyi então.. tbm não achei nenhum modulo no account-payment apesar da descrição do projeto citar a gestão de paypal, ogone e outros. Enfim, se não for interessante submeter pra lah, sugiro apenas a mudança do nome para payment_pagseguro_oca já que pra mim não se trata de um módulo de localização e tbm por não ter dependência de nada da localização por hora.

Isso eu concordo completamente. O ```l10n_br_``` tem que sinalizar que depende de alguns modulos da localizacao e se integra com eles. Alias eh por isso que o modulo chave do framework generateDS eu chamei ele de spec_driven_model, tb sem prefixo. E um dia de repente ele passa a voar num outro repo da OCA assim como ja externalizamos o OCA/account-fiscal-rules no passado (e hoje a gente nem usa mais e a galera usa).

2020-07-08 22:47 UTC, Filipecamposfontes commented
Percepção inicial. 

Ele carregou direitinho no e-commerce do odoo 12 mas nos teste com o webform de redirecionamento para o PagSeguro mas não foi.
Quem estiver com este projeto em mão e quiser testar estou com uma instalação em andamento e posso fazer os teste, reportar os Bugs e ajudar no desenvolvimento deste modulo.
Tenho o modulo do pagseguro da Betavision que comprei pela loja da Odoo S.A em outra instalação em produção e para trocar fazer a troca por este deu conflito de XML mesmo desativando o modulo da Betavision. e desinstalando.
outra duvida foi que nas configurações deste modulo solicita 4 informações de conta do usuário e o pagseguro fornece somente o Token.
E para adiantar quero aplicar as traduções neste modulo,  alguém pode me enviar o link de onde posso traduzir este modulo do pagseguro.

2020-07-14 21:07 UTC, marcos-mendez commented
> > @mileo primeiramente parabéns pelo trabalho. Estava aqui tratando outros assuntos e veio algo em relação a esta integração. Enfim, minha dúvida é se a integração com o pagseguro deveria ser feita a nível da localização Brasil ou se deveria ser submetida para outro projeto OCA como o account-payment por exemplo.
> > >
> 
> Sabe me dizer se o pagseguro é aceito em outros países?
> 
> OBS: Ainda tem um longo trabalho para finalizar esse módulo, só fiz a casca.

Negativo, e inclusive por isso nós estamos avaliando como ajudar.

podemos fazer um br_payment_aquires tipo para os gatways tupiniquins

@jaqueline você viu isso?

2020-07-14 22:36 UTC, marcelsavegnago commented
> > > @mileo primeiramente parabéns pelo trabalho. Estava aqui tratando outros assuntos e veio algo em relação a esta integração. Enfim, minha dúvida é se a integração com o pagseguro deveria ser feita a nível da localização Brasil ou se deveria ser submetida para outro projeto OCA como o account-payment por exemplo.
> > > >
> > 
> > 
> > Sabe me dizer se o pagseguro é aceito em outros países?
> > OBS: Ainda tem um longo trabalho para finalizar esse módulo, só fiz a casca.
> 
> Negativo, e inclusive por isso nós estamos avaliando como ajudar.
> 
> podemos fazer um br_payment_aquires tipo para os gatways tupiniquins
> 
> @jaqueline você viu isso?

@jaqueline se for trabalhar em algo, pensa de forma bem modular(payment_pagseguro, payment_mercadopago e etc) e avalie bem as dependências para não gerar dependências desnecessárias. O fato de começar o nome do módulo **l10n_br_** eu entende que cabe avaliação de caso a caso mas como disse antes eu não forçaria dependência da localização brasileira a não ser que seja necessário.

2021-12-15 23:11 UTC, marcos-mendez commented
Negativo, somente Brasil

Em ter, 14 de jul de 2020 19:37, Marcel Savegnago ***@***.***>
escreveu:

> @mileo <https://github.com/mileo> primeiramente parabéns pelo trabalho.
> Estava aqui tratando outros assuntos e veio algo em relação a esta
> integração. Enfim, minha dúvida é se a integração com o pagseguro deveria
> ser feita a nível da localização Brasil ou se deveria ser submetida para
> outro projeto OCA como o account-payment por exemplo.
>
> Sabe me dizer se o pagseguro é aceito em outros países?
> OBS: Ainda tem um longo trabalho para finalizar esse módulo, só fiz a
> casca.
>
> Negativo, e inclusive por isso nós estamos avaliando como ajudar.
>
> podemos fazer um br_payment_aquires tipo para os gatways tupiniquins
>
> @jaqueline <https://github.com/jaqueline> você viu isso?
>
> @jaqueline <https://github.com/jaqueline> se for trabalhar em algo, pensa
> de forma bem modular(payment_pagseguro, payment_mercadopago e etc) e avalie
> bem as dependências para não gerar dependências desnecessárias. O fato de
> começar o nome do módulo *l10n_br_* eu entende que cabe avaliação de caso
> a caso mas como disse antes eu não forçaria dependência da localização
> brasileira a não ser que seja necessário.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/l10n-brazil/pull/917#issuecomment-658447179>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJEVVIB4HHBH5AZYGEZBGRTR3TMZLANCNFSM4OKVCR2A>
> .
>

2021-12-22 18:08 UTC, rvalyi commented
Essa branch ta bem esquezita parece que tem demais commits. Daria para fazer um rebase dela com a 12.0 da OCA?

2021-12-23 20:31 UTC, mileo commented
@kmmelcher esses seus 3 últimos dois commits não estão corretos.

1. Vc não deveria ter feito um merge e sim o rebase
2. Não seria preciso essa remoção
3. A branch de destino é a 12.0 então o README já esta correto.

2022-01-18 14:50 UTC, marcelsavegnago commented
All green

2022-01-18 19:16 UTC, marcos-mendez reviewed
Estou com dificuldades na LXC para instalar o modulo vou fazer mais alguns test e vejo o que é

2022-01-28 17:04 UTC, DiegoParadeda commented
@cristiano-one @kmmelcher encontrei um bug pequeno aqui na cobrança.

![image](https://user-images.githubusercontent.com/12245538/151589223-c9688fae-8f90-4a66-8f82-f7b8e2f444a6.png)
![image](https://user-images.githubusercontent.com/12245538/151589232-f3242e79-3b39-4326-b109-1689005d85e4.png)

O payment_token criado fica disponível para reutilização no site (pelo mesmo cliente é claro) - imagem 2.

Porém, até onde eu sei, a PagSeguro não permite a reutilização do cartão (como mostrei na imagem 1)

Então vejo duas possíveis saídas pra esse problema:

1. Ver se existe alguma opção no request feito pra PagSeguro que indica que você pretende reutilizar esse cartão encriptado - se existir podemos considerar isso.

2. Deletar o payment_token após a operação (verificar se isso não quebra o funcionamento da Captura e Estorno)
2.1 Se não der pra deletar o payment_token, ou se não achar interessante podem utilizar a seguinte estratégia:

```
payment_token_id.active = False
```

2022-01-28 17:55 UTC, kmmelcher commented
@DiegoParadeda Resolvido!

2022-03-11 17:37 UTC, DiegoParadeda approved these changes

2022-03-11 18:30 UTC, sadamo approved these changes

2022-03-11 19:23 UTC, marcelsavegnago commented
@mileo logo após o merge vcs pretendem já migrar para 14.0 ?

2022-03-16 13:46 UTC, marcelsavegnago commented
@mileo pelo que entendi vocês retiraram o módulo das configurações do pre-commit ? Se sim, teria como habilitar e rodar o pre-commit ?

2022-03-16 17:29 UTC, mileo commented
> @mileo pelo que entendi vocês retiraram o módulo das configurações do pre-commit ? Se sim, teria como habilitar e rodar o pre-commit ?

@DiegoParadeda @sadamo FYC

2022-03-17 19:09 UTC, renatonlima requested changes

2022-03-17 19:09 UTC, renatonlima commented on payment_pagseguro/models/payment_transaction.py
> +    u"BRL",
u' strings Is not necessary in Pyhton 3

2022-03-17 19:09 UTC, renatonlima commented on payment_pagseguro/models/payment_transaction.py
> +    u"BRL",
Isso também me levou a pensar no motivo que usar essa constante, porque só esta sendo usado na linha 260 para pegar apenas o primeiro item "BRL", ao que parece o PagSeguro só aceita pagamentos em reais, nesse campo no objeto payment.transaction existe o campo currency_id e eu acho que na linha 260 deveria ser usado o valor desse campo.

2022-03-17 19:09 UTC, renatonlima commented on payment_pagseguro/models/payment_transaction.py
> +                "currency": INT_CURRENCIES[0],
Caso a fatura esteja em outra moeda, o que é feito? É gerado um pagamento convertido em reais ou é gerado um raise com a mensagem que o meio de pagamento só pode ser usado para pagamentos em reais?

2022-03-22 18:44 UTC, kmmelcher commented on payment_pagseguro/models/payment_transaction.py
> +    u"BRL",
Retiramos essa lista de moedas e substítuímos por uma string 'BRL' hardcoded

2022-03-22 18:45 UTC, kmmelcher commented on payment_pagseguro/models/payment_transaction.py
> +                "currency": INT_CURRENCIES[0],
Fizemos uma checagem no método de capture transaction para validar a moeda tanto no invoice quanto no sale order.

2022-03-22 18:47 UTC, kmmelcher commented
Aumentamos o coverage do nosso teste, porém o coverage do project ainda está menor do que o targe e não sabemos o porquê. Alguém sabe o motivo?

2022-03-22 19:24 UTC, marcelsavegnago commented
@kmmelcher faz um rebase com a 12.0 original fazendo favor.

2022-03-23 11:42 UTC, kmmelcher commented
@marcelsavegnago rebase feito, agora todos os testes estão passado

2022-03-24 01:33 UTC, rvalyi requested changes

2022-03-24 01:33 UTC, rvalyi commented on .pre-commit-config.yaml
> +  ^payment_pagseguro/|
o modulo não passa o pre-commit? Batendo o olho parece que estaria perto de passar, não valeria a pena ativar o pre-commit tirando essa linha?

2022-03-24 01:33 UTC, rvalyi commented on payment_pagseguro/models/payment_transaction.py
> +            "_create_pagseguro_charge: Values received:\n%s", pprint.pformat(res)
Eu não tenho certeza se é seguro fazer isso. Porque no momento vcs estão logando 10 dos 16 numeros do cartão no log assim como a data de expiração. Eh provável que isso ajuda por exemplo um pirata que teria algum banco encriptado con os mesmos cartões a quebrar a criptografia por exemplo. Ou também se o Pagseguro passasse a retornar a informação completa vc iria logar direito pro estagiário ver. Então sei la eu não faria um log disso tudo não, talvez apenas de alguns valores desse dicionario.
![2022-03-23_22-31](https://user-images.githubusercontent.com/16926/159824201-71ca0a13-1749-4dff-bce0-2a7ec129fe2e.png)

2022-03-24 10:09 UTC, kmmelcher commented on .pre-commit-config.yaml
> +  ^payment_pagseguro/|
Olá @rvalyi, essa linha já foi removida, o pagseguro já está passando pelo pre-commit. Esse próprio comentário aqui no PR está com a label "Outdated", porque já foi removido

2022-03-24 10:23 UTC, kmmelcher commented on payment_pagseguro/models/payment_transaction.py
> +            "_create_pagseguro_charge: Values received:\n%s", pprint.pformat(res)
Obrigado pela sugestão @rvalyi, concordo contigo! apesar de ser feito a criptografia do cartão por meio do checkout transparente da pagseguro, nos requests a gente recebe de volta os dados completos do cartão, mesmo passando apenas o token. 
Estou pensando em colocar as seguintes chaves no dicionário: amount, created_at, description, id, paid_at, payment_response, message, reference, reference_id e status. O que você acha?

2022-03-24 12:59 UTC, rvalyi commented on payment_pagseguro/models/payment_transaction.py
> +            "_create_pagseguro_charge: Values received:\n%s", pprint.pformat(res)
Pode ser assim sim.

2022-03-24 16:02 UTC, rvalyi commented on payment_pagseguro/models/payment_transaction.py
> +            "_create_pagseguro_charge: Values received:\n%s", pprint.pformat(res)
@kmmelcher para vc entender, a gente ta com pé atras com isso porque já rolou isso no repo (que é a pior falha de segurança que eu ja vi na OCA inteira)... https://github.com/OCA/l10n-brazil/pull/1562#issuecomment-902030370

2022-03-24 16:29 UTC, kmmelcher commented on payment_pagseguro/models/payment_transaction.py
> +            "_create_pagseguro_charge: Values received:\n%s", pprint.pformat(res)
Entendo, tranquilo!

2022-04-05 18:10 UTC, sadamo approved these changes

2022-04-05 18:27 UTC, lluisgustavoreis approved these changes

2022-04-05 18:33 UTC, rvalyi approved these changes
LGTM

2022-04-05 18:37 UTC, marcelsavegnago approved these changes
LGTM
Se possível aproveitem o embalo e migrem o módulo para 14.0 :)

2022-04-05 18:58 UTC, marcelsavegnago commented
/ocabot merge nobump

2022-04-05 20:16 UTC, merged

2022-04-05 21:25 UTC, marcelsavegnago commented
@mileo não sei se os teus meninos :D assinaram a CLA da OCA, caso não tenham feito e puder solicitar que façam.. acho que é bom.