[ADD] l10n_br_repair : Add Brazilian Localization Repair
OCA/l10n-brazil pull request #925
Opened 2020-07-18 16:37 UTC by marcelsavegnago

2020-07-21 05:46 UTC, marcelsavegnago commented
@renatonlima consegui chegar ao ponto de gerar as faturas e os documentos fiscal. Porém, no caso do documento fiscal acontece igual aconteceu com o sales. Gera o documento fiscal de produto com todos os itens do reparo (produto e serviço) e o documento fiscal de serviço gerou vazio.

Não consegui manipular a invoice com o super e portanto sobrescrevi a função de geração da invoice do módulo repair. Enfim, para efeito de testes está quase. 😄

2020-08-21 17:56 UTC, rvalyi commented
Ola @marcelsavegnago . Parabens pela contribuicao.

Bem ate onde eu vejo o modulo repair original da OCA eh porco na geracao do invoice no sentido que ele nao tem nenhum daqueles hooks _prepare* nem no invoice nem nos invoice lines. Foram anos enchendo o saco da Odoo SA a cada release para eles fizer os que temos em sale, purchase e estoque... Nao tem com o modulo repair hoje que tem esse action_invoice_create https://github.com/odoo/odoo/blob/12.0/addons/repair/models/repair.py#L285 monolitico apenas.
Se vc tiver muita coragem, poderia sugerir a inclusao desses hooks na branch master/v14 do Odoo.

Alias no repair_discount do qual vc depende, vc pode ver que eles tiveram que sobre carregar esse action_invoice_create e depois que tudo ta criado eles fazem uns write de novo, algo bem lento que era terrivel nos modulos sale ou purchase mas deve ser aceitavel com o repair.

Ai eu vi que vc implementou uns _prepare_invoice e _prepare_invoice_line hooks e que vc redefiniu o action_invoice_create https://github.com/Escodoo/l10n-brazil/blob/12.0-add-l10n_br_repair/l10n_br_repair/models/repair_order.py#L398 para chama-los. Pode funcionar, mas ai como vc nao chama o super() qualquer outro modulo que herdar action_invoice_create tb seria incompativel. Eu nao acho muito critico nesse modulo especial, mas eh bom saber desse problema...

Vc ainda tem documentos fiscais vazios? 
Veja como eu defini os documentos fiscais e linhas de documentos ficais no modulo l10n_br_account:
https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_account/models/account_invoice.py#L59

Por padrao essas chavez apontem em documentos e linhas "dummy" pro ORM do Odoo nao encher o saco com os registros que nao sao de empresas brasileiras ou que sao de demo. Ai quando vc quer ter esses registros (ou seja nao vazios), eles tem que ser criados (pensa no sistema product.template / product.product) e entao vc tem que passar False para esses ids nos creates.

Isso acontece nos modulos l10n_br_sale, l10n_br_purchase porque nos prepares, ao chamar `result.update(self._prepare_br_fiscal_dict())` esses metodos vao botar aqueles False para vc:
https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_fiscal/models/document_fiscal_mixin_methods.py#L47
https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py#L147

Vc tem certeza que entendeu esse mecanismo? Eh por ai que tem que checar para os documentos fiscais nao vir zerados...

2020-10-15 03:21 UTC, marcelsavegnago commented
> Bem ate onde eu vejo o modulo repair original da OCA eh porco na geracao do invoice no sentido que ele nao tem nenhum daqueles hooks _prepare* nem no invoice nem nos invoice lines. Foram anos enchendo o saco da Odoo SA a cada release para eles fizer os que temos em sale, purchase e estoque... Nao tem com o modulo repair hoje que tem esse action_invoice_create https://github.com/odoo/odoo/blob/12.0/addons/repair/models/repair.py#L285 monolitico apenas.
> Se vc tiver muita coragem, poderia sugerir a inclusao desses hooks na branch master/v14 do Odoo.

@rvalyi Farei isso em breve. 😃

2020-10-15 03:22 UTC, marcelsavegnago commented
> Alias no repair_discount do qual vc depende, vc pode ver que eles tiveram que sobre carregar esse action_invoice_create e depois que tudo ta criado eles fazem uns write de novo, algo bem lento que era terrivel nos modulos sale ou purchase mas deve ser aceitavel com o repair.

@rvalyi dei uma revisada no módulo e optei em remover o módulo de desconto e estou adicionando o campo de desconto diretamente pelo módulo de localização.. O que acha ?

2020-10-15 03:23 UTC, marcelsavegnago commented
> Ai eu vi que vc implementou uns _prepare_invoice e _prepare_invoice_line hooks e que vc redefiniu o action_invoice_create https://github.com/Escodoo/l10n-brazil/blob/12.0-add-l10n_br_repair/l10n_br_repair/models/repair_order.py#L398 para chama-los. Pode funcionar, mas ai como vc nao chama o super() qualquer outro modulo que herdar action_invoice_create tb seria incompativel. Eu nao acho muito critico nesse modulo especial, mas eh bom saber desse problema...

@rvalyi da forma como o módulo foi construído não vejo outra saída por enquanto.

2020-10-15 03:25 UTC, marcelsavegnago commented
> Vc ainda tem documentos fiscais vazios?
> Veja como eu defini os documentos fiscais e linhas de documentos ficais no modulo l10n_br_account:
> https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_account/models/account_invoice.py#L59

@rvalyi 
neste caso eu resolvi com esta linha
https://github.com/Escodoo/l10n-brazil/blob/5a08cb8c24b4e89e1f80ab8cfe3e3f1636ab6493/l10n_br_repair/models/repair_order.py#L628

2020-10-15 03:28 UTC, marcelsavegnago commented
> Vc tem certeza que entendeu esse mecanismo? Eh por ai que tem que checar para os documentos fiscais nao vir zerados...

@rvalyi este módulo ta ajudando a começar entender.. mas ainda com falhas :D

2020-10-26 23:31 UTC, mileo commented
@gabrielcardoso21 pode ajudar a revisar quando sobrar um tempo?

2020-10-28 03:23 UTC, mileo commented
@marcelsavegnago testando rapidamente, senti falta de uma operação fiscal para atender alguns requisitos fiscais que podem até não ser o escopo deste PR e deixarmos pra depois/abrir um issue sobre isso etc.... Mas vale deixar no seu radar.

Você já ouviu falar de Remessa / Retorno para concerto ? Por exemplo: https://ajuda.bling.com.br/hc/pt-br/articles/360046195753-Nota-Fiscal-de-Remessa-e-Retorno-para-conserto#:~:text=Esse%20tipo%20de%20nota%20fiscal,o%20produto%20volta%20do%20conserto.

Geralmente é feita uma nota fiscal de remessa para entrada do produto (As vezes o cliente não é contribuinte do ICMS, então a empresa que esta fazendo o concerto pode emitir essa nota) e para saída uma nota de retorno de remessa. Isso é feito para itens de maior valor e que vão transitar por longas distâncias.

Entretanto nem todas as empresas fazem essas duas operações, pode ser feito o concerto sem toda esta burocracia e ai englobaria somente os produtos e serviços prestados ( Que é o caso que você já esta contemplando).

2020-10-28 04:15 UTC, marcelsavegnago commented
> Geralmente é feita uma nota fiscal de remessa para entrada do produto (As vezes o cliente não é contribuinte do ICMS, então a empresa que esta fazendo o concerto pode emitir essa nota) e para saída uma nota de retorno de remessa. Isso é feito geralmente para itens de maior valor e que vão transitar por longas distâncias.

Sim.. já pensei nisso e acho muito válido mas de fato não é o escopo desta PR.

Mas, sobre a entrada e devolução dos equipamentos que serão reparados eu estou pensando em utilizar o RMA já que ele gerencia este picking de entrada e retorno. Sendo assim, em conjunto com o l10n_br_stock_account já daria para configurar certinho estas operações. O RMA precisa ainda de uma integração com o módulo de reparos para ficar mais completo mas não seria nada demais (tem um repositório que tem alguns módulos a mais do RMA e acho que dá para usar como referência).

O módulo Repair é meio toscão e o certo seria melhorar ele na Odoo S.A. ou agregar algumas coisas pela OCA:

- Geração do picking dos componentes que serão utilizados. Hoje, o Odoo baixa de uma vez os componentes quando é finalizado o reparo. Além disso, o fluxo não é muito legal quando as peças que serão utilizadas no reparo tem controle de série ou lote pois estes são exigidos logo na criação do reparo.

- Ajustar os métodos de faturamento e preparação das linhas e do cabeçalho. (sugerido pelo @rvalyi )

2020-10-28 16:18 UTC, marcelsavegnago commented
@renatonlima @rvalyi @mbcosta deu uma boa trabalhada nesta PR este final de semana e consegui implementar alguns testes aproveitando boa parte do que foi implementado no l10n_br_sale. Se puderem dar uma criticada eu agradeço.

2020-10-31 18:56 UTC, mileo approved these changes
Parabéns pelo trabalho @marcelsavegnago. 

Vai ajudar a abrir novos projetos nessa área e pensarmos em novas melhorias para este módulo.

Teste no Runbot e revisei o código, LGTM.

2020-10-31 19:00 UTC, mileo commented
@marcelsavegnago pode colocar o módulo como "Alpha" essa é uma área ainda pouco explorada pela localização. E ainda não temos um roadmap definido. []s

2020-10-31 19:05 UTC, marcelsavegnago commented
> Parabéns pelo trabalho @marcelsavegnago.

Vlwww @mileo. Foi bom fazer esta localização. Consegui me aprofundar mais na mecânica dos demais módulos localizados.

> Vai ajudar a abrir novos projetos nessa área e pensarmos em novas melhorias para este módulo.

Com certeza. 
 
> Teste no Runbot e revisei o código, LGTM.

Vlww

2020-10-31 23:05 UTC, mileo approved these changes

2020-11-02 03:46 UTC, rvalyi commented on l10n_br_repair/__manifest__.py
> +        'l10n_br_account',
nao seria mais explicito depender de l10n_br_stock_account ao em vez de ter ele carregado de forma implicita pela auto_install?

2020-11-02 04:06 UTC, rvalyi requested changes
pedi uma mudança pequena no manifest. Tb levantei um possivel refator para fazer junto com o modulo l10n_br_fiscal, mas isso vale confirmaçao.

2020-11-02 04:06 UTC, rvalyi commented on l10n_br_repair/models/repair_order.py
> +    amount_insurance = fields.Float(
@marcelsavegnago @renatonlima @mileo 
Esses campos: amount, discount, freight, insurance, costs... eles se repitem aqui:

- no sale.order https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_sale/models/sale_order.py#L93 
- no fiscal.document: https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_fiscal/models/document.py#L589
- no purchase order e nao vi, sera se nao deveria?
- no account.invoice, vc tem eles no fiscal.document, mas como nao sao campos do 10n_br_fiscal.document.mixin nao fica facil manipular eles atraves do invoice.

Enfim, nao seria melhor jogar esses campos no l10n_br_fiscal.document.mixin? Existe uma logica consistente para saber quais desses campos exactamente transferir do fiscal.document pro l10n_br_fiscal.document.mixin?

2020-11-02 19:50 UTC, marcelsavegnago commented on l10n_br_repair/models/repair_order.py
> +    amount_insurance = fields.Float(
> Enfim, nao seria melhor jogar esses campos no l10n_br_fiscal.document.mixin? Existe uma logica consistente para saber quais desses campos exactamente transferir do fiscal.document pro l10n_br_fiscal.document.mixin?

@rvalyi Acho válido. O método _amount_all seria migrado para l10n_br_fiscal.document_fiscal_mixin_methods ?

2020-11-02 19:52 UTC, marcelsavegnago commented on l10n_br_repair/models/repair_order.py
> +    amount_insurance = fields.Float(
@rvalyi Eu pretendo colocar este módulo em uso ainda este mês. Você acredito que este refactor impactaria em algo ?

2020-11-02 23:12 UTC, rvalyi commented on l10n_br_repair/models/repair_order.py
> +    amount_insurance = fields.Float(
@marcelsavegnago vou dar um gas nisso com o @renatonlima para matar esse assunto essa semana ainda. A meu ver é o tipo de limpeza que tem que ser feito ainda antes de migrar para a 14.0 então temos uma certa pressa tb.

2020-11-03 01:26 UTC, marcelsavegnago commented on l10n_br_repair/models/repair_order.py
> +    amount_insurance = fields.Float(
@rvalyi Combinado. Eu acho válido já aproveitar o momento para deixar mais limpo as coisas. Vlwww

2020-11-09 17:23 UTC, rvalyi commented on l10n_br_repair/models/repair_order.py
> +    amount_insurance = fields.Float(
So para avisar, comecei a ver isso esse fds. Acho importante termos o merge do l10n_br_purchase antes para checar melhor os efeitos colaterais disso, mas vamos melhor isso ja ja então.

2020-11-24 00:35 UTC, marcelsavegnago commented on l10n_br_repair/models/repair_order.py
> +    amount_insurance = fields.Float(
Grande @rvalyi tudo bem?  conseguiu evoluir algo ?

2020-12-02 13:52 UTC, marcelsavegnago commented on l10n_br_repair/models/repair_order.py
> +    amount_insurance = fields.Float(
@rvalyi e @renatonlima alguma novidade sobre este tema ?

2020-12-14 14:15 UTC, mileo commented
@marcelsavegnago já podemos revisar?

2020-12-14 14:58 UTC, marcelsavegnago commented
> @marcelsavegnago já podemos revisar?

A principio sim.. deu um erro no travis e estou vendo oq pode ser.

2020-12-14 15:04 UTC, marcelsavegnago commented
@mileo sabe oq pode ser o erro do travis ?
https://travis-ci.com/github/OCA/l10n-brazil/jobs/459519251#L450

2020-12-14 15:39 UTC, mileo commented
> @mileo sabe oq pode ser o erro do travis ?
> https://travis-ci.com/github/OCA/l10n-brazil/jobs/459519251#L450

Alguma coisa sem explicação, mandei o teste rodar novamente.

2020-12-14 16:11 UTC, mileo requested changes

2020-12-14 16:11 UTC, mileo commented on .travis.yml
> +  - "3.5"
@marcelsavegnago  favor dar um rebase ou remover este trecho.

2020-12-14 16:14 UTC, marcelsavegnago commented on .travis.yml
> +  - "3.5"
Blz.. fiz o rebase novamente e dei um push..

2020-12-21 11:40 UTC, marcelsavegnago commented on l10n_br_repair/models/repair_order.py
> +    amount_insurance = fields.Float(
ping @rvalyi e @renatonlima

2020-12-21 11:41 UTC, marcelsavegnago commented
> @marcelsavegnago já podemos revisar?

@mileo agora está ok para revisão. Vi que a cobertura de teste diminuiu um pouco mas acho que não seja problema por enquanto.

2020-12-26 23:10 UTC, marcelsavegnago commented on l10n_br_repair/models/repair_order.py
> +    amount_insurance = fields.Float(
> So para avisar, comecei a ver isso esse fds. Acho importante termos o merge do l10n_br_purchase antes para checar melhor os efeitos colaterais disso, mas vamos melhor isso ja ja então.

@rvalyi e @renatonlima alguma novidade sobre o l10n_br_purchase e o possível refactor do l10n_br_fiscal? Eu acho muito válido aproveitar o momento para a limpeza comentada pelo @rvalyi mas gostaria de um retorno sobre o andamento para poder me planejar em relação ao módulo desta PR. Caso o refactor/limpeza fique para outro momento, podem revisar esta PR por favor ?

Vlww.

2021-01-04 12:35 UTC, rvalyi commented
bom dia @marcelsavegnago esse seu modulo repair vamos testar em prod essa semana. Dai a principio acertando os detalhes, a gente consegue finalmente fazer merge.

2021-01-04 12:54 UTC, marcelsavegnago commented
> bom dia @marcelsavegnago esse seu modulo repair vamos testar em prod essa semana. Dai a principio acertando os detalhes, a gente consegue finalmente fazer merge.

Blzz.. obrigado pela força

2021-01-09 20:15 UTC, jpcarassato approved these changes
Ok

2021-01-14 17:14 UTC, marcelsavegnago commented
@mileo @gabrielcardoso21 @luismalta podem revisar esta PR por favor ?

2021-01-15 20:02 UTC, rvalyi commented
acabou que ainda nao testamos na produçao, porem estamos para testar nos dias muito proximo. Ate que tudo bem, por mim a questao é fazer merge do purchase antes (que é modulo que temos desde as v7/v8) porque teria uns pequenos refatores que eu comentei, mas eu queria certeza que mantemos uma consistencia entre os documentos fiscais de entrada e saida mexendo nisso.  Mas enfim isso é so minha opiniao. se os outros querem fazer merge antes tudo bem tb. De qualquer forma nao deveria demorar mais ate porque dos l10n_br_purchase ja foram bem testados e incluimos umas contribuiçoes do @gabrielcardoso21 na branch.

2021-01-15 22:59 UTC, marcelsavegnago commented
> acabou que ainda nao testamos na produçao, porem estamos para testar nos dias muito proximo. Ate que tudo bem, por mim a questao é fazer merge do purchase antes (que é modulo que temos desde as v7/v8) porque teria uns pequenos refatores que eu comentei, mas eu queria certeza que mantemos uma consistencia entre os documentos fiscais de entrada e saida mexendo nisso. Mas enfim isso é so minha opiniao. se os outros querem fazer merge antes tudo bem tb. De qualquer forma nao deveria demorar mais ate porque dos l10n_br_purchase ja foram bem testados e incluimos umas contribuiçoes do @gabrielcardoso21 na branch.

Tranquilo, o purchase já ta praticamente saindo do forno.

2021-01-25 16:01 UTC, marcelsavegnago commented
@renatonlima @rvalyi chegaram a testar algo deste módulo?

2021-01-25 16:22 UTC, rvalyi commented
> @renatonlima @rvalyi chegaram a testar algo deste módulo?

ainda nao :-( Ta na fila, mas a fila ta atrasada. Como eu disse a unica coisa eh que teria que fazer o merge do purchase que eh apenas migraçao de algo existente e depois um lever refator sobre qual eu falei e verificar que tudo funciona junto. So que como vc viu ainda um problema com o purchase... Enfim isso eh a minha opiniao, se os outros querem fazer merge antes, tudo bem para mim.

2021-01-25 16:46 UTC, marcelsavegnago commented
> > @renatonlima @rvalyi chegaram a testar algo deste módulo?
> 
> ainda nao :-( Ta na fila, mas a fila ta atrasada. Como eu disse a unica coisa eh que teria que fazer o merge do purchase que eh apenas migraçao de algo existente e depois um lever refator sobre qual eu falei e verificar que tudo funciona junto. So que como vc viu ainda um problema com o purchase... Enfim isso eh a minha opiniao, se os outros querem fazer merge antes, tudo bem para mim.

Tranquilo.. vou testar com as atualizações recentes da localização e já verificar as ultimas PRs mescladas para ver se cabe alguma alteração até então.

2021-02-01 16:03 UTC, renatonlima requested changes

2021-02-01 16:03 UTC, renatonlima commented on l10n_br_repair/models/repair_line.py
> +    _inherit = [_name, 'l10n_br_fiscal.document.line.mixin']
@marcelsavegnago Eu vi que os objetos repair.line e repair.fee você esta repetindo uma boa parte do código para adaptar o mixin, você poderia criar um AbstractModel RepairLineMixin e colocar esse codigo e herda-lo nos repair.line e repair.fee desta forma você reduz consideravelmente a duplicação do código.

2021-02-01 16:03 UTC, renatonlima commented on l10n_br_repair/models/repair_order.py
> +    amount_insurance = fields.Float(
@marcelsavegnago e @rvalyi Esses campos de amount acaba se repetindo nos objetos, porque na maioria dos casos tem que alterar o atributo compute e os outros campos como amount_untaxed amount_total podem ser diferentes entre esses objetos (sale, picking, invoice, purchase)

2021-02-02 03:59 UTC, marcelsavegnago commented on l10n_br_repair/models/repair_line.py
> +    _inherit = [_name, 'l10n_br_fiscal.document.line.mixin']
@renatonlima Done

2021-02-02 04:08 UTC, marcelsavegnago commented
@mileo e @rvalyi pronto para revisão

2021-02-02 11:18 UTC, rvalyi approved these changes
Ok para mim. Parabens pelo trabalho @marcelsavegnago !

2021-02-02 12:27 UTC, marcelsavegnago commented
@OCA/local-brazil-maintainers Bora fazer o merge ? :)

2021-02-02 14:21 UTC, renatonlima requested changes, later dismissed

2021-02-02 14:21 UTC, renatonlima commented on l10n_br_repair/README.rst
> +* l10n_br_stock
Deveria ser apenas a dependencia do l10n_br_stock_account e do repair, como no depends do manifest

2021-02-02 14:21 UTC, renatonlima commented on l10n_br_repair/__manifest__.py
> +    'auto_install': True,
Isso vai forçar sempre que for instalado o repair e já tiver o l10n_br_stock_account a ser instalado o l10n_br_repair, será se deveria ser assim? Penso que talvez a empresa tenha a localização brasileira instalada ou queira instalar o repair só para controlar reparos internamente e não precisar faturar ou gerar nota, na minha opinição isso deveria ser opcional. Você também poderia colocar uma opção de configuração semelhante ao https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_base/models/res_config_settings.py#L28 para ficar mais amigavel a escolha desta opção pelo usuário.

2021-02-02 14:21 UTC, renatonlima commented on l10n_br_repair/models/repair_line_mixin.py
> +    _inherit = ['l10n_br_repair.repair.line.mixin.methods',
Olá Marcel, por que você dividiu o mixin em campos e metódos? Isso não é necessário, no fiscal.document.line nós fizemos isso porque na herança com o account.invoice existe um inherits e no caso dos inherits (com s no final) só são herdados os campos mas não os métodos, mas se você olhar o [sale](https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_sale/models/sale_order_line.py#L11), [purchase](https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_purchase/models/purchase_order_line.py#L12) e [stock](https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_stock_account/models/stock_move.py#L13), injetamos diretamente o l10n_br_fiscal.document.fisca.line.mixin

2021-02-02 14:21 UTC, renatonlima commented on l10n_br_repair/models/repair_line_mixin.py
> +    _name = 'l10n_br_repair.repair.line.mixin'
Acho que para ficar mais explicito poderia ser l10n_br_repair.fiscal.line.mixin

2021-02-02 14:21 UTC, renatonlima commented on l10n_br_repair/models/repair_line.py
> +        related='repair_id.company_id.tax_framework',
Esses campos que são related do repair_id poderia ficar no mixin

2021-02-02 14:21 UTC, renatonlima commented on l10n_br_repair/models/res_company.py
> +
Pode remover essa linha

2021-02-02 14:21 UTC, renatonlima commented on l10n_br_repair/views/repair_line.xml
> +                    <field name="cfop_id" attrs="{'invisible': [('fiscal_genre_code', '=', '00'), ('cfop_id', '!=', False)]}"/>
Esse domain poderia ser assim https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_sale/views/sale_view.xml#L78

2021-02-02 14:21 UTC, renatonlima commented on l10n_br_repair/views/repair_line.xml
> +                    <field name="service_type_id" attrs="{'invisible': [('fiscal_genre_code', '!=', '00'), ('cfop_id', '=', False)]}"/>
Esse domain poderia ser assim https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_sale/views/sale_view.xml#L81

2021-02-02 14:21 UTC, renatonlima commented on l10n_br_repair/views/repair_line.xml
> +                    <field name="tax_framework" invisible="1"/>
Adiciona o campo tax_icms_or_issqn como invisible=1 para ser usado nos domains do cfop_id e service_type_id

2021-02-02 14:21 UTC, renatonlima commented on l10n_br_repair/views/repair_fee.xml
> +                    <field name="cfop_id" attrs="{'invisible': [('fiscal_genre_code', '=', '00'), ('cfop_id', '!=', False)]}"/>
O mesmo domain acima no form do repair.line

2021-02-02 14:21 UTC, renatonlima commented on l10n_br_repair/views/repair_fee.xml
> +                    <field name="service_type_id" attrs="{'invisible': [('fiscal_genre_code', '!=', '00'), ('cfop_id', '=', False)]}"/>
O mesmo domain acima no form do repair.line

2021-02-02 14:21 UTC, renatonlima commented on l10n_br_repair/views/repair_fee.xml
> +                    <field name="fiscal_operation_type" invisible="1" readonly="1"/>
Adiciona o campo tax_icms_or_issqn como invisible=1 para ser usado nos domains do cfop_id e service_type_id

2021-02-02 14:24 UTC, renatonlima commented
> @OCA/local-brazil-maintainers Bora fazer o merge ? :)

![ezgif com-gif-maker](https://user-images.githubusercontent.com/211005/106613618-286a3880-6549-11eb-948c-50ac3408fae1.gif)

2021-02-02 14:24 UTC, renatonlima commented
@marcelsavegnago,

Eu fiz o review do PR, vi algumas coisas, mas são simples... ficou muito bom parabéns pelo trabalho!

2021-02-02 14:25 UTC, marcelsavegnago commented on l10n_br_repair/models/repair_line_mixin.py
> +    _name = 'l10n_br_repair.repair.line.mixin'
Perfeito

2021-02-02 14:25 UTC, marcelsavegnago commented on l10n_br_repair/models/repair_line_mixin.py
> +    _inherit = ['l10n_br_repair.repair.line.mixin.methods',
Ahh blzz.. vou juntar então

2021-02-02 14:26 UTC, marcelsavegnago commented on l10n_br_repair/models/repair_line.py
> +        related='repair_id.company_id.tax_framework',
Então.. tentei fazer assim mas reclamou da inexistencia do campo repair_id

2021-02-02 14:27 UTC, marcelsavegnago commented on l10n_br_repair/views/repair_line.xml
> +                    <field name="tax_framework" invisible="1"/>
blz

2021-02-02 15:13 UTC, marcelsavegnago commented on l10n_br_repair/__manifest__.py
> +    'auto_install': True,
Feito.. no momento só removi o auto_install. Em outra PR implemento uma solução amigável para o usuário.

2021-02-02 15:15 UTC, mileo commented
> > @OCA/local-brazil-maintainers Bora fazer o merge ? :)
> 
> ![ezgif com-gif-maker](https://user-images.githubusercontent.com/211005/106613618-286a3880-6549-11eb-948c-50ac3408fae1.gif)

kkkk

2021-02-02 15:18 UTC, mileo approved these changes

2021-02-02 16:04 UTC, marcelsavegnago commented
@renatonlima ajustes efetuados

2021-02-02 19:46 UTC, renatonlima commented
@marcelsavegnago 

Eu vi que você cria o [res.config.settings](https://github.com/OCA/l10n-brazil/blob/a2c262577448431faa2cb6a9bce82eae431be63b/l10n_br_repair/models/res_config_settings.py) mas não bem a view dele, você esqueceu de fazer um git add?

2021-02-02 22:22 UTC, marcelsavegnago commented
> @marcelsavegnago
> 
> Eu vi que você cria o [res.config.settings](https://github.com/OCA/l10n-brazil/blob/a2c262577448431faa2cb6a9bce82eae431be63b/l10n_br_repair/models/res_config_settings.py) mas não bem a view dele, você esqueceu de fazer um git add?

Então.... não lembro agora hehehe. Mas estou olhando o módulo repair e não tem um menu Config. O que achar ? removo a entrada ou adiciono um menu config por este módulo por enquanto e vou tentando inserir via PR no módulo repair da Odoo mesmo. 

Obs. Trabalhando com o módulo repair penso que vale fazer igual fizeram com o maintenance. Criar um módulo repair_base incluindo algumas coisas básicas até que a Odoo decida incluir diretamente no módulo.

2021-02-02 22:59 UTC, renatonlima commented
@marcelsavegnago Eu vi que vc já coloca isso no res.company, então se não tem um menu de configuração, vc pode remover a classe res.config.settings https://github.com/OCA/l10n-brazil/pull/925/files#diff-6e38e7c33760e8188cc9f0a219021a0c6ee84f7ba4b75efd5ed3f29d098cb9dbR8

2021-02-02 23:10 UTC, renatonlima approved these changes

2021-02-02 23:12 UTC, renatonlima commented
/ocabot merge nobump

2021-02-02 23:16 UTC, marcelsavegnago commented
Conforme combinado com o @renatonlima a entrada em res.config.settings será mantida. Pretendo criar um módulo para o repair similar a este https://github.com/OCA/maintenance/tree/11.0/base_maintenance_config e em seguida ajustar o módulo l10n_br_repair para utilizar esta view.

cc @mileo @rvalyi

2021-02-02 23:50 UTC, merged