Feature/dfe mdfe
OCA/l10n-brazil pull request #928
Opened 2020-07-24 17:48 UTC by gabrielcardoso21

Modelos e campos relacionados à DF-e e MDF-e sem a transmissão.

2020-09-25 17:52 UTC, mileo commented on l10n_br_fiscal/views/mdfe/mdfe_views.xml
> +}
WTF

2020-09-25 17:52 UTC, mileo commented on l10n_br_fiscal/models/attachment.py
> +#
REMOVE Blank line

2020-09-25 17:55 UTC, marcelsavegnago commented on l10n_br_fiscal/views/mdfe/mdfe_views.xml
> +}
Eu tbm tinha achado estranho hehehehe

2020-09-25 19:58 UTC, mileo commented
@gabrielcardoso21 poderia verificar os erros do travis e do runbot por gentileza?

2020-09-28 10:53 UTC, mileo commented
@gabrielcardoso21 pode ver o que houve com o runbot?

2020-09-28 12:46 UTC, mileo approved these changes

2020-09-28 13:09 UTC, mileo commented
@gabrielcardoso21 please fix:

```
2020-09-28 12:58:13,730 175 WARNING openerp_test odoo.fields: Field l10n_br_fiscal.dfe.display_name depends on itself; please fix its decorator @api.depends().
```

2020-09-28 13:09 UTC, mileo requested changes
Runbot Error

2020-09-28 13:19 UTC, gabrielcardoso21 commented
> @gabrielcardoso21 please fix:
> 
> ```
> 2020-09-28 12:58:13,730 175 WARNING openerp_test odoo.fields: Field l10n_br_fiscal.dfe.display_name depends on itself; please fix its decorator @api.depends().
> ```

De acordo com essa issue https://github.com/odoo/odoo/issues/41081, corrigir o problema não some com o erro. Tive que trocar a abordagem, não mais usando o campo display_name e sim a função name_get.

2020-09-28 15:21 UTC, mileo approved these changes

2020-09-28 17:27 UTC, marcelsavegnago reviewed
![image](https://user-images.githubusercontent.com/3595132/94465757-c793b380-0196-11eb-8dd0-176f441026d6.png)

2020-09-28 17:44 UTC, marcelsavegnago approved these changes
Entendo que é uma área intermediária para buscar documentos eletrônicos emitidos contra a empresa me parece ok.

2020-09-28 17:50 UTC, mileo commented
/ocabot merge minor

2020-09-28 18:20 UTC, merged