[12.0] [ADD] l10n br nfse issnet
OCA/l10n-brazil pull request #930
Opened 2020-07-30 21:37 UTC by marcelsavegnago

2020-09-16 09:05 UTC, mileo commented on l10n_br_nfse_issnet/README.rst
> +* repair_discount module
Acho que rolou um copiar e colar.

2020-09-16 09:11 UTC, mileo requested changes

2020-09-16 09:11 UTC, mileo commented on l10n_br_nfse_issnet/models/l10n_br_fiscal_document.py
> +                    )
Sinceramente eu não gosto muito deste trecho de código aqui, se possível isso deve ser delegado para a biblioteca.

E inclusive vi que o #942 esta com mesmo problema e podemos ver uma repetição de código com o mesmo padrão: 

https://github.com/OCA/l10n-brazil/blob/db4d55fe442a415b546e911ef0c9e6a84f31c3ad/l10n_br_nfse_ginfes/models/document.py#L165-L182

@luismalta

2020-09-16 09:15 UTC, mileo commented
Trabalho top @marcelsavegnago! Quem vê esse trechinho de código as vezes não enxerga o trabalho que deu.

Fico feliz que mais gente esta entendendo como funciona o GenerateDS, a geração de libs e a transmissão. É muito importante transmitir esse conhecimento para que mais pessoas ajudem a manter tudo isso.

Obrigado por me colocar como contribuidor, nem todos tem esse bom senso.

2020-09-16 09:34 UTC, marcelsavegnago commented on l10n_br_nfse_issnet/README.rst
> +* repair_discount module
Opss :D

2020-12-14 02:07 UTC, marcelsavegnago commented
Pessoal, 

ISSNet está praticamente pronto. Preciso de apoio na revisão e ainda esta semana vou começar a homologar com um cliente.

Para fins de teste e validação eu inclui as PRs abaixo no requirements.txt.

https://github.com/erpbrasil/erpbrasil.edoc/pull/29

**master-gen** https://github.com/erpbrasil/nfselib.issnet/pull/1
**master** https://github.com/erpbrasil/nfselib.issnet/pull/2
@rvalyi Não tenho certeza se segui os procedimentos conforme você orientou e se puder verificar eu agradeço. 

@mileo assim as PRs forem aceitas eu vou precisar da sua ajuda para poder deixar correto para o pypi.. se puder ajudar eu agradeço muito.

cc @mileo @gabrielcardoso21 @luismalta @rvalyi @renatonlima

2020-12-14 15:35 UTC, mileo commented
> Pessoal,
> 
> ISSNet está praticamente pronto. Preciso de apoio na revisão
> 
> Esta semana vou começar a homologar em um cliente de Ribeirão Preto.
> 
> Obs. Para permitir testes e validações eu inclui temporariamente as libs necessárias já no requirements.txt
> 
> [erpbrasil/erpbrasil.edoc#29](https://github.com/erpbrasil/erpbrasil.edoc/pull/29)
> 
> **master-gen** [erpbrasil/nfselib.issnet#1](https://github.com/erpbrasil/nfselib.issnet/pull/1)
> **master** [erpbrasil/nfselib.issnet#2](https://github.com/erpbrasil/nfselib.issnet/pull/2)
> @rvalyi Não tenho certeza se segui os procedimentos conforme você orientou e se puder verificar e criticar eu agradeço.
> 
> @mileo assim que as PRs forem aceitas, vou precisar da sua ajuda para poder deixar pronto para colocar no pypi.. se puder ajudar eu agradeço muito.
> 
> cc @mileo @gabrielcardoso21 @luismalta @rvalyi @renatonlima

Joia.

Vamos revisar essa semana.

Pedi pro @luismalta já ir dando uma olhada nos https://github.com/erpbrasil/nfselib.issnet/pulls se ele não achar nada errado fazemos o merge e publicamos a lib.

2020-12-21 12:51 UTC, mileo commented on requirements.txt
> +
Isso ainda não vai adiantar... Pois vai ser necessário fechar uma nova versão do edoc.

2020-12-21 13:04 UTC, mileo commented on requirements.txt
> +
Fechada a nova versão: https://pypi.org/project/erpbrasil.edoc/1.1.0/

2020-12-21 13:05 UTC, mileo commented on requirements.txt
> +
@marcelsavegnago

2020-12-21 17:40 UTC, marcelsavegnago commented on requirements.txt
> +
Done

2020-12-26 23:12 UTC, marcelsavegnago commented
@gabrielcardoso21 @luismalta @sadamo podem revisar esta PR fazendo favor ?

2020-12-28 14:14 UTC, eduaparicio approved these changes

2021-01-04 12:23 UTC, marcelsavegnago commented
Bom dia pessoal,

Gostaria da ajuda de vocês na revisão e aprovação desta PR. Como os principais envolvidos estão cientes, este módulo tem como base o módulo l10n_br_nfse_ginfes que já foi aceito pela comunidade.

cc @mileo @rvalyi @renatonlima @gabrielcardoso21 @luismalta

2021-01-05 12:56 UTC, luismalta approved these changes

2021-01-06 11:24 UTC, marcelsavegnago commented
ping @mileo

2021-01-06 12:15 UTC, gabrielcardoso21 approved these changes

2021-01-06 12:51 UTC, marcelsavegnago commented
@renatonlima @rvalyi @mileo poderiam mesclar a PR ?

2021-01-06 13:21 UTC, rvalyi commented
E que na vdd @marcelsavegnago o merge pelo ocabot iria falhar por conta da regressao nos testes do modulo payment_cielo da KMEE igual deu pau nos outros PRs recentes. So nao deu nesse porque vc rodou a CI antes do payment_cielo quebrar. o @luismalta comentou que a KMEE ta sabendo do problema agora.

2021-01-06 13:28 UTC, marcelsavegnago commented
> E que na vdd @marcelsavegnago o merge pelo ocabot iria falhar por conta da regressao nos testes do modulo payment_cielo da KMEE igual deu pau nos outros PRs recentes. So nao deu nesse porque vc rodou a CI antes do payment_cielo quebrar. o @luismalta comentou que a KMEE ta sabendo do problema agora.

Ops.. verdade. O @DiegoParadeda está tratando agora.

2021-01-09 05:00 UTC, marcelsavegnago commented
@rvalyi pode mesclar esta PR ?

2021-01-11 15:01 UTC, marcelsavegnago commented
ping @mileo

2021-01-11 18:39 UTC, rvalyi approved these changes
parabens @marcelsavegnago !

2021-01-11 18:42 UTC, renatonlima approved these changes

2021-01-11 18:43 UTC, renatonlima commented
kudos @marcelsavegnago

2021-01-11 18:53 UTC, rvalyi commented
/ocabot merge nobump

2021-01-11 19:31 UTC, merged

2021-01-11 19:33 UTC, marcelsavegnago commented
Pessoal.. muito obrigado pela ajuda e apoio de todos q de alguma forma contribuíram.

cc @mileo @renatonlima @rvalyi @gabrielcardoso21 @luismalta @mbcosta .. peço desculpas se esqueci de alguém.

2021-01-11 19:42 UTC, rvalyi commented
Hehe @marcelsavegnago primeiro modulo na localizaçao de muitos com certeza! Tem alguns na fila, sinto muito pela demora. Eh que estamos tb dando uma prioridade para que os modulos l10n_br_fiscal e ate l10n_br_nfe estejam logo OK para nao occorrer muita divgergencia com a v14 de forma descontrolada. Estamos num go-live ferrado mas logo o fogo passa e ai teremos mais disponibilidade para a P&D da localizaçao.

2021-01-11 19:47 UTC, marcelsavegnago commented
> Hehe @marcelsavegnago primeiro modulo na localizaçao de muitos com certeza! Tem alguns na fila, sinto muito pela demora. Eh que estamos tb dando uma prioridade para que os modulos l10n_br_fiscal e ate l10n_br_nfe estejam logo OK para nao occorrer muita divgergencia com a v14 de forma descontrolada. Estamos num go-live ferrado mas logo o fogo passa e ai teremos mais disponibilidade para a P&D da localizaçao.

Opaa.. vlwwww.. Acho que levou o tempo que precisava e ficou bem legal que já fomos melhorando alguns detalhes do l10n_br_nfse..

Em breve vem mais heheheh.. o provedor de utilizado por Sertãozinho jájá tendo que pegar para fazer.. (vou dar uma olhada quais cidades atende tbm)