[12.0] l10n_br_nfse_ginfes
OCA/l10n-brazil pull request #942
Opened 2020-08-27 15:07 UTC by luismalta

This PR add a module to Ginfes, a specific nfse provider. This module depends on l10n_br_nfse that is added on PR #941 .
All commits on this PR were extracted from #813 .

2020-08-27 17:04 UTC, mileo commented on l10n_br_nfse_ginfes/models/document.py
> +            if processo.webservice == 'CancelarNfseV3':
Ficou faltando nas constantes

2020-08-27 17:06 UTC, mileo commented on l10n_br_nfse_ginfes/models/document.py
> +                                "NFS-e enviada e corresponde com o provedor")
Estou achando esses retornos muito verbosos, será que não seria possível tratar isso no erpbrasil.edoc e só devolver o retorno tratado?

2020-08-27 17:27 UTC, gabrielcardoso21 approved these changes

2020-08-27 17:27 UTC, gabrielcardoso21 commented on l10n_br_nfse_ginfes/__manifest__.py
> +    'name': 'Edoc Nfse Ginfes',
Atualizar o nome do módulo para "NFS-e (Ginfes)" para seguir o padrão

2020-08-27 17:27 UTC, gabrielcardoso21 commented on l10n_br_nfse_ginfes/models/document.py
> +            if processo.webservice == 'ConsultarNfsePorRpsV3':
Adicionar nas constantes

2020-08-27 17:39 UTC, rvalyi commented
Pessoal, so um retorno: eu estou acompanhando o dev desses modulos desde o inicio e finalmente começa a ter cara boa para rolar merge. A unica coisa que eu nao gosto hoje eh o nfselib ajustado manualmente com varios esquemas o que perde um pouco a filosofio do meu trabalho inicial com generateDS e que eu tinha documentado aqui https://github.com/akretion/edoc-gen
Como temos o mesmo problema com as ultimas contribuicoes no nfelib isso faz parte das coisas que eu estou começando a retrabalhar esses dias agora que o fogo no l10n_br_fiscal passou. De repente eu consigo trazer uma solução para isso tudo logo para poder rolar merge.

Ao mesmo tempo, vejo vcs comecar muitas coisas, mas eh bom nao esquecer que libs assim mesmo que bem feitas hoje tem zero teste https://github.com/erpbrasil/erpbrasil.edoc A gente pode ate abrir um pouco exessao na qualidade da OCA para agilizar ja que no grosso o codigo dessa lib tem cara boa, mas no ideal seria bom vcs tentarem botar alguns testes minimos la tb... Bibliotecas como mock ou https://github.com/kevin1024/vcrpy sao ideias para testar esse tipo de libs.

2020-08-28 20:27 UTC, marcelsavegnago approved these changes

2020-09-15 15:28 UTC, marcelsavegnago commented on l10n_br_nfse_ginfes/tests/nfse/001_50_nfse.xml
> +                        <CodigoCnae>3101-2/00</CodigoCnae>
Acredito que o valor deve ser sem a mascara

2020-09-16 08:47 UTC, mileo approved these changes

2020-09-16 09:03 UTC, mileo commented
Este módulo ficou bacana e bem limpo no fim das contas. Entretanto comentando a questão das dependências que o @rvalyi citou temos um débito técnico a sanar. E pelo menos do nosso lado não vai ser possível tratar agora em setembro, ficando para o próximo trimestre.

Quem tiver conhecimento para instalar as dependências pode instalar esse módulo sem problemas. 

Vejo duas opções:

1 - Aguardar para fazer o merge dele, assim como outros módulos similares **(NF-E e e outros de NFS-E)** algo que só deve então acontecer em novembro; Eu sinceramente prefiro a opção 1, nada melhor como ter tranquilidade, entretanto temos a questão tempo e orçamento para chegar lá.

2 - Fazer o merge agora entretanto setar a status de desenvolvimento do módulo como Alpha e deixar claro esta questão no README; Por exemplo (https://github.com/OCA/wms/blob/12.0/wms/__manifest__.py#L24) 

A opção 2 resulta em mais pessoas interessadas em testar o módulo, as libs e ainda quem sabe contribuir no orçamento/contribuição para fechar a questão 1.

@rvalyi @marcelsavegnago @gabrielcardoso21 @luismalta

2020-09-16 09:11 UTC, mileo requested changes
Favor verificar o comentário https://github.com/OCA/l10n-brazil/pull/930#pullrequestreview-489428154

Referente ao trecho: https://github.com/OCA/l10n-brazil/blob/db4d55fe442a415b546e911ef0c9e6a84f31c3ad/l10n_br_nfse_ginfes/models/document.py#L165-L182

2020-09-16 12:42 UTC, gabrielcardoso21 commented
> Este módulo ficou bacana e bem limpo no fim das contas. Entretanto comentando a questão das dependências que o @rvalyi citou temos um débito técnico a sanar. E pelo menos do nosso lado não vai ser possível tratar agora em setembro, ficando para o próximo trimestre.
> 
> Quem tiver conhecimento para instalar as dependências pode instalar esse módulo sem problemas.
> 
> Vejo duas opções:
> 
> 1 - Aguardar para fazer o merge dele, assim como outros módulos similares **(NF-E e e outros de NFS-E)** algo que só deve então acontecer em novembro; Eu sinceramente prefiro a opção 1, nada melhor como ter tranquilidade, entretanto temos a questão tempo e orçamento para chegar lá.
> 
> 2 - Fazer o merge agora entretanto setar a status de desenvolvimento do módulo como Alpha e deixar claro esta questão no README; Por exemplo (https://github.com/OCA/wms/blob/12.0/wms/__manifest__.py#L24)
> 
> A opção 2 resulta em mais pessoas interessadas em testar o módulo, as libs e ainda quem sabe contribuir no orçamento/contribuição para fechar a questão 1.
> 
> @rvalyi @marcelsavegnago @gabrielcardoso21 @luismalta

Eu prefiro a opção 2. Sou do ponto de vista que se o código estiver na versão 12.0 oficial da localização vamos ter um motivo bem mais forte para resolver a questão das bibliotecas.

2020-09-17 19:31 UTC, marcelsavegnago commented
> @rvalyi @marcelsavegnago @gabrielcardoso21 @luismalta

@mileo Eu precisaria de mais referencial técnico de como ter isso ajustado de forma correta nas libs externas do Odoo mas aceito ajuda porque não tive a capacidade de encontrar algo que pudesse me servir de base para já ter feito tudo nos conformes ao trabalhar nas funcionalidades da Issnet. Porém, aceito ajuda kkk

Eu gostei muito do que está sendo feito em relação ao generateDS e entendo que este é o caminho que devemos manter em mente e seguir. O trabalho de arquitetura e desenho efetuado pelo @rvalyi me parece bem concreto e deve ser valorizado e colocado em prática como um todo.

Como as libs estão no erpbrasil e infelizmente os critérios de qualidade similares a OCA ainda não foram implantados e entendo os porquês. Entendo e concordo com as preocupações do @rvalyi quando aos critérios de qualidade, arquitetura, padronização e modularização (for outros.. Porém, se não estou enganado eu percebi uma certa "flexibilidade" dele quanto a estas bibliotecas externas desde que exista o compromisso de todos em adequar o mais breve possível.

Concordo com o @gabrielcardoso21 que o lado positivo de conseguir avançar mais brevemente com NFSe e NFe sejam fatores que podem motivar deixar as coisas como devem ser. Já tiraria alguma dores de cabeça da frente e infelizmente sem a emissão de NFSe e NFe rodando a tendencia é sempre o pessoal se afastar. 

Pessoalmente, a pressão por conta de ter NFSe e NFe rodando não está fácil.. e seria muito importante poder contar com isso o quanto antes. Além disso, já deixo claro o compromisso de manter a qualidade em foco.

Resumindo eu preciso votar na opção 2 :D kkkk 

Obs. Sei que sou o cara que menos contribuiu até agora e que menos poderia falar qq coisa.. mas espero que os comentários sejam úteis.

2020-09-17 20:53 UTC, rvalyi requested changes, later dismissed
Pessoal, tou revisando a dependencia do nfselib ( e nfelib e erpbrasil.edoc.gen) ja ja. Ja acertei varias coisas mas fiquei enrolado esses ultimos dias. Me dam ate dia 23 que prometo ter dado uma boa revisada nessas libs. Pelo menos ja ficou trivial fazer o merge desse PR para quem quiser usar ate la. Nao falta coisas para acertar no projeto ate la.

2020-09-21 03:03 UTC, rvalyi commented
Pessoal, mais uma consideração que talvez passou despercebida: os testes Travis estao falhando tb https://travis-ci.org/github/OCA/l10n-brazil/jobs/727683902#L2252

2020-09-21 12:26 UTC, luismalta commented
Quanto ao teste do Travis, esse PR esta dependendo das correções do PR #958.

2020-09-21 13:14 UTC, marcelsavegnago commented
> Quanto ao teste do Travis, esse PR esta dependendo das correções do PR #958.

@luismalta na PR 958 tem um questionamento do Renato em aberto.

2020-09-21 14:18 UTC, rvalyi commented
Ola pessoal, so informando que fiquei o fds inteiro trabalhando nas ferramentas generateDS que eu tinha bolado pro projeto. Ai por exemplo no mais baixo nivel tem o wrapper para chamar o generateDS, trabalhei nessa branch https://github.com/akretion/erpbrasil.edoc.gen/tree/generate_python-standard-generateDS-package mas tem mais commits e PR chegando. Tou conseguindo gerir o nfelib correctemente por examplo, inclusive com os varios schemas. Vem PRs por ai. Enquanto isso eu acho importante vcs acertarem o modelo de dado fiscal de acordo com os comentarios do @renatonlima  no PR #958. Outra coisa, meu talk sobre as ferramentas generateDS pro Odoo na OCA foi aceito e sera apresentado dia 16 de Outubro, mais detalhes em breve.

2020-09-28 12:37 UTC, mileo approved these changes

2020-09-28 12:41 UTC, mileo commented
Pessoal os problemas deste PR foram resolvidos. Tirando as questões relacionadas as bibliotecas ele esta pronto para ser integrado.

2020-10-14 20:03 UTC, luismalta commented
Está dependendo do PR #984

2020-11-12 11:39 UTC, mileo commented on l10n_br_nfse_ginfes/__manifest__.py
> +            'nfselib',
Não esquece de trocar aqui e no requirements, se possível coloque também a versão da lib.

2020-11-24 12:06 UTC, mileo commented
/ocabot merge minor

2020-11-24 12:34 UTC, merged