[12.0] Simplificação do módulo l10n_br_coa
OCA/l10n-brazil pull request #946
Opened 2020-09-02 01:33 UTC by renatonlima

Hoje no módulo l10n_br_coa é criado um novo objeto l10n_br_account_tax_template para armazenar os impostos comuns entre os planos de contas e reutiliza-los, Esse PR elimina o objeto l10n_br_account_tax_template e utiliza a funcionalidade de plano de contas pai para carregar os impostos de forma correta.

Foi adicionado no account.tax.group dados das contas contábeis para adicionar propriedades para definir as contas dos grupo dos impostos no momento em que for carregado o plano de contas.

Ao carregar o plano de contas l10n_br_coa_generic, é utilizado os ir.property para carregar as contas contábeis de acordo com o account.tax.group

![Screenshot from 2020-09-01 22-30-46](https://user-images.githubusercontent.com/211005/91921958-20a91e00-eca3-11ea-964a-6f29b2e75c96.png)

![Screenshot from 2020-09-01 22-31-04](https://user-images.githubusercontent.com/211005/91921964-23a40e80-eca3-11ea-9132-dacb975eadc8.png)

2020-09-02 01:38 UTC, renatonlima commented
Para finalizar esse PR falta adicionar as propriedades dos account.tax.group para o l10n_br_coa_simple

2020-09-02 14:14 UTC, rvalyi requested changes

2020-09-02 14:14 UTC, rvalyi commented on l10n_br_coa_simple/__manifest__.py
> +    "depends": ["l10n_br_coa", "l10n_br_base"],
O PR eh legal, mas aqui depender do l10n_br_base nao eh legal. Nao ha necessidade absoluta disso. E mais, conversamos que no contexto que Odoo SA gosta de ir fechando parceria em especial com pessoas despreparadas que nunca olharam a OCA e não dam um pio sobre a questão do open source, monte de gente vai tentando a sorte implementando de qualquer forma com qualquer pessoa seja com Odoo EE ou nao.

Nisso eh legal que a localização OCA consiga facilmente demostrar que eh algo serio e que ajuda, e abaixar a barreira de entrada eh importante. Permitir a alguem que vai de Odoo EE de usar um plano de conta da OCA eh um grande passo nessa direção a meu ver. Depois quando o cara iludido que tentou implementar larga o projeto, como acontece em 90% dos casos e que a gente recebe os emais 1 ou 2 anos depois, se a empresa pelo menos usou um dos planos de conta da OCA, a chance da gente conseguir salvar o projeto eh muito maior do que se tiver que jogar o plano com todos lançamentos fora ou migrar isso com um dinheiro que esse pessoal não tem ou não tem mais. Depois ainda tem a questao de mudar a licença dos módulos dos planos para LGPL como ja falamos, mas isso pode ser feito num outro PR.

2020-09-02 14:15 UTC, rvalyi commented on l10n_br_coa_generic/__manifest__.py
> +    "depends": ["l10n_br_coa", "l10n_br_base"],
Eu acharia melhor tirar a dependencia do l10n_br_base aqui, ver meu comentario sobre o l10n_br_coa_simple.

2020-09-02 14:40 UTC, renatonlima commented on l10n_br_coa_simple/__manifest__.py
> +    "depends": ["l10n_br_coa", "l10n_br_base"],
Eu havia adicionado essa dependência do l10n_br_base porque se os módulos l10n_br_coa_simple e l10n_br_coa_generic forem instalados com os dados de demo e o l10n_br_base não estiver instalado vai gerar um erro https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_coa_simple/hooks.py#L20 porque hora ao instalar esses módulos (l10n_br_coa_simple e l10n_br_coa_generic) com dados de demo é carregado o plano de contas para as empresas criadas no módulo l10n_br_base, também podemos remover essa depedencia e verificar no hook se existe o registro das empresas caso nao existe não tenta carregar o plano de contas.

2020-09-02 14:43 UTC, rvalyi commented on l10n_br_coa_simple/__manifest__.py
> +    "depends": ["l10n_br_coa", "l10n_br_base"],
Eu entendi, faz sentido. Eu acharia melhor fazer a checagem no hook por iser. So esse hook de dados de demo nao justifica a dependencia a meu ver. Mas tem que verificar que sem a dependencia continua tudo legal com os dados de demo quando juntar todos modulos no Runbot por examplo.

2020-09-02 15:04 UTC, renatonlima commented on l10n_br_coa_simple/__manifest__.py
> +    "depends": ["l10n_br_coa", "l10n_br_base"],
Raphaël eu removi a dependencia do l10n_br_base e no hook que carrega os planos de contas para a empresas de demonstração eu verifico se existe a empresa antes de carregar o plano, desta forma resolvemos a depedencia e garantimos que não vai ter erro ao carregar os dados de demo independente na sequencia de instalação dos modulos.

2020-09-02 17:28 UTC, rvalyi commented
Eu chequei o codigo e testei, ficou bem certinho, inclusive com as 3 empresas de demo. So vou deixar vc fazer o `Para finalizar esse PR falta adicionar as propriedades dos account.tax.group para o l10n_br_coa_simple` para aprovar entao.

2020-09-03 01:02 UTC, rvalyi commented
alem da simplicicacao do codigo usando o recurso nativo de plano de conta pai, talvez vale explicar o raciocínio por tras do que o @renatonlima escreveu em cima:
```Foi adicionado no account.tax.group dados das contas contábeis para adicionar propriedades para definir as contas dos grupo dos impostos no momento em que for carregado o plano de contas.```
No Odoo nativo, quando vc pega um plano de conta europeio, geralmente vc tem um plano de conta oficial e umas 2 ou 3 taxas dedutíveis por examplo, nisso no Odoo nativo, todas contas que o Renato colocou no account.tax.group estao nesses 2 ou 3 account.tax.template e ponto.

So que no Brasil, temos muitas aliquotas de forma que ficava inviável ter centenas de account.tax.template todas devidamente parametrizados para todas aliquotas e todos planos possiveis. Isso era a abordagem ate a v10, funcionava, mas era muito trabalhoso de parametrizar e de manter, por isso que a ideia da Akretion na v12 foi de criar o objeto `l10n_br_fiscal.tax` https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_fiscal/models/tax.py que reflete fielmente a logica de calculo dos impostos barsileiros e que fica com carga de dados de acordo com as tabelas oficiais. So que no modulo l10n_br_fiscal q9e nao depende do modulo account) não tem o conceito de conta contábil ainda, esse casamento com as contas contabeis certas acontece no modulo l10n_br_account aqui https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_account/models/account_tax.py (e aqui https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_account/models/fiscal_tax.py )

Porem nesse momento de tornas as aliquotas brasileiras em account.tax do Odoo, precisamos dessas configuracoes contabeis. E a forma que parece mais obvia e de junta-las dentros dos account.tax.group dos planos de conta, e eh por isso que o @renatonlima accrescentou esses parametros no grupo.

Tambem na Europa, o sistema das taxas dedutiveis funciona pelo `account.fiscal.position` e conservamos esse sistema nativo como tinhamos feito em alguncs casos desde a v8. E por isso que o Renato tb acrescentou as posições fiscais nos planos fornecidos na OCA (falta faze-lo no plano simples porem ainda).

Estamos ciente de uma proposta de mecanismo mais distante do funcionamento nativo no PR #806 com o conceito de 'Modelos de lançamentos contábeis' da KMEE. Porem a nosso ver, mesmo com outro mecanismo alternativo, deveria se parametrizar essas propriedades da forma mais proxima do funcionamento nativo do Odoo, dentro do plano e primeiro temos que ter como básico das taxas dedutíveis funcionando pelo map_tax da posição fiscal da forma nativa e depois eventualmente sistemas alternativos para atender necessidades mais especiais.

cc @mileo @marcelsavegnago

2020-09-15 05:06 UTC, marcelsavegnago commented
@rvalyi eu gostei da ideia da simplificação. Aparentemente carregou tudo certinho. 

@renatonlima também estou com o @rvalyi em relação a aguardar a adição das propriedades para aprovar.

2020-09-16 01:52 UTC, marcelsavegnago approved these changes

2020-09-16 04:08 UTC, rvalyi approved these changes
kudos @renatonlima for this excellent work!! I tested quite a bit and it really makes it easier and ore standard to set up a chart of account and maintain the 2 ones of the project.

2020-09-16 08:42 UTC, mileo commented
/ocabot merge major

2020-09-16 08:43 UTC, mileo approved these changes

2020-09-16 08:43 UTC, mileo commented
Boa!

2020-09-16 09:42 UTC, merged