[12.0] l10n_br_nfse: fix cnae mask
OCA/l10n-brazil pull request #958
Opened 2020-09-16 11:44 UTC by luismalta

2020-09-16 11:48 UTC, mileo reviewed
Poderia trocar para a função: https://github.com/erpbrasil/erpbrasil.base/blob/master/src/erpbrasil/base/misc.py#L10

2020-09-16 12:23 UTC, gabrielcardoso21 approved these changes

2020-09-16 14:43 UTC, renatonlima requested changes, later dismissed

2020-09-16 14:43 UTC, renatonlima commented on l10n_br_nfse/models/document_line.py
> +            'codigo_cnae': misc.punctuation_rm(self.cnae_id.code) or None,
Esse campo deveria ser um related do cnae_id

2020-09-16 14:53 UTC, renatonlima commented
Pessoal,

Eu vi tbm que o campo cnab_id esta como um related do product_id, porque existe o campo product_id no cadastro de produtos? Eu entendo que o cnae_id deva ir na linha do documento fiscal porque é necessário na NFS-e, mas esse campo não deveria estar no cadastro de produtos, deveria estar no operation.line, no service.type ou municipio, e o cnae_id não deveria ser um related, já que se for alterado o cadastro do produto nas NFS-e antigas tbm vai aparecer diferente.

É importante vocês explicarem melhor essas implementações envolvendo a parte fiscal para ser validada e implementada de forma correta.

2020-09-21 14:47 UTC, marcelsavegnago commented
@luismalta vi que você fez uma atualização e se nela já foram tratados os itens levantados pelo @renatonlima o que acha de solicitar uma nova revisão dele?

2020-09-25 19:59 UTC, mileo approved these changes

2020-09-25 20:01 UTC, mileo commented
/ocabot merge minor

2020-09-25 20:22 UTC, merged