Feature/new users
OCA/l10n-brazil pull request #959
Opened 2020-09-16 12:14 UTC by mileo

New users:
- simples 
- presumido

To help with demo and demonstrations

2020-09-16 12:22 UTC, gabrielcardoso21 approved these changes

2020-09-16 18:37 UTC, renatonlima requested changes, later dismissed

2020-09-16 18:37 UTC, renatonlima commented on l10n_br_base/demo/res_users_demo.xml
> +        <field name="company_id" ref="l10n_br_base.empresa_lucro_presumido"/>
A empresa deste user deve ser base.main_company isso impacta a instalação dos módulos subsequentes

2020-09-16 18:41 UTC, mileo commented on l10n_br_base/demo/res_users_demo.xml
> +        <field name="company_id" ref="l10n_br_base.empresa_lucro_presumido"/>
Não sei se vc reparou, mas eu só movi isso de arquivo. Está assim na master... Vc quer que mude?

2020-09-18 18:46 UTC, marcelsavegnago commented on l10n_br_base/demo/res_users_demo.xml
> +        <field name="company_id" ref="l10n_br_base.empresa_lucro_presumido"/>
@mileo se for algo simples e já trazer beneficio.. não seria melhor já fazer a correção sugerida pelo @renatonlima ? 

cc @rvalyi

2020-09-18 18:50 UTC, marcelsavegnago approved these changes
Aparentemente Ok.. 

Acho válido apenas saber se a questão levantada pelo Renato será trata nesta mesma PR ou próxima.

2020-09-18 18:56 UTC, mileo commented
/ocabot merge nobump

2020-09-18 19:17 UTC, merged