[12.0][FIX] CST
OCA/l10n-brazil pull request #986
Opened 2020-10-21 02:29 UTC by renatonlima

2020-10-21 03:49 UTC, mileo approved these changes

2020-10-21 10:24 UTC, rvalyi requested changes
a sua mudança no l10n_br_stock parece que cria um efeito colateral que quebra os testes, vé aqui os testes do l10n_br_sale quebrando https://travis-ci.com/github/OCA/l10n-brazil/jobs/402975493#L2484

2020-10-22 20:46 UTC, renatonlima commented
@rvalyi 


Eu removi o commit da criação do estoque para as empresas, pois isso já se faz nativo o modulo stock sobreescreve o create do objeto res.company fazendo isso. então neste caso só deixei o commit da correções dos CSTs de entrada. Por causa do merge do módulo l10n_br_stock_account agora o travis esta quebrado eu fiz a correção no PR #1000 vai ser necessário fazer o merge deste PR para fazer o rebase e deixar verde.

2020-10-23 00:34 UTC, rvalyi approved these changes

2020-10-23 00:34 UTC, rvalyi commented
/ocabot merge nobump

2020-10-23 00:47 UTC, merged